### ISSUE TITLE
Changing App Service plan level on Azure makes meilisearch unresponsive

### ISSUE THREAD

**Issue by Caspar-Progius** [meilisearch/meilisearch#4123] opened 2023-10-12 15:32 UTC
**Describe the bug**
When deploying Meilisearch on Azure with the one click template in the documentation and then changing the App Service Plan level, the application becomes "kind of" unresponsive. This means that i.e. Index creation is not working or requesting Task status is returning 404's even though the tasks were clearly created. Some requests however still work normally like "client.get_all_stats()". All in all the whole application just becomes unusable and needs to be completely deleted. One can even select the highest level plan and still get this result. The application logging doesn't show anything suspicious, with the requests being shown as received and a 200 HTTP code returned.

**To Reproduce**
1. Go to https://www.meilisearch.com/docs/learn/cookbooks/azure#one-click-deploy
2. Click on Deploy to Azure
3. Fill in the details and deploy the Application
4. Change the App Service Plan of the application
5. Try to create an index (I tried python SDK and via Curl)
6. See that the Task is returned as "enqueued"
7. Try to get the Task by number and see the 404 "No Task found" error
8. Try to see if an index was created and see that no index was created even after 10 minutes or so.

**Expected behavior**
Changing the App Service plan shouldn't have any impact on Meilisearch other than compute constraints.

**Meilisearch version:**
Meilisearch 1.4.0
Python SDK 0.28.3 

**Additional context**
Note that for reproducibility it is important to switch the App Service plan before any index is created. In general I have found that changing the App Service plan just seems to mess up the application, even if an index with data has been created before, but it is less reproducible as the bug described above. 

Maybe there is just an underlying issue with how meilisearch is deployed/configured and what happens in the backend when azure changes the App Service plan.  For me that is very hard to investigate as it requires a deep understanding of meilisearch. However I would be happy to help anyone who wants to look at this, because we are only allowed to use Azure as a cloud service and need to be able to scale the app service plan from time to time. We are otherwise very happy with Meilisearch :)

**Comment by curquiza** [comment] 2023-10-16 09:08
Hello @Caspar-Progius 

If you get `404 "No Task found" error` is means you did not use the right id to get the task

Can you try the [global task route](https://www.meilisearch.com/docs/reference/api/tasks#get-tasks) instead (no task id are needed)

**Comment by Caspar-Progius** [comment] 2023-10-16 10:55
Yes, but as I described, the bug is that the tasks are not registered correctly anymore. Both using the correct task id or using the global task route will not show the task. Additionally index creation, index settings updates or adding documents don't work either. 

This is most likely a bug with how meilisearch and app service interact.

**Comment by curquiza** [comment] 2023-10-16 11:32
@Caspar-Progius 
Do you have the same issue without using Python SDK?

I made tests and I don't see any issues ith the task registration
Can you give as a concrete example about how to reproduce the issue?

**Comment by Caspar-Progius** [comment] 2023-10-16 14:33
Thank you for trying this out!!

Yes I did try using Curl as well and got the same results. Did you follow the exact same steps 1-7 as described in the initial post? 

I will try to make a broken instance available to you.

**Comment by curquiza** [comment] 2023-10-16 16:21
I did, but not on Azure, I did it on my machine (I tried to isolate the issue first)

I talked with engineers, and the Azure context should not impact this.

Do you have a persistent disk/volume on Azure?

**Comment by Caspar-Progius** [comment] 2023-10-16 18:09
Okay, I think it is definitely something Azure App service related as the Bugs only start to occur once I switch the App Service Plan tier.

I never had this problem when running locally and was quite surprised by this when we decided to deploy on Azure App Service. I understand that this seems a bit strange, since it theory the Azure context shouldn't make a difference. 

What do you mean with persistent disk/volume on Azure? As per the Biceps file a new Storage account and container is created every time I launch the one click deployment. I make sure to delete old resources whenever I deploy it with the same name.

I have created an Example Meilisearch Instance on Azure App Service, that I have brought into the buggy condition by switching from S1 to B3 Plan and then to P1v2 Plan. Is there a way I can share the Meilisearch Admin key with you, so you can see it for yourself?

Could it be that his something to do with the RAM and CPU sizes changing and therefore being wrongly allocated?

**Comment by curquiza** [comment] 2023-10-18 14:25
> What do you mean with persistent disk/volume on Azure? As per the Biceps file a new Storage account and container is created every time I launch the one click deployment. I make sure to delete old resources whenever I deploy it with the same name.

By persistent I mean a disk that is always booked for your usecase, not shared, not switched off/on regularly to optimize the resources on the Cloud provider side. Meilisearch absolutely needs to access to a persistent database.

> I have created an Example Meilisearch Instance on Azure App Service, that I have brought into the buggy condition by switching from S1 to B3 Plan and then to P1v2 Plan. Is there a way I can share the Meilisearch Admin key with you, so you can see it for yourself?

Definitely the issue is on the Azure side, I'm not sure our team can do something to help you here. But you can still share the admin key by email, we will try to take a look 😊

In the meantime, I don't know if you are aware of it, but to ease your deployment and settings management, you can also use our [cloud offer](https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=github&utm_medium=meilisearch) to manage Meilisearch in an easier way. And the migration to another version of Meilisearch can only be done with one click.

**Comment by knd775** [comment] 2023-10-30 01:36
We've had issues with the task queue randomly becoming corrupted recently, even without changing the plan level. It actually happened to two different instances in different subscriptions at the same time (both in the same region, East US)

**Comment by curquiza** [comment] 2023-10-30 09:53
@knd775 are you on Azure too?

**Comment by knd775** [comment] 2023-10-31 15:31
> @knd775 are you on Azure too?

Yep

**Comment by curquiza** [comment] 2023-10-31 16:19
I have to say it's almost impossible for our team to debug since we don't have this issue with other cloud providers, and we don't have enough information to fix this...
Probably manipulations on the Azure side that impact the persistency of the disk, so the meilisearch DB. I'm afraid the Meili team cannot do that much on this

**Comment by knd775** [comment] 2023-10-31 20:16
My concern is that the task queue doesn't seem very resilient. A bit of instability and it becomes irrecoverably corrupted. That's worrying, regardless of where it's hosted.

**Comment by dureuill** [comment] 2023-11-02 09:21
Hello @knd775 👋 

It's a bit unclear to me what you mean by "the task queue doesn't seem very resilient". 

The task queue doesn't become randomly corrupted and was specifically designed not to get corrupted on hard reboots of Meilisearch or by sending invalid commands. In that sense, the task queue is resilient. If you've found a way to corrupt the task queue with Meilisearch reboots and/or with a specific sequence of action, please open a new bug report 🙏 

Now, the task queue (and Meilisearch in general) isn't resilient in the following scenarios:
1. On network file systems. This is [a limitation](http://www.lmdb.tech/doc/) of our LMDB backend ("Do not use LMDB databases on remote filesystems"). Perhaps the persistent storage of Azure is using a network file system, which causes the issue you're seeing and would explain why it only happens in Azure.
2. In the face of unreliable storage. We don't apply error correction to the task queue that would allow us to recover from this kind of error. It's unfortunate, but on the other hand, I'm not sure a lot of search engines are held to this standard; this would possibly come with a hefty price on performance.

Please note that we don't recommend users use Meilisearch as their *primary* datastore: https://www.meilisearch.com/docs/learn/cookbooks/meilisync_mysql

**Comment by Caspar-Progius** [comment] 2023-11-03 13:59
Thanks everyone for the replies and for looking into this issue. 

For us the task queue only gets corrupted when we switch the app service plan, otherwise it is running stable. I still have the test instance running, if anyone wants to have a look. Its just responding with internal server error now, so I am not sure how use full that would be.

In general we currently can't use Meilisearch Cloud for two reasons:

1. We work with very sensitive data, so we need to be 100% GDPR compliant and have some additional secrecy agreements in place.
2. We have modified the facet search, so it works like the one from Algolia. As far as I understood, you can't run custom images on Meilisearch Cloud? 

Before anyone asks, the bug is occuring with the official Meilisearch images as well as our modified ones.

I can imagine there are quite a few potential customers for whom using multiple cloud providers is difficult for legal and/or technical reasons. So maybe it is worth it to invest some time into creating a ARM template that launches a Azure VM instance with local storage and doesn't rely on Azure App Service? 

Also it would be very helpful if there was a way to "factory reset" Meilisearch if the task queue or any other part of Meilisearch is corrupted. Currently the most frustrating thing is, that we have to completely delete and redeploy the app when this bug occurs.

**Comment by knd775** [comment] 2023-11-03 15:43
> On network file systems. This is [a limitation](http://www.lmdb.tech/doc/) of our LMDB backend ("Do not use LMDB databases on remote filesystems"). Perhaps the persistent storage of Azure is using a network file system, which causes the issue you're seeing and would explain why it only happens in Azure.

This is in fact the case. The storage configured in the template is a network share. This is how storage works in azure app services. App service instances do have their own storage, but it's not persistent long term. It could be possible to copy the db files to the local disk from the network mount on first run, but that'd have to be handled by the container and likely wouldn't be worth it for you all.

I also agree with @Caspar-Progius. Just being able to reset the task queue would be ideal. If it can't be done automatically when corruption is detected, then at least by an api call. Rebuilding the instance is annoying and time-consuming, even with terraform.

**Comment by dureuill** [comment] 2023-11-06 08:44
Hello again both of you,

> The storage configured in the template is a network share

This is unfortunate :-(. I suggest you change the type of disk if possible at all, so that we can get back to supported territory.

Thanks for the suggestion of providing a way to drop the task DB. I think it is probably a useful capability in general, but it is not a good solution to avoid re-indexing documents in the case of a corrupted task DB. The reason is that, if the task DB got corrupted, it is likely that the document DBs got corrupted as well, maybe silently. In case of DB corruption, it is much safer to start out fresh.

**Comment by Caspar-Progius** [comment] 2023-11-06 11:30
Hey dureuill,

The Meilisarch Website provides a one click deployment ARM template in the documentation here:

https://www.meilisearch.com/docs/learn/cookbooks/azure

So you might also want to change the storage type there or warn users.

>Thanks for the suggestion of providing a way to drop the task DB. I think it is probably a useful capability in general, but it is not a good solution to avoid re-indexing documents in the case of a corrupted task DB. 

The solution is not meant to avoid re-indexing, but just redeployment of the entire application after any DB corruption (task or index). Re-indexing wouldn't be a big problem, but currently you have to completely delete and redeploy meilisearch.  

I suggest an option to reset Meilisearch to its initial state, after image deployment. This would just drop any DB's, so one would need to re-configure and re-index everything, but at least the underlying VM  and storage don't need to be deleted and redeployed.

**Comment by dureuill** [comment] 2024-01-22 08:46
Hello :wave:

as there hasn't been any movement on this issue for a while, and we're not going to address supporting Meilisearch on filesystems not supported by LMDB, I'm going to close it. Sorry for not addressing the underlying issue

Feel free to reopen if you deem it necessary 😊

**Closed by dureuill** 2024-01-22 08:46 UTC
Labels: needs more info, support

**Comment by Kerollmops** [comment] 2024-02-15 09:57
Hey @Caspar-Progius and @knd775 👋

Thank you very much for the report and help in identifying this problem. [I investigated the matter](https://github.com/meilisearch/meilisearch/issues/4402#issuecomment-1945722743), and you are right: changing the plan on Azure, downgrading or upgrading breaks the database. This does not even appear when Meilisearch is indexing or anything. I tried to upgrade from Standard S1 to S2/S3 with a stalled Meilisearch, and the database was inconsistently modified.

The results are probably related to the Azure snapshotting system that inconsistently snapshot the files. We are discussing this with an Azure employee on the linked issue ☝️.

However, everything works fine on Azure as long as you do not upgrade or downgrade your plan. We are searching for a solution to fix the snapshots before you can change the plan. We are compatible with Azure! Continue reading the issue linked above.

**Comment by Caspar-Progius** [comment] 2024-02-15 11:38
Hey,

thank you very much for looking into this!
