### ISSUE TITLE
Quoted search breaks when adding a custom ranking rule

### ISSUE THREAD

**Issue by roshammar** [meilisearch/meilisearch#2821] opened 2022-09-30 14:25 UTC
**Describe the bug**

I want to add a custom ranking rule, so that higher rated items are ranked better.

Everything works as expected if I add a custom ranking rule *at the end of the list* as shown here (using the python client):

```python
ranking_rules = [
    "words",
    "typo",
    "proximity",
    "attribute",
    "sort",
    "exactness",
    "rating:desc",
]

index.update_ranking_rules(ranking_rules)
```

However, I wanted my custom ranking rule to have a bigger impact and moved it towards the start of the ranking rules list.

```python
ranking_rules = [
    "words",
    "rating:desc",
    "typo",
    "proximity",
    "attribute",
    "sort",
    "exactness",
]
```

Doing this produces no error, but when searching, quotes around the terms no longer works. Just gives 0 hits without any error.

It is not entirely clear from the documentation if the custom rule can appear anywhere in the list or only at the end.

So depending on that, this might be a request for a documentation improvement + a feature request, or a bug report otherwise :)
 

**To Reproduce**

```python

def test_ranking(index_name, include_custom):

    doc = {
        "id": "doc-id-1",
        "text": "the quick brown fox",
        "rating": 2
    }

    task = client.create_index(index_name)
    client.wait_for_task(task["taskUid"])
      
    idx = client.get_index(index_name)

    ranking_rules = [
        "words",
        "typo",
        "proximity",
        "attribute",
        "sort",
        "exactness",
    ]
    
    if include_custom:
        ranking_rules.insert(0, "rating:desc")

    task = idx.update_ranking_rules(ranking_rules)
    client.wait_for_task(task["taskUid"])
        
    task = idx.add_documents([doc])
    client.wait_for_task(task["taskUid"])
    
    print(len(idx.search('"quick brown"')["hits"]))
    
    client.delete_index(index_name)
    
test_ranking("test_without", include_custom=False) # prints 1
test_ranking("test_with", include_custom=True) # prints 0

```

**Expected behavior**

Either an error being raised that says that I cannot include my custom ranking rule wherever, or quoted search working in both cases.

**Meilisearch version:** v0.28.1

**meilisearch-python version:** v0.19.1

**Additional context**
Intel macOS, meilisearch running in Docker

**Comment by roshammar** [comment] 2022-10-04 08:07
Update: It looks like the quoting bug is also triggered by stopwords.

If I do the following in my setup, then quoting also stops working:
```python
index.update_settings({"stopWords": stopwords})
```

Unfortunately I have not yet been able to create a small code sample to reproduce this. Everything works as expected if I just update `test_ranking()` above and add stopwords, but in my real-world project it breaks.

**Comment by oluademola** [comment] 2022-10-05 15:43
Hello @roshammar. Thank you for the detailed information. I'd take a look at this tomorrow and revert to you.

**Comment by oluademola** [comment] 2022-10-12 07:18
Hello! After giving the stop word scenario a closer look. It indeed appears to impact phrase searches. Using the [movies.json](https://docs.meilisearch.com/movies.json) dataset, I could reproduce it by adding "the" as a stopword and phrase search "the endless", a title of a movie, and it returns an empty hit. When the stop word is removed, the movie is returned, which is the expected result.

<img width="1077" alt="Screenshot 2022-10-12 at 08 05 31" src="https://user-images.githubusercontent.com/101267639/195275276-c3d5ce4a-903c-49ca-b248-ea41f387074e.png">

Escalating to the @meilisearch/core-team

**Comment by ManyTheFish** [comment] 2022-10-12 08:38
Hello @oluademola and @roshammar!
This bug should be fixed since the `v0.29` with https://github.com/meilisearch/milli/pull/594,
if you keep having the bug with the last version don't hesitate to notify us, and we will investigate deeper to fix the bug!

**Comment by oluademola** [comment] 2022-10-12 09:12
Hi @ManyTheFish

Thank you very much. Indeed the first scenario is fixed in v0.29. However, I can replicate the stop word issue even in the latest version (v0.29). I still get an empty hit when I phrase search with stopword configured (`"the"`) using the same dataset and search query above.

Thank you.

**Comment by ManyTheFish** [comment] 2022-10-12 13:51
Indeed! There is a bug with stop words, I've created an [issue for this specific case](https://github.com/meilisearch/milli/issues/661).
Closing this issue in favor of https://github.com/meilisearch/milli/issues/661

Thank you for finding this bug in Meilisearch! 👍

**Closed by ManyTheFish** 2022-10-12 13:51 UTC
Labels: bug

**Comment by curquiza** [comment] 2022-10-12 17:01
FYI, I've created this issue on Meilisearch's side for the traceability, but the fix should be indeed done on milli's side
https://github.com/meilisearch/meilisearch/issues/2905

**Comment by roshammar** [comment] 2022-10-12 18:44
Thank you @oluademola, @ManyTheFish, and @curquiza for your support!
