### ISSUE TITLE
No result returned when using a hard separator within phrase search

### ISSUE THREAD

**Issue by oluademola** [meilisearch/meilisearch#2962] opened 2022-10-25 11:01 UTC
**Describe the bug**
According to the [documentation](https://docs.meilisearch.com/reference/api/search.html#phrase-search-3), using a hard separator within a phrase search effectively splits it into separate phrase searches: “Octavia.Butler” will return the same results as “Octavia” “Butler”.

**To Reproduce**
1. Download the [movies.json](https://docs.meilisearch.com/movies.json) dataset and index it to Meilisearch.
2. Phrase search "Four.Rooms" returns no result.

**Expected behavior**
Phrase search "Four.Rooms" should return a result as "Four" "Rooms"

**Screenshots**
<img width="1242" alt="Screenshot 2022-10-25 at 11 56 16" src="https://user-images.githubusercontent.com/101267639/197755853-a5fd6f20-48c4-405c-956f-c54629ab8cb5.png">
<img width="1358" alt="Screenshot 2022-10-25 at 11 55 47" src="https://user-images.githubusercontent.com/101267639/197755916-812c6a3c-3c12-4e6d-8780-c77b72e65f08.png">

**Meilisearch version:** v0.29.1
**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment] 2022-10-25 11:44
Thanks @oluademola 

We will look into this soon

**Comment by ManyTheFish** [comment] 2022-11-08 09:30
Hello @curquiza and @oluademola,
This issue is not a bug, but a feature to handle non-separating dots like `3.5`, `node.js`.
It is related to https://github.com/meilisearch/charabia/issues/62

Trying `"Four. Rooms"` instead of `"Four.Rooms"` should work.

**Comment by curquiza** [comment] 2022-11-08 09:59
Thanks @ManyTheFish 

@oluademola is it something a user asked for or something you think inconsistent regarding the docs?

Indeed, as Many explained, this is something we changed because the users wanted to find "S.O.S" when typing "sos", or "node.js" when typing "nodejs"

If it's something a user asked for, could you open a product discussion with more details @oluademola? I mean the context of the user, whey they need this.

**Comment by oluademola** [comment] 2022-11-09 06:49
Thank you @ManyTheFish and @curquiza 

@curquiza, a user was trying to achieve this by following the instructions in the docs because it says so. I'd go with this and communicate this feedback to the user. 

Thanks again.

**Comment by curquiza** [comment] 2022-11-09 09:50
Ok @oluademola, thanks for letting us know. The user is more than welcome to open a discussion in the product discussion if needed 😄 

I close this issue then!

**Closed by curquiza** 2022-11-09 09:50 UTC
Labels: feature request, support
