### ISSUE TITLE
Highlighting is broken with non ascii characters

### ISSUE THREAD

**Issue by burtgulash** [meilisearch/MeiliSearch#1173] opened 2021-01-08 11:57 UTC
There is a field in my index **category** with value **Vývoj**, that I am searching for.
- In the first case I cut the last letter and send **vývo** as a query. This case actually highlights correctly.
- In the second case I try to search directly by sending the full word **vývoj** as a query. No highlight in the result. Matches object contains two overlapping match ranges.

```
curl -X POST http://localhost:7700/indexes/myindex/search --data '{"q":"vývo","attributesToHighlight": ["category"],"matches":true}'

"_formatted": {
  "category": "<em>Vývoj</em>"
},
"_matchesInfo": {
  "category": [
    {
      "start": 0,
      "length": 5
    }
  ]       
}
```

This one gets messed up.
```
curl -X POST http://localhost:7700/indexes/myindex/search --data '{"q":"vývoj","attributesToHighlight": ["category"],"matches":true}'

"_formatted": {
  "category": "Vývoj"  
},      
"_matchesInfo": {      
  "category": [      
    {      
      "start": 0,      
      "length": 5      
    },      
    {      
      "start": 0,      
      "length": 6      
    }      
  ]       
}
```

```
% meilisearch --version
meilisearch-http 0.17.0
```

**Comment by timoschwarzer** [comment] 2021-02-17 10:25
### Reproduction

#### When searching documents without special characters:

```json
[
  {
    "id": "123",
    "title": "This is a test with special characters blah blub"
  }
]
```

Search term is "characters":

```json
title: "This is a test with special <em>characters</em> blah blub"
```

#### And **with** special characters:

```json
[
  {
    "id": "123",
    "title": "This is a test with special chäräcters blah blub"
  }
]
```

Search term is "chäräcters":

```json
title: "This is a test with special <em>chäräcte</em>rs blah blub"
```

One thing I noticed is that it ignores a word entirely for highlighting if the last character of a query word is a special one, e.g.

<details>
	<summary>Examples</summary>
	
![image](https://user-images.githubusercontent.com/8849554/108190857-c138b080-7112-11eb-9363-bec255ca3b9b.png)

![image](https://user-images.githubusercontent.com/8849554/108190916-d01f6300-7112-11eb-9069-267a37193006.png)

![image](https://user-images.githubusercontent.com/8849554/108190945-d7df0780-7112-11eb-9d05-1c5352b67523.png)


</details>

**Comment by timoschwarzer** [comment] 2021-03-15 12:03
Quoting from @curquiza 

> However, the core team is working hard on a new search engine that will fix all the highlight issues.
I'm going to close this PR since it will be fixed later in a different way thanks to the new search engine implementation!

So this will likely be fixed soon :)

**Comment by ManyTheFish** [comment] 2021-07-05 15:18
closing in favor of #1480

**Closed by ManyTheFish** 2021-07-05 15:18 UTC
Labels: type:bug
