### ISSUE TITLE
Relevancy issue (ranking rules ?)

### ISSUE THREAD

**Issue by pokemaster974** [meilisearch/meilisearch#3093] opened 2022-11-20 21:52 UTC
**Describe the bug**
Adding "Exactness" first into the ranking rules, doesn't work as expected.

**To Reproduce**
1. Adding some documents into an index
2. Try different queries
3. Check the results and their order displayed

**Expected behavior**
I've updated the ranking rules of my index like this :
```
    "rankingRules": [
        "exactness",
        "words",
        "typo",
        "proximity",
        "attribute",
        "sort"
    ],
```
Regarding the [examples](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#examples) I've understand things like this : with `exactness` first in the ranking rules, typing `eric zemmour` will give me first results with `eric zemmour` then results with one letter of difference (in the example : `Knight` and `Knights`).
So it's expected that if there is no result with `eric zemmour`, resultts with `deric zemmour` will be displayed first.
It's not the case (cf screenshots) and only results with `eric` are displayed first (because of the matching strategy)

**Screenshots**
All informations contained in these screenshots are publicy available into afnic website.
Results with `"Eric Zemmour"`
![image](https://user-images.githubusercontent.com/28442699/202927849-82a945ca-c106-40c8-b86a-728556124eb2.png)

Results with `Eric Zemmour`
![image](https://user-images.githubusercontent.com/28442699/202927875-f30686d4-72a0-4a60-b68d-6f4396d6099c.png)

Results with `Zemmour Eric`
![image](https://user-images.githubusercontent.com/28442699/202927921-7fdf8b9e-34cf-4d92-87e9-0f01f0b88030.png)

Results with `Les Amis Zemmour Eric`
![image](https://user-images.githubusercontent.com/28442699/202928013-376e175f-0f6f-4d7e-9f52-548c90bd39b3.png)

**Meilisearch version:**
v0.29.1

**Additional context**

**Comment by oluademola** [comment] 2022-11-29 22:56
Hello @pokemaster974 

I think the problem is that you're trying to query in the middle of the word (Deric). Meilisearch doesn't support this. It is a prefix-based search engine meaning documents are sorted by first comparing the search term against the beginning of each word in your dataset before the ranking rules are applied. This means if you search for “book”, Meilisearch will find documents containing “bookshop”, or "bookshelf" but not “yearbook”. I believe this explains why Meilisearch returned search results for Eric and Zemmour in that manner. Furthermore, enclosing your search term in double quotes typically returns only documents containing those terms in the order they were given. This type of search doesn't consider typos.

A workaround could be to split the words into a new document field such that the engine can use to prefix-search to retrieve the document. You can find more information [here](https://github.com/meilisearch/meilisearch/issues/1248).

I hope this helps. Thanks

**Comment by pokemaster974** [comment] 2022-12-04 16:52
> Hello @pokemaster974
> 
> I think the problem is that you're trying to query in the middle of the word (Deric). Meilisearch doesn't support this. It is a prefix-based search engine meaning documents are sorted by first comparing the search term against the beginning of each word in your dataset before the ranking rules are applied. This means if you search for “book”, Meilisearch will find documents containing “bookshop”, or "bookshelf" but not “yearbook”. I believe this explains why Meilisearch returned search results for Eric and Zemmour in that manner. Furthermore, enclosing your search term in double quotes typically returns only documents containing those terms in the order they were given. This type of search doesn't consider typos.
> 
> A workaround could be to split the words into a new document field such that the engine can use to prefix-search to retrieve the document. You can find more information [here](https://github.com/meilisearch/meilisearch/issues/1248).
> 
> I hope this helps. Thanks

Hi @oluademola thanks for the reply.
I try some tests, and following your explaination typing `Deri Zemmour` will give me same results as `Deric Zemmour`.
But sadly it's not the case.

Ranking rules ares :
```
[
    "words",
    "exactness",
    "typo",
    "proximity",
    "attribute",
    "sort"
]
```

`Deric Zemmour`.
![image](https://user-images.githubusercontent.com/28442699/205504159-35c9cf80-7ea6-4bc3-ae2f-6027e0565b06.png)

`Deri Zemmour`
![image](https://user-images.githubusercontent.com/28442699/205504170-a4116456-6fec-46ad-b151-64e26999d242.png)

**Comment by oluademola** [comment] 2022-12-05 12:57
Hello @pokemaster974 

In my example, I provided one word as an example. The policy for word matching in Meilisearch is more than that and behaves differently when querying multiple words. When searching multiple words, Meilisearch sorts documents by decreasing the number of matching terms, which means that if no document contains all of the given terms, the last query term is removed, and so on. For example, Meilisearch will first return documents containing Deri and Zemmour, and then documents containing Deri, or documents containing Deric and Zemmour, and then documents containing Deric. You can find more information in the [dedicated documentation](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#_1-words). Additionally, you can customize how the words match with the [matchingStrategy parameter](https://docs.meilisearch.com/reference/api/search.html#matching-strategy)

I hope this answers your question.

**Comment by curquiza** [comment] 2023-01-12 13:30
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-01-12 13:30 UTC
Labels: support
