### ISSUE TITLE
windows movies 1 document indexing fails with memory error

### ISSUE THREAD

**Issue by anborg** [meilisearch/meilisearch#4027] opened 2023-09-04 01:44 UTC
**Describe the bug**

I stated meilisearch with below bat file:
```
@echo off
setlocal
set MEILI_NO_ANALYTICS=true
set MEILI_ENV=production
set MEILI_MASTER_KEY=aSampleMasterKey 
set MEILI_DB_PATH=%~dp0\..\tmp_meilidata
::set MEILI_DB_PATH=C:\mnt\disks\datadisk\apps\meilisearch\data
::set MEILI_MAIN_MAP_SIZE=409600000
::set MEILI_UPDATE_MAP_SIZE=40960000
%~dp0\meilisearch.exe --master-key %MEILI_MASTER_KEY% 
endlocal
```

I ran this python to index movies.json [2k records only]. I expect no indexing/outofmemory error
```py
import meilisearch
import json


def index_movies_dump():
    json_file = open('movies_2k.json', encoding='utf-8')
    movies = json.load(json_file)
    client.create_index('movies', {'primaryKey': 'id'})
    client.index('movies').add_documents(movies)
def test_index():
    indexes = client.get_indexes({'limit': 3})
    for result in indexes['results']:
        print("indexname: ", result.uid)

def test_movies():
    results = client.index('movies').search('botman')
    print(results)
    for movie in results['hits']:
        print(movie.id, movie.title)

# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    client = meilisearch.Client('http://localhost:7700', 'aSampleMasterKey')
    index_movies_dump()
    test_index()
    test_movies()
```]


Error 

```log
Config file path:       "none"
Database path:          "C:\\apps\\env-winos\\bin\\\\..\\tmp_meilidata"
Server listening on:    "http://localhost:7700"
Environment:            "production"
Commit SHA:             "cdb4b3e024a06472b9e2ec5e861c9998cfc7e964"
Commit date:            "2023-08-23T15:30:56Z"
Package version:        "1.3.2"
Anonymous telemetry:    "Disabled"
Instance UID:           "01728e17-8a81-4c0f-ab1c-5ae6a7aa9b13"

A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.

Check out Meilisearch Cloud!    https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=engine&utm_medium=cli
Documentation:                  https://www.meilisearch.com/docs
Source code:                    https://github.com/meilisearch/meilisearch
Discord:                        https://discord.meilisearch.com

[2023-09-04T01:37:39Z INFO  actix_server::builder] starting 4 workers
[2023-09-04T01:37:39Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2023-09-04T01:37:58Z INFO  actix_web::middleware::logger] ::1 "POST /indexes HTTP/1.1" 202 121 "-" "Meilisearch Python (v0.28.2)" 0.003011
[2023-09-04T01:37:58Z INFO  actix_web::middleware::logger] ::1 "POST /indexes/movies/documents HTTP/1.1" 202 132 "-" "Meilisearch Python (v0.28.2)" 0.015844
thread 'batch-operation' panicked at 'the allocator is unable to allocate that much memory (11365556736 bytes requested)', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\grenad-0.4.4\src\sorter.rs:350[2023-09-04T01:37:59Z INFO  actix_web::middleware::logger] ::1 "GET /indexes?limit=3 HTTP/1.1" 200 165 "-" "Meilisearch Python (v0.28.2)" 0.310070
:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-09-04T01:37:59Z INFO  actix_web::middleware::logger] ::1 "POST /indexes/movies/search HTTP/1.1" 200 94 "-" "Meilisearch Python (v0.28.2)" 0.002215
```

**Comment by irevoire** [comment] 2023-09-04 12:21
Hey, can you try indexing a single small document just to see if the issue reproduces?

**Comment by anborg** [comment] 2023-09-04 14:49
> Hey, can you try indexing a single small document just to see if the issue reproduces?

Just tried one document .... 

Memory allocation Error: 

```log
[2023-09-04T14:46:04Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/movies/documents HTTP/1.1" 202 132 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" 0.004154
thread 'batch-operation' panicked at 'the allocator is unable to allocate that much memory (11365556736 bytes requested)', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\grenad-0.4.4\src\sorter.rs:350:9
```

![image](https://github.com/meilisearch/meilisearch/assets/56970398/2bdce256-6e86-4697-8fb8-0a34cf1ae63b)

**Comment by irevoire** [comment] 2023-09-05 14:01
Hey @anborg,

> Memory allocation Error:

Can you now try to run start meilisearch with the `--max-indexing-memory 0` cli parameter?
With this, meilisearch will use as little memory as possible.

-----

As for the rest of the message. That’s the kind of thing we try to show in our integrations;
- [Adding a document in javascript](https://github.com/meilisearch/meiliSearch-js#add-documents-)
- [Or adding a document in python](https://github.com/meilisearch/meiliSearch-python#add-documents-)

And for the searches, there is the dashboard integrated into meilisearch that lets you see the data in your instance.
Creating new repositories with everything packed in could be a good idea, but tbh, we don’t have the time to tackle this right now. Contributions are always accepted, though!

**Comment by anborg** [comment] 2023-09-05 14:14
Thanks @irevoire , 

Thanks --max-indexing-memory avoids crash.

meili-start.bat
```bat
@echo off
setlocal
set MEILI_NO_ANALYTICS=true
set MEILI_ENV=production
set MEILI_MASTER_KEY=aSampleMasterKey 
set MEILI_DB_PATH=%~dp0\..\tmp_meilidata

::set MEILI_MAIN_MAP_SIZE=409600000
::set MEILI_UPDATE_MAP_SIZE=40960000
%~dp0\meilisearch.exe --master-key %MEILI_MASTER_KEY%  --max-indexing-memory 0
endlocal
```

> with everything packed in could be a good idea
>  Contributions are always accepted, though!

Sure will try putting a end-2-end nodocker sample.

**Comment by irevoire** [comment] 2023-09-05 14:32
> Thanks --max-indexing-memory avoids crash.

Okay interesting, so I think there are multiple things to understand here:
- `MEILI_MAIN_MAP_SIZE` and `MEILI_UPDATE_MAP_SIZE` were not used anymore because they’ve been deprecated in meilisearch v1.0 
- The default behavior of meilisearch tries to use a quantity of memory that is too high for Windows, and that’s a bug

**Comment by curquiza** [comment] 2023-10-25 17:56
I close this issue since it's more related to the global OOO issue the engine has, and a solution has been given to user
Feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-10-25 17:56 UTC
Labels: support
