### ISSUE TITLE
Search result count?

### ISSUE THREAD

**Issue by Bajix** [meilisearch/MeiliSearch#469] opened 2020-02-11 20:58 UTC
It occurs to me that the search API lacks a result count, and simply has hits / offset / limit / processingTimeMs and query. This makes it hard to build query pagination as there's no way to determine whether there are more results and how many pages of results there are. It would be great if this could be included

**Comment by Kerollmops** [comment] 2020-02-11 21:27
Hey!
This is a duplicate of #461, and we plan to add this in the future if it does not make performances issues.

**Comment by Bajix** [comment] 2020-03-18 18:53
I suppose I should've already closed this >.<

Can you clarify if this will be included within 0.9.0?

**Comment by Kerollmops** [comment] 2020-03-18 19:36
No, we would prefer to keep it open to make sure other people know that this feature as been requested and let them tell us why they want it too.

This will not be implemented in v0.9.0.

The big problem with this feature is that MeiliSearch is lazy and doesn’t exactly know how many documents can be returned until it needs to return them.

To make sure I understand correctly your request, don’t you just want to know if there is a next page of documents available? Because in that case you can ask the engine for one more document (21), only display the originally requested number (20) and display the next page button only if the +1 has been returned (21th).

**Comment by Bajix** [comment] 2020-03-18 21:01
Actually I've already implemented infinite scrolling in both an iOS and web app with this simply by checking if there are fewer than the requested number of entries. The question has arisen in our dashboard of whether this could be used for another one of our use cases where we have table of documents that we want to be able to search against to then apply admin actions. For this use case it's been requested that we have an overall count of the matching documents. Conceivably this could be done where we query postgres for counts and meilisearch for matches, but that approach doesn't work particularly well for user inputed query strings. 

Considering the lazy nature of this, it may very well be that count doesn't make sense to include by default. Perhaps this could be a dedicated endpoint?

**Comment by Kerollmops** [comment] 2020-03-19 08:58
I am wondering if this count must be exact, if not, we could return an approximate number of candidates documents. Would it fit your needs?

I am also wondering what this count has been requested for? Is it a count that would help the end-users be informed on the approximate number of documents that could have been found?

**Comment by Kerollmops** [comment] 2020-03-20 14:16
[I just saw that Algolia can displays approximate counts](https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/how-to/pagination/#response-details) when exhautive counts are too much to compute, it also returns an `exhaustiveNbHits` boolean that specifies to the end-user if the count is approximate or not.

I think that can be good feature to add, we will probably always show an approximate count for the moment and in a future, show an exhaustive one when we find a good way to compute it.

**Closed** 2020-03-25 14:34 UTC
Labels: R_2020_Q2, duplicate, enhancement, feature-proposal, performance
