### ISSUE TITLE
 Release v0.29.2- Duplicate records when searching

### ISSUE THREAD

**Issue by seifrached** [meilisearch/meilisearch#3050] opened 2022-11-15 02:07 UTC
hello everybody,

When searching, the record is duplicated, also when searching, the relationships not charged correctly! in my case i have Model: "PROPERTY" hasMany(image) and belongsTo(user). The relationship "image" is empty for last record indexed 

https://user-images.githubusercontent.com/45343853/201807917-dd5bcf38-d7f2-44ae-a58f-cad0ceea5113.mp4

**Meilisearch version:** [e.g. v0.29.1]
Additional information that may be relevant to the issue.
[e.g. Windows 11 Professionnel, Chrome]

**Comment by curquiza** [comment] 2022-11-15 11:24
Hello @seifrached 

I think it's related to this: https://github.com/meilisearch/meilisearch/issues/3021
@meilisearch/core-team can you confirm this is a duplicate issue?

We will release v0.29.2 today that should fix this problem 😊 
Sorry for the inconvenience

**Comment by seifrached** [comment] 2022-11-15 17:15
@curquiza 
also with v0.29.2 the bug persists

**Comment by curquiza** [comment] 2022-11-15 18:37
Thanks for the report @seifrached we'll investigate this soon

**Comment by Kerollmops** [comment] 2022-11-15 18:42
Hey @seifrached,

Unfortunately, the bug in v0.29.1 corrupted your database, the only way you can recover your data is to send again your documents in a fresh index.

The bug that was part of v0.29.0 and v0.29.1 was considering freshly deleted documents as not deleted and reinserting them in the database. This is the reason why you can't even do a dump export.

I am sorry if it wasn't clear. We will change the changelog to help users recover from that and reduce confusion about that bug.

**Comment by seifrached** [comment] 2022-11-15 18:48
> 

Hello @Kerollmops 

I hope that the problem will be solved, and for my part, if there is something new, I will tell you 👍

**Comment by Kerollmops** [comment] 2022-11-16 11:00
Hey @seifrached,

The problem should be fixed by now on v0.29.2. You must reimport your dataset on a fresh install and not run your Meilisearch on an existing database. You can't use a dump to import your data. You must do HTTP calls to send your dataset and settings again. Have you tried that to check that the bug is fixed?

**Comment by seifrached** [comment] 2022-11-16 14:57
> Hey @seifrached,
> 
> The problem should be fixed by now on v0.29.2. You must reimport your dataset on a fresh install and not run your Meilisearch on an existing database. You can't use a dump to import your data. You must do HTTP calls to send your dataset and settings again. Have you tried that to check that the bug is fixed?

It is currently working, "no duplicate records", but after checking i found that the problem lies in the settings ! 
When setting up rankingRules or synonyms or typo Tolerance the relationships does not retrieved.

**Comment by Kerollmops** [comment] 2022-11-16 16:20
Hum... looks like it is another issue, then.

Could you please clarify the _relationships does not retrieved_ sentence? I am not sure to catch the meaning here.
Would it be possible to open a new bug report issue in this repository with a minimal reproducible example?

**Closed** 2022-11-16 18:31 UTC
Labels: support
