### ISSUE TITLE
Search Chinese Content, Typo tolerance looks not work

### ISSUE THREAD

**Issue by ldnvnbl** [meilisearch/meilisearch#2222] opened 2022-03-10 05:32 UTC
**Describe the bug**

When I search Chinese content with one word typo， it looks not hit anything. Is meilisearch not support or need some configuration that I don't known.

can anyone help me, thanks !!!

**Screenshots**
this is no typo search result:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/3798479/157595793-9e968297-0734-43ac-812e-2fa3c770ebd8.png">

one typo Hanzi search result:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/3798479/157595945-69e62e7e-1b44-42d4-91dd-b68f3adcb5f1.png">

**Meilisearch version:** 

v0.25.2

**Additional context**

- Mac os
- Chrome

**Comment by ldnvnbl** [comment] 2022-03-11 02:53
[poems.json.gz](https://github.com/meilisearch/meilisearch/files/8228521/poems.json.gz)

@curquiza  Hi, I upload the json file with gz format, there are 3 documents.


### step 1: create index

```bash
curl \
  -X POST 'http://127.0.0.1:7700/indexes/poems/documents' \
  -H 'Content-Type: application/json' \
  --data-binary @poems.json
```
### step 2: query with right keyword

```bash
curl -XPOST 'http://127.0.0.1:7700/indexes/poems/search' -H 'Content-Type: application/json' -d '{"q": "小小生金屋"}'
```

this query can hit one document with id 3.

### step 3: query with that keyword but with one Hanzi typo

```bash
curl -XPOST 'http://127.0.0.1:7700/indexes/poems/search' -H 'Content-Type: application/json' -d '{"q": "小笑生金屋"}'
```
this query hit nothing. because the second Hanzi is typo.

### expect

As I read this document https://docs.meilisearch.com/learn/advanced/typotolerance.html. In english, the query keyword with one typo character can hit  something, so I think In Chinese the query with one Hanzi typo should also hit the document with id 3.

**Comment by curquiza** [comment] 2022-03-16 19:26
Thanks @ldnvnbl 
I succeeded to reproduce the bug, @ManyTheFish will take a look at it when he will be available. Currently he's focusing on improving the cropping and the highlighting :)

Sorry for the bug!

**Comment by curquiza** [comment] 2022-03-22 12:14
Hello again @ldnvnbl 

For your information, we are currently working on improving the typo tolerance management of Meilisearch, see: https://github.com/meilisearch/meilisearch/issues/2213
Once v0.27.0 is out (beginning of May for the official release, RC version are coming in April) you will be able to customize the minimum size of a word to accept a typo by decreasing the default value.

This should fix your issue. We'll let you know when the first testable version of Meilisearch are out.

**Comment by CNLHC** [comment] 2022-03-26 02:11
I think even we enable the users to custom the `minWordSizeForxTypos`, this problem can not be fully fixed.

The reason is one character typo may lead to different LAC(Lexical Analysis of Chinese) results.  
Take the payload posted by @ldnvnbl as an example, we have two strings: A:`小小生金屋` and B:`小笑生金屋`. They only differ in the second character. However, this 1-typo will lead to different tokenizer results.
```
>>> list(jieba.cut_for_search("小小生金屋") )
['小小', '生', '金屋']
>>> list(jieba.cut_for_search("小笑生金屋") )
['小笑生', '金屋']
```

If we use the string B to search string A, tweaking the `minWordSizeFor2Typos` to 1 will solve the problem since the Levenshtein distance between `小小` and `小笑生` is 2.

If we use string A to search string B, then no document is recalled since the typo leads to a new word `生` (It is a word. One Hanzi word is common in Chinese) which does not exist in the inverted index.

**Comment by ManyTheFish** [comment] 2022-03-28 08:38
Hey @CNLHC! You're right in this case, and I don't have any solution for it.
But, in another hand, customizable typos would allow typos on 3 character long search words.
This could be interesting in the case where you are searching string A in string B. Computed with `ngrams`,
the query A would search for `['小小', '生', '金屋']` and` ['小小生', '金屋']` (concatenation of the two first words),
where the Levenstein distance between `'小小生'` and `'小笑生'` is 1.

I understand that my response will not solve your specific case, and, for now, I don't really have any fix in mind to solve it 😕.
We could change Jieba, but I don't think it would be better. 🤔

**Comment by ICHx** [comment] 2022-05-11 13:54
> Hey @CNLHC! You're right in this case, and I don't have any solution for it. But, in another hand, customizable typos would allow typos on 3 character long search words. This could be interesting in the case where you are searching string A in string B. Computed with `ngrams`, the query A would search for `['小小', '生', '金屋']` and` ['小小生', '金屋']` (concatenation of the two first words), where the Levenstein distance between `'小小生'` and `'小笑生'` is 1.
> 
> I understand that my response will not solve your specific case, and, for now, I don't really have any fix in mind to solve it 😕. We could change Jieba, but I don't think it would be better. 🤔

Hi, I recently worked on a project to increase ES search quality on Chinese document.  In this case, due to the typo, Jieba would not work and result in over-segmentation.  I suggest to do fuzzy/n-gram match with IME mappings, such as Cangjie, Jyutping and Pinyin mapping.

**Comment by ManyTheFish** [comment] 2022-05-16 12:18
Hello @ICHx and thank you, I will study your suggestion!
A small question to be sure, is this paper: https://aclanthology.org/C10-2085.pdf the English version of yours?

**Comment by ICHx** [comment] 2022-05-17 06:27
> Hello @ICHx and thank you, I will study your suggestion! A small question to be sure, is this paper: https://aclanthology.org/C10-2085.pdf the English version of yours?

not my paper, but i think it is

**Comment by curquiza** [comment] 2022-09-07 15:39
Hello everyone
We are going to close this issue in favor of https://github.com/meilisearch/product/discussions/503
Anyone having inputs on this discussion will be more than welcome to comment!

We plan to open different issues on the [tokenizer repo](https://github.com/meilisearch/charabia) during hacktoberfest to let people contribute and improve Chinese support in Meilisearch.

Thanks in advance for your help on improving Chinese in Meilisearch

**Closed by curquiza** 2022-09-07 15:39 UTC
Labels: bug, tokenizer, language
