### ISSUE TITLE
Create dump got error

### ISSUE THREAD

**Issue by AlphaPigger** [meilisearch/meilisearch#2381] opened 2022-05-08 15:41 UTC
**Describe the bug**
create dump got errors(Internal error: failed to persist temporary file: Cross-device link (os error 18))

**To Reproduce**
1.create dump:http://127.0.0.1:7701/dumps
2.check dump status:http://127.0.0.1:7701/dumps/{dump_uid}/status

**Expected behavior**
i expect status is done

**Screenshots**
![image](https://user-images.githubusercontent.com/17999021/167303375-e042edb0-b4c6-46bb-ba53-ee4b7dfa0ba0.png)

**Meilisearch version:** 
v0.23.1

**Additional context**
1.i create a meilisearch instace by docker:
docker run -d -p 7701:7700 -v D:\tianlinqing\docker_files\meilisearch23\dumps:/dumps -v D:\tianlinqing\docker_files\meilisearch23\data.ms:/data.ms getmeili/meilisearch:v0.23.1
2.os:window10
3.execute environment:powershell based on wsl2 backend
4.in addition:it works well when i change the version of meilisearch as latest(v.26.1)

**Comment by curquiza** [comment] 2022-05-09 12:11
Hello @AlphaPigger 

>  4.in addition:it works well when i change the version of meilisearch as latest(v.26.1)

We only maintain the latest version of Meilisearch. We probably had bugs in previous versions that have been fixed now

I close this! Feel free to open an issue if you have any trouble with the latest version of Meilisearch!

**Closed** 2022-05-09 12:11 UTC
Labels: support

**Comment by AlphaPigger** [comment] 2022-05-09 14:30
Hello @curquiza 
Is there any else way to create the dumps in version v0.23.1?  There are so many datas that must be persisted.Thanks

**Comment by curquiza** [comment] 2022-05-09 16:16
I'm sorry for this issue! I've just tried to create a dump using v0.23.1, but I did not get any problem... the dump was well created.
I can try to help you debug, but I cannot guarantee anything. Can you tell me
- on which OS are you doing the dumps?
- Are you using docker?
- Have you launched Meilisearch with any [commend line option](https://docs.meilisearch.com/learn/configuration/instance_options.html) like `--dump-dir`?

Otherwise, you can fetch your own data using the [`GET /documents` endpoint](https://docs.meilisearch.com/learn/configuration/instance_options.html#command-line-options-and-flags), and put it into the new Meilisearch instance

**Comment by AlphaPigger** [comment] 2022-05-10 01:25
Hello @curquiza 
1.os:window10 based on wsl2
2.docker command:docker run -d -p 7701:7700 -v D:\tianlinqing\docker_files\meilisearch23\dumps:/dumps -v D:\tianlinqing\docker_files\meilisearch23\data.ms:/data.ms getmeili/meilisearch:v0.23.1
Besides,the way you mentioned is to get all documents and add all documents into new Meilisearch?This is so troublesome，but it can be the last way to attempt.
Thanks

**Comment by MarinPostma** [comment] 2022-05-10 10:41
@AlphaPigger, sorry for the inconveniences, this was an issue with former MeiliSearch versions. The issue is that you are creating the dump on a different filesystem than the one the MeiliSearch database is. Can you try to make sure that both the database and the dump path end up on the same filesystem, and try again? This should fix this issue.

This issue should be fixed on newer MeiliSearch versions.

**Comment by AlphaPigger** [comment] 2022-05-10 12:08
Hello @MarinPostma
Creating dumps and importing dumps  both have some problems and it is exactly related to the volumns.I choose another way that recovering data by source data to avoid creating dump. thanks a lot for your reply
