### ISSUE TITLE
Stopwords array is not ordered the same way it has been provided

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2139] opened 2022-02-03 14:15 UTC
**Describe the bug**
When updating stop words for example with `["the", "a"]` the `stopWords` field will return with the following value `["a", "the"]` upon requesting the settings.

**To Reproduce**
1. Go to add synonyms using the `/settings` route with `["the", "a"]` as value.
2. Get the settings
3. They are not in the same order

**Expected behavior**
Keep them in the same order

**Meilisearch version:** 
v0.25.2

**Comment by curquiza** [comment] 2022-02-03 15:01
Hello @bidoubiwa

Indeed, the stop words are not returned the same way as the users sent them, but by alphabetical order.

If I'm not wrong, this behavior has always been the same. At least, I tested with v0.21.0 and v0.18.0 (not before) and the behavior is the same, I mean, they are returned by alphabetical order.

This has been chosen because stop words are designed to receive a huge list, like a dictionary, and the alphabetical order seemed more appropriate.

However, there is currently no spec regarding the stop-words, this will come when we'll stabilize the API for v1.

After this, If you still think this is a behavior that might be changed, please let us know in the product repository, not here (since it's not a bug). This will help the product team create the spec regarding the stop words in the future 🙂

I'm closing this since it's not a bug but an expected behavior. Sorry, there is no spec to document it, but I'm sure you understand why! Be sure it will come! 😄

**Closed by curquiza** 2022-02-03 15:01 UTC
