### ISSUE TITLE
POST requests error to 405

### ISSUE THREAD

**Issue by Calemy** [meilisearch/meilisearch#2619] opened 2022-07-17 01:54 UTC
**Describe the bug**
every POST request sent to meilisearch errors out to 405

**To Reproduce**
1. Install and run meilisearch-http (0.28.0)
2. go to integrated dashboard
3. check your console

**Expected behavior**
the post request going through as usual

**Screenshots**
![](https://x.catboy.best/VVNBsTN.png)

**Meilisearch version:** v0.28.0

**Additional context**
Running on Ubuntu 22.04

**Comment by oluademola** [comment] 2022-07-19 05:59
Hi @Calemy. That is a bit strange. I ran a test from my end and was unable to reproduce the problem. Have you tried restarting the server? Does the problem persist?

<img width="883" alt="Screenshot 2022-07-19 at 06 56 30" src="https://user-images.githubusercontent.com/101267639/179676182-27dcef42-9e7c-437e-99e9-f91d530b9b99.png">

**Comment by Calemy** [comment] 2022-07-19 06:17
I've tried troubleshooting pretty much everything that came up to my mind. I'm really not sure what could cause this since this is the first time i run into this issue

**Comment by oluademola** [comment] 2022-07-19 07:15
Hi @Calemy 

The index `uid` is required to perform a search request. Your route should be in this format `/indexes/{index_uid}/search` and not `/indexes//search`

Hope this helps. Thanka.

**Comment by Calemy** [comment] 2022-07-19 07:16
Trying to create an index does not work either because that also errors to 405 like every other post request

**Comment by oluademola** [comment] 2022-07-19 07:27
Hi @Calemy. How are you creating the index? Have you indexed any data to your meilisearch server? You might want to have a look at the [quick start guide](https://docs.meilisearch.com/learn/getting_started/quick_start.html#setup-and-installation) to get started.

**Comment by Calemy** [comment] 2022-07-19 07:29
I'm using the javascript wrapper and tried to update the filter attributes. When i try that i get the 405

**Comment by oluademola** [comment] 2022-07-19 07:34
Could you show me how you're implementing this?

**Comment by Calemy** [comment] 2022-07-19 07:49
![grafik](https://user-images.githubusercontent.com/45440100/179696334-63de660c-befc-4286-b208-4eadafe47288.png)

**Comment by oluademola** [comment] 2022-07-19 09:08
Hi @Calemy 

With respect to the screenshot above. There is a great chance that you are using Meilisearch v0.28.0 with a JS client that is older. The HTTP methods changed from POST -> PUT in v0.28.0. You must make sure that you use a JS package (v0.27.0) that is compatible with v0.28 to resolve this.

Let me know if this resolves the problem. Thanks.

**Comment by derbl4ck** [comment] 2022-07-20 15:36
Hi @Calemy 

i also have the feeling that this problem is triggered with the version jump from v0.27 to v0.28. Using `getmeili/docs-scraper:v0.12.2` with v0.28 also results in HTTP 405 (e.g. on `POST /indexes/docs/settings`).

We should introduce a compatibility table.

**Comment by oluademola** [comment] 2022-07-21 13:16
Hello @derbl4ck 

Yes, it is. For now, docs-scraper is only compatible with v0.27 and we are sorry for all the breaking changes. You can have a look at the breaking changes introduced with the new version [here](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.1). Also, I suggest you check the compatibility section of your tools or SDK on the repos when considering updating your meilisearch server.

Again sorry for the inconvenience. Thanks.

**Comment by curquiza** [comment] 2022-08-23 12:02
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2022-08-23 12:02 UTC
Labels: support
