### ISSUE TITLE
/stats endpoint internal server error

### ISSUE THREAD

**Issue by djrodgerspryor** [meilisearch/meilisearch#3502] opened 2023-02-16 03:13 UTC
**Describe the bug**
Hitting the stats endpoint on our Meilsearch index reliably produces an HTTP 500 error and an internal error message:

```
curl -v -H "Authorization: Bearer $(chamberprod read -q meilisearch meili_master_key)" 10.8.78.128:7700/stats | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.8.78.128:7700...
* Connected to 10.8.78.128 (10.8.78.128) port 7700 (#0)
> GET /stats HTTP/1.1
> Host: 10.8.78.128:7700
> User-Agent: curl/7.85.0
> Accept: */*
> Authorization: Bearer parq78bdx3bwbh4jadqogchetphh3jr3
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 205
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< content-type: application/json
< date: Thu, 16 Feb 2023 03:06:46 GMT
<
{ [205 bytes data]
100   205  100   205    0     0   4577      0 --:--:-- --:--:-- --:--:--  5000
* Connection #0 to host 10.8.78.128 left intact
{
  "message": "invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `.` at 1",
  "code": "internal",
  "type": "internal",
  "link": "https://docs.meilisearch.com/errors#internal"
}
```

The logs from the server added no additional info; it would be nice to see a full stacktrace there when errors are encountered.

We have only one index, and can read stats for it without issue, so I'm guessing that the problem is in the global stats somewhere:

```
$ curl -H "Authorization: Bearer $(chamberprod read -q meilisearch meili_master_key)" 10.8.78.128:7700/indexes | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   177  100   177    0     0   3862      0 --:--:-- --:--:-- --:--:--  4214
{
  "results": [
    {
      "uid": "compilation",
      "createdAt": "2023-02-09T11:21:50.224338487Z",
      "updatedAt": "2023-02-16T02:58:59.745210844Z",
      "primaryKey": "uuid"
    }
  ],
  "offset": 0,
  "limit": 20,
  "total": 1
}
$ curl -H "Authorization: Bearer $(chamberprod read -q meilisearch meili_master_key)" 10.8.78.128:7700/indexes/compilation/stats | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   363  100   363    0     0   7993      0 --:--:-- --:--:-- --:--:--  8642
{
  "numberOfDocuments": 90348,
  "isIndexing": true,
  "fieldDistribution": {
    "activities": 63389,
    "description": 90348,
    "library_uuids": 90348,
    "publisher_uuid": 90348,
    "release_note": 90348,
    "serial_number": 90348,
    "student_facing_description": 90348,
    "subtitle": 90348,
    "teacher_note": 90348,
    "title": 90348,
    "topic_descriptions": 90348,
    "topics": 90348,
    "uuid": 90348,
    "version_created_on": 90348
  }
}
```

**To Reproduce**
Hit the `/stats` endpoint.

I've only got one server to test this on right now, but I'm planning on cycling to a new one in a few days, so I'll update with whether the error persists.

**Expected behavior**
I expected the stats to be returned with no error.

**Meilisearch version:**
1.0.0

**Additional context**
We're running Meilisearch on an AWS `m6i.2xlarge` instance with 8 vCPU and 32GB of memory with about 43GB of data in the one index.

**Comment by curquiza** [comment] 2023-02-16 15:06
Hello @djrodgerspryor thanks for the report

Is it possible for you to share your dataset so that we can reproduce the issue? Here we don't have enough information to reproduce the bug, and then, fix it

It can be a piece of your dataset, enough to trigger the bug. Or you can send it by email, we only will use it for test purpose, and then, delete it from our machines.

**Comment by irevoire** [comment] 2023-02-16 16:53
Hey @djrodgerspryor, thanks for your report; I looked at the code, and from what I see, it can be only one thing: one of your update files has an invalid file (which is supposed to be impossible).

Could you give me the return of;
```bash
ls -1 data.ms/update_files
```

On my side, it's a list of uuidv4: 
```
% ls -1 data.ms/update_files
221f9d93-3732-4836-8c54-86a5883d2847
578d49df-1813-414f-9ce3-24020f9f67b1
721b579d-9b0e-40f5-a52e-fc5b9a031667
7773cace-3106-440b-86e0-78ee7d17d2b4
eecc5f4a-37a5-434c-bfdc-c1a7c9041e70
```

Also;
1. Did you ever write something in this directory? The `data.ms` is not supposed to be used by anyone else that meilisearch; thus, that could be the cause of the issue
2. What filesystem are you using?
3. And finally, if you want to « hard-fix » the bug, I guess the solution would be to delete everything in this directory once meilisearch has processed all your tasks

**Comment by djrodgerspryor** [comment] 2023-02-16 22:05
Unfortunately I can't share the full dataset because it has some PII in it. I'll see if I can reproduce this on a smaller, clean dataset.

1. Nothing interesting is running on this server aside from meilisearch, so nothing else would have written to the meilisearch data directory
2. We're running `ext4` on the Meilisearch data directory

Here's a listing of all the directories (all of the `update_files` look like real UUIDs to me):
```
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ pwd
/meilisearch/data
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l
total 44
drwxr-xr-x 2 root root  4096 Feb  8 12:15 auth
drwxr-xr-x 2 root root  4096 Feb  8 12:15 dumps
drwxr-xr-x 3 root root  4096 Feb  9 11:21 indexes
-rw-r--r-- 1 root root    36 Feb  9 10:35 instance-uid
drwxr-xr-x 2 root root  4096 Feb  8 12:15 tasks
drwxr-xr-x 2 root root 20480 Feb 16 22:00 update_files
-rw-r--r-- 1 root root     5 Feb  9 10:35 VERSION
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l
total 44
drwxr-xr-x 2 root root  4096 Feb  8 12:15 auth
drwxr-xr-x 2 root root  4096 Feb  8 12:15 dumps
drwxr-xr-x 3 root root  4096 Feb  9 11:21 indexes
-rw-r--r-- 1 root root    36 Feb  9 10:35 instance-uid
drwxr-xr-x 2 root root  4096 Feb  8 12:15 tasks
drwxr-xr-x 2 root root 20480 Feb 16 21:56 update_files
-rw-r--r-- 1 root root     5 Feb  9 10:35 VERSION
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l auth/
total 52
-rw------- 1 root root 49152 Feb  8 12:15 data.mdb
-rw------- 1 root root  8192 Feb 16 00:00 lock.mdb
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l dumps
total 0
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l indexes
total 4
drwxr-xr-x 2 root root 4096 Feb  9 11:21 b5aab3bb-c11c-44db-853b-fce1d0da4d8d
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l indexes/b5aab3bb-c11c-44db-853b-fce1d0da4d8d/
total 42415708
-rw------- 1 root root 43433672704 Feb 16 21:59 data.mdb
-rw------- 1 root root       65664 Feb 16 21:59 lock.mdb
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l tasks
total 37184
-rw------- 1 root root 38068224 Feb 16 21:59 data.mdb
-rw------- 1 root root     8192 Feb 16 21:59 lock.mdb
[ec2-user@meilisearch-i-09c93025706d712fc.au.s522.net data]$ ls -l update_files/
total 640
-rw------- 1 root root  45578 Feb 16 21:51 0a3cf2ed-2b21-452f-881a-9a9a8f46e7c5
-rw------- 1 root root   4898 Feb 16 21:59 1772d076-a4f8-4123-a6d0-bb0ed49bfb40
-rw------- 1 root root  45578 Feb 16 21:51 25284af0-bc61-4e6e-81b1-871933c30f52
-rw------- 1 root root   4898 Feb 16 21:59 2cf05376-329c-4d0f-8b35-d6dafb3dc68c
-rw------- 1 root root 240160 Feb 16 21:55 39e179ad-8433-4cea-80e8-53453abb0289
-rw------- 1 root root    583 Feb 16 21:52 434ad787-a358-4d41-8478-786870fc4c20
-rw------- 1 root root  19753 Feb 16 21:53 87f23f95-fe55-4cdb-a9a4-38ff54632bff
-rw------- 1 root root    654 Feb 16 21:55 93d9594b-234b-4365-bdf7-108c962664a4
-rw------- 1 root root 240160 Feb 16 21:56 c5a5eedb-57d1-446a-9e91-307bb4bf3b11
-rw------- 1 root root    583 Feb 16 21:49 cb279574-d16f-4aa8-a9ed-8e065ec312a9
-rw------- 1 root root    654 Feb 16 21:54 d844a667-9b8f-484d-b745-0197c48d2350
-rw------- 1 root root  19753 Feb 16 21:53 de1b4472-62c7-4bbf-b5b2-dc316e440e6c
```

**Comment by djrodgerspryor** [comment] 2023-02-20 20:58
Ah, excellent point. Sure enough there is something there:
```
$ ls -lah update_files/
total 40K
drwxr-xr-x 2 root root  36K Feb 20 20:46 .
drwxr-xr-x 7 root root 4.0K Feb  8 12:15 ..
-rw------- 1 root root    0 Feb  9 22:23 .tmpVBMIzN
```

No idea what created it, but it looks like an empty temp file which didn't get clean up somehow.

After deleting it, everything works perfectly. Thanks for your help working this one out!

**Comment by curquiza** [comment] 2023-02-23 15:42
Closed by https://github.com/meilisearch/meilisearch/pull/3528, will be present in v1.0.2 release

**Closed by curquiza** 2023-02-23 15:42 UTC
Labels: bug
