### ISSUE TITLE
Confusing matches in `_matchesPosition` when using phrase search

### ISSUE THREAD

**Issue by LukasKalbertodt** [meilisearch/meilisearch#4732] opened 2024-06-26 12:29 UTC
> **This issue is open to contribution, for more information see the below comment:**
> https://github.com/meilisearch/meilisearch/issues/4732#issuecomment-2202282648

**Describe the bug**
Given this document:

```json
{
    "id": "123",
    "text": "Lorem ipsum dolor sit amet"
}
```

Searching for `"Lorem ipsum"` (phrase search!) and setting `showMatchesPosition: true`, returns this:

```json
{
  "id": "123",
  "text": "Lorem ipsum dolor sit amet",
  "_matchesPosition": {
    "text": [
      { "start": 0, "length": 5 },
      { "start": 6, "length": 5 }
    ]
  }
}
```

This is unexpected for phrase search, I think. I would have expected one match range that encloses all of "Lorum ipsum". 

**To Reproduce**
1. `curl -H 'Content-Type: application/json' 'localhost:7700/indexes' --data '{"uid":"test","primaryKey":"id"}'`
2. `curl -H 'Content-Type: application/json' 'localhost:7700/indexes/test/documents' --data '[{"id":"123","text":"Lorem ipsum dolor sit amet"}]'`
3. `curl -H 'Content-Type: application/json' 'localhost:7700/indexes/test/search' --data '{"q":"\"Lorem Ipsum\"","showMatchesPosition":true}'`

**Expected behavior**
Getting one match position back that encloses the full phrase: `{ start: 0, length: 11 }`

**Meilisearch version:**
v1.8

**Comment by ManyTheFish** [comment] 2024-06-27 06:05
Hello @LukasKalbertodt,
I understand your report, and I hesitated to merge phrase matches when I implemented the feature.
However, this way of highlighting allows us to retrieve the matches word-by-word, which can be useful in some cases. 🙂 
It's not a bug; the matching positions match words or prefixes.

Is there a use case that absolutely needs these matches to be merged?

Thanks!

**Comment by LukasKalbertodt** [comment] 2024-06-27 07:01
Mhhh I can't yet think of use cases for the current behavior :thinking: 
But I suppose if you treat it like a feature, then it would be hard to change it without breaking stuff. 

> Is there a use case that absolutely needs these matches to be merged?

"Absolutely" is a strong word. As a user, I would prefer my whole phrase highlighted. I think it makes more sense and gives immediate feedback that the query is indeed understood as a phrase search. But the spaces between the words not being highlighted is probably not a huge deal for most users. 

And I suppose I, as a dev, can still merge the match myself: since it's phrase search, there is no typo tolerance and I can just compare the query vs the merged match. 

Still, I think the behavior should be different and I would be glad if you'd reconsider, but of course you might as well close this as wont fix and it'll be fine.

**Comment by ManyTheFish** [comment] 2024-07-02 08:18
Hello!
After discussing this with the team, we agree to change the behavior of the match positions when computing a phrase search.
However, it's not a priority for the team, so I explain how to change the behavior below for an external contribution.

First of all, the changes are localized in the [`matches/` folder](https://github.com/meilisearch/meilisearch/tree/main/milli/src/search/new/matches). 
The `mod.rs` file contains the [Matcher](https://github.com/meilisearch/meilisearch/blob/809e742253511dae3adab970592f5a76f8c7d182/milli/src/search/new/matches/mod.rs#L108-L118) in charge of the whole matching/highlighting algorithm, the `matching_words.rs` contains the [MatchingWords](https://github.com/meilisearch/meilisearch/blob/809e742253511dae3adab970592f5a76f8c7d182/milli/src/search/new/matches/matching_words.rs#L27-L32) in charge of categorizing if a token matches or partially matches a query word or query phrase.

To change the behavior, the [`compute_partial_match(..)` function](https://github.com/meilisearch/meilisearch/blob/809e742253511dae3adab970592f5a76f8c7d182/milli/src/search/new/matches/mod.rs#L125-L174) should be changed; this function is in charge to register or not a set of tokens as matches for a phrase or not. If the set of tokens matches a query phrase, each token is registered as an independent match.
This should be changed to consider the whole set of tokens as a unique match.

I put this issue as a `good first issue`.

**Comment by flevi29** [comment] 2024-09-11 14:40
Okay, I just did that and it sort of works, but whatever is using the matcher only cuts the first token/word.
![image](https://github.com/user-attachments/assets/6fe8670e-e908-4604-8550-cee653c1569d)

EDIT: It's `format` on the `Matcher`

**Comment by ManyTheFish** [comment] 2024-09-12 06:41
Hello @flevi29,
I may help you for this, don't hesitate t create a draft PR with your changes, this way I can suggest changes more easily.
Don't hesitate to ping me on it 😄

**Comment by flevi29** [comment] 2024-09-12 14:07
Hello @ManyTheFish, I've opened a draft PR.

**Closed** 2024-11-06 08:55 UTC
Labels: bug, good first issue
