### ISSUE TITLE
Internal Error: Decoding failed

### ISSUE THREAD

**Issue by leottk** [meilisearch/meilisearch#2871] opened 2022-10-07 08:14 UTC
**Describe the bug**

Hello,

I open the second issue because i'm not sure that is the same type of error 

```json
{"uid":2904,"indexUid":"immobilier","status":"failed","type":"documentAddition","details":{"receivedDocuments":22190,"indexedDocuments":0},"error":{"message":"internal: decoding failed.","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"},"duration":"PT4639.245112269S","enqueuedAt":"2022-08-12T23:02:48.917021644Z","startedAt":"2022-08-15T08:18:12.513009311Z","finishedAt":"2022-08-15T09:35:31.758121580Z"}

{"uid":2873,"indexUid":"immobilier","status":"failed","type":"documentAddition","details":{"receivedDocuments":17941,"indexedDocuments":0},"error":{"message":"internal: decoding failed.","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"},"duration":"PT5007.311464276S","enqueuedAt":"2022-08-12T23:02:24.942854005Z","startedAt":"2022-08-13T13:58:28.432752350Z","finishedAt":"2022-08-13T15:21:55.744216626Z"}

{"uid":2878,"indexUid":"immobilier","status":"failed","type":"documentAddition","details":{"receivedDocuments":17778,"indexedDocuments":0},"error":{"message":"An internal error has occurred. `panic`.","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"},"duration":"PT1447.543833492S","enqueuedAt":"2022-08-12T23:02:29.054549684Z","startedAt":"2022-08-13T21:11:26.590928297Z","finishedAt":"2022-08-13T21:35:34.134761789Z"}
```

**To Reproduce**

This is the first time i use Meilisearch so i don't know how to reproduce, i just checked the Meilisearch documentation to see the Error code and open this issue.

Pls help me to resolve this bug.

**Meilisearch version:** [v0.25.2]

**Comment by oluademola** [comment] 2022-10-10 13:59
Hello @leottk 

Sorry for the inconvenience and thank you for using Meilisearch! Since this is your first time, I'd encourage you always install or run on the latest version of Meilisearch so that you have the best service experience (meaning you'll enjoy the latest performance improvements of the search engine and bug fixes). Regarding the error, to better assist you and for more context, what format and type of data are you trying to index to meilisearch? It is worth noting that Meilisearch accepts datasets in JSON, CSV, and NDJSON only. 

Looking forward to your response. Thanks 🙂

**Comment by leottk** [comment] 2022-10-11 14:57
Hello @oluademola,

Thank you for your advices,

To answer your question, we used JSON format to index to Meilisearch

**Comment by oluademola** [comment] 2022-10-11 16:39
Hello @leottk 

Thank you for your response. Unfortunately, I am unable to reproduce this problem even with v0.25. Also, this is a really old version of Meilisearch and does not qualify for bug fixes. I encourage you to try indexing your dataset with the latest version of the engine (v0.29), and if this issue persists, we'd be more than happy to request a sample of your dataset to investigate further.

Thanks again!

**Comment by leottk** [comment] 2022-10-12 08:45
Hello @oluademola,

Thank you for your response, 

At this moment, its hard for us to update the new version of Meilisearch because its linked to many changes in our products so i would like to demand you if we can retrieve the failed files in which contains the update_ids above to verify if we got some errors in the data set. 

I checked the logs file and i got this report below: 

```

 - Error : update_ids [2865, 2904, 2873, 2878] have failed. Please investigate.+
                                                                                +
  - 51 files successfully processed in a month

To check update status and log message :
curl -H 'Content-Type: application/json' -H "Authorization: Bearer MASTER_KEY" -X GET "[http://SERVER_IP:PORT/tasks/UPDATE_ID]http://SERVER_IP:PORT/tasks/UPDATE_ID"

Failed files are stocked in the 'failures_to_investigate' directory.

```
If we have access to the folder failures_to_investigate, its could help us to understand the error :)

Thank you for your help, 

Kind regards,

**Comment by leottk** [comment] 2022-10-14 10:26
Hello @oluademola,

We found the dataset in which contains errors. 

[update_to_update_03_2022-08-13.zip](https://github.com/meilisearch/meilisearch/files/9785018/update_to_update_03_2022-08-13.zip)

And this one work without error:
[update_to_update_9015_2022-10-08.zip](https://github.com/meilisearch/meilisearch/files/9785136/update_to_update_9015_2022-10-08.zip)

Hope you can help us to resolve this error, 

Thanks again !

**Comment by oluademola** [comment] 2022-10-21 12:44
Hi @leottk,

The JSON dataset provided above is not a valid JSON. You can confirm this with a JSON validator (such as https://jsonlint.com/). The screenshot below shows your dataset validation result on the JSONLint validator, indicating the missing syntax. 

<img width="362" alt="Screenshot 2022-10-21 at 12 55 18" src="https://user-images.githubusercontent.com/101267639/197198457-f4d2ef63-e06d-4c49-afc9-1a0676e4611e.png">

This could be resolved by formatting your dataset to a valid JSON array (For example: by wrapping the objects in a square bracket `[]`, making it a valid JSON array, and separating the objects with a comma `,` appropriately). 

I hope this helps. Thanks!

**Comment by leottk** [comment] 2022-10-21 14:59
Hello @oluademola ,

Thank you for your response. 

This file is a raw file. Before indexing, I have already corrected this error and wrapping the object in a square bracket and separating the objects with à comma. But when indexing we always have this error.

**Comment by oluademola** [comment] 2022-10-21 15:20
Hello @leottk 

Could you please share the valid JSON dataset you're indexing?

Thanks.

**Comment by curquiza** [comment] 2022-11-24 16:39
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2022-11-24 16:39 UTC
Labels: support
