### ISSUE TITLE
Change of behaviour in facets when using distinct attribute

### ISSUE THREAD

**Issue by jordyw-exsited** [meilisearch/meilisearch#3235] opened 2022-12-13 10:30 UTC
I am not sure if this is an actual bug or it is inteded to work like this, however it is a functional change that happened somewhere between versions 0.28.0 and 0.30.2. 

When you would have multiple documents that are grouped together using a distinct attribute and you would like to get the facet counts on an attribute I would expect to get all different values of that facets for the entire group of documents, like it used to be.
To illustrate more in depth what I'm trying to achieve I'll be using an example from the Meilisearch docs:

```
[
  {
    "id": 1,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "brown",
    "product_id": "123456"
  },
  {
    "id": 2,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "black",
    "product_id": "123456"
  },
  {
    "id": 3,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "blue",
    "product_id": "123456"
  }
]
```

Let's say we have the above product that we'll group together using the `product_id` field as a distinct attribute. When I would search for `"leather jacket"` I would see 1 product. However when I use `color` as filterable attribute I would expect to get the facets for each available color in the group. returning the following:

```
    "facetDistribution": {
        "color": {
            "brown": 1,
            "black": 1,
            "blue": 1
        }
    }
```

Whereas now I only get:

```
    "facetDistribution": {
        "color": {
            "brown": 1
        }
    }
```

This makes it rather impossible to render all correct filters using a count.

**To Reproduce**
1. Use the above json to add documents to the index.
2. Set `product_id` as the distinct attribute on the index.
3. Add `color` to the filterable attributes.
4. Search with following query:

```
{
    "q": "",
    "facets": [
        "color"
    ]
}
```

**Meilisearch version:**
v0.30.2

**Comment by mmachatschek** [comment] 2022-12-13 12:21
@jordyw-exsited we are using distinct attributes too and we have the exact opposite conclusion 😅 I actually think that the behaviour described by you is correct.

When we need to have attributes that count to all products on a index with distinct attribute set, we just add an additional attribute.

```json
[
  {
    "id": 1,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "brown",
    "colors": ["brown", "black", "blue"],
    "product_id": "123456"
  },
  {
    "id": 2,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "black",
    "colors": ["brown", "black", "blue"],
    "product_id": "123456"
  },
  {
    "id": 3,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "blue",
    "colors": ["brown", "black", "blue"],
    "product_id": "123456"
  }
]
```

if you then check the facetsdistribution response you get:

```json
{
    "facetDistribution": {
        "colors": {
            "brown": 1,
            "black": 1,
            "blue": 1
        }
    }
}
```

**Comment by jordyw-exsited** [comment] 2022-12-13 12:30
@mmachatschek This could indeed work, but this seems a bit like duplicate data to me. 

For now I'll implement it the way you describe. Thanks for the explanation.

**Comment by ManyTheFish** [comment] 2022-12-13 13:59
hello @jordyw-exsited, it seems that you want a [disjunctive facet distribution](https://github.com/meilisearch/product/discussions/187), but unfortunately we don't support it so far.
About this change of behavior, we will investigate why v0.28 is different, but the current behavior is the expected one.

However, I can suggest a workaround to avoid duplicating data in your documents by doing 2 search queries:
1) a first query that will be used to fetch the results and the number of hits: `{"q": "Leather jacket", "filter": "color = brown"}`
2) a second query without filters to fetch the facet distribution `{"q": "Leather jacket", "facets": ["color"], "attributesToRetrieve": []}`

> note that if you use the finite pagination attributes (`page`, `hitsPerPage`), you should instead replace the second query by `{"q": "Leather jacket", "facets": ["color"], "page": 0}`

> note that there is a bug on finite pagination in v0.30.1 and v0.30.2 that should be fixed in v0.30.3

**Comment by loiclec** [comment] 2022-12-13 15:36
I followed the steps to reproduce given in the description of the issue using Meilisearch v0.28.0, but I got the same result as in v0.30.0:
```json
  "facetDistribution": {
    "color": {
      "brown": 1
    }
  }
```

**Comment by curquiza** [comment] 2023-01-24 17:02
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-01-24 17:02 UTC
Labels: support
