### ISSUE TITLE
Request to `/health` results in `OpenSSL/3.0.11: error:0A00010B:SSL`

### ISSUE THREAD

**Issue by newdev8** [meilisearch/meilisearch#4143] opened 2023-10-19 22:33 UTC
**Describe the bug**
When sending a cURL request to `/health` I get the error `curl: (35) OpenSSL/3.0.11: error:0A00010B:SSL routines::wrong version number`

**To Reproduce**
1. Run `curl -X GET 'https://localhost:7700/health' -H "Authorization: Bearer xxxxxxxxxxxxxxx"`
2. See error

**Expected behavior**
It should return the status.

**Screenshots**
Not applicable

**Meilisearch version:**
v1.4.2, also happens in v1.4.1, I don't know if it also happens in previous versions.

**Additional context**
Raspberry Pi 4B 8GB running Gentoo on kernel 6.5.7.
I setup a self-signed certificate for Meilisearch which is trusted by the system.

**Comment by curquiza** [comment] 2023-10-23 14:10
Hello @curquiza 
I'm sorry but I don't succeed in reproducing your issue.
I cannot test on a Raspberry Pi, but we have some users using it and they don't get the issue.

It looks like it's more an error on your side with security and OpenSSL rather than in Meilisearch. I'm sorry but I'm afraid we couldn't help you that much here 😕
Maybe this can help you: https://syntaxfix.com/question/389/curl-35-error-1408f10b-ssl-routines-ssl3-get-record-wrong-version-number

**Comment by curquiza** [comment] 2024-01-03 17:16
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-01-03 17:16 UTC
Labels: support
