### ISSUE TITLE
Precise match instead of typo tolerant?

### ISSUE THREAD

**Issue by iredmail** [meilisearch/MeiliSearch#1106] opened 2020-11-25 14:37 UTC
Dear developers,

I understand MeiliSearch supports typo tolerant, but does it support precise search?
For example, i store shasum256 in meilisearch and search it, will it match similar shasums due to the typo tolerant? Anyway to precise match the query string like a MySQL server?

**Comment by bb** [comment] 2020-11-25 15:39
This looks like a duplicate of #1103. If you want to do exact match on the full field instead of `contains`, you may want to use a facet filter. Those work fine for me.

**Comment by theo-lubert** [comment] 2020-11-26 14:45
Facet filtering is not an option in many cases, especially for auto-completion.

**Comment by qdequele** [comment] 2020-12-03 16:36
Hello,

I created a feature for that on our [public roadmap](https://roadmap.meilisearch.com/c/61-policy-for-prefix-search?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.

**Closed** 2020-12-05 10:14 UTC
Labels: type:feature-proposal
