### ISSUE TITLE
Snapshot file permissions changed in v0.24.0

### ISSUE THREAD

**Issue by gmatt** [meilisearch/MeiliSearch#1956] opened 2021-12-01 14:05 UTC
**Describe the bug**
The created snapshots have 600 unix file permissions, whereas previously, they had 644.

With an older Meilisearch version (v0.22.0, I believe), the created snapshots had different unix file permissions than with v0.24.0.

```
-rw-------   1 user  group   2.4M  1 Dec 13:48 data.ms.snapshot
-rw-r--r--   1 user  group   1.2M 22 Nov 11:59 data.ms.snapshot_1141
```

This change broke our workflow. On CI, we use a docker container to create a snapshot, which we deploy at a later stage. We save the snapshot to a volume attached to the docker container.
When deploying the snapshot, we get a permission issue.  
In the newer Meilisearch docker images, the default user was changed, so on the host image filesystem, the owner of the file will be different, and as the permissions also changed, the current user won't have read permission to the file.

Is there a reason to change the 644 permissions to 600?

If there is, then we'll find another solution.

Sorry for any potentially missing information.

**To Reproduce**
Create a snapshot on a unix system with Meilisearch v0.24.0.

**Expected behavior**
The snapshot should have 644 permission.

**MeiliSearch version:** v0.24.0.

**Additional context**
Environment:
Ubuntu 18.04.6 LTS

**Comment by MarinPostma** [comment] 2021-12-01 14:23
@gmatt thanks for the report. This is not intentional, I wonder what the cause of that is. I am currently investigating the issue. This will be fixed in 0.25.0 :)

**Closed** 2021-12-03 12:06 UTC
Labels: bug
