### ISSUE TITLE
Attributes known by MeiliSearch but invisible for the user

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#767] opened 2020-06-10 13:00 UTC
Related to [this comment](https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641320322) in [this discussion](https://github.com/meilisearch/MeiliSearch/issues/761).

There are some situations where MeiliSearch knows information that the user cannot guess.

Example:

- I add a document with `title` and `author` attributes.
- I update the settings to only have `title` as displayed and searchable attributes -> now, I cannot see any `author` in my settings and in my documents either.
- I add another document with `title` and `author`

The `author` field is not considered as a **new** field and is not added to the searchable and displayed attributes (we can expect this addition because the `acceptNewFields` boolean is set to `true` by default in my settings).

But here, for MeiliSearch, `author` is not a **new** field.

In [your comment](https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641901020) @Kerollmops you say:

> We must not save an attribute that will never be used (not in the settings) and consider it a new attribute if we see new documents containing it (because we must not be aware of it) #761 (comment).

I understand here you want to remove the `author` field from MeiliSearch if it's not used in the settings or in the documents.
But what about the information (= the value) in the document for the `author` field?
The user might have miss-manipulated the settings and wants the `author` field to come back right after. We cannot erase their data.
(Hope I'm clear)

I don't know what is the best behavior to adopt. Maybe having an entrypoint in the API to know what MeiliSearch knows...? I mean, all the attributes it already knows and to which you can access/manipulate with your settings...?

**Comment by MarinPostma** [comment] 2020-06-15 11:01
IMO, if a field is no present in the settings, then it should be forgotten.  We could return the list to the user as a read-only list, but that would not make much sense because he wouldn't be able to edit it, and if he could, that would lead to potentially inconsistent states  and we don't want that. 

It's easy enough to check what fields are still used upon setting update and forget the one that are not used.

> The user might have miss-manipulated the settings and wants the author field to come back right after. We cannot erase their data.

In this case, he'll go through re-indexing, be he would probably have any way when updating his settings... I see no real issue here

**Comment by curquiza** [comment] 2020-06-15 12:56
Ok, so for you guys @MarinPostma and @Kerollmops, it's not a problem to erase the user data, if I understand well, right?

I don't have any strong opinion on that since MS is not really a DB...

What do you think @eskombro and @bidoubiwa?

**Comment by MarinPostma** [comment] 2020-06-15 13:07
Well we're not **really** erasing user data... Just the way his data is stored. If the user puts back the setting, the engine will go through reindexing, and the previous state will be restored without any more input from his side

**Comment by Kerollmops** [comment] 2020-06-15 13:37
Yeah, the problem is if the user:
 - Adds documents containing the `title` and `author` fields
 - Removes the `author` field from the searchable and displayed attributes settings. The field doesn't exists in the settings anymore so we remove it from the database entirely.
 - Adds the `author` field to the distinct attribute for example, the engine will just not be aware of this fielda anymore and the distinct will not work.

We should probably inform users about this behavior, at least on the documentation. That at any moment in time only the fields that are present in the settings are kept in memory and any field that is removed from there will be completly forgotten by the engine. He must do all the settings changes at the time to be sure to not loose data.

**Comment by MarinPostma** [comment] 2020-06-15 17:01
> we remove it from the database entirely.
we remove it from the schema, it will still belong to the document right?

But what if:
- user adds documents with `title` and `author`
- remove all `authors` occurences` from settings
- add new documents with `accept_new_fields` set to true

in this case the `author` field becomes a new field once again and is set as searchable and displayed attribute, but if the user purposely removed author, this becomes an issue.

That last point makes me think that we shouldn't remove the field

**Comment by bidoubiwa** [comment] 2020-06-16 09:26
isn't the [data never erased](https://docs.meilisearch.com/guides/advanced_guides/field_properties.html#data-storing) (scroll down docs already exist). It is just stored until it is either displayed or searchable, in which case MeiliSearch will re-index that data and it will be visible again ?

>Removes the author field from the searchable and displayed attributes settings. The field doesn't exists in the settings anymore so we remove it from the database entirely.

Does this mean the field is not stored in any way?

Could we not add a field in the settings called "knownFields" or something like that? Were the user would be able to remove the field from the known fields if he wants the automatic behavior again?

**Comment by MarinPostma** [comment] 2020-06-16 19:41
yes sure! we need to keep in mind that when a user removes a field from `knownFields`, all occurences of this field in the setting should be removed as well, as we remove it from the schema and references to that field would break db's consistency. Are we all fine with this?

**Comment by eskombro** [comment] 2020-06-17 10:56
IMO this makes everything clear and transparent for the user. If your field name is present in knownFields, it wont be ever treated as a new field, but if you remove it explicitly from knownFields, you are clearly asking MeiliSearch to forget everything he knows about that field. So you don't actually need to check if a field is present in some document or some setting every time you modify your settings to be able to estimate the behavior and not risk losing your data! I like it

**Comment by curquiza** [comment] 2020-06-17 11:24
@MarinPostma, before coding, could you describe better the behavior of the `knowFields` settings?
- get/update/reset sub-routes (because I guess there will be)
- the default value of this settings (`[]`?)
- ...

**Comment by MarinPostma** [comment] 2020-06-17 11:51
@curquiza I'll update the tracking issue with the details

**Comment by curquiza** [comment] 2020-06-17 12:17
Sorry I forgot to ask that:
Could you detailed in which case the `knownFields` would be updated.
I think about:
- when adding documents with new fields
- when creating a custom ranking rules (ex: `asc(author)`)
- when adding a search atrtributes...
- ...

### Behavior question

If I add `author` in `searchableAttributes`, it will be added into `knownFields`. After that, If I remove `author` from `searchableAttributes` and I don't have any document with `author`, what is the expected behavior? To be removed from `knownFields` or not?
I would say yes, it should be removed from `knownFields` if there is no document (and no settings) with `author`, but should stay in `knownFields` if any documents of settings would contain `author`.
Do you agree with that @eskombro, @bidoubiwa, @Kerollmops, @MarinPostma ?
Is it doable @MarinPostma and @Kerollmops?

**Comment by MarinPostma** [comment] 2020-06-17 12:40
well I thought that we'd just expose the Schema that we have currently. I think this should be as simple as possible. When we remove a field from the known fields, we have no other choice but remove all occurences to keep the state valid. However, the case you mention makes things more complicated IMO, and the benefit is not clear to me. What if I add a field to the known fields and there are no mention of it anywhere else, do I delete it? How do I know how it was added to the database in the first place?

**Comment by curquiza** [comment] 2020-06-17 12:45
> What if I add a field to the known fields and there are no mention of it anywhere else, do I delete it? How do I know how it was added to the database in the first place?

You completely right, make it simple!

**Comment by MarinPostma** [comment] 2020-06-17 12:57
>It's been decided that there will be a list of known attributes in the the settings.
>
>once a field is forgotten, all references to it are forgotten to, to keep db consistent.
three new setting routes are added:
GET /indexes/:index_uid/settings/known-fields: returns [Strings] containing all known fields
POST /indexes/:index_uid/settings/known-fields: takes a body of [Strings] containing each known field
DELETE /indexes/:index_uid/settings/known-fields/ resets all known fields disclosure: this is dangerous, and must be used with caution
you can find these settings in the "all settings" route as usual
As a last note, this really is a power-user setting, and users should be warned that this can be dangerous to use

do we agree on that? from #778

**Comment by curquiza** [comment] 2020-06-17 13:10
> DELETE /indexes/:index_uid/settings/known-fields/ resets all known fields

Does it means that the `knownFields` is set back to its default value? Is the default value an empty array`[]`?

**Comment by MarinPostma** [comment] 2020-06-17 13:12
Yes

**Comment by Kerollmops** [comment] 2020-06-17 14:05
Hey,

What would happen in this situation:
 - the user add the `asc(price)` criterion to the ranking rules, the `price` field is automatically added to the `knowFields`.
 - the user remove this `price` field from the `knownFields` list.

Do we need to remove the `asc(price)` criterion without telling the user? Or do we need to throw an error telling the user that the attribute must not appear in any other setting before behing able to remove it from the `knownFields`?

**Comment by MarinPostma** [comment] 2020-06-17 14:09
+1 @Kerollmops I agree that warning the user about that would be better

**Comment by curquiza** [comment] 2020-06-17 14:09
> What would happen in this situation:

    the user add the asc(price) criterion to the ranking rules, the price field is automatically added to the knowFields.
    the user remove this price field from the knownFields list.

> Do we need to remove the asc(price) criterion without telling the user? Or do we need to throw an error telling the user that the attribute must not appear in any other setting before behing able to remove it from the knownFields?

I would rather the error.

**Comment by Kerollmops** [comment] 2020-06-17 14:13
Warning the user about forcing him to first remove the `price` field from every setting is also against our "simplicity" focus. Where the user needs to perform two updates to do what he wanted to do in the first place.

I will not hide it to you but I`m not a huge fan of this `knowFields` setting, it fix of issue but create others.

**Comment by curquiza** [comment] 2020-06-17 14:16
> I will not hide it to you but I'm not a huge fan of this knowFields setting, it fix of issue but create others.

Hum, you're right, without starting to code we can find out a lot of weird behavior...
What do you think then @Kerollmops? If the field is not found in any settings or documents, we remove it from the schema and we lost the user data?

**Comment by MarinPostma** [comment] 2020-06-17 14:44
So we do nothing?

**Comment by bidoubiwa** [comment] 2020-06-18 11:12
> If the user removes an attribute from all of the settings then the attributes will be added again if it is still present in the new documents added by the user.

> For 1. I keep this behavior, some users will probably don't understand it, but this is the easiest one to understand and to deal with. If you no more want to have your fields added you can either not unset acceptNewFields or remove these fields from your documents.

This is not the behavior as of today? Maybe I understand badly but is it not the opposite?

> For 2. I would change this engine behavior and completly remove the field and associated data from the KV store when the field is no more in the settings. Do I miss something with this behavior, I remember that there were a problem with that (moving a field from one setting to another by doing it in two steps is not possible).

Is this a suggestion? Where if the attribute is no more in the settings it is no more a known field? Resolving the problem of this issue?

**Comment by mccordnate** [comment] 2020-06-26 02:26
> For 2. I would change this engine behavior and completly remove the field and associated data from the KV store when the field is no more in the settings. Do I miss something with this behavior, I remember that there were a problem with that (moving a field from one setting to another by doing it in two steps is not possible).

Does this use case make sense as a potential edge case for this solution?

- User creates field: `date` (using epoch time)
- `date` is not searchable or displayed
- Searches are filtered using `date`

The justification for a user doing this:

1. User didn't want to expose `date` via searchableAttributes as `date` number would be meaningless for regular search results
2. User didn't want to expose `date` via displayedAttributes as they didn't need `date` information in front end

**Comment by Kerollmops** [comment] 2020-06-26 09:01
Yeah @mccordnate you make a good point here!

This is a problem as you point out and Algolia was pretty smart about that as it is impossible to filter documents by using attributes that are not registered as facets IIRC.

One potential way of fixing this edge case and keeping the current behavior (removing attributes which are not in the settings) is by adding a `attributes_for_filtering` setting where the user can list field that are used for filtering, however I am not in favor of this solution as it kind of complexifies the use of filters, a user needs to add the filter before behing able to filter on it.

One another way could be to do the same as Algolia, only attributes that are marked as facets can be used for filtering, this is a great solution as it allows futur performance improvements. The current filter implementation is lazy, it deserialize each document field one by one when a filter as been requested, it is [_O(N)_ where _N_ is the number of candidates documents for the worst case](https://en.wikipedia.org/wiki/Time_complexity#Table_of_common_time_complexities) (filtering on documents ids is the worst thing you can do). Declaring attributes as faceted allows the engine to categorize (aggregate) documents by their attribute values **at compile time** and therefore the engineis able at query time to retrieve the bast documents without having to walk through all the candidates documents but through the values and in the order it wants (ascending or descending values).

The second solution will be harder to make but it is the best one, we will need to support numeric facets (not that hard) and to rework the current filtering system (no more _O(N)_). I am not sure if we want to dive into this right now but this is currently the best solution I have in mind.

We could also keep the system like it is right now (hidding known attributes to the user) or implement the first solution I proposed and keep it temporarily (the `attributes_for_filtering`).

**Comment by bidoubiwa** [comment] 2020-07-01 11:03
What do you think of this solution for the settings

## Settings behavior
`SearchableAttributes`: Accepts all new fields found in added documents, if `acceptNewFields` is `true` and if the field is not in the `ignoreField` list. 
`DisplayedAttributes`: Accepts all new fields found in added documents, if `acceptNewFields` is `true` and if the field is not in the `ignoreField` list.
`IgnoreField`: Fields in this array will be ignore in all automatic settings behavior (i.e: searchable and displayed)
`AcceptNewField`: If set to true, add all new fields found in added documents and not present in `ignoreFields` will be addded to `searchableAttributes` and `displayedAttributes`. 

If a field is removed from the ignoreFields list, then at the next occurence in a document, it will be added to SearchableAttributes and DisplayedAttributes.

### Exemple where field is ignored
1. Update settings
`POST /settings`
```
{
  attributesForFaceting: ['genre']
  searchableAttributes: [],
  displayedAttributes: [],
  ignoreFields: ['genre'],
  accepteNewFields: true
}
```

2. Add document
```json
{
  id: 1
  title: "Batman"
  genre: "Thriller"
}
```

3. Get settings after document has been indexes
`GET /settings`
```json
{
...
    attributesForFaceting: ['genre']
    searchableAttributes: ['id', 'title'],
    displayedAttributes: ['id', 'title'],
    ignoreFields: ['genre'],
    accepteNewFields: true
}
```

### Exemple where field is not ignored
1. Update settings
`POST /settings`
```
{
  attributesForFaceting: ['genre']
  searchableAttributes: [],
  displayedAttributes: [],
  accepteNewFields: true
}
```

2. Add document
```json
{
  id: 1
  title: "Batman"
  genre: "Thriller"
}
```

3. Get settings after document has been indexes
`GET /settings`
```json
{
...
    attributesForFaceting: ['genre']
    searchableAttributes: ['id', 'title', 'genre'],
    displayedAttributes: ['id', 'title', 'genre'],
    accepteNewFields: true
}
```

**Comment by qdequele** [comment] 2020-12-05 17:43
One part of this issue has switched to a spec on https://github.com/meilisearch/specifications/pull/3. The other will be rediscussed later. But I think this issue is not relevant anymore. Please reopen it if I'm wrong.

**Closed by qdequele** 2020-12-05 17:43 UTC
