### ISSUE TITLE
[It's a feature request] while hovering on social media logos can we change their color to their original color (i.e Blue color for Twitter etc)

### ISSUE THREAD

**Issue by UtkarshMishra12** [meilisearch/meilisearch#3130] opened 2022-11-24 08:36 UTC
**Describe the bug**

It's a feature request, while hovering on social media logos can we change their color to their original color (i.e Blue color for Twitter etc)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by oluademola** [comment] 2022-11-29 07:21
Hello @UtkarshMishra12 

I think this is out of scope. It appears this is not a bug, and the issue is unrelated to Meilisearch. I believe you could achieve that by styling the hover class in your front end. 

Please let me know if I'm missing anything.

Thanks

**Comment by UtkarshMishra12** [comment] 2022-11-29 07:25
@oluademola Yes you are right

**Closed** 2022-11-29 11:13 UTC
Labels: support
