### ISSUE TITLE
The facets attributes are not added in displayedAttributes and searchableAttributes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#761] opened 2020-06-08 07:46 UTC
I create an index `indexUID` with no primary key

Then I add the `genre` attribute as `attributesForFaceting` (via this route `POST {{url}}/indexes/indexUID/settings/attributes-for-faceting`) and this addition is well processed.
Here are the settings right now:
```json
{
    "rankingRules": [
        "typo",
        "words",
        "proximity",
        "attribute",
        "wordsPosition",
        "exactness"
    ],
    "distinctAttribute": null,
    "searchableAttributes": [],
    "displayedAttributes": [],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": [
        "genre"
    ]
}
```

Then, I add this document:

```json
[
  { "id": 2, "title": "Pride and Prejudice", "author": "Jane Austin", "genre": "romance" }
]
```

And when I use the route `GET {{url}}/indexes/indexUID/documents`, I don't have the `genre` attributes:

```json
[
    {
        "id": 2,
        "title": "Pride and Prejudice",
        "author": "Jane Austin"
    }
]
```

Indeed, here are the settings now:

```json
{
    "rankingRules": [
        "typo",
        "words",
        "proximity",
        "attribute",
        "wordsPosition",
        "exactness"
    ],
    "distinctAttribute": null,
    "searchableAttributes": [
        "id",
        "title",
        "author"
    ],
    "displayedAttributes": [
        "title",
        "id",
        "author"
    ],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": [
        "genre"
    ]
}
```

**Bug: the `attributesForFaceting` are not added to `searchableAttribtues` and `displayedAttributes`.**

FYI, if I add the document before changing the `attributesForFaceting` settings, the `genre` attribute is present in `searchableAttributes` and `displayedAttributes`.

So, the problem seems to come from the order of steps execution.

Version: on `master`.

- [ ] Fix in the code
- [ ] Add test in the "classic" order = create index -> add document -> change facets settings -> check searchable and displayed attributes
- [ ] Add test in the "buggy" order = create index -> change facets settings -> add document -> check searchable and displayed attributes

**Comment by MarinPostma** [comment] 2020-06-08 10:54
@Kerollmops isn't that expected behavior? I think we discussed that already

**Comment by Kerollmops** [comment] 2020-06-08 13:30
@MarinPostma Ho yeah, I miss-read the issue, you are right, this was discussed and this behavior is the expected one.

----

@curquiza When the user specifies that a field must be a facet attribute we don't want to display or make it searchable because facets can be hidden.

In your example you explicitly specified that you wanted the "genre" attribute to be a facet attribute, you don't specified that the attribute must be displayed or searchable. The second behavior you talked about, where you added the document then changed the facetting setting, is correct too. When you add a document, all the attributes are marked as searchable and displayed for convenience, we can't add all attributes as facetted ones for performances reason.

**Comment by curquiza** [comment] 2020-06-08 13:33
Thanks @Kerollmops and @MarinPostma for the explanation!

@bidoubiwa, should we documente that? Did you know this behavior?

**Comment by bidoubiwa** [comment] 2020-06-08 13:43
Shouldn't `genre` be in the `searchableAttributes` by default ? 
Do you mean that if I add things in this order
1. Index creation
2. Add `genre` in `attributesForFacetting`
3. Add a document with the following keys : 
   - id
   - title
   - author
   - genre 

`Genre` will not be added to the `searchableAttributes`? This is a weird behavior. The searchable attributes should contain by default all attributes found in the documents.
This is made even weirder by the fact that if i switch 2 and 3, then `genre` is added to the searchable attributes?

**Comment by curquiza** [comment] 2020-06-08 13:54
I agree with @bidoubiwa, I find this behavior weird, but maybe because I don't really know the use-cases of facets.

> When the user specifies that a field must be a facet attribute we don't want to display or make it searchable because facets can be hidden

Why?

Plus, I think this weird that it works in an order but not in the other.

**Comment by eskombro** [comment] 2020-06-08 14:45
I do think that if you want to hide it, the you can absolutely remove it from displayed or searchabale attributes. I didn't take part on that discussion, so I don't know what the implications of that would be, but I am just trying to point to what would be the intuitive behaviour for me. In the case exposed by @curquiza I don't think I would easily infer that `genre` wasn't present in the displayed or searchable attributes because it was defined as a facet. Also, it would seem logical to me that it becomes a searchable attribute by default (as any other field) even if it is not displayed.

**Comment by Kerollmops** [comment] 2020-06-08 14:56
Hey,

Thank you for all your messages and concern. I just searched a little bit in the documentation but didn't find what I was searching for: What's the behavior of adding a document attriubte the the list of `searchableAttributes` (using the specific route), does it also add this field to the `displayedAttributes`, I don't remember?

Is it the same for the `displayedAttributes`? Does adding an unknown attribute the list of displayed field add it to the `searchableAttributes`?

I don't remember why we statued on this behavior for new `facetedAttributes` but one thing we can do is making the faceted attribute a displayed and searchable attribute when it is not already known. But when the attribute is already known we don't change its properties.

I would also like to wait for @marin's feedback, but it's its day off, so we will have an answer tomorrow.

**Comment by curquiza** [comment] 2020-06-08 15:20
> What's the behavior of adding a document attribute to the list of searchableAttributes (using the specific route), does it also add this field to the displayedAttributes, I don't remember?

With MeiliSearch, updating the `searchableAttributes` via the settings routes does not change the `displayedAttributes` settings (hopefully ^^)

> Is it the same for the displayedAttributes? Does adding an unknown attribute to the list of displayed attributes add it to the searchableAttributes?

Same, touching `displayedAttributes` via the settings route will not change the `seachableAttributes` if the user does not ask for.

> I don't remember why we statued on this behavior for new facetedAttributes but one thing we can do is making the faceted attribute a displayed and searchable attribute when it is not already known. But when the attribute is already known we don't change its properties.

I checked the Algolia's behavior. They don't change `attributesToRetrive` (our `displayedAttributes`) no matter what the settings applied on faceting and "when" it's done.

**Comment by MarinPostma** [comment] 2020-06-09 08:07
> I would also like to wait for @marin's feedback, but it's its day off, so we will have an answer tomorrow.

I always had concerns with this. Actually it took me some time to figure out what was going on at the time. I am not so found of this behavior where the state of your system depends on the order of the operations, this is confusing. If I remember well, this was a status quo decision, where we wanted to keep the  behavior consistent across settings. So maybe the best for now is to leave it as is, and what for user input to make the right decision?

**Comment by curquiza** [comment] 2020-06-09 08:51
> If I remember well, this was a status quo decision, where we wanted to keep the behavior consistent across settings.

I'm not sure to understand why this current behavior (of not being the same depending on the order) is consistent across settings 🙂

**Comment by MarinPostma** [comment] 2020-06-09 10:06
well, if I remember correctly, any setting made on fields prior to indexing is not overridden by indexing. To be more precise, if a field is already found in the schema, settings relating to this field are not updated.

**Comment by curquiza** [comment] 2020-06-09 12:30
Yes, but according to [the acceptNewFields behavior](https://docs.meilisearch.com/references/accept_new_fields.html#accept-new-fields), every new field should be automatically added to the searchable-attributes and the displayed-attributes.
So, the weird behavior described here makes the `acceptNewFields` not work.

**Comment by MarinPostma** [comment] 2020-06-09 12:54
Uhm... So if I especially set displayed attributes and forget to turn this off, my settings are overridden on next indexing, it that correct?

**Comment by curquiza** [comment] 2020-06-09 13:04
Hum! According to your question, here the test I did:
- Create an index
- Add `["title"]` as `displayedAttributes`, here are the settings right now:
```json
{
    "rankingRules": [
        "typo",
        "words",
        "proximity",
        "attribute",
        "wordsPosition",
        "exactness"
    ],
    "distinctAttribute": null,
    "searchableAttributes": [],
    "displayedAttributes": [
        "title"
    ],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": []
}
```
- Adding documents:
```json
[
    {
        "id": 2,
        "title": "Pride and Prejudice",
        "author": "Jane Austin"
    }
]
```
Here are my settings right now:
```json
{
    "rankingRules": [
        "typo",
        "words",
        "proximity",
        "attribute",
        "wordsPosition",
        "exactness"
    ],
    "distinctAttribute": null,
    "searchableAttributes": [
        "id",
        "author",
        "genre"
    ],
    "displayedAttributes": [
        "genre",
        "title",
        "id",
        "author"
    ],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": []
}
```
-> displayedAttributes: all the others fields have been added to `displayedAttributes` according to `acceptNewFields` behavior. It seems ok for me, are you ok with this behavior @MarinPostma, @bidoubiwa and @eskombro?
-> searchableAttributes: the `title` field has not been added. I guess that is what you mentienned `To be more precise, if a field is already found in the schema, settings relating to this field are not updated.`. For me, this kind of behavior is not obvious, but I can understand there is a logic behind the code. Need more opinion about that, I cannot affirm that mine is the common way to expect MeiliSearch 🙂

**Comment by Kerollmops** [comment] 2020-06-09 13:15
> searchableAttributes: the title field has not been added.

@curquiza I find the latest behavior you describe totally correct and expected. The other behavior would have been to erase the previous properties of an attribute even if the attribute was explicitly added to the settings by the user. I don't see the engine add all already known attributes of the newly added documents to the `displayedAttributes` and `searchableAttributes` settings, doing so would break the settings everytime the user send document to the database.

**Comment by bidoubiwa** [comment] 2020-06-09 13:17
Yes it contradicts multiple parts : 

### References

[acceptNewFields](https://docs.meilisearch.com/references/accept_new_fields.html#accept-new-fields) in references
One of the places were it contradicts: 
> If set to true, which is the default value, all new fields are automatically added to the searchable-attributes and the displayed-attributes lists.

[Searchable Attributes](https://docs.meilisearch.com/references/searchable_attributes.html#reset-searchable-attributes) in references 
One of the places were it contradicts: 
> #Default value
All attributes found in the documents added to the index.

[Displayed Attributes](https://docs.meilisearch.com/references/displayed_attributes.html#reset-displayed-attributes) in references 
One of the places were it contradicts: 
> Default value
All attributes found in the documents added to the index.

[Settings route](https://docs.meilisearch.com/references/settings.html)
| Variable                                                                              | Description                                                                      | Default value                                                                                     |
| ------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| **[searchableAttributes](/guides/advanced_guides/settings.md#searchable-attributes)** | Fields in which to search for matching query words sorted by order of importance | All attributes found in the documents                                                             |
| **[displayedAttributes](/guides/advanced_guides/settings.md#displayed-attributes)**   | Fields displayed in the returned documents                                       | All attributes found in the documents                                                             |
| **[acceptNewFields](/guides/advanced_guides/settings.md#accept-new-fields)**          | Defines whether new fields should be searchable and displayed or not             | `true`                                                                                            |

### Guides

[Fields properties](https://docs.meilisearch.com/guides/advanced_guides/field_properties.html#searchable-fields)

> **By default, all field attributes are added to the searchable-attributes list**. If a new document is ingested and one of its fields was never present in any other document, the latter will be automatically added to the searchable-attributes list. This behavior can be changed.

> **By default, all field attributes are added to the displayed-attributes list**. If a new document is ingested and one of its fields was never present in any other document, the latter will be automatically added to the displayed-attributes list. This behavior can be changed.


[Settings](https://docs.meilisearch.com/guides/advanced_guides/settings.html#settings-configuration)
| Variable                                                                              | Description                                                                      | Default value                                                                                     |
| ------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| **[searchableAttributes](/guides/advanced_guides/settings.md#searchable-attributes)** | Fields in which to search for matching query words sorted by order of importance | All attributes found in the documents                                                             |
| **[displayedAttributes](/guides/advanced_guides/settings.md#displayed-attributes)**   | Fields displayed in the returned documents                                       | All attributes found in the documents                                                             |
| **[acceptNewFields](/guides/advanced_guides/settings.md#accept-new-fields)**          | Defines whether new fields should be searchable and displayed or not             | `true`                                                                                            |


To all those places, the following information must be accessible: 
> When adding a document in which there is for the first time an attribute that you have previously added in the attributesForFacetting list, this attribute will not be automatically added to the searchableAttributes and displayedAttributes list.

I feel like the idea is not bad but that the fact that it only works in a certain order but not in another makes it messy. 
I understand the need in private facets, but users that wants to make some fields private will have to understand `searchableAttribute` and `displayAttribute`. Whereas users that do not want to make fields private do not have to understand those settings. 
With your suggestion, users that do not need private fields have to understand `searchableAttribute` and `displayAttribute` in order to put their facets manually back in the list. Which is for me a little counterproductive. 

If we take the example of the movie dataset, with `genre` it is a facet but is also an information that will be displayed. This is the case with a lot of facets. Why should we take the side of saying `all facets should be private` more than the opposite side? 

## Update with latest comments

> well, if I remember correctly, any setting made on fields prior to indexing is not overridden by indexing. To be more precise, if a field is already found in the schema, settings relating to this field are not updated.

This is news. Again, I'm not convinced by this usage. A user should not have to understand settings if he wants the default public behavior.

**Comment by MarinPostma** [comment] 2020-06-09 13:22
I find it confusing too, but I'm not sure what the alternative would be

**Comment by curquiza** [comment] 2020-06-09 13:23
>  I don't see the engine add all already known attributes of the newly added documents to the displayedAttributes and searchableAttributes settings

@Kerollmops I don't understant, that's the classic behavior of MeiliSearch for. If you don't that, you can set `acceptNewFields` to false.

**Comment by Kerollmops** [comment] 2020-06-09 13:28
@curquiza the `acceptNewFields` behavior is to add new fields, in other words: fields that the engine is not already aware about and that are not present in the settings, to the list of displayed and searchable attributes automatically.

In the case you describe the engine is already aware of the title attribute because it has been added to the `facettedAttributes`. The engine **must not** add it to the `displayedAttributes` and `searchableAttributes` settings because this is not a **new** field.

**Comment by bidoubiwa** [comment] 2020-06-09 13:33
> doing so would break the settings everytime the user send documents to the database.

This is already the case.
When you look at curquiza's example:  
1. She add `["title"]` to the `displayedAttributes`
2. She add a document with the following attributes : `id`, `title`, `author`, `genre

### result 
`displayedAttributes` look like this:  `["genre", "title", "id","author" ]`
`searchableAttributes` look like this:  `["genre", "id","author" ]`

There is no indication this is how MeiliSearch is going to react. It could have been the following behavior with the same logic: 

## Option A 
`displayedAttributes`  `["title"]`
`searchableAttributes`   `["title", "genre", "id","author" ]`
## Option B 
`displayedAttributes`  `["title"]`
`searchableAttributes`   `["genre", "id","author" ]`
## Option C 
`displayedAttributes`  `["genre", "title", "id","author" ]`
`searchableAttributes`   `["genre", "title", "id","author" ]`

I don't see why the actual behavior makes more sense than any of the other options. 
If it should not be breakable, should it not be `option A`? 

> The engine must not add it to the displayedAttributes and searchableAttributes settings because this is not a new field.

I don't feel like this is intuitive. I'm not sure I like this but maybe it's me.

**Comment by curquiza** [comment] 2020-06-09 13:37
@Kerollmops I understand now your point of view and the concept of **new** fields.

But, why is it not the same behavior of `distinctaAttribute` so?

Here is my test:
- create an index
- update the distinct attribute to `"title"`
Here are my settings:
```json
{
    "rankingRules": [
        "typo",
        "words",
        "proximity",
        "attribute",
        "wordsPosition",
        "exactness"
    ],
    "distinctAttribute": "title",
    "searchableAttributes": [],
    "displayedAttributes": [],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": []
}
```
- add the same document that above
- here are my settings now:
```json
{
    "rankingRules": [
        "typo",
        "words",
        "proximity",
        "attribute",
        "wordsPosition",
        "exactness"
    ],
    "distinctAttribute": "title",
    "searchableAttributes": [
        "id",
        "title",
        "author",
        "genre"
    ],
    "displayedAttributes": [
        "title",
        "author",
        "genre",
        "id"
    ],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": []
}
```

**Comment by Kerollmops** [comment] 2020-06-09 13:40
> There is no indication this is how MeiliSearch is going to react. It could have been the following behavior with the same logic [...]

@bidoubiwa There is an explicit indication that this will be how MeiliSearch will react and you already talked about that in a previous comment:

> By default, all field attributes are added to the searchable-attributes list. If a new document is ingested and one of its fields was never present in any other document, the latter will be automatically added to the searchable-attributes list. This behavior can be changed.

> By default, all field attributes are added to the displayed-attributes list. If a new document is ingested and one of its fields was never present in any other document, the latter will be automatically added to the displayed-attributes list. This behavior can be changed.

All **new, unknow** attributes are added to the searchable and displayed attributes settings.

-----

> But, why is it not the same behavior of `distinctAttribute` so?

@curquiza Yeah, that's different, that's a bug I think, this is because we manage this field a big differently, this is like a special casing and will be fixed, thank you for the report.

**Comment by bidoubiwa** [comment] 2020-06-09 13:44
> But every single time a new update will be done the engine will put the "genre" field into the displayed and searchable settings. I find that confusing and not a correct behavior.

You'r right. Either he puts `acceptNewFields` to false but then he has to add manually every new fields. Either he has to manually remove the fields each time. 

In each case, one of the users will have to do some work to get its results. I prefer it to be the one that already knows about the settings.

It really depends on which use-case we want to make more difficult. But not everyone can have a smooth solution. I agree with you.

---

> All new, unknown attributes are added to the searchable and displayed attributes settings.

and 

>  If a new document is ingested and one of its fields was never present in any other document, , the latter will be automatically added to the XX list


Are quiet different

In your description you talk about the fact that it is known via settings or documents. I specifically talk about being known in documents.

**Comment by curquiza** [comment] 2020-06-09 13:45
About the docs:

> If a new document is ingested and one of its fields was never present in any other document, the latter will be automatically added to the searchable-attributes list.

We should be more accurate, like "never present in any other document and in the settings" or "unknown by MeiliSearch" (I don't know the best way to explain that 😅)

**Comment by Kerollmops** [comment] 2020-06-09 13:50
If the `acceptNewFields` settings is set to `true`, which is the default, any document attribute that is not present in any of the settings is automatically added to the `displayedAttributes` and `searchableAttributes` settings.

**Comment by curquiza** [comment] 2020-06-09 14:00
Sorry if my question is not related to this discussion, but here my test 😇 
- create an index
- udpate ranking rules like this:
```json
[
	"asc(title)",
	"typo"
]
```
Here are the settings now:
```json
{
    "rankingRules": [
        "asc(title)",
        "typo"
    ],
    "distinctAttribute": null,
    "searchableAttributes": [
        "title"
    ],
    "displayedAttributes": [
        "title"
    ],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": []
}
```

Just a question: why `title` is automatically added to `searchableAttributes` and `displayedAttributes`?
I particularly don't understand why it's added in `displayedAttributes`.
And, does a field need to be a searchable-attribute to be used in the ranking rules?

**Comment by curquiza** [comment] 2020-06-09 14:05
> If the acceptNewFields settings is set to true, which is the default, any document attribute that is not present in any of the settings is automatically added to the displayedAttributes and searchableAttributes settings.

Is this sentence still true if MeiliSearch knows a field (in the schema) but this field is not displayed in any settings.
Ex:
- I add a document with `title` and `author`.
- I use only `title` as displayed and searchable attributes -> now, I cannot see any `author` in my settings and in my documents either.
- I add another document with `title` and `author`
-> Would the `author` field be considered as a **new** field and would be added to the searchable and displayed attributes?

**Comment by MarinPostma** [comment] 2020-06-10 09:44
Have we decided anything yet? We should settle on something that's easy to explain too. Maybe meili settings should be inferred only if no settings were ever set before, i.e if the user used settings at least once, then we shouldn't override them anymore, and the user is expected to take full control from there?

**Comment by curquiza** [comment] 2020-06-10 10:02
@MarinPostma 
I think @Kerollmops is right and we should keep this "weird" (depending of the POV) behavior for the moment. I realized it would mean a LOT of changes in MeilSearch.

There is still the issue I mention in the comment right above yours: sometimes MeiliSearch knows stuff that the user cannot know. Same, it would mean a lot of changes for the core-engine team but we should consider that.
Should I open an issue @Kerollmops?

Then, we should :
- discuss together all these points (directly)
- open a better discussion than this one to ask for the community opinion
- status for a decision after that.

**Comment by Kerollmops** [comment] 2020-06-10 10:09
@curquiza Yeah we should open 3 issues that doesn't follow the rules I described:
 - the `distinctAttribute` must be taken into account https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641302502.
 - When an attribute is found in the `rankingRules` an attribute must not be considered new https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641317172.
 - We must not save an attribute that will never be used (not in the settings) and consider it a new attribute if we see new documents containing it (because we must not be aware of it) https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641320322.

**Comment by MarinPostma** [comment] 2020-06-25 07:55
> We must not save an attribute that will never be used (not in the settings) and consider it a new attribute if we see new documents containing it (because we must not be aware of it) #761 (comment).

How do we know that @Kerollmops, where would that attribute come from?

**Comment by Kerollmops** [comment] 2020-06-26 09:09
@MarinPostma When documents are indexed we look at all the attributes it contains, when a new attribute is found (an attribute that is not in any settings) and the `acceptNewFields` is set to `true` we register this attribute into the settings in the `searchable_attributes` and `displayed_attributes`.

**Comment by MarinPostma** [comment] 2020-06-26 10:35
@Kerollmops how is this different from removing it from schema when no occurrences are found in the schema?

**Comment by qdequele** [comment] 2020-12-05 17:44
@MarinPostma, @curquiza What is the state of this issue? Could we close it?

**Comment by bidoubiwa** [comment] 2020-12-07 09:41
Is this not the issue of 

**CASE 1**: `add documents` then `add facets in settings`
**CASE 2**: `add facets in settings` and then `add documents`

Where in case 1 all fields will be present in `displayedAttributes` and `searchableAttributes` but in case 2 facets will not be added in either of these settings. 

In which case, this is not fixed.

**Closed** 2020-12-16 14:34 UTC
Labels: type:bug, type:ux
