### ISSUE TITLE
Task panicked in multi-search

### ISSUE THREAD

**Issue by theotruvelot** [meilisearch/meilisearch#4444] opened 2024-02-26 15:26 UTC
**Describe the bug**
A error when a multi-search call, meilisearch return a 500.

**To Reproduce**
Hard to reproduce, but the call is a multi-search with 7 index with each a filter, limit 15, and the query is "po_"

**Expected behavior**
a return with the result of the multi-search

**Logs**
Log of the response :
``Inside `.queries[1]`: task 6393955 panicked``
Log in meilisearch from console : 
`thread 'tokio-runtime-worker' panicked at 'assertion failed: self.stable_store.len() < u16::MAX as usize', milli/src/search/new/interner.rs:60:13`

**Meilisearch version:**
v1.6.1 self hosted with docker and kube

**Additional context**
Additional information that may be relevant to the issue.
Call made with php sdk 1.1.0

**Comment by irevoire** [comment] 2024-02-28 09:50
Hey @theotruvelot, that’s very valuable, but we cannot really reproduce the issue.

Could you maybe share with us a way of reproducing it on our side?
Or if your data are not too sensitive a snapshot or dump of your instance + your whole query?

**Comment by theotruvelot** [comment] 2024-02-28 11:46
Hey @irevoire, I cannot give you a snapshot or dump because there is sensitive data.

I got a normal utilisation of meilisearch, with an import of 40 constant documents and like 2k search per day.

To reproduce it, make a multi-search with 7 index, with each a filter, limit 15 and in each index there is 1 million documents.
Make the multi-search at the same time as importing like 40 documents (processing) (~ 80 enqueued).

**Comment by irevoire** [comment] 2024-02-28 14:01
I tried with a hackernews dataset, but it doesn’t reproduce on my side, sorry 😔 

If you want/can, you can share sensitive data by email with us (tamo@meilisearch.com); we’ve already done that quite a few times, and we’ll delete the data right after our investigation.

Otherwise, this issue looks really similar to: https://github.com/meilisearch/meilisearch/issues/4247
And it is probably not related to the multi-search, so maybe you could find a smaller reproducer but I don’t think I’ll be able to help more, sorry 😔

**Comment by theotruvelot** [comment] 2024-02-28 14:26
Hello @dureuill ! 

It was at the request of Quentin de Quelen, with whom I had a meeting, that I brought up this issue. I've only had this error 3 times in the last 15 days, and twice at the same time.
I know the information I'm giving isn't very useful, but I only have the error log and unfortunately I can't share my database...
I don't log the complete multi-search body. I just log the query.

If you want I can add a log to share it with you if the error comes back.

**Comment by dureuill** [comment] 2024-02-28 14:29
That would be great if you could add that log 😊

Another possibility that would give us more context would be to use a Meilisearch version compiled with debug symbols, started with the env variable RUST_BACKTRACE=1, and then observe the panic again, but that's a lot more involved!

Thank you :heart:

**Comment by curquiza** [comment] 2024-05-22 12:28
Closing this due to a lack of answer, feel free to reopen if needed

**Closed by curquiza** 2024-05-22 12:28 UTC
Labels: bug, needs more info
