### ISSUE TITLE
Corrupted task queue while swapping index

### ISSUE THREAD

**Issue by grizzm0** [meilisearch/meilisearch#4926] opened 2024-09-12 07:58 UTC
We've got 7 languages, each with 3 different indices (brand, category and product) totalling in 21 indices.

We create temporary indices, copy settings etc, fill them with data then swap the temporary index with the production index for each of these 21 indices.

18 of these indices swaps without any issues. However, all of our Swedish indices fail with the following message. And I can't seem to find any documentation about corrupted task queue.

The swapping works fine in development with the exact same data. So it's probably an issue with our production server.

Anyone knows how to solve this or what could be wrong?

```
{
    "uid": 128341,
    "indexUid": null,
    "status": "failed",
    "type": "indexSwap",
    "canceledBy": null,
    "details": {
        "swaps": [
            {
                "indexes": [
                    "sv_SEK_product_tmp_php_66e29879f060d5_65007136",
                    "sv_SEK_product"
                ]
            }
        ]
    },
    "error": {
        "message": "Corrupted task queue.",
        "code": "internal",
        "type": "internal",
        "link": "https://docs.meilisearch.com/errors#internal"
    },
    "duration": "PT0.001760044S",
    "enqueuedAt": "2024-09-12T07:32:48.551970758Z",
    "startedAt": "2024-09-12T07:33:01.231349397Z",
    "finishedAt": "2024-09-12T07:33:01.233109441Z"
}
```

**Comment by grizzm0** [comment] 2024-09-24 08:57
We could not resolve the issue. The swap of the same index always gave corrupt task queue error. We ended up creating a new server with v1.10.

**Comment by curquiza** [comment] 2024-09-24 12:00
In this case, let's close the issue, since we cannot reproduce it and you solved it differently.

Really sorry for the trouble @grizzm0 😞

**Closed by curquiza** 2024-09-24 12:00 UTC
