### ISSUE TITLE
Missing Chinese search results

### ISSUE THREAD

**Issue by chu-bin** [meilisearch/meilisearch#2091] opened 2022-01-19 06:39 UTC
In some cases, Chinese search words may not be split and insert <em></em> in the "_format" field

**To Reproduce**
```js
import { MeiliSearch } from "meilisearch";
const data = [
  {
    id: 1,
    title: "正常format的测试数据",
    content: "这是一个正常的虚拟机数据",
  },
  {
    id: 2,
    title: "异常的测试数据",
    content: `虚拟机 a : a : a`,
  },
];
const client = new MeiliSearch({ host: "http://127.0.0.1:7700" });
client
  .index("data")
  .addDocuments(data)
  .then((res) => console.log(res));

```
**response**
```json
{"hits":[{"id":1,"title":"正常format的测试数据","content":"这是一个正常的虚拟机数据","_formatted":{"id":1,"title":"正常format的测试数据","content":"这是一个正常的<em>虚拟机</em>数据"}}],"nbHits":1,"exhaustiveNbHits":false,"query":"虚拟机","limit":200,"offset":0,"processingTimeMs":0}
```

**Expected behavior**
“虚拟机” should be fully highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/44690217/155504259-b04addfc-0044-439e-9637-ff80f7cd4f8f.png)

**MeiliSearch version:** v 0.25.1

**Additional context**
macbook pro(intel), mac os 12.1, chrome 97.0.4692.71

**Comment by chu-bin** [comment] 2022-01-21 02:53
@curquiza  Do you plan to fix this problem?

**Comment by curquiza** [comment] 2022-01-25 15:42
Hello @chu-bin!

> Will upgrading the version of Jieba solve this problem?

We don't know yet, we need to investigate to give you a confident answer.

> Do you plan to fix this problem?

More than fixing this problem, we plan to work on our tokenizer this year. I mean, there are multiple issues regarding our tokenizer and we want to improve it to fix most of them. Also, we want to make it more "contribuable" so that everyone can contribute by adding their own language support.
I cannot promise this issue will be fixed, because we don't know how to do it now, but it will be taken into consideration (https://github.com/meilisearch/tokenizer/issues/65)

**Comment by curquiza** [comment] 2022-05-18 13:45
I can still reproduce the bug with v0.27.1

Documents
```json
[
  {
    "id": 1,
    "title": "正常format的测试数据",
    "content": "这是一个正常的虚拟机数据"
  },
  {
    "id": 2,
    "title": "异常的测试数据",
    "content": "虚拟机 a : a : a"
  }
]
```

Search
```json
{
    "q": "虚拟机"
}
```

Result:

```json
{
    "hits": [
        {
            "id": 1,
            "title": "正常format的测试数据",
            "content": "这是一个正常的虚拟机数据"
        }
    ],
    "nbHits": 1,
    "exhaustiveNbHits": false,
    "query": "虚拟机",
    "limit": 20,
    "offset": 0,
    "processingTimeMs": 2
}
```

Expected result: get document with id `2`

**Comment by ms300** [comment] 2022-08-22 16:25
Sorry i don't have a Rust runtime. But when i run jieba original version (python) it works as expected.

![image](https://user-images.githubusercontent.com/3821012/185970811-5041ca1e-faec-4bae-894d-0f66f8a4a22b.png)

**Comment by ms300** [comment] 2022-08-22 16:42
@curquiza 

Hi, it works well in jieba-rs too. could you tell which function or command is called when using jieba as a tokenizer?

testing code:
```rust
extern crate jieba_rs;
use jieba_rs::Jieba;

fn main() {
    let jieba = Jieba::new();
    let words = jieba.cut("虚拟机 a : a : a", false);
    assert_eq!(
        words,
        vec!["虚拟机", " ", "a", " ", ":", " ", "a", " ", ":", " ","a"]
    );
}
```

**Comment by curquiza** [comment] 2022-08-23 10:14
Thanks for your comment @ms300 

It can interest @ManyTheFish!

**Comment by ManyTheFish** [comment] 2022-08-23 10:27
Hello @ms300,
below is [the code used by Meilisearch to segment Chinese](https://github.com/meilisearch/charabia/blob/faafb12257eb6b534264981414a2eed1e66f8f6b/src/segmenter/chinese.rs#L14), we may probably deactivate the HMM feature: 🤔 
```rust
impl Segmenter for ChineseSegmenter {
    fn segment_str<'o>(&self, to_segment: &'o str) -> Box<dyn Iterator<Item = &'o str> + 'o> {
        let segmented = JIEBA.cut(to_segment, true); // Use Hidden Markov Models.

        Box::new(segmented.into_iter())
    }
}
```

don't hesitate to make a [pull request on the dedicated repo: Charabia](https://github.com/meilisearch/charabia) if you think that we should change something!

thank you!

**Comment by ManyTheFish** [comment] 2022-09-07 15:20
Hello,
I don't manage to reproduce the issue with [v0.29.0rc2](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.0rc2).

This bug can be considered fixed.

I close this issue, don't hesitate to reopen it if I'm wrong.

**Closed by ManyTheFish** 2022-09-07 15:20 UTC
Labels: bug, tokenizer, language
