### ISSUE TITLE
[v1.12.0-rc2] Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.} 

### ISSUE THREAD

**Issue by tysonite** [meilisearch/meilisearch#5108] opened 2024-12-02 12:02 UTC
**Describe the bug**
I wanted to check if issue #4984 has been resolved and how Meili performs after the fix. While the original issue described in #4984 no longer appears, I am now encountering internal server errors when processing certain queries. Such errors are not observed for some of the queries, but I cannot determine the pattern yet - appreciate any suggestions.

The following error messages are present in log while type query's text:
```
meilisearch-1  | 2024-12-02T12:44:37.598251Z ERROR HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 11 in the fieldids weights mapping.}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 500, message: "Inside `.queries[0]`: internal: missing 11 in the fieldids weights mapping.", error_code: "internal", error_type: "internal", error_link: "https://docs.meilisearch.com/errors#internal" }
meilisearch-1  | 2024-12-02T12:44:37.599324Z  INFO HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 11 in the fieldids weights mapping.}: meilisearch: close time.busy=1.60ms time.idle=4.97ms
meilisearch-1  | 2024-12-02T12:44:37.773484Z ERROR HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 500, message: "Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.", error_code: "internal", error_type: "internal", error_link: "https://docs.meilisearch.com/errors#internal" }
meilisearch-1  | 2024-12-02T12:44:37.774040Z  INFO HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: meilisearch: close time.busy=374µs time.idle=1.83ms
meilisearch-1  | 2024-12-02T12:44:38.008931Z ERROR HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 500, message: "Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.", error_code: "internal", error_type: "internal", error_link: "https://docs.meilisearch.com/errors#internal" }
meilisearch-1  | 2024-12-02T12:44:38.009444Z  INFO HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: meilisearch: close time.busy=454µs time.idle=1.47ms
meilisearch-1  | 2024-12-02T12:44:38.088736Z ERROR HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 500, message: "Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.", error_code: "internal", error_type: "internal", error_link: "https://docs.meilisearch.com/errors#internal" }
meilisearch-1  | 2024-12-02T12:44:38.089581Z  INFO HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: meilisearch: close time.busy=762µs time.idle=2.51ms
meilisearch-1  | 2024-12-02T12:44:38.266675Z ERROR HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 500, message: "Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.", error_code: "internal", error_type: "internal", error_link: "https://docs.meilisearch.com/errors#internal" }
meilisearch-1  | 2024-12-02T12:44:38.267212Z  INFO HTTP request{method=POST host="10.112.33.103:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=500 error=Inside `.queries[0]`: internal: missing 12 in the fieldids weights mapping.}: meilisearch: close time.busy=552µs time.idle=1.59ms

```

The index settings:
```
{
  "displayedAttributes": [
    "*"
  ],
  "searchableAttributes": [
    "channel_id_number",
    "call_letter",
    "expanded_call_letter",
    "network",
    "callsign",
    "city",
    "state",
    "website_address"
  ],
  "filterableAttributes": [
    "callsign",
    "is_adult_channel",
    "logo_filename",
    "logo_height",
    "logo_ratio",
    "logo_width",
    "trickplay_avail",
    "call_letter",
    "channel_id_number",
    "city",
    "expanded_call_letter",
    "network",
    "poster",
    "state",
    "time_zone_change",
    "timezone",
    "website_address"
  ],
  "sortableAttributes": [
    "channel_id_number",
    "city",
    "network",
    "state"
  ],
  "rankingRules": [
    "words",
    "typo",
    "proximity",
    "attribute",
    "sort",
    "exactness"
  ],
  "stopWords": [],
  "nonSeparatorTokens": [],
  "separatorTokens": [],
  "dictionary": [],
  "synonyms": {},
  "distinctAttribute": null,
  "proximityPrecision": "byWord",
  "typoTolerance": {
    "enabled": true,
    "minWordSizeForTypos": {
      "oneTypo": 5,
      "twoTypos": 9
    },
    "disableOnWords": [],
    "disableOnAttributes": [
      "channel_id_number"
    ]
  },
  "faceting": {
    "maxValuesPerFacet": 100,
    "sortFacetValuesBy": {
      "*": "alpha"
    }
  },
  "pagination": {
    "maxTotalHits": 1000
  },
  "searchCutoffMs": null,
  "localizedAttributes": null,
  "facetSearch": true,
  "prefixSearch": "indexingTime"
}
```

The corresponding query sent by meili-ui:

```
{
    "queries": [
        {
            "indexUid": "index_name",
            "q": "ori",
            "facets": [],
            "attributesToHighlight": [
                "*"
            ],
            "highlightPreTag": "<ais-highlight-0000000000>",
            "highlightPostTag": "</ais-highlight-0000000000>",
            "limit": 21,
            "offset": 0
        }
    ]
}
```

**To Reproduce**
TBD

**Meilisearch version:**
[e.g. v1.12.0-rc2]

**Comment by curquiza** [comment] 2024-12-02 16:27
@tysonite sorry for the inconvenience

Can you send us your task queue: https://github.com/meilisearch/meilisearch/pull/5076?

cc: @meilisearch/engine-team For your information

**Comment by curquiza** [comment] 2024-12-02 16:28
Also @tysonite 
if you have a way to reproduce it's even better 🙏 
Otherwise, can you send [snapshot](https://www.meilisearch.com/docs/reference/api/snapshots#create-a-snapshot)?

**Comment by tysonite** [comment] 2024-12-02 16:57
@curquiza , I probably can send you a snapshot or even source (CSV file) file to populate your DB instance. But I would like to send it via a private message if you share some way to do that. Not sure that publicly sharing is acceptable.

**Comment by irevoire** [comment] 2024-12-03 14:13
Hey @tysonite, I chatted with the team, and it looks like your case fall exactly on this bug we just fixed in this PR yesterday: https://github.com/meilisearch/meilisearch/pull/5109

If I understand correctly, you have a good reproducer that you can run on your side easily.
Could you try to reproduce your issue with the latest rc: https://github.com/meilisearch/meilisearch/releases/tag/v1.12.0-rc.3

And thanks a lot for trying the rc before the official release, that helps a lot especially for this release which is pretty big :pray:

**Comment by tysonite** [comment] 2024-12-03 15:23
Hi @irevoire , yeah, it seems the issue you referenced fixed things on my end. I tried rc.3 and do not see anymore this issue. Thank you!

**Comment by irevoire** [comment] 2024-12-03 16:44
Awesome, thanks a lot for the investigation!

I'm closing for now, if you encounter any other issue do not hesitate to open another issue, it really helps us to have people like you trying the RC! :heart_hands:

**Closed by irevoire** 2024-12-03 16:44 UTC
Labels: needs more info

**Comment by tysonite** [comment] 2024-12-03 18:40
@irevoire Sure thing. Thanks for an awesome product!
