### ISSUE TITLE
Two environments, same meilisearch version, but different indexing times

### ISSUE THREAD

**Issue by hasnat-rhino** [meilisearch/meilisearch#2306] opened 2022-04-11 11:28 UTC
**Describe the bug**
Two environments on AWS EC2, same meilisearch version 'meilisearch-http 0.25.0', but different indexing times (one takes days where as other takes hours)

**To Reproduce**
1. Import data
2. Tasks API returns a huge response of  > 30MB on one meilisearch server, other server returns a response for tasks of 2MB
3. Tasks with 30MB response meilisearch server takes weeks of time to complete indexing, where as tasks of 2MB meilisearch server takes hours to complete
4. CPU utilization is at 2%

**Expected behavior**
Both same meilisearch versions should take same amount of time to finish indexing

**Screenshots**

**Meilisearch version:** [e.g. v0.25.0]

**Additional context**
Additional information that may be relevant to the issue.

The data import code is written in PHP laravel 

PHP 7.4.27 (cli) (built: Dec 20 2021 21:28:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

Laravel Framework 8.65.0

Batching has been implemented on 500 batches when sending to meilisearch for indexing

ENV files are also the same in both environments(both meilisearch servers)

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=file
SESSION_LIFETIME=120
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=""
REDIS_PORT=6379
REDIS_CLIENT=predis
SCOUT_QUEUE=true
#Meilisearch
SCOUT_DRIVER=meilisearch

Thank you very much for any help.

**Comment by curquiza** [comment] 2022-04-11 13:25
Hello @hasnat-rhino 
Thanks for your report

I'm not sure to understand what are your both environment? What makes them differ from each other?

We personally did not succeed to reproduce: the same indexation involves the same time on my machine, (with small variations depending on the current job of our machine) but not difference between days and hours

Have you activated the `--enable-auto-batching` flag to one of your Meilisearch?

**Comment by hasnat-rhino** [comment] 2022-04-11 17:59
Hi,

Thank you for the reply, 

No auto batching has been enabled since we are using meilisearch-http 0.25.0, and auto batching was in 0.26.0 release
The two environments i was referring to was, the two servers for development and production servers on aws EC2, 

development - t2.micro 1vcpus | 0.5 Gib,  - indexes , 100 documents in 5 minutes
tasks api returns 2.42MB response, with 0 - enqueued, succeeded - 7907

production - t3.medium 2vcpus | 4Gib - indexes , 100 documents in 30 minutes
tasks api returns 34.56MB response, with 0 - enqueued 19999+, succeeded - i can't check since even postman app crashes

Apparently the production meilisearch server is the one that is taking really a lot of time to finish indexing. 
Is there anyway to clear the tasks API tasks list, Sorry for being so non technical,i would to ask politely,  in order to use auto batching i think i will need to migrate 0.25.0 to 0.26.0 right? Also Even if i do so, the documentation says just put --enable-auto-batching, but i am confused where this should be used on the server since i did not find anything on the documentation.

Any help is greatly appreciated. Thank you.

**Comment by curquiza** [comment] 2022-04-14 17:13
Hello @hasnat-rhino 

Thanks for the details! :)

I see you sent your documents in a loooooot of differents batches (more than 19999+ tasks) for the production environment and only a few for the the dev environment (7907).

You have to know that Meilisearch is faster processing one big batch of documents rather than multiple smaller batches. You have all the information regarding the perfomance optimization here: https://docs.meilisearch.com/learn/advanced/indexation.html#indexation-and-performance

Hope it will help you adapting the right behavior using Meilisearch with your usecase.
We also are working hard on the indexation speed since we know it's one of our main user issue. We opened a discussion [here](https://github.com/meilisearch/meilisearch/discussions/2131) if you have any feedback, even after having implemented the good practices

We are sorry for the issue your encountered when using Meilisearch and hope the guide will help you :)

**Comment by curquiza** [comment] 2022-05-02 08:30
I close this issue due to a lack of answer, feel free to ask to re-open if needed.

**Closed by curquiza** 2022-05-02 08:30 UTC
Labels: needs more info
