### ISSUE TITLE
Cant run Meilisearch Binary on Linux Alpine

### ISSUE THREAD

**Issue by K2ouMais** [meilisearch/meilisearch#4377] opened 2024-01-31 10:09 UTC
**Describe the bug**
After installing Meilisearch:
https://www.meilisearch.com/docs/learn/getting_started/installation#local-installation

When I try to run ```./meilisearch``` the error says ```not found```.

**To Reproduce**
1. Download the docker image alpine:3.19
2. Run the Meilisearch installation in container
3. Run binary

**Expected behavior**
That Meilisearch would start.

**Screenshots**
![image](https://github.com/meilisearch/meilisearch/assets/52510455/3f2e8e39-2b60-43c2-9a84-3fe7d55c4f61)

**Meilisearch version:**
1.6.0

**Additional context**
Tried on Linux Alpine 3.19.
I get the same error when I download an older version and also try to run it.

**Comment by curquiza** [comment] 2024-01-31 11:04
Hello @K2ouMais 
I succeeded in reproducing the issue

However the binary meilisearch file is well downloaded, installed and executable

Looks like the issue is on Alpine side, but I don't know where it comes from. I'm not able to reproduce the issue on MacOs or ubuntu.

**Comment by K2ouMais** [comment] 2024-01-31 14:22
@curquiza 
I was able to reproduce this also on debian and also ubuntu/wsl.
Are you sure this is able to run in ubuntu?

**Comment by curquiza** [comment] 2024-01-31 15:03
Yes sure, with `ubuntu:latest` image.

I just also tested with `debian:latest` image.

```bash
docker run --rm -it debian:latest sh
```

**Comment by curquiza** [comment] 2024-01-31 15:05
But with `alpine:latest` it does not work
<img width="687" alt="Capture d’écran 2024-01-31 à 16 05 02" src="https://github.com/meilisearch/meilisearch/assets/20380692/1adea604-ef96-4927-88a2-05674e2ae4be">

**Comment by curquiza** [comment] 2024-01-31 15:24
We just found out the issue: the binary downloaded cannot work with the internal musl C library present in Alpine. You cannot used the assets attached to the release (so the script provided in the docs)

I will open an issue to improve the script and return an error when there is a musl C library.

In the meantime you can
- use the docker image we provide (tab "docker" on [this page](https://www.meilisearch.com/docs/learn/getting_started/installation#local-installation))
- build binary from source (tab "source" on [this page](https://www.meilisearch.com/docs/learn/getting_started/installation#local-installation))

**Comment by curquiza** [comment] 2024-01-31 15:28
I close this issue in favor of https://github.com/meilisearch/meilisearch/issues/4379

**Closed by curquiza** 2024-01-31 15:28 UTC
Labels: needs more info, help wanted

**Comment by barart** [comment] 2025-01-28 02:12
Why is this closed? I think this issue needs to be open, its still a issue

**Comment by curquiza** [comment] 2025-01-28 07:57
Hello @barart! It's closed in favor of https://github.com/meilisearch/meilisearch/issues/4379
cf: https://github.com/meilisearch/meilisearch/issues/4377#issuecomment-1919340139

**Comment by barart** [comment] 2025-01-28 13:49
> Hello @barart! It's closed in favor of https://github.com/meilisearch/meilisearch/issues/4379
> cf: https://github.com/meilisearch/meilisearch/issues/4377#issuecomment-1919340139

But #4379 is asking to output a error on donwnload-latest.sh script when running on Alpine, this is about Meilisearch not running on alpine, is completely different issue

**Comment by curquiza** [comment] 2025-01-28 14:02
This current issue is not about Meilisearch not running on alpine, but about the installation script that will not work on alpine (`curl -L https://install.meilisearch.com | sh`) because we do not provide any Meilisearch release asset for Alpine.

Meilisearch can compile and run on Alpine since our docker image is built at top of a Docker alpine image. 

We do not plan to release Alpine assets on GitHub directly, so that's why we would like to adapt the script to throw the appropriate error
If you want to use alpine, you can compile from source, see [our docs](https://www.meilisearch.com/docs/learn/self_hosted/install_meilisearch_locally#local-installation)

**Comment by Lsm-CVX** [comment] 2026-04-26 10:40
HI all, 

I had the same issue (alpine 3.23) and I don't want to compile it and not use docker so here is the trick I used : I got the meilisearch from the docker. My way is a bit convoluted but I strictly don't want this docker thing on my LXC so here it is.

```bash
#Look for the latest version 
VERSION=$(curl -sf "https://api.github.com/repos/meilisearch/meilisearch/releases/latest" | jq -r '.tag_name')
echo "Resolved version: $VERSION"

#Look for the bearer token
 TOKEN=$(curl -sf "https://auth.docker.io/token?service=registry.docker.io&scope=repository:getmeili/meilisearch:pull" | jq -r '.token')
echo "Token: $TOKEN"

#look for index 
INDEX=$(curl -sf -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.list.v2+json" "https://registry-1.docker.io/v2/getmeili/meilisearch/manifests/${VERSION}")
echo "INDEX : $INDEX"

 # Resolve the amd64 sub-manifest digest
 DIGEST=$(echo "$INDEX" | jq -r ' .manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest' | head -n1)
echo "amd64 manifest digest: $DIGEST"

# Pickup the manifest
MANIFEST=$(curl -sf -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://registry-1.docker.io/v2/getmeili/meilisearch/manifests/${DIGEST}")
echo "Manifest: $MANIFEST"

# We iterate layers to find the one containing /bin/meilisearch
LAYERS=$(echo "$MANIFEST" | jq -r '.layers[].digest')


mkdir -p /tmp/meili_extract

for DIGEST in $LAYERS; do
curl -sf -H "Authorization: Bearer $TOKEN" -L "https://registry-1.docker.io/v2/getmeili/meilisearch/blobs/${DIGEST}" -o /tmp/meili_extract/layer.tar.gz

 # Check if this layer contains the meilisearch binary
 if tar -tzf /tmp/meili_extract/layer.tar.gz 2>/dev/null | grep -q "bin/meilisearch$"; then
    tar -xzf /tmp/meili_extract/layer.tar.gz -C /tmp/meili_extract --wildcards "*/meilisearch"  --no-anchored 2>/dev/null || tar -xzf /tmp/meili_extract/layer.tar.gz  -C /tmp/meili_extract bin/meilisearch
     break
 fi
  done

# Find and install the binary
BINARY=$(find /tmp/meili_extract -name "meilisearch" -type f | head -n1)
    if [ -z "$BINARY" ]; then
         echo "ERROR: meilisearch binary not found in any layer"
         exit 1
   fi

install -m 755 "$BINARY" /usr/local/bin/meilisearch
rm -rf /tmp/meili_extract
```
