### ISSUE TITLE
Importing dumps on Windows giving os error 32

### ISSUE THREAD

**Issue by Fronix** [meilisearch/meilisearch#2878] opened 2022-10-10 09:20 UTC
**Describe the bug**
After the recent update (0.29) I decided to try using dumps when upgrading.
I'm running into an issue where I get this error `Error: The process cannot access the file because it is being used by another process. (os error 32)`  when using `--import-dump`

I've verified that the file is read and writeable and it's still giving me the error.

**To Reproduce**
1. Create a dump from 0.28
2. Import the created dump to the new 0.29 version
3. This error should pop up after trying to import: `Error: The process cannot access the file because it is being used by another process. (os error 32)`

**Expected behavior**
I expect the import to be completed and not fail

**Screenshots/Logs**
Full log of the import: https://pastebin.com/tnVB5v6f

**Meilisearch version:** [e.g. v0.20.0]
Dump version: 0.28.0
Import dump version: 0.29.0

**Additional context**
OS: Windows 10 and Windows Server 2019

**Comment by oluademola** [comment] 2022-10-13 14:44
Hello @Fronix,

Indeed this appears to be a bug. I was able to reproduce the same problem on windows 11. Additionally, I can confirm there is no problem with the rights, and I even tried disabling any antivirus that might be attempting to scan the process. I couldn't get any helpful info about what could be wrong checking with the windows process explorer as well.  Thank you for bringing this to our notice.

<img width="848" alt="Screenshot 2022-10-13 150342" src="https://user-images.githubusercontent.com/101267639/195628051-3a7443c7-bfde-47bf-ba1c-8fcbf91ec17a.png">

Escalating to the @meilisearch/core-team

**Comment by curquiza** [comment] 2022-10-13 15:16
Thanks @oluademola for the investigation, passing this from `support` to `bug`

Thanks @Fronix for the report 🙏 

FYI, we have a lot on our plate now and Windows bugs are not the priority due to all the changes we have to implement. However we will try to do our best to fix this!

Anyone in the community, we would love to have your help on this if you are available ❤️

**Comment by curquiza** [comment] 2023-01-23 17:11
Just discussed with @oluademola, who made the test: it's fixed in v1.0.0-rc.1 🎉 
Will be fixed once v1.0.0 is out on 6th February.

**Closed by curquiza** 2023-01-23 17:11 UTC
Labels: bug, windows, contribution accepted, help wanted
