### ISSUE TITLE
/health returns okay despite Permission denied (os error 13)

### ISSUE THREAD

**Issue by szepeviktor** [meilisearch/meilisearch#4809] opened 2024-07-18 10:24 UTC
**Describe the bug**
For 3 months I had `Permission denied (os error 13)` error.
But `/health` returns okay.

**To Reproduce**
1. `GET /health`
2. see HTTP/200

**Expected behavior**
Please include check for `Permission denied (os error 13)`
I do not know what causes it.

**Meilisearch version:**
v1.1.0

**Additional context**
`Permission denied (os error 13)` gone away after an upgrade and the deletion of `/data/*`

**Comment by dureuill** [comment] 2024-07-22 07:58
Hello @szepeviktor :wave: I'm sorry you encountered this issue

can you specify after which action you were getting `permission denied`? whether it is expected or not that `/health` be capable of detecting the condition might depend on this.

Furthermore, `/health` must strike a balance between the range of conditions it detects and its performance

**Comment by szepeviktor** [comment] 2024-07-22 08:04
`permission denied` occurred silently 4 months ago. I couldn't find the cause.
After an upgrade to the latest version it _went away_.

**Comment by dureuill** [comment] 2024-07-22 08:45
> permission denied occurred silently 4 months ago. I couldn't find the cause.

It's okay not to have the cause 🙂 I need to know *where* you could observe this `permission denied` issue. Was it in the task queue? On which tasks? Was it after a search? etc.

**Comment by szepeviktor** [comment] 2024-07-22 08:52
> _where_ you could observe this `permission denied` issue

This is an unused staging environment. There were no searches thus no HTTP traffic towards Meilisearch, only /health requests.
`Permission denied (os error 13)` was in the output - redirected to a log file - much more frequent (thousands of times) than /health requests.

**Comment by dureuill** [comment] 2024-07-22 09:13
Unfortunately that's not enough information to know if we should make changes to `/health` here.

1. is this happening due to the update files directory being inaccessible: we could consider checking that it is writable in health (need to check with the team)
2. is this happening due to an index directory being inaccessible: I don't think we can checking all index directories in `/health` as it wouldn't scale

**Comment by szepeviktor** [comment] 2024-07-22 09:22
> the update files directory being inaccessible

Thank you.
That would be fine.

**Comment by curquiza** [comment] 2024-08-06 12:24
Hello here, after discussing with the team, we decided not to implement this change, sorry 😔
Even if the improvement is good (and we agree), this is too risky: the `/health` route is used by our Cloud offering, and by some of our OSS user's architecture as THE reliable way to check the validity of the instance 
Any change on this route can be too impactful on the usage. We want to avoid it as much as possible

We always try to do the best for the users, even small "details" like error message, but we will always choose stability first. I hope you understand. Sorry again, I close this issue.

**Closed by curquiza** 2024-08-06 12:24 UTC
Labels: needs more info

**Comment by szepeviktor** [comment] 2024-08-06 13:03
All right.
