### ISSUE TITLE
 Compilation failed V0.29.1

### ISSUE THREAD

**Issue by Avey777** [meilisearch/meilisearch#2900] opened 2022-10-12 09:01 UTC
![image](https://user-images.githubusercontent.com/35259040/195299276-911f549c-e9e1-4498-80da-a27c6b75d78c.png)

os：win10

**Comment by oluademola** [comment] 2022-10-20 18:20
Hello @Avey777 

Unfortunately, I could not reproduce the problem using a windows machine (windows 11). I am not sure what went wrong, but did you try with rustc 1.64.0?

<img width="761" alt="Screenshot 2022-10-20 190511" src="https://user-images.githubusercontent.com/101267639/197027421-be7cc9c7-c44f-4767-98d3-ebbc7ec5d53e.png">

**Comment by curquiza** [comment] 2022-11-24 16:40
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2022-11-24 16:40 UTC
Labels: windows, support
