### ISSUE TITLE
V0.21 facetsDistribution attributes in search response are all lowercased

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1504] opened 2021-07-13 14:02 UTC
**Describe the bug**
Previously we kept the casing of filters in facetsDistribution. 

Given the following dataset:
```json
[
  { "id": 1,    "title": "Alice In Wonderland",                    "author": "Lewis Carroll",            "genre": "Fantasy" }
]
```

and the following query: 

`/search?facetsDistribution=genres`

The return is as follows: 
```
{
    "hits": [
        {
            "id": 1,
            "title": "Alice In Wonderland",
            "author": "Lewis Carroll",
            "genre": "Fantasy"
        }
    ],
    "query": "alice in ",
//...
    "facetsDistribution": {
        "genre": {
            "fantasy": 1
        }
    },
    "exhaustiveFacetsCount": false
}
```

**To Reproduce**
1. Index the provided dataset
2. Add `genre` in filterableAttributes
2. Search with facetsDistribution = ["genres"]
4. Casing lost in response

**Expected behavior**
Keeping same casing

**MeiliSearch version:** 
v0.21.0

**Comment by qdequele** [comment] 2021-07-13 15:49
Hello @bidoubiwa, I will close this issue because it's a duplicate of https://github.com/meilisearch/MeiliSearch/issues/1452. Thanks for all your tests!

**Closed by qdequele** 2021-07-13 15:49 UTC
