### ISSUE TITLE
Meilisearch only shows 5 items in a category  when 9 is in the category

### ISSUE THREAD

**Issue by leeweaver2222** [meilisearch/meilisearch#3284] opened 2022-12-30 14:01 UTC
Im using  v.0.30.5.

When coding  like this 

  public $category;
    public function render()
    {
        $search = Product::search('', function ($meilisearch, string $query, array $options) {

            $options['facets'] = ['colour'];

            return $meilisearch->search($query, $options);   
       
        })
        ->raw();

        $products = $this->category->products->find(collect($search['hits'])->pluck('id'));

        return view('livewire.product-browser',[
            'products' => $products
        ]);
    }

It only pulls 5 out of the category when 9 are in the category on the website but in the dashboard it pulls 9 

Whats the problem please.

Lee

**Comment by curquiza** [comment] 2023-01-02 12:59
Hello @leeweaver2222 

Can you send us information so that we can reproduce the bug? 
We would need the dataset (or the part of the dataset), but also your Meilisearch settings.

**Comment by leeweaver2222** [comment] 2023-01-03 22:34
The error
Undefined array key "facets"

The code

class ProductBrowser extends Component
{

    public $category;

    public $queryFilters = [];

    public $priceRange = [
    'max' => null
    ];

    public function mount()
    {
        $this->queryFilters = $this->category->products
                                    ->pluck('variations')
                                    ->flatten()
                                    ->groupBy('type')
                                    ->keys()
                                    ->mapWithKeys(fn ($key) => [$key => []])
                                    ->toArray();

    }


    public function render()
    {
        if(App::isLocale('en'))
        {
            $currencies = Currency::where('name', 'Pound Sterling')->get();
        }
        if(App::isLocale('eu'))
        {
            $currencies = Currency::where('name', 'Euro')->get();
        }
        if(App::isLocale('us'))
        {
            $currencies = Currency::where('name', 'US Dollar')->get();
        }
        if(App::isLocale('ca'))
        {
            $currencies = Currency::where('name', 'Canadian Dollar')->get();
        }
        if(App::isLocale('au'))
        {
            $currencies = Currency::where('name', 'Australian Dollar')->get();
        }


        $search = Product::search('', function ($meilisearch, string $query, array $options) {

            $filters = collect($this->queryFilters)->filter(fn($filter) => !empty($filter))
            ->recursive()    
            ->map(function ($value, $key) {
    
                    return $value->map(fn ($value) => $key . ' = "' . $value . '"');
    
            })
            ->flatten()
            ->join(' OR ');

            $options['filter'] = null;


            $options['facets'] = ['colour', 'size', 'fragrance', 'theme', 'crystal', 'price'];
            $options['filter'] = 'category_ids = ' . $this->category->id;


            if($filters)
            {
                
            $options['filter'] = $filters;

            }

            if($this->priceRange['max'])
            {
                $options['filter'] .= (isset($options['filter']) ? ' AND ' : '') . 'price < ' . $this->priceRange['max'];
            }
            
            return $meilisearch->search($query, $options);
        
        })->raw();


        $maxPrice = $this->category->products->max('price');
        
        $this->priceRange['max'] = $this->priceRange['max'] ?: $maxPrice;

        $products = $this->category->products->find(collect($search['hits'])->pluck('id'));

        return view('livewire.product-browser', [
            'currencies' => $currencies,
            'products' => $products,
            'filters' => $search['facets'],
            'maxPrice' => $maxPrice
        ]);
    }

All the facets have  been added scout.php 

<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Search Engine
    |--------------------------------------------------------------------------
    |
    | This option controls the default search connection that gets used while
    | using Laravel Scout. This connection is used when syncing all models
    | to the search service. You should adjust this based on your needs.
    |
    | Supported: "algolia", "meilisearch", "database", "collection", "null"
    |
    */

    'driver' => env('SCOUT_DRIVER', 'collection'),

    /*
    |--------------------------------------------------------------------------
    | Index Prefix
    |--------------------------------------------------------------------------
    |
    | Here you may specify a prefix that will be applied to all search index
    | names used by Scout. This prefix may be useful if you have multiple
    | "tenants" or applications sharing the same search infrastructure.
    |
    */

    'prefix' => env('SCOUT_PREFIX', ''),

    /*
    |--------------------------------------------------------------------------
    | Queue Data Syncing
    |--------------------------------------------------------------------------
    |
    | This option allows you to control if the operations that sync your data
    | with your search engines are queued. When this is set to "true" then
    | all automatic data syncing will get queued for better performance.
    |
    */

    'queue' => env('SCOUT_QUEUE', true),

    /*
    |--------------------------------------------------------------------------
    | Database Transactions
    |--------------------------------------------------------------------------
    |
    | This configuration option determines if your data will only be synced
    | with your search indexes after every open database transaction has
    | been committed, thus preventing any discarded data from syncing.
    |
    */

    'after_commit' => false,

    /*
    |--------------------------------------------------------------------------
    | Chunk Sizes
    |--------------------------------------------------------------------------
    |
    | These options allow you to control the maximum chunk size when you are
    | mass importing data into the search engine. This allows you to fine
    | tune each of these chunk sizes based on the power of the servers.
    |
    */

    'chunk' => [
        'searchable' => 500,
        'unsearchable' => 500,
    ],

    /*
    |--------------------------------------------------------------------------
    | Soft Deletes
    |--------------------------------------------------------------------------
    |
    | This option allows to control whether to keep soft deleted records in
    | the search indexes. Maintaining soft deleted records can be useful
    | if your application still needs to search for the records later.
    |
    */

    'soft_delete' => false,

    /*
    |--------------------------------------------------------------------------
    | Identify User
    |--------------------------------------------------------------------------
    |
    | This option allows you to control whether to notify the search engine
    | of the user performing the search. This is sometimes useful if the
    | engine supports any analytics based on this application's users.
    |
    | Supported engines: "algolia"
    |
    */

    'identify' => env('SCOUT_IDENTIFY', false),

    /*
    |--------------------------------------------------------------------------
    | Algolia Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure your Algolia settings. Algolia is a cloud hosted
    | search engine which works great with Scout out of the box. Just plug
    | in your application ID and admin API key to get started searching.
    |
    */

    'algolia' => [
        'id' => env('ALGOLIA_APP_ID', ''),
        'secret' => env('ALGOLIA_SECRET', ''),
    ],

    /*
    |--------------------------------------------------------------------------
    | MeiliSearch Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure your MeiliSearch settings. MeiliSearch is an open
    | source search engine with minimal configuration. Below, you can state
    | the host and key information for your own MeiliSearch installation.
    |
    | See: https://docs.meilisearch.com/guides/advanced_guides/configuration.html
    |
    */

    'meilisearch' => [
        'host' => env('MEILISEARCH_HOST', 'http://localhost:7700'),
        'key' => env('MEILISEARCH_KEY', null),
        'index-settings' => [
             'products' => [
                 'filterableAttributes'=> ['id', 'colour', 'size', 'fragrance', 'theme', 'crystal', 'price', 'category_ids'],
            ],
        ],
    ],

];

The index has been synced as per  instructions the Laravel Scout website

And the  the facets have been updated on Postman

Ever since you changed the Facets Distribution to facets  everyone ive spoke to has said nothing but problems 

There error code I dont know where to look for that in Meillisearch Latest Version Im new to Meilisearch  and also the documentation on the official website for  Meilisearch is not very clear with each version I use the categories only only on 9 or 10 or 20 when I have 100 products in there.

**Comment by curquiza** [comment] 2023-01-09 17:37
Hello @leeweaver2222,

You only give the code, we need
- the dataset
- the settings of your meilisearch (`filterableAttributes`, `searchableAttributes`...)
- the search you type (if you type some)
- what you get, and what you expected to get

**Comment by curquiza** [comment] 2023-01-24 17:02
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-01-24 17:02 UTC
Labels: needs more info, support
