### ISSUE TITLE
Duplicate IDs when indexing

### ISSUE THREAD

**Issue by philippeauriach** [meilisearch/MeiliSearch#1716] opened 2021-09-22 20:51 UTC
**Describe the bug**
Uploading several batches of the same content result in duplicates ids in meilisearch. Objects are coming from a Strapi service, and sent to a meilisearch instance (local docker latest image : 0.22.0) via the meilisearch nodejs package.
  
Full reproduction project available at : https://github.com/philippeauriach/meilisearch-dup-id

**To Reproduce**
- clone https://github.com/philippeauriach/meilisearch-dup-id
- configure your meilisearch instance endpoint in `hooks/meilisearch/utils.js` if needed
- `yarn install`
- `yarn develop`
- => you should have 27 products in your meilisearch instance (expected behavior)
- kill the process, run it again `yarn develop`
- => meilisearch now has 54 products (broken behavior, products are duplicated)

**Expected behavior**
Products should be replaced when having the same ID

**Screenshots**
<img width="713" alt="Capture d’écran 2021-09-22 à 22 49 59" src="https://user-images.githubusercontent.com/920265/134419913-877cfc9c-1755-43ef-8f52-4c574c012fc2.png">

**MeiliSearch version:** v0.22.0

**Additional context**
Strapi ?

**Comment by curquiza** [comment] 2021-09-23 12:28
Thank you so much for the report!
@ManyTheFish is investigation on it 🙂

**Comment by ManyTheFish** [comment] 2021-09-23 14:44
Hello @philippeauriach! Thanks for your bug report, this should be fixed in the next version of Meilisearch.

The bug occurs because a Document addition of `0` documents is made between other document addition.
To fix the bug in your application, you can change a bit your code in order to avoid empty document addition:

https://github.com/philippeauriach/meilisearch-dup-id/pull/1

**Comment by khash** [comment] 2021-09-28 12:13
FWIW, I've come across this issue with a pure Ruby client. Now I don't know if it is the same issue or not, but there is how you can recreate it:

(in this example `index = client.index('acme')`)

1. Add some docs `index.add_documents([{id: "foo"}, {id: "bar"}])`
2. Add an empty array `index.add_documents([])`

This will break the index in a way that while the API returns the documents correctly with `/indexes/acme/documents`, doing a `GET` on `/indexes/acme/documents/foo` returns a 404. 

This means if you run the first line again (add docs), you will end up with duplicates.

**Comment by curquiza** [comment] 2021-09-29 14:17
Hello @khash! Your bug should not be present in the next version. I did not succeed to reproduce your issue on our branch that will be merged into `main` soon :)

**Closed** 2021-09-29 15:31 UTC
Labels: bug

**Comment by Arsapol** [comment] 2022-11-07 13:10
I face this problem in version 0.29.1 when I update index setting more than 1 time.

Before update : Every works fine
After update : Document data duplicate with the same id

**Comment by curquiza** [comment] 2022-11-07 14:55
Hello @Arsapol 

Is it related to this? https://github.com/meilisearch/meilisearch/issues/3021

Otherwise, can you open an issue with the detailed steps to reproduce?

**Comment by Kerollmops** [comment] 2022-11-08 16:08
Indeed it looks related to #3021 and will be fixed in the next release of Meilisearch, i.e. v0.30.
