### ISSUE TITLE
Masterkey is not working under docker compose

### ISSUE THREAD

**Issue by PfiatDe** [meilisearch/meilisearch#3902] opened 2023-07-10 07:16 UTC
**Describe the bug**
Having some problems with the masterkey. It is not getting accepted. Running v1.2 with docker compose.
The masterkey was generated by meilisearch during first startup. The environment variable is set. 

```
/o/meilisearch> sudo docker exec -it fa952710fb99 sh
/meili_data # env
HOSTNAME=fa952710fb99
SHLVL=1
HOME=/root
MEILI_HTTP_ADDR=0.0.0.0:7700
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MEILI_MASTER_KEY='DxjJQT6vcMQIpjlwXrukoWnRrEkK1TLMY6rt5vaBOhc'
MEILI_SERVER_PROVIDER=docker
PWD=/meili_data
/meili_data # exit
/o/meilisearch> curl \
                                               -X GET 'http://localhost:7700/keys' \
                                               -H 'Authorization:DxjJQT6vcMQIpjlwXrukoWnRrEkK1TLMY6rt5vaBOhc'
{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}⏎                                                                                                                                                      
```
Container logs
```
meilisearch-meilisearch-1  |
meilisearch-meilisearch-1  | 888b     d888          d8b 888 d8b                                            888
meilisearch-meilisearch-1  | 8888b   d8888          Y8P 888 Y8P                                            888
meilisearch-meilisearch-1  | 88888b.d88888              888                                                888
meilisearch-meilisearch-1  | 888Y88888P888  .d88b.  888 888 888 .d8888b   .d88b.   8888b.  888d888 .d8888b 88888b.
meilisearch-meilisearch-1  | 888 Y888P 888 d8P  Y8b 888 888 888 88K      d8P  Y8b     "88b 888P"  d88P"    888 "88b
meilisearch-meilisearch-1  | 888  Y8P  888 88888888 888 888 888 "Y8888b. 88888888 .d888888 888    888      888  888
meilisearch-meilisearch-1  | 888   "   888 Y8b.     888 888 888      X88 Y8b.     888  888 888    Y88b.    888  888
meilisearch-meilisearch-1  | 888       888  "Y8888  888 888 888  88888P'  "Y8888  "Y888888 888     "Y8888P 888  888
meilisearch-meilisearch-1  |
meilisearch-meilisearch-1  | Config file path:  "none"
meilisearch-meilisearch-1  | Database path:             "./data.ms"
meilisearch-meilisearch-1  | Server listening on:       "http://0.0.0.0:7700"
meilisearch-meilisearch-1  | Environment:               "development"
meilisearch-meilisearch-1  | Commit SHA:                "d963b5f85ae9aea42615924de4e41e96a1e5358e"
meilisearch-meilisearch-1  | Commit date:               "2023-05-30T18:20:28+00:00"
meilisearch-meilisearch-1  | Package version:   "1.2.0"
meilisearch-meilisearch-1  | Anonymous telemetry:       "Disabled"
meilisearch-meilisearch-1  |
meilisearch-meilisearch-1  | A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.
...
meilisearch-meilisearch-1  | [2023-07-10T06:59:27Z INFO  actix_web::middleware::logger] 172.20.0.1 "GET /keys HTTP/1.1" 403 146 "-" "curl/7.81.0" 0.000501
```

docker-compose.yml
```
version: '3.4'
services:
  meilisearch:
    image: getmeili/meilisearch
    command: meilisearch --no-analytics
    ports:
      -   target: 7700
          published: 7700
          protocol: tcp
    environment:
      - MEILI_MASTER_KEY='DxjJQT6vcMQIpjlwXrukoWnRrEkK1TLMY6rt5vaBOhc'
    volumes:
        - ./meili_data:/meili_data
    networks:
      - web
    labels:
```

Tried changing the key, rebuild container, deleted the database, nothing was working.
Am I missing something here?

**Comment by oluademola** [comment] 2023-07-11 11:26
Hello @PfiatDe. Thanks for the report. The error message you mentioned in the initial bug description is caused by the absence of the "Bearer" authorization scheme in your curl request, and it should be `-H 'Authorization: Bearer xxx'` instead of `-H 'Authorization:xxx'`. However, I can confirm that specifying the master key as an environment variable in the compose file indeed doesn't work and results in an invalid API key error even when the scheme is included in the request. @gillian-meilisearch I can reproduce the bug.

**Comment by dureuill** [comment] 2023-07-13 07:28
Hello @PfiatDe, thanks for reporting the issue,

looking at the `env` output, the `MEILI_MASTER_KEY` environment variable has a value that contains literal quotes `'` at the beginning and the end (it is not just the display from `env` because other variables don't have it).

I can reproduce this condition with `export MEILI_MASTER_KEY="'DxjJQT6vcMQIpjlwXrukoWnRrEkK1TLMY6rt5vaBOhc'"` (note the double quote enclosing the single quotes).

Then, I reproduce the issue, but I can fix it by adding again these literal quotes to the authorization header. That is to say,

    -H 'Authorization: Bearer DxjJQT6vcMQIpjlwXrukoWnRrEkK1TLMY6rt5vaBOhc'

Is an invalid API key error, but

    -H "Authorization: Bearer 'DxjJQT6vcMQIpjlwXrukoWnRrEkK1TLMY6rt5vaBOhc'"

works.

So I think this is intended behavior. We could maybe guard against this by disallowing stray quotes in master keys, but that would be a breaking change.

I'm going to close this issue, feel free to reopen if my analysis does not apply to your case or any other reason.

**Closed by dureuill** 2023-07-13 07:28 UTC
Labels: bug
