### ISSUE TITLE
error when uploading: "message": "internal: number is not a valid finite number."

### ISSUE THREAD

**Issue by justinslud** [meilisearch/meilisearch#2807] opened 2022-09-27 20:52 UTC
I have a script that runs a database query, receives the response at json, then uploads that json to meilisearch (v0.28.1, running bare-metal on debian). The first few times I ran the script there were no errors, then I suddenly got this message from the `/tasks` endpoint:

```json
{
  "uid": ...,
  "indexUid": ...
  "status": "failed",
  "type": "documentAdditionOrUpdate",
  "details": {
    "receivedDocuments": 5000,
    "indexedDocuments": 0
  },
  "error": {
    "message": "internal: number is not a valid finite number.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
  },
  ...
}
```

Any ideas what this could be? Thank you!

**Comment by murilohns** [comment] 2022-10-24 00:52
I'm with the same problem.

I'm indexing this kind of document, under the "sues" index:
```
{
  "id": "cl9m1yixl00000tpc9pct70iy",
  "sueId": "0000637-44.2020.8.26.0100",
  "description": "long string"
}
```

Then, I'm trying to add "sueId" and "description" as filterableAttributes.

```
PATCH localhost:7700/indexes/sues/settings
{
  "filterableAttributes": [
    "sueId",
    "description"
  ]
}
```

Response:

```
{
	"taskUid": 2,
	"indexUid": "sues",
	"status": "enqueued",
	"type": "settingsUpdate",
	"enqueuedAt": "2022-10-24T00:47:18.763182253Z"
}
```

Then, when the task finishes, i got this result:

```
{
  "uid": 2,
  "indexUid": "sues",
  "status": "failed",
  "type": "settingsUpdate",
  "details": {
    "filterableAttributes": [
      "description",
      "sueId"
    ]
  },
  "error": {
    "message": "internal: number is not a valid finite number.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
  },
  "duration": "PT11.011410120S",
  "enqueuedAt": "2022-10-24T00:47:18.763182253Z",
  "startedAt": "2022-10-24T00:47:18.764135935Z",
  "finishedAt": "2022-10-24T00:47:29.775546055Z"
}
```

**Comment by murilohns** [comment] 2022-10-24 00:58
When I try to PATCH the filterableAttributes without indexed documents, it works perfectly, but then, when I try to index these documents, it fails.

FilterableAttributes task:
```json
{
  "results": [
    {
      "uid": 0,
      "indexUid": "sues",
      "status": "succeeded",
      "type": "settingsUpdate",
      "details": {
        "filterableAttributes": [
          "description",
          "sueId"
        ]
      },
      "duration": "PT0.017362787S",
      "enqueuedAt": "2022-10-24T00:54:59.264930772Z",
      "startedAt": "2022-10-24T00:54:59.26611368Z",
      "finishedAt": "2022-10-24T00:54:59.283476467Z"
    }
  ],
  "limit": 20,
  "from": 0,
  "next": null
}
```

Index Task:
```json
{
  "uid": 1,
  "indexUid": "sues",
  "status": "failed",
  "type": "documentAdditionOrUpdate",
  "details": {
    "receivedDocuments": 35990,
    "indexedDocuments": 0
  },
  "error": {
    "message": "internal: number is not a valid finite number.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
  },
  "duration": "PT10.815025797S",
  "enqueuedAt": "2022-10-24T00:56:54.166542009Z",
  "startedAt": "2022-10-24T00:56:54.179671924Z",
  "finishedAt": "2022-10-24T00:57:04.994697721Z"
}
```

**Comment by murilohns** [comment] 2022-10-24 01:18
Update: I just created the filterableAttribute for sueId, and indexed the documents only with `id and sueId` properties, and it works!

Probably it's a problem with the value of my description field 😬

**Comment by murilohns** [comment] 2022-10-24 01:33
Updated: Maybe it's a problem with special characters 🤔 
I have indexed the `description` field removing the special characters `let description = fullDescription.replace(/[^\w\s\d]/gm, "")` and it worked.

**Comment by oluademola** [comment] 2022-11-07 07:49
Hello @murilohns 

Thank you for the detailed explanation. Unfortunately, I was not able to reproduce the error. Could you please provide a sample document from your dataset or the contents of your description field? 

Thanks.

**Comment by murilohns** [comment] 2022-11-07 13:13
@oluademola I was indexing 30k documents, I don't know which one triggered the problem :(

**Comment by irevoire** [comment] 2022-11-07 13:25
@murilohns and can you share your whole dataset?

**Comment by Wattyyy** [comment] 2022-11-17 02:23
I encountered the same problem after executing add_documents() or add_documents_in_batches() from a python client.
By removing columns containing long strings from "filterableAttributes", I can successfully index all the documents.

**Comment by curquiza** [comment] 2022-11-24 16:38
Hello @Wattyyy, can you share you dataset and the steps to reproduce the issue?

**Comment by Wattyyy** [comment] 2022-11-25 12:45
@curquiza 
I reproduced the error by using internal data, so I cannot share the same data. I will share equivalent data with you after I prepare it.

**Comment by Wattyyy** [comment] 2022-11-26 14:08
Hello @curquiza, I created a repository to reproduce an error saying "internal: number is not a valid finite number.".
By following the steps written in README.md, you will reproduce the error. If you have any problems such as you cannot reproduce the error, feel free to contact me.

https://github.com/Wattyyy/ms-error-reproduction

**Comment by curquiza** [comment] 2022-11-28 09:48
Thank you so much @Wattyyy we will investigate this soon!

**Comment by curquiza** [comment] 2022-11-28 14:43
Also @Wattyyy we have just released [v0.30.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0), if you have the time, can you check if your issue is fixed by using v0.30.0?

**Comment by Wattyyy** [comment] 2022-11-28 14:55
@curquiza 
Thanks for the information. I will try the new version on my repository.

**Comment by Wattyyy** [comment] 2022-11-28 16:34
@curquiza 
Hello @curquiza, I found that MeiliSearch v0.30.0 solved the issue!
I experimented with my repository settings on amd64/ubuntu22.04 8GB RAM instance, and indexes were successfully created! (Of course, there are few cases where making very long sentences filterable.)

Thanks, MeiliSearch Team!

**Comment by Wattyyy** [comment] 2022-11-28 17:11
Hello @curquiza, I found that MeiliSearch v0.30.0 solved the issue!
I made sure whether the error was reproduced in my repository settings on amd64/ubuntu22.04 8GB RAM instance, and indexes were successfully created! (Of course, there are few cases where making very long sentences filterable.)

Thanks, MeiliSearch Team!

**Comment by curquiza** [comment] 2022-11-29 09:24
Thanks @Wattyyy! I close the issue!

**Closed by curquiza** 2022-11-29 09:24 UTC
Labels: bug, needs more info
