### ISSUE TITLE
MeiliSearchApiError: task 4499 panicked

### ISSUE THREAD

**Issue by lampofaladdin** [meilisearch/meilisearch#3592] opened 2023-03-16 11:02 UTC
**Describe the bug**

**To Reproduce**
1. install meili_search use docker
2. use nodeJs SDK
3. get search index   ``` index= this.searchClient.index('car');```
4. add document  ``` index.addDocuments(docs); ```
5. serach  document ```index.search('some chinese text');```
6.  get error ```MeiliSearchApiError: task 80043 panicked```
7. docker log error ```thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', /usr/local/cargo/git/checkouts/milli-00376cd5db949a15/e021bc1/milli/src/search/matches/matching_words.rs:37:74```

**Expected behavior**
work good

**Screenshots**
![image](https://user-images.githubusercontent.com/26974584/225595731-16f3f913-22b7-4b77-aae4-f7ed744dccd0.png)

**Meilisearch version:** [v1.0]

**Additional context**
only special keywords make error like '''合创汽车''', usually it works good.

document example:
```javascript
[
  {
    id: 364,
    name: 'car name in chinese',
    poster: 'https://xx.xx.xxx.png',
    minPrice: 11111,
    maxPrice: 22222,
    saleRank: 11,
  },]
```

os: Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022
nodeJS: v16.19.1
SDK: meilisearch@^0.30.0

Thanks.

**Comment by curquiza** [comment] 2023-03-16 13:02
Hello @lampofaladdin 
I did not succeed to trigger any error with your document example, I even added `合创汽车` in it

```json
[
  {
    "id": 364,
    "name": "car name in chinese",
    "test": "合创汽车",
    "poster": "https://xx.xx.xxx.png",
    "minPrice": 11111,
    "maxPrice": 22222,
    "saleRank": 11
  }
]
```

Can you do the following steps
- use v1.0.2 and see if you still have the error?
- if yes, can you send us the docuemnts/dataset to reproduce the error?


Thanks in advance for your help, we will fix it as soon as possible once we have these information 🙏

**Comment by lampofaladdin** [comment] 2023-03-17 03:48
@curquiza 
thank you.

v1.0.2 still not work.
![image](https://user-images.githubusercontent.com/26974584/225806837-ef30f056-d4c0-411c-8581-16da7d3b992e.png)

how to send you document?

**Comment by Kerollmops** [comment] 2023-03-20 17:02
Hey @lampofaladdin 👋,

Sorry for the delay. Could you please send the documents to kero@meilisearch.com? We will investigate that this week.

Have a nice day 🌴

**Comment by lampofaladdin** [comment] 2023-03-22 09:40
I've sent the email
 Thanks for your help!

**Comment by Kerollmops** [comment] 2023-03-28 09:15
Hey @lampofaladdin,

Thank you for the dataset. I investigated the bug using it and didn't find any issues. Is there anything more you can share with us? For example, your settings could probably involve synonyms or stop words that could trigger this bug.

Have a great day 🚚

**Comment by lampofaladdin** [comment] 2023-03-30 10:32
Thank you again.

**Comment by Kerollmops** [comment] 2023-03-30 11:46
Hey @lampofaladdin,

No, you are absolutely not an idiot! It is a bug on our side, the engine must never panic!
Thank you for the settings, I will try to reproduce the bug and fix it.

Have a good day!

**Comment by lampofaladdin** [comment] 2023-07-18 04:08
@ManyTheFish 
It works good!
Thanks for your help!

**Comment by gillian-meilisearch** [comment] 2023-07-18 08:31
@lampofaladdin from your comment above it looks like we're good to close this issue. Thanks for checking it out again ❤️ If any issue remains feel free to re-open and let us know.

**Closed by gillian-meilisearch** 2023-07-18 08:31 UTC
Labels: bug
