### ISSUE TITLE
Can't add documents (internal unexpected crash)

### ISSUE THREAD

**Issue by Avey777** [meilisearch/meilisearch#3018] opened 2022-11-01 14:31 UTC
![image](https://user-images.githubusercontent.com/35259040/199256980-9a23428e-a2ba-40bc-be74-e1f0c58fd7b8.png)

Meilisearch version: [e.g. v0.20.0]
0.30.o rc1
![image](https://user-images.githubusercontent.com/35259040/199258230-5c2b4046-eb94-4dcc-82b7-07b8dacf85f3.png)

Additional context
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]
OS: Windows10
Architecture: x86_64

**Comment by irevoire** [comment] 2022-11-01 14:56
Hey @Avey777 thanks a lot for testing the rc, could you share your documents with us so we can reproduce the bug?

**Comment by Avey777** [comment] 2022-11-02 13:11
{
	"id": "1",
	"objectID": "1",
	"productId": "1",
	"poster": "https://oss.tospinomall.com.gh/product_pic/d52846becdc245bea85821e16b2136d5?.webp",
	"good_title": "Tospnio Earphone Carrying Case, Small Round Hard EVA Shockproof Pocket Earbud Organizer Box",
	"tsin": "SPULWOOF35GV1",
	"brand_id": "1",
	"category_id": "551",
	"delivery_type": "2",
	"good_code": "",
	"goods_type": "1",
	"is_cash_delivery": "1",
	"keyword": "Hard Earphone Case Headphone Organizer, Lightweight Coin Purse, Bluetooth Earpiece Bag, High Protection Small EVA Storage Carrying Case, USB Cable Portable Storage Bag，Earphone box, earphone storage box, black earphone box, small earphone box, light earphone box，Small storage box",
	"seller_id": "31",
	"shop_id": "31",
	"transport_mode": "3"
}

**Comment by Avey777** [comment] 2022-11-02 13:12
> 嘿@Avey777非常感谢您测试 rc，您能否与我们分享您的文档，以便我们重现该错误？

```
{
	"id": "1",
	"objectID": "1",
	"productId": "1",
	"poster": "https://oss.tospinomall.com.gh/product_pic/d52846becdc245bea85821e16b2136d5?.webp",
	"good_title": "Tospnio Earphone Carrying Case, Small Round Hard EVA Shockproof Pocket Earbud Organizer Box",
	"tsin": "SPULWOOF35GV1",
	"brand_id": "1",
	"category_id": "551",
	"delivery_type": "2",
	"good_code": "",
	"goods_type": "1",
	"is_cash_delivery": "1",
	"keyword": "Hard Earphone Case Headphone Organizer, Lightweight Coin Purse, Bluetooth Earpiece Bag, High Protection Small EVA Storage Carrying Case, USB Cable Portable Storage Bag，Earphone box, earphone storage box, black earphone box, small earphone box, light earphone box，Small storage box",
	"seller_id": "31",
	"shop_id": "31",
	"transport_mode": "3"
}
```

**Comment by irevoire** [comment] 2022-11-02 14:19
Hey @Avey777, I added your document to my index but couldn't reproduce your issue (it just works).
You only sent this one document and nothing else (settings or anything)?

**Comment by Avey777** [comment] 2022-11-02 14:25
> 嘿@Avey777，我将您的文档添加到我的索引中，但无法重现您的问题（它只是有效）。您只发送了这一个文档，没有其他任何内容（设置或其他内容）？

http://ipv4.amiemall.com:7700/

aveyamie

You can try it .

**Comment by irevoire** [comment] 2022-11-02 14:30
Nice, thank you, @Avey777! I also tried adding this simple document that we have in our tests suite:
```json
{
  "id": "287947",
  "title": "Shazam!",
  "poster": "https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
  "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
  "release_date": 1553299200,
  "genres": [
    "Action",
    "Comedy",
    "Fantasy"
  ]
}
```

And I got the same error, maybe it's related to windows 10? :thinking:

**Comment by Avey777** [comment] 2022-11-02 14:33
> 很好，谢谢你，@Avey777！我还尝试在测试套件中添加这个简单的文档：
> 
> ```json
> {
>   "id": "287947",
>   "title": "Shazam!",
>   "poster": "https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
>   "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
>   "release_date": 1553299200,
>   "genres": [
>     "Action",
>     "Comedy",
>     "Fantasy"
>   ]
> }
> ```
> 
> 在一个干净的新索引上，我得到了同样的错误：
> 
> ```json
> {
>   "details": {
>     "receivedDocuments": 1
>   },
>   "duration": "PT0.101019S",
>   "enqueuedAt": "2022-11-02T14:29:10.2810072Z",
>   "error": {
>     "code": "internal",
>     "link": "https://docs.meilisearch.com/errors#internal",
>     "message": "An unexpected crash occurred when processing the task.",
>     "type": "internal"
>   },
>   "finishedAt": "2022-11-02T14:29:10.3838136Z",
>   "indexUid": "mieli",
>   "startedAt": "2022-11-02T14:29:10.2827946Z",
>   "status": "failed",
>   "type": "documentAdditionOrUpdate",
>   "uid": 23
> }
> ```
> 
> 也许它与 Windows 10 有关？🤔
> 
> @Avey777你在日志中看到什么吗？

admin API key

**Comment by Avey777** [comment] 2022-11-02 14:37
> > 很好，谢谢你，@Avey777！我还尝试在测试套件中添加这个简单的文档：
> > ```json
> > {
> >   "id": "287947",
> >   "title": "Shazam!",
> >   "poster": "https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
> >   "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
> >   "release_date": 1553299200,
> >   "genres": [
> >     "Action",
> >     "Comedy",
> >     "Fantasy"
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在一个干净的新索引上，我得到了同样的错误：
> > ```json
> > {
> >   "details": {
> >     "receivedDocuments": 1
> >   },
> >   "duration": "PT0.101019S",
> >   "enqueuedAt": "2022-11-02T14:29:10.2810072Z",
> >   "error": {
> >     "code": "internal",
> >     "link": "https://docs.meilisearch.com/errors#internal",
> >     "message": "An unexpected crash occurred when processing the task.",
> >     "type": "internal"
> >   },
> >   "finishedAt": "2022-11-02T14:29:10.3838136Z",
> >   "indexUid": "mieli",
> >   "startedAt": "2022-11-02T14:29:10.2827946Z",
> >   "status": "failed",
> >   "type": "documentAdditionOrUpdate",
> >   "uid": 23
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 也许它与 Windows 10 有关？🤔
> > @Avey777你在日志中看到什么吗？
> 
> admin API key

My colleague had the same problem in debian11.
I don't see an error log other than that

**Comment by thijndehaas** [comment] 2022-11-12 13:51
We run on Debian 11 and receive the same error for https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc1
This was in all calls to `documentAdditionOrUpdate`.

**Comment by Kerollmops** [comment] 2022-11-12 14:48
Hey @thijndehaas,

Could you please send us your dataset in private to kero@meilisearch.com? We were not able to reproduce the bug. Would you be able to share the logs of the search engine too? There must be something in there to help us debug.

**Comment by thijndehaas** [comment] 2022-11-12 15:14
Maybe this is helpfull:
```
[2022-11-12T15:11:47Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/indexname/documents HTTP/1.1" 202 140 "-" "Meilisearch PHP (v0.25.0)" 0.000324
thread '<unnamed>' panicked at 'the allocator is unable to allocate that much memory', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.3/src/sorter.rs:350:9
```

We index with 5000 documents in every batch, so I have tried it with 1000, 100, 10 and 1 document but they all give this error.

**Comment by thijndehaas** [comment] 2022-11-12 15:35
Even this doesn't work:
```php
$client->createIndex('indexname');
$index = $client->index('indexname');
$index->addDocuments([['id' => 1, 'name' => 'test']]);
```

```
[2022-11-12T15:34:05Z INFO  actix_server::builder] Starting 16 workers
[2022-11-12T15:34:05Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2022-11-12T15:34:08Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes HTTP/1.1" 202 125 "-" "Meilisearch PHP (v0.25.0)" 0.000844
[2022-11-12T15:34:08Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/indexname/documents HTTP/1.1" 202 135 "-" "Meilisearch PHP (v0.25.0)" 0.001959
[2022-11-12T15:34:08Z INFO  index_scheduler] A batch of tasks was successfully completed.
thread '<unnamed>' panicked at 'the allocator is unable to allocate that much memory', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.3/src/sorter.rs:350:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kerollmops** [comment] 2022-11-12 15:41
Thank you @thijndehaas,

This log is helpful. It looks like the indexing part of the engine is trying to allocate too much memory, and the system refuses to allow that. Would it be possible to have more information on the resources available on the machine that runs Meilisearch, please? Could you also share the command line arguments you have specified (don't leak your master key)? Are you running Meilisearch on Kubernetes or anything that resembles a system that shares the same resources, like a VM?

**Comment by thijndehaas** [comment] 2022-11-12 15:56
On MeiliSearch 0.29.1 I can index 10.000 documents at once and now not even a single document. So I don't think it is a server limit.
The server should have plenty of resources:
132GB ram
AMD Ryzen 9 5950X 16-Core Processor

We start Meilisearch in supervisor as a regular process with:
```
/home/meilisearch/meilisearch --http-addr=127.0.0.1:7700 --env=production --db-path=/home/meilisearch/data.ms --master-key=HIDDEN --no-analytics --max-indexing-threads=20
```

Entire supervisor config file:
```
[program:meilisearch]
command=/home/meilisearch/meilisearch --http-addr=127.0.0.1:7700 --env=production --db-path=/home/meilisearch/data.ms --master-key=HIDDEN --no-analytics --max-indexing-threads=20

autostart=true
autorestart=true

priority=5

stdout_events_enabled=true
stderr_events_enabled=true

stdout_logfile=/var/log/supervisor/meilisearch_out.log
stderr_logfile=/var/log/supervisor/meilisearch_err.log

user=root
```

This is the release we're running on:
https://github.com/meilisearch/meilisearch/releases/download/v0.30.0rc1/meilisearch-linux-amd64

**Comment by Kerollmops** [comment] 2022-11-12 16:43
Thank you for that information. It can help us debug. You have a huge machine with a lot of RAM.
 - Were you using this same setup when you were using v0.29.1? 
 - Could you please try [reducing the amount of memory Meilisearch is allowed to use when indexing](https://docs.meilisearch.com/learn/configuration/instance_options.html#max-index-size) to something like 12GiB/8GiB?
 - I don't know much about [supervisorrd](http://supervisord.org) but does it control the amount of memory a program can use without letting it knows? There can be kind of the same issues with Kubernetes.

**Comment by thijndehaas** [comment] 2022-11-13 10:58
It has to do something with the memory. As soon as the max-indexing-memory is set it works as excpecxted. All of this attempts work, even the very low or high memory values:
```
--max-indexing-memory=1Mb
--max-indexing-memory=10Mb
--max-indexing-memory=100Mb
--max-indexing-memory=1Gb
--max-indexing-memory=10Gb
--max-indexing-memory=100Gb
--max-indexing-memory=1000Gb
--max-indexing-memory=10000Gb
```

Is it possible that this change can't read the memory of our machine anymore?
https://github.com/meilisearch/meilisearch/commit/61edcd585aa4213074536a585a914f8ec8b6cc5c

I simply replaced Meilisearch version v0.29.1 with the latest RC and moved data.ms to data.ms.bak to test if it would work. So this machine has been running v0.29.1 for a while.
Starting Meilisearch from the terminal gives the same result as supervisor.

**Comment by curquiza** [comment] 2022-11-17 18:11
People having the same issue here, can you test [v0.30.0rc2](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc2) we have just released?
It might involve deleting your data.ms and re-import your data again (sorry for this)

**Comment by TUGTEN** [comment] 2022-11-21 02:47
I am still getting the same error on the latest rc (v0.30.0rc2)

My machine : Windows 11, 8GB RAM

**Logs:**
```[2022-11-21T02:28:46Z INFO  actix_server::builder] Starting 6 workers
[2022-11-21T02:28:46Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2022-11-21T02:29:00Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes HTTP/1.1" 202 118 "-" "Meilisearch Python (v0.22.2)" 0.011562
[2022-11-21T02:29:00Z INFO  actix_web::middleware::logger] 127.0.0.1 "PATCH /indexes/anime/settings HTTP/1.1" 202 120 "-" "Meilisearch Python (v0.22.2)" 0.007669
[2022-11-21T02:29:00Z INFO  index_scheduler] A batch of tasks was successfully completed.
[2022-11-21T02:29:00Z INFO  index_scheduler] A batch of tasks was successfully completed.
[2022-11-21T02:29:12Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /tasks HTTP/1.1" 200 782 "-" "insomnia/2022.6.0" 0.000660
[2022-11-21T02:30:00Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/anime/documents?primaryKey=id HTTP/1.1" 202 130 "-" "insomnia/2022.6.0" 0.014506
thread 'batch-operation' panicked at 'the allocator is unable to allocate that much memory (2831242231808 bytes requested)', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\grenad-0.4.4\src\sorter.rs:350:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-11-21T02:30:05Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /tasks HTTP/1.1" 200 1262 "-" "insomnia/2022.6.0" 0.000175`
```
**create_index.py**
```import meilisearch

mclient = meilisearch.Client('http://127.0.0.1:7700')
mclient.create_index("anime", {"primaryKey": "id"})

config = {
    'searchableAttributes': [
        'synonyms',
    ],
    'displayedAttributes': [
        'title',
        'picture',
        'malScore',
        'type',
        'nsfw'
    ],
    'sortableAttributes': [
        'malScore',
    ],
    'pagination': {
        
        'maxTotalHits': 7
    },
}
task = mclient.index("anime").update_settings(config)
print(task)
```

**Adding documents :**
```curl --request POST \
  --url 'http://localhost:7700/indexes/anime/documents?primaryKey=id' \
  --header 'Content-Type: application/json' \
  --data '[
	{
		"id": "63481090d42135a7d14adda1",
		"title": "!NVADE SHOW!",
		"type": "SPECIAL",
		"picture": "https://cdn.myanimelist.net/images/anime/1930/122178.jpg",
		"synonyms": "!NVADE SHOW! !nvade Show!",
		"nsfw": "white",
		"malScore": 6.06
	},
	{
		"id": "63481090d42135a7d14adda2",
		"title": "0",
		"type": "SPECIAL",
		"picture": "https://cdn.myanimelist.net/images/anime/12/81160.jpg",
		"synonyms": "0 Zero 0 (Zero) Chiaki Kuriyama - 0 Chiaki Kuriyama - Zero Chiaki Kuriyama: 0 Chiaki Kuriyama: 「0」 Kuriyama Chiaki - 0 「0」 栗山 千明「0」 栗山千明 - 0",
		"nsfw": "white",
		"malScore": 4.65
	}
]'
```

**Comment by dureuill** [comment] 2022-11-21 08:53
Regarding this issue, RC2 was adding additional logging, so it is no surprise that the issue still reproduces.

However, we can now see why the allocation is failing: the allocator is apparently trying to allocate around 2.83TB, which the OS does not allow.

It doesn't appear very realistic, but is that number related to how much RAM your machine might have?

Looks like further investigation is needed to understand why so much memory is requested.

**Comment by thijndehaas** [comment] 2022-11-21 09:28
I also tried this out. If I try to index 3 documents they all give the same amount of bytes:
```
[2022-11-21T09:20:32Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/indexname/documents HTTP/1.1" 202 139 "-" "Meilisearch PHP (v0.25.0)" 0.000342
thread 'batch-operation' panicked at 'the allocator is unable to allocate that much memory (46097024679936 bytes requested)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
[2022-11-21T09:20:32Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/indexname/documents HTTP/1.1" 202 139 "-" "Meilisearch PHP (v0.25.0)" 0.000346
thread 'batch-operation' panicked at 'the allocator is unable to allocate that much memory (46097024679936 bytes requested)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
[2022-11-21T09:20:32Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/indexname/documents HTTP/1.1" 202 139 "-" "Meilisearch PHP (v0.25.0)" 0.000524
thread 'batch-operation' panicked at 'the allocator is unable to allocate that much memory (46097024679936 bytes requested)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
```

The strange thing is that it does work as intended with the `--max-indexing-memory=50Gb` parameter.

Server specs:
Disk size 1.5T (635GB used)
Ram 132GB (57GB in use)

**Comment by dureuill** [comment] 2022-11-21 09:42
Hello, thijndehaas!

Thanks for trying with the new RC and reporting the logs!

Unless I'm mistaken, it looks like the allocator is mistakenly requesting about 46TB of RAM, which is understandingly refused by the system. 

I'm not familiar with how we detect how much RAM we can allocate though, so this will need investigation by someone else from the team (or bootstrapping me on this part)

**Comment by thijndehaas** [comment] 2022-11-21 09:43
Yes I think something changed in the RAM detection since v0.29

**Comment by dureuill** [comment] 2022-11-21 14:21
> Yes I think something changed in the RAM detection since v0.29

This looks spot-on!

Looks like we updated `sysinfo` (that we use to determine the maximum system RAM size) from 0.23.x to 0.26.x since 0.29:

```diff
 [[package]]
 name = "sysinfo"
-version = "0.23.13"
+version = "0.26.6"
```

(diff of the `Cargo.lock` between the `release-v0.30.0` branch and the `v0.29.0` tag)

However, when looking at the docs.rs for these two releases of `sysinfo`:

- [sysinfo 0.23.13](https://docs.rs/sysinfo/0.23.13/sysinfo/struct.System.html#method.total_memory): 
  > Returns the RAM size **in KB**.
- [sysinfo 0.26.6](https://docs.rs/sysinfo/0.26.6/sysinfo/struct.System.html#method.total_memory)
  > Returns the RAM size **in bytes**.

(emphasis mine)

However, it looks like we're still [computing the available memory as if it was in KB](https://github.com/meilisearch/meilisearch/blob/v0.30.0rc2/meilisearch-http/src/option.rs#L578), resulting in a 1024 factor of difference.

I'll open a PR shortly to change that.

**Comment by curquiza** [comment] 2022-11-21 17:16
Should be fixed by https://github.com/meilisearch/meilisearch/pull/3096

v0.30.0rc3 has been released containing the bug fix. Let us know!

**Closed by curquiza** 2022-11-21 17:16 UTC
Labels: bug

**Comment by LeilaHaouassa** [comment] 2023-10-03 07:41
Hello everyone, I see this is labeled as closed but I installed meilisearch on my machine last week and I'm having the same issue with this error 
`thread 'batch-operation' panicked at 'the allocator is unable to allocate that much memory (11327975424 bytes requested)', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\grenad-0.4.4\src\sorter.rs:350:9` 
and I installed using the direct download from this link [meilisearch-windows-amd64.exe](https://github.com/meilisearch/meilisearch/releases/download/v1.4.0/meilisearch-windows-amd64.exe)

**Comment by curquiza** [comment] 2023-10-03 11:51
Hello @LeilaHaouassa 

Can you open an issue instead of commenting a really old one?

We need the steps you made to reproduce the issue. Also, we need the version of Meiliserach you use.
