### ISSUE TITLE
Unexpected message error on badly formatted search parameters

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#598] opened 2020-04-08 15:47 UTC
## Should there be a comprehensible error in case of badly formatted search params ?
I tried a search query with the following parameters : 
```
q = "prince"
attributesToRetrieve = "*"
```

```bash
curl 'http://127.0.0.1:7700/indexes/movies_test/search?q=prince \ 
     &attributesToRetrieve=*' \
     -H "X-Meili-API-Key: 123"
```
and receive this as an answer : 
```bash
{"message":"document 11723790483854160345 not found"}%
```
I made this request thinking that the "*" was a valid input for query parameters. Which appears to not be the case.

**Should those errors be expected when a search parameter is badly formatted?**

## Human readable dataset used in the test

```
[
  { id: 123, title: 'Pride and Prejudice', comment: 'A great book' },
  { id: 456, title: 'Le Petit Prince', comment: 'A french book about a prince that walks on little cute planets' },
  { id: 2, title: 'Le Rouge et le Noir', comment: 'Another french book' },
  { id: 1, title: 'Alice In Wonderland', comment: 'A weird book' },
  { id: 1344, title: 'The Hobbit', comment: 'An awesome book' },
  {
    id: 4,
    title: 'Harry Potter and the Half-Blood Prince',
    comment: 'The best book',
  },
  { id: 42, title: "The Hitchhikers Guide to the Galaxy" },
]
```
## Testing script : 

Create index
```bash
curl -X POST 'http://localhost:7700/indexes' --data '{ "uid": "test"}' -H "X-Meili-API-Key: 123"
```

Add documents 
```
curl -X POST 'http://localhost:7700/indexes/test/documents' --data '[{"id":123,"title":"Pride and Prejudice","comment":"A great book"},{"id":456,"title":"Le Petit Prince","comment":"A french book about a prince that walks on little cute planets"},{"id":2,"title":"Le Rouge et le Noir","comment":"Another french book"},{"id":1,"title":"Alice In Wonderland","comment":"A weird book"},{"id":1344,"title":"The Hobbit","comment":"An awesome book"},{"id":4,"title":"Harry Potter and the Half-Blood Prince","comment":"The best book"},{"id":42,"title":"The Hitchhikers Guide to the Galaxy"}]' -H "X-Meili-API-Key: 123"
```

make the search
```bash
curl 'http://127.0.0.1:7700/indexes/movies_test/search?q=prince&attributesToRetrieve=*' -H "X-Meili-API-Key: 123"
```

**Comment by MarinPostma** [comment] 2020-06-23 08:45
@bidoubiwa I can't reproduce on master, can you confirm me that the bug is still there, or close this issue? thanks :)

**Comment by bidoubiwa** [comment] 2020-06-23 09:24
If you can't reproduce it I assume it has been fixed!

**Closed** 2020-06-23 10:01 UTC
