### ISSUE TITLE
actions: ["stats.get"] Mandatory?

### ISSUE THREAD

**Issue by fauzulkc** [meilisearch/meilisearch#4221] opened 2023-11-11 12:00 UTC
I have been using Multi-Tenancy since early, and I use the mini-dashboard to check the results. Since I updated to 1.4.x I found my client search wasn't working form the token.

Unable to find a good reason, I recreated an API key for an application, which then created a new Tenant Token to be used.  Weirdly, it don't work again. 
![image](https://github.com/meilisearch/documentation/assets/24224476/6dfb2534-f0da-4d9c-882c-c4818fd97d32)

```json
{
    "message": "The provided API key is invalid.",
    "code": "invalid_api_key",
    "type": "auth",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key"
}
```

So I dug deeper....

I queried with the newly generated API key from the backend for a specific index, and it worked fine. 🤔.  As per documentation, if I have the `actions:['search']` set, I am all good. I did have `"documents.*'`, and `"indexes.*"` too. But, when I was trying the API key on the mini-dashboard it didn't show the results with the generated key but it worked fine with the master key. As I went through the actions permission again, and picked out and added each of them into new token and kept trying which one worked I found out that for some reason the `'stats.get'` is not a mandatory action which needed to be set to fix the issue. Keep in mind this is also after I have added the `'version'` to the list as per the dashboard documentation.

😌So, Finally I set my api key to have the `'stats.get'` or rather a `'stats'*'` included in the actions list, and generated a new tenant token and everything worked fine again.

So, I don't know when it became necessary, but the documentation is either lacking it or it is a bug. Do let me know if I can help out by contributing for this. I will rather be happy, but I would need some confirmation or clarification to proceed.

Thank You.

**Comment by Kerollmops** [comment] 2023-11-21 15:51
Hey @fauzulkc 👋

Thanks for reporting this to us. However, the mini-dashboard you recorded is probably just showing the cached stats you got from the previous API key you provided. The tenant token are search API keys and do not show allow `stats.*`.

Can you do the safe experiment by performing hard reloads (clear cache) when you change the key, please? Maybe a simple page reload can do the trick 🤔

**Comment by fauzulkc** [comment] 2023-11-21 15:53
> Hey @fauzulkc 👋
> 
> Thanks for reporting this to us. However, the mini-dashboard you recorded is probably just showing the cached stats you got from the previous API key you provided. The tenant token are search API keys and do not show allow `stats.*`.
> 
> Can you do the safe experiment by performing hard reloads (clear cache) when you change the key, please? Maybe a simple page reload can do the trick 🤔 

Alright, I will get back to you; hopefully tomorrow

**Comment by curquiza** [comment] 2023-12-15 11:55
hello @fauzulkc 

do you have more information about this? 😊

**Comment by fauzulkc** [comment] 2023-12-15 12:16
> hello @fauzulkc 
> 
> do you have more information about this? 😊 

Sorry, didn't have the opportunity. I hope to find some time soon and do the extra test that @Kerollmops mentioned.

**Comment by fauzulkc** [comment] 2023-12-15 13:38
> Hey @fauzulkc 👋
> 
> Thanks for reporting this to us. However, the mini-dashboard you recorded is probably just showing the cached stats you got from the previous API key you provided. The tenant token are search API keys and do not show allow `stats.*`.
> 
> Can you do the safe experiment by performing hard reloads (clear cache) when you change the key, please? Maybe a simple page reload can do the trick 🤔

also @curquiza 

So I just did the test, and I can confirm without `stats.get` or `stats.*`, my search key the isn't able to browser the documents and the indexes.

When a tenant token is created from this key the behavior extends and the tenant won't show any results either.

![image](https://github.com/meilisearch/meilisearch/assets/24224476/228784f5-3663-4761-8895-8656a3ce17e9)
![image](https://github.com/meilisearch/meilisearch/assets/24224476/a4d473c5-57f9-40cd-af61-cac1b3012d61)

Here a screenshot from another key with `stats.get`
![image](https://github.com/meilisearch/meilisearch/assets/24224476/1f7b48c4-d3d5-414e-b1af-a91a7015df1b)

and this one works as expected, showing the documents and indexes, and the behavior extend to the tenant tokens generated from this key, showing proper results of the documents from search.

![image](https://github.com/meilisearch/meilisearch/assets/24224476/779c0b87-37ef-4e09-a261-c1c64c51d361)

**Comment by Kerollmops** [comment] 2023-12-18 10:29
Thank you, @fauzulkc, for taking the time to do further tests.

The dashboard needs the key to have the `stats.get` rights to fetch the list of indexes and show them in this dropdown. As the dashboard is meant for tests, asking the user for a key with more rights than just the search ones is okay.

Maybe the @meilisearch/docs-team can specify a key with the `stats.*` and `search` rights at most?

**Comment by fauzulkc** [comment] 2023-12-18 12:47
> Thank you, @fauzulkc, for taking the time to do further tests.
> 
> The dashboard needs the key to have the `stats.get` rights to fetch the list of indexes and show them in this dropdown. As the dashboard is meant for tests, asking the user for a key with more rights than just the search ones is okay.
> 
> Maybe the @meilisearch/docs-team can specify a key with the `stats.*` and `search` rights at most?

The issue is if I don't have `stats.get` or `stats.*` included for the key, the tenant tokens generated from the key don't show search results which is the main problem for me here. As it's not mentioned in the docs I had to experiment to figure out and hope everyone doesn't have to go through the same trouble if we can pin point the right direction.

**Comment by Kerollmops** [comment] 2023-12-18 13:55
> The issue is if I don't have stats.get or stats.* included for the key, the tenant tokens generated from the key don't show search results which is the main problem for me here.

You were testing this tenant token on the mini dashboard, and this dashboard needs the `stats.get` right to list the index names. However, tenant tokens can only have the `search` rights, and therefore it is not possible to use a tenant token on the dashboard.

**Comment by fauzulkc** [comment] 2023-12-18 14:20
> > The issue is if I don't have stats.get or stats.* included for the key, the tenant tokens generated from the key don't show search results which is the main problem for me here.
> 
> You were testing this tenant token on the mini dashboard, and this dashboard needs the `stats.get` right to list the index names. However, tenant tokens can only have the `search` rights, and therefore it is not possible to use a tenant token on the dashboard. 

> > The issue is if I don't have stats.get or stats.* included for the key, the tenant tokens generated from the key don't show search results which is the main problem for me here.
> 
> You were testing this tenant token on the mini dashboard, and this dashboard needs the `stats.get` right to list the index names. However, tenant tokens can only have the `search` rights, and therefore it is not possible to use a tenant token on the dashboard. 

Nope. I have my separate app that uses Tenant tokens to do search. I am not using tenant tokens for the mini dashboard. The dashboard is using the key(s) created via the master key.

I tried the dashboard only to do testing.

The case is this.
If my key for the backend have stats permission, the dashboard shows index and documents, and so does my tenant tokens from a frontend client. The tenant tokens are created from the backend application using a key with stats permission here.

If I don't have stats in my backend key, the tenant tokens don't get search results, just like the dashboard won't show index or the documents. The tokens in this case also created with using a backend key but this time without the stats permission


I hope this clarifies the concern.

**Comment by curquiza** [comment] 2023-12-27 11:57
Hello @fauzulkc 

Taking the conversation since @Kerollmops is on Holiday

> If I don't have stats in my backend key, the tenant tokens don't get search results, just like the dashboard won't show index or the documents. The tokens in this case also created with using a backend key but this time without the stats permission

There is an issue here. Your tenant tokens should be able to SEARCH (with the /search route, not the /documents route) even if they have been created with a key only having the `action: search`

Can you detail the steps to reproduce the issues with your application, WITHOUT mentioning the mini dashboard (since it's only for test and it needs `stats` actions to work)?

**Comment by curquiza** [comment] 2024-02-12 13:19
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-02-12 13:19 UTC
Labels: needs more info
