### ISSUE TITLE
Search request throwing an error

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#859] opened 2020-07-16 17:24 UTC
**Describe the bug**
I made a search request with the following query `Steins;Gate: The Movie − Load Region of Déjà Vu` and it raised this error 
```json
{
  "message":"impossible to search documents; heed error; MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size",
  "errorCode":"search_error",
  "errorType":"internal_error",
  "errorLink":"https://docs.meilisearch.com/error/search_error"
}
```

**To Reproduce**
1. Create an index and add a movie dataset
2. make a search request on `Steins;Gate: The Movie − Load Region of Déjà Vu`
3. error

**Expected behavior**
Is it because my search request is too long? Otherwise I expected it to work

**Comment by MarinPostma** [comment] 2020-07-16 21:15
@bidoubiwa that's weird! What meilisearch version is that?

**Comment by KidsDontPlay** [comment] 2020-07-18 13:02
I have the problem as well. I'm using 0.11.1.
The problem is the `−`. It's not the normal minus `-`.

**Comment by bidoubiwa** [comment] 2020-07-20 08:20
I'm using the latest (v0.12.0).

**Comment by curquiza** [comment] 2021-03-31 15:48
I tried to reproduce on v0.20.0 and I get:
```json
{"hits":[],"offset":0,"limit":20,"nbHits":0,"exhaustiveNbHits":false,"processingTimeMs":348,"query":"Steins;Gate: The Movie − Load Region of Déjà Vu"}
```
I'm closing this issue, feel free to reopen if anyone has this issue

**Closed by curquiza** 2021-03-31 15:48 UTC
Labels: type:bug
