### ISSUE TITLE
Highlighting is not working properly in Arabic

### ISSUE THREAD

**Issue by mamprogr** [meilisearch/meilisearch#4105] opened 2023-10-07 18:28 UTC
**Describe the bug**
When I search for words contains "ال" ("ال" in Arabic means "the"), the highlighting highlights all "ال" in all words instead of the search words only.

**To Reproduce**
1. Insert an Arabic document. like:
```
المسألة الخامسة في الإجماع السكوتي الإجماع السكوتي: هو قول بعض المجتهدين في العصر الواحد وسكوت من الباقين بعد إطلاعهم على هذا القول وعلمهم به من غير إنكار وقد اختلف الأصوليون في اعتبار القول مع السكوت على مذاهب خمسة
```
2. Search using this keyword:
```
الباقين
````
3. The output is:
![image](https://github.com/meilisearch/meilisearch/assets/734475/fa5a49e4-c51d-497f-ad77-d1c32e6fea0d)

**Expected behavior**
Only the blue bordered words should be highlighted:
![image](https://github.com/meilisearch/meilisearch/assets/734475/78ceeac7-4cb9-442c-9e8b-58a90a8f9668)

**Meilisearch version:**
v1.4.0

**Additional context**
- In Arabic, we use "ال" for most words, so highlighting it is an annoying thing.
- I tried to add it as a stop word, but it wasn't helpful because in Arabic it is glued without space to the next word. i.e., "ال باقيين" written as "الباقيين".

**Comment by curquiza** [comment] 2023-10-10 10:02
Hello @mamprogr 

I succeeded in reproducing the highlight issue, it's indeed a bug

In the meantime you can use phrase search by using `"` around the words of your query.

```
{
    "q": "\"الباقين\"",
    "attributesToHighlight": ["title"]
}
```

**Comment by curquiza** [comment] 2023-10-11 11:26
Ivoking @ManyTheFish if you have more insight to give on this issue 🧞

**Comment by ManyTheFish** [comment] 2023-10-16 16:10
Hello @mamprogr and @curquiza,
currently, Meilisearch highlights the stop words because we don't want the end-user to have a partial highlighting about this, for example, if you search for "soup of the day" and `of` and `the` are considered stop words, you don't want only to highlight `soup` and `day` like  "***soup*** of the ***day***".
However, the highlight flooding you are experiencing is indeed more disturbing than helpful, this could be enhanced by only highlighting the best matches per field, this would remove all this noise without having to ignore stopwords but it will probably miss some relevant matches in the process.

It's an enhancement that could be open to contribution and I can give some hints about how to implement it if someone is interested in contributing. 😄

**Comment by curquiza** [comment] 2023-10-17 11:43
hello @mamprogr and @ManyTheFish 

Thank you for your investigation @ManyTheFish 

it's indeed more a feature request than a bug, I update the labels

I opened a request on the product side here: https://github.com/meilisearch/product/discussions/701
@mamprogr feel free to add more information about your needs and use-case!

I close the issue since it's not a bug we can fix. I will open a new issue once we know how we want to implement this new improvement.

**Comment by abdullah-alnahas** [comment] 2023-10-18 09:42
Hello @ManyTheFish,
I am interested in implementing this. Could you provide some hints or guidance on the matter?

**Comment by curquiza** [comment] 2023-10-18 10:52
Hello @abdullah-alnahas 
we don't know yet if this is something we want to do, and how we want to solve this issue
First, you can participate in this discussion by defining your need and your usecase in this discussion: https://github.com/meilisearch/product/discussions/701

**Comment by curquiza** [comment] 2023-10-30 10:05
Following discussion [here](https://github.com/orgs/meilisearch/discussions/701#discussioncomment-7421540), looks like the behavior is not expected and this issue is not a feature request, but could be a bug.
I re-open the issue.

We need more investigation. If someone know why, feel free to open PRs, or to help us investigate.

**Comment by curquiza** [comment] 2024-09-17 08:47
Hello @mamprogr and @abdullah-alnahas 

We have just tested in [v1.10.0](https://github.com/meilisearch/meilisearch/releases/v1.10.0) and the issue is fixed 🎉

I close this issue, feel free to let us know if it does not fix your problem

**Closed by curquiza** 2024-09-17 08:47 UTC
Labels: bug, language
