### ISSUE TITLE
Different nbHits with limit and offset parameter

### ISSUE THREAD

**Issue by wendyZHANG27** [meilisearch/meilisearch#2176] opened 2022-02-17 02:42 UTC
"nbHits" get changed when using the limit and offset parameter. 
Take the "movies" dataset as an example. The keyword to search is `spider forest`.
Case 1:
search: 
`http://127.0.0.1:7700/indexes/movies/search?q=spider%20forest`
result: 
`"nbHits":33,"query":"spider forest","limit":20,"offset":0`
Case 2:
search: 
`http://127.0.0.1:7700/indexes/movies/search?q=spider%20forest&limit=10&offset=30`
result:
`"nbHits":42,"query":"spider forest","limit":10,"offset":30`

**Comment by curquiza** [comment] 2022-02-17 14:01
Hello @wendyZHANG27 

`nbHits` is not an exact integer representing the number of hits. It's an approximation. Here is the confusion. We are sorry for this and definitely want to improve this feature to remove this confusion.
I've open [a discussion](https://github.com/meilisearch/product/discussions/394) in our product repository. You're usecase and your feedback are more than welcome if you have the time 🙏

I'm closing this since it's not a bug but a design issue.

**Closed by curquiza** 2022-02-17 14:01 UTC
