### ISSUE TITLE
Internal Crash for parsing sample data in python script

### ISSUE THREAD

**Issue by anjanesh** [meilisearch/meilisearch#3582] opened 2023-03-10 09:25 UTC
**Describe the bug**
The movies.json doesn't seem to get loaded.

**To Reproduce**
```python
import meilisearch
import json
import asyncio

apiKey = 'xxx'

client = meilisearch.Client('http://localhost:7700', apiKey)

json_file = open('movies.json', encoding='utf-8')
movies = json.load(json_file)
client.index('movies').add_documents(movies)

print("task = ", client.get_task(0))

async def meilisearch_search():
	return client.index('movies').search('batman')	

loop = asyncio.get_event_loop()

res = loop.run_until_complete(meilisearch_search())
print(res)

loop.close()
```

**Expected behavior**

**Screenshots**
```
PS D:\> python .\meilisearch-test.py
task =  {'uid': 0, 'indexUid': 'movies', 'status': 'failed', 'type': 'documentAdditionOrUpdate', 'canceledBy': None, 'details': {'receivedDocuments': 31944, 'indexedDocuments': 0}, 'error': {'message': 'An unexpected crash occurred when processing the task.', 'code': 'internal', 'type': 'internal', 'link': 'https://docs.meilisearch.com/errors#internal'}, 'duration': 'PT0.039173700S', 'enqueuedAt': '2023-03-10T08:56:30.8561016Z', 'startedAt': '2023-03-10T08:56:30.8751564Z', 'finishedAt': '2023-03-10T08:56:30.9143301Z'}
{'hits': [], 'query': 'batman', 'processingTimeMs': 0, 'limit': 20, 'offset': 0, 'estimatedTotalHits': 0}
PS D:\>
```

**Meilisearch version:** v1.0.2

**Additional context**
Windows 11 Ent - PowerShell

**Comment by anjanesh** [comment] 2023-03-13 13:11
Just to note - this same code works on my macOS Mojave i7 MacBook Pro with the expected search results.

**Comment by curquiza** [comment] 2023-03-13 13:44
Hello @anjanesh 

Thanks for the report!
I put the `support` label to call our support team on it 😊 

@oluademola, could you try to reproduce the bug on Windows with v1.0.2, v1.1.0-rc.1?

It's weird we have this kind of basic bug in the stable release.

**Comment by oluademola** [comment] 2023-03-14 15:37
Hello @anjanesh and @curquiza. Unfortunately, I could not reproduce the error in my test. I used the same script above with v1.0.2, and it appears I got the expected result. Please take a look at the screenshot below. 

<img width="657" alt="Screenshot 2023-03-14 163111" src="https://user-images.githubusercontent.com/101267639/225052540-3526b5f3-c5ec-4503-acdf-b89d8499b5d6.png">

I'd let you know if I find anything different testing the rc of v1.1

**Comment by curquiza** [comment] 2023-03-14 16:10
@anjanesh is it a bug you can reproduce each time you run the script? Or is it a flaky bug?

**Comment by curquiza** [comment] 2023-05-10 13:22
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-05-10 13:22 UTC
Labels: needs more info, support

**Comment by anjanesh** [comment] 2023-05-10 14:51
Well ... I have a new Windows 11 Home laptop and don't know how to install this.

![image](https://github.com/meilisearch/meilisearch/assets/85973/a18f6929-2293-4f96-99fc-74468080bd7d)

There's no problem on *nix machines.

**Comment by anjanesh** [comment] 2023-05-11 00:10
I got it working in my Windows 11 Home with version 1.1.1 and Python 3.11 !
