### ISSUE TITLE
Too many open files (os error 24)

### ISSUE THREAD

**Issue by cseblog** [meilisearch/meilisearch#2652] opened 2022-07-31 03:40 UTC
**Describe the bug**
        {
            "uid": 0,
            "indexUid": "post_history",
            "status": "failed",
            "type": "documentAdditionOrUpdate",
            "details": {
                "receivedDocuments": 360461,
                "indexedDocuments": 0
            },
            "error": {
                "message": "Too many open files (os error 24)",
                "code": "internal",
                "type": "internal",
                "link": "https://docs.meilisearch.com/errors#internal"
            },
            "duration": "PT99.484276S",
            "enqueuedAt": "2022-07-31T03:20:03.724226Z",
            "startedAt": "2022-07-31T03:20:03.724793Z",
            "finishedAt": "2022-07-31T03:21:43.209069Z"
        }
**To Reproduce**

360461 documents of forum small posts
I had created an index on my M1 macbook 32GB Ram, 
Unable to inject via Rust api. 

**Expected behavior**

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]
0.28.0
**Additional context**
Mac OS, 32 GB, M1Pro

**Comment by cseblog** [comment] 2022-07-31 04:10
I split the data set into 100K chunks of documents, then the injection is okay. Any way to have Meilisearch inject 1 million documents?

**Comment by oluademola** [comment] 2022-08-02 07:40
Hi @cseblog 

Regarding the error, the default setting for the maximum number of open files might be too low, as is usually the case on most machines. Here is an [article](http://woshub.com/too-many-open-files-error-linux/) to help you better understand the problem and implement the solution to fix it. To index 1M records, I'd advise updating the default `searchableAttributes `list to only contain fields you want to search. You should send your documents in batches, but I strongly advise you to try the auto-batching feature to speed up the indexing process. About disk space, we recommend reserving at least 10 times the size of your raw data, meaning if your document size is 10GB, you should at least reserve 100GB of SSD disk space for Meilisearch. See more performance optimization suggestions in the [dedicated documentation](https://docs.meilisearch.com/learn/advanced/indexation.html#improving-indexation-performance). 

Hope this helps. Thanks.

**Comment by cseblog** [comment] 2022-08-03 01:13
Thanks for your nice reply. I will check it out.

**Comment by curquiza** [comment] 2022-08-23 12:02
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2022-08-23 12:02 UTC
Labels: support

**Comment by hoangminhung** [comment] 2022-10-28 07:39
@cseblog  @curquiza i stick to your suggest article to resolve this problem, but it seem not work. Here is my output.
I am using AWS AMI for meilisearch Meilisearch-v0.29.0-Ubuntu-20.04

`root@ip-172-31-42-183:~# cat /proc/sys/fs/file-nr
2432	0	9223372036854775807
root@ip-172-31-42-183:~# ps -aux | grep meilisearch
root        1013  1.5 39.0 35130748364 773884 ?  Ssl  07:28   0:07 /usr/bin/meilisearch --http-addr 0.0.0.0:7700 --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps
root        1063  0.0  0.0   8168   656 pts/0    R+   07:36   0:00 grep --color=auto meilisearch
root@ip-172-31-42-183:~# ulimit -s
8192
root@ip-172-31-42-183:~# ulimit -n
50000`

**Comment by curquiza** [comment] 2022-10-31 08:57
Hello @hoangminhung
Have you tried to update `ulimit -Sn XXX` where XXX is a big number?

If yes, can you open a detailed issue (I mean, with detailed steps) to reproduce your bug?
