### ISSUE TITLE
Chainsaw Server CPU load + Disk IO always increasing + Disk storage always increasing

### ISSUE THREAD

**Issue by milanbgd011** [meilisearch/meilisearch#3466] opened 2023-02-07 10:39 UTC
**Describe the bug**
On server I see constant CPU load increase, very linear increase over time, with same usage

**To Reproduce**
I have 1 index.
I use 2 workers to update data from my main DB to meilisearch index, both transfering very small amount of DIFF data to them.

**Expected behavior**
CPU not to go up during time.

**Screenshots**
![Screenshot 2023-02-07 at 11 34 29](https://user-images.githubusercontent.com/20988958/217222080-9915f93f-eb03-49af-86e6-422fddd40e75.png)

**Meilisearch version:**
v0.35.0

**Additional context**
Ubuntu 22.04 LTS, hosted on Digital Ocean.
Minimal Docker install with docker-compose of the meilisearch instance, nothing else.

**Comment by milanbgd011** [comment] 2023-02-07 12:23
Hi @curquiza 

I did not update to 1.0, waiting for 1.0.1 :) so I am sure I can push it to production, so far I can wait a bit.

Yes, meilisearch is alone with docker-compose only on it + 2 very tiny deno apps.

Data set is just 10k of product specs info, not too complex.

Here are more screenshots from the machine:

### GLANCES (look at the "meilisearch1" on top, it has isolated CPU for that docker image only)
![Screenshot 2023-02-07 at 13 19 20](https://user-images.githubusercontent.com/20988958/217243521-e31e1d2f-1e10-4d2c-bf31-e084f643333a.png)

### DOCKER STATS
![Screenshot 2023-02-07 at 13 19 34](https://user-images.githubusercontent.com/20988958/217243524-7974a891-b0eb-4762-9423-5b188ad59399.png)

### DOCKER LOGS
![Screenshot 2023-02-07 at 13 20 01](https://user-images.githubusercontent.com/20988958/217243526-c186905a-24d4-49a7-9377-5d41cccc145b.png)

**Comment by curquiza** [comment] 2023-02-07 12:32
Indeed 10k is not big, but it can depend on the size of each document. Can you give an example of one product? How many fields, the number of characters per field?

Also, is meilisearch processing any tasks? You can check it with the [`GET /tasks` route](https://docs.meilisearch.com/reference/api/tasks.html#get-tasks)

**Comment by milanbgd011** [comment] 2023-02-07 12:49
Not a single task is being processed at all, here is /tasks:

```bash
{
  results: [
    {
      uid: 647336,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.307683898S",
      enqueuedAt: "2023-02-07T12:44:34.026971537Z",
      startedAt: "2023-02-07T12:44:34.46367463Z",
      finishedAt: "2023-02-07T12:44:34.771358528Z"
    },
    {
      uid: 647335,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.453124153S",
      enqueuedAt: "2023-02-07T12:44:34.005262235Z",
      startedAt: "2023-02-07T12:44:34.007786427Z",
      finishedAt: "2023-02-07T12:44:34.46091058Z"
    },
    {
      uid: 647334,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.371444262S",
      enqueuedAt: "2023-02-07T12:44:33.025302422Z",
      startedAt: "2023-02-07T12:44:33.343081278Z",
      finishedAt: "2023-02-07T12:44:33.71452554Z"
    },
    {
      uid: 647333,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.330780306S",
      enqueuedAt: "2023-02-07T12:44:33.005863237Z",
      startedAt: "2023-02-07T12:44:33.010055701Z",
      finishedAt: "2023-02-07T12:44:33.340836007Z"
    },
    {
      uid: 647332,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.321717155S",
      enqueuedAt: "2023-02-07T12:44:29.028076023Z",
      startedAt: "2023-02-07T12:44:29.397884825Z",
      finishedAt: "2023-02-07T12:44:29.71960198Z"
    },
    {
      uid: 647331,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.382842515S",
      enqueuedAt: "2023-02-07T12:44:29.010520478Z",
      startedAt: "2023-02-07T12:44:29.013156314Z",
      finishedAt: "2023-02-07T12:44:29.395998829Z"
    },
    {
      uid: 647330,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.380338439S",
      enqueuedAt: "2023-02-07T12:44:28.021959199Z",
      startedAt: "2023-02-07T12:44:28.374809807Z",
      finishedAt: "2023-02-07T12:44:28.755148246Z"
    },
    {
      uid: 647329,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.364410640S",
      enqueuedAt: "2023-02-07T12:44:28.005987646Z",
      startedAt: "2023-02-07T12:44:28.008396799Z",
      finishedAt: "2023-02-07T12:44:28.372807439Z"
    },
    {
      uid: 647328,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.311637374S",
      enqueuedAt: "2023-02-07T12:44:24.023619451Z",
      startedAt: "2023-02-07T12:44:24.347679212Z",
      finishedAt: "2023-02-07T12:44:24.659316586Z"
    },
    {
      uid: 647327,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.336803779S",
      enqueuedAt: "2023-02-07T12:44:24.005416082Z",
      startedAt: "2023-02-07T12:44:24.009081712Z",
      finishedAt: "2023-02-07T12:44:24.345885491Z"
    },
    {
      uid: 647326,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.317429588S",
      enqueuedAt: "2023-02-07T12:44:23.056350832Z",
      startedAt: "2023-02-07T12:44:23.378047207Z",
      finishedAt: "2023-02-07T12:44:23.695476795Z"
    },
    {
      uid: 647325,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.360253042S",
      enqueuedAt: "2023-02-07T12:44:23.006694461Z",
      startedAt: "2023-02-07T12:44:23.009443782Z",
      finishedAt: "2023-02-07T12:44:23.369696824Z"
    },
    {
      uid: 647324,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.312324264S",
      enqueuedAt: "2023-02-07T12:44:19.024070936Z",
      startedAt: "2023-02-07T12:44:19.346523221Z",
      finishedAt: "2023-02-07T12:44:19.658847485Z"
    },
    {
      uid: 647323,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.336703327S",
      enqueuedAt: "2023-02-07T12:44:19.005760944Z",
      startedAt: "2023-02-07T12:44:19.008017908Z",
      finishedAt: "2023-02-07T12:44:19.344721235Z"
    },
    {
      uid: 647322,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.312581834S",
      enqueuedAt: "2023-02-07T12:44:18.022644473Z",
      startedAt: "2023-02-07T12:44:18.32258329Z",
      finishedAt: "2023-02-07T12:44:18.635165124Z"
    },
    {
      uid: 647321,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.312538320S",
      enqueuedAt: "2023-02-07T12:44:18.005373392Z",
      startedAt: "2023-02-07T12:44:18.008249126Z",
      finishedAt: "2023-02-07T12:44:18.320787446Z"
    },
    {
      uid: 647320,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.321990022S",
      enqueuedAt: "2023-02-07T12:44:14.020325668Z",
      startedAt: "2023-02-07T12:44:14.354237883Z",
      finishedAt: "2023-02-07T12:44:14.676227905Z"
    },
    {
      uid: 647319,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.344354654S",
      enqueuedAt: "2023-02-07T12:44:14.005016729Z",
      startedAt: "2023-02-07T12:44:14.007388782Z",
      finishedAt: "2023-02-07T12:44:14.351743436Z"
    },
    {
      uid: 647318,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.345472236S",
      enqueuedAt: "2023-02-07T12:44:13.029062725Z",
      startedAt: "2023-02-07T12:44:13.358980744Z",
      finishedAt: "2023-02-07T12:44:13.70445298Z"
    },
    {
      uid: 647317,
      indexUid: "worker-deno",
      status: "succeeded",
      type: "documentAdditionOrUpdate",
      canceledBy: null,
      details: { receivedDocuments: 1, indexedDocuments: 1 },
      error: null,
      duration: "PT0.341783292S",
      enqueuedAt: "2023-02-07T12:44:13.006147343Z",
      startedAt: "2023-02-07T12:44:13.008829126Z",
      finishedAt: "2023-02-07T12:44:13.350612418Z"
    }
  ],
  limit: 20,
  from: 647336,
  next: 647316
}
```

**Comment by milanbgd011** [comment] 2023-02-07 12:54
> Indeed 10k is not big, but it can depend on the size of each document. Can you give an example of one product? How many fields, the number of characters per field?

It is like 200 fields with 30 characters per field, not more.

**Comment by milanbgd011** [comment] 2023-02-07 13:31
If you guy have any other ideas let me know. I have expirience with devops, coding and all. Can check a lot of stuff for you in production directly. I have time for this, just let me know what do you think I should do/try. 

Thank you for a wonderful product!!! Meilisearch rules!

**Comment by curquiza** [comment] 2023-02-07 15:22
Also, is there any search done (how many, how big)? It could explain the usage

**Comment by milanbgd011** [comment] 2023-02-08 04:49
> Also, is there any search done (how many, how big)? It could explain the usage

Well, whatever the search is being done we have day-night here, because it is in local language and traffic drops to zero during nighttime ~03AM, so this should at least show some drop there. Look at the bandwidth usage, it has drops each day, this should also mean we have drops in CPU usage, but it is always constant and going up. Makes no sense. If the site was on english and international then this chart would make sense.

**Comment by curquiza** [comment] 2023-02-09 11:25
Thank you very much for your feedback @milanbgd011 
To be honest we did not succeed to reproduce the issue, which is problematic to fix it...

To be sure it does not impact your Meilisearch experience
- do you encounter any latency due to this when using Meilisearch, especially during the search?
- is your DigitalOcean bill related to your CPU/RAM usage?

**Comment by milanbgd011** [comment] 2023-02-09 12:19
It is a bit slower, but not too much for users to notice, but is degraded.
DigitalOcean gives fixed CPU/RAM per month, no changes there during time.

I will dig into the devops part of this deeper to make sure all is clear in that area. Will report back.

**Comment by curquiza** [comment] 2023-02-09 12:24
Also For your information, since you are probably paying DO server, and your data seems small -> an alternative is also our [Cloud solution](https://cloud.meilisearch.com/login): it's free for the 10k first search and 100k first documents (totally present in the DB, not the number of indexation). See [our pricing](https://www.meilisearch.com/pricing) for more information

**Comment by milanbgd011** [comment] 2023-02-10 12:58
Thank you for suggestion, will take a look.

---

Very interesting drop, without me doing anything at all.
Like it flushed something big to the disk and then CPU dropped.

# 6 hours

![Screenshot 2023-02-10 at 13 55 21](https://user-images.githubusercontent.com/20988958/218097623-2d1364c8-97bf-4b65-b675-cf549a523e1c.png)

# 24 hours

![Screenshot 2023-02-10 at 13 56 47](https://user-images.githubusercontent.com/20988958/218097867-f020fd41-2107-4fc0-8a79-1a7154945d39.png)

# 7 days

![Screenshot 2023-02-10 at 13 57 19](https://user-images.githubusercontent.com/20988958/218097919-009d89d5-9149-4b85-8cf6-a2ece268e4fc.png)

**Comment by milanbgd011** [comment] 2023-02-11 07:10
Very weird behaviour. I did not touch anything. Traffic is the same.
Some disk writing occured and then CPU fell to previous levels.
Will monitor further to see if it will rise again.
It works fast in production, leaving it as is so I can track the problem further.

# 24 hours
![Screenshot 2023-02-11 at 08 06 19](https://user-images.githubusercontent.com/20988958/218245603-48c4ef04-482c-4ade-9197-50a29dd04f23.png)

# 7 days
![Screenshot 2023-02-11 at 08 06 35](https://user-images.githubusercontent.com/20988958/218245605-5eeeba22-963a-4830-8913-0d59935cd4e7.png)

# 14 days
![Screenshot 2023-02-11 at 08 06 59](https://user-images.githubusercontent.com/20988958/218245606-e08897f8-b501-4df7-9d2c-21d3bcc5c0f4.png)

**Comment by milanbgd011** [comment] 2023-02-11 07:18
Reading https://github.com/meilisearch/meilisearch/issues/3349#issuecomment-1411923608
in (3.) he explains what could be the reason for problem.

One thing that is maybe specific to this situation is that I have 10.000 records in index and I am updating individual fields on that index all the time, but on coupe of records each minute. This is "always-updating" index, I do not recreate index from zero at all, only first time.

I will leave it in production for now to see how it behaves and when 1.0.1 or 1.0.2 comes I will then switch to it and then can see clearly if that problem is solved or not with new version.

**Comment by milanbgd011** [comment] 2023-02-13 06:35
And then it crashed, the flat line at the end...  Will switch to 1.0 version to test...

![Screenshot 2023-02-13 at 07 33 48](https://user-images.githubusercontent.com/20988958/218387540-3ecd35fb-dee6-4766-8230-de6863e68b19.png)

**Comment by irevoire** [comment] 2023-02-13 14:39
Hey, @milanbgd011; sorry for the delay. We were on weekend!

Thanks a lot for all your charts. It's super interesting for us to get this kind of feedback even if we don't have an immediate solution :grimacing: 

> And then it crashed [...]

What happened? Do you have some logs? Was it OOM killed (but the memory usage was super slow :thinking:)

Also, once it crashed the memory usage didn't reduce all that much from what I see; what was consuming memory if it wasn't meilisearch?

**Comment by milanbgd011** [comment] 2023-02-14 11:12
This is 1vCPU/1GB Digital Ocean instance, looking at graphs it is within the load. 
Meilisearch is using 200mb total memory, very efficient.
My dataset is small and do not have a lot of filterable/searchable params.
So, 10k records with 200 fields each not containing much characters.

I am switching to V1.0 today and will monitor if this behaviour repeats or not. There are some bugs fixed which I mentioned above, so maybe this is it. I will have exact same load as before to test in prod and see what is happening.

Just let me know where are logs inside docker container? I cant find any.

**Comment by irevoire** [comment] 2023-02-15 10:23
> Just let me know where are logs inside docker container?

I believe you can run `docker logs {container-name}` to get the log of one specific container 🤔 

> Hmmm.... indexed data of meilisearch on disk is 750MB, but in ram is only 200mb. Maybe it needs to "touch" disk too often because of the low RAM situation?

Hum, I'm not sure I understood.
But are you taking the cached ram into account? That's also used by meilisearch.

On htop, for example, the yellow part of the ram usage represents the cached memory. It doesn't appear as « owned » by meilisearch because the kernel can decide to use it for something else if it needs to, but if there is no process running, usually everything will be used for meilisearch 😁 
<img width="857" alt="image" src="https://user-images.githubusercontent.com/7032172/219000670-7b8e4b22-79fb-4d72-b076-6b7fa6a75b5e.png">

**Comment by milanbgd011** [comment] 2023-02-15 12:38
When docker reboots it takes all logs with it, so no logs available. 
I meant that meilisearch saves data on disk in /data.ms folder which is 750MB, but keeps only 200MB in RAM memory.
I switched to V1.0 in production, will update here if any problems found.

**Comment by milanbgd011** [comment] 2023-02-15 21:28
Switched to V1.0, disabled "enviroment: development" which was ON because I wanted to check thru UI how things work. Now environment is in production. Made workers that pump data in a bit less agressive. Chart looks clean for now:

![Screenshot 2023-02-15 at 22 26 56](https://user-images.githubusercontent.com/20988958/219171951-343551c3-9343-4bc7-a9e7-675cbc4331a3.png)

**Comment by curquiza** [comment] 2023-02-16 08:38
Thanks @milanbgd011, your reports are really appreciated
Let us know if it changes

**Comment by milanbgd011** [comment] 2023-02-18 06:32
Seems fixed in v1.0 with production mode ON.

It is really crazy to think that this is 1vcpu shared / 1gb RAM memory with this load stats, I used 4vcpu/8gb RAM for exact same setup for Elastic search that had worse load stats than this.  🤯🤯🤯

![Screenshot 2023-02-18 at 07 29 44](https://user-images.githubusercontent.com/20988958/219845111-7b5f619d-140d-4c83-8055-2da68b632966.png)

**Comment by gmourier** [comment] 2023-02-18 10:31
Thank you, @milanbgd011, for all those tests, sharing, and tenacity. Don't hesitate to reopen this issue if it happens.

**Comment by milanbgd011** [comment] 2023-03-01 12:07
Time to reopen issue with new data. This is v1.0.0 in production mode.

I have automated deploy via Ansible scripts and am reusing the same setup for many machines, but here booting only meilisearch instead of something else. This is 100% only meilisearch data, nothing else is on machine, absolutely nothing.

**PROBLEMS:**
- It seems that precisely each 5 days, even time is similar during the day something happens and load drops
- disk usage is growing all the time, while memory usage is actually dropping
- disk IO is constantly growing

## 14 days

![Screenshot 2023-03-01 at 13 06 21](https://user-images.githubusercontent.com/20988958/222134899-ec3d06e5-d43c-42a3-9491-95712c4b9075.png)

## 7 days

![Screenshot 2023-03-01 at 13 05 52](https://user-images.githubusercontent.com/20988958/222134879-b603f12f-b5e5-4fe9-acf8-e8927f88a372.png)


## 24 hours

![Screenshot 2023-03-01 at 13 06 07](https://user-images.githubusercontent.com/20988958/222134889-1bbf89df-682d-4ff7-9f69-de5aae3f99d9.png)

**Comment by irevoire** [comment] 2023-03-06 14:35
Is meilisearch being killed every five days?

**Comment by curquiza** [comment] 2024-02-12 13:13
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to open a new issue if needed 😊

**Closed by curquiza** 2024-02-12 13:13 UTC
Labels: bug, needs more info, CPU/RAM usage
