### ISSUE TITLE
Facet field is not added in searchable Attribute

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1066] opened 2020-11-04 14:24 UTC
**Describe the bug**
When adding a field to facetsDistribution before adding the documents, this field will not be added to the `searchableAttributes` once I add the documents.
 
When I watch the settings, this is the value of searchableAttribute: `*`. Since it is a wildcard, I excepted it to have all fields, and not exclude what I have added to facetsDistribution.

If I add settings after my documents, then all facets are in the searchable attributes.

**To Reproduce**
Steps to reproduce the behavior: **order is important**

1. Create an index 
2. Add facetsDistribution: `["genres"]`
3. Add a document 
```json
{
  "id": 1,
   "title": "batman",
  "genres": ["horror"]
}
```
4. Search for horror it will find 0 documents

**Expected behavior**
Since the value of searchable Attribute is a wildcard, I except it to have all fields.  And if it does not, I should be aware of that. 

**Screenshots**
In this example years is a facet.

<img width="674" alt="Screenshot 2020-11-04 at 15 22 38" src="https://user-images.githubusercontent.com/33010418/98123017-a0c14f00-1eb1-11eb-9ef5-01a13f53ae50.png">

<img width="920" alt="Screenshot 2020-11-04 at 15 22 43" src="https://user-images.githubusercontent.com/33010418/98123013-9ef78b80-1eb1-11eb-9ecb-06587432ff8f.png">

MeiliSearch version: v0.15

## TODO
- [ ] When searchable is `*` it should contain all fields
- [ ] tests

#### 1. Settings before Docs

- Create index
- Add settings 
```json
{
  "attributesForFaceting": ["genres"] 
{
```
- Add documents
```json
[
{
  "id": 1,
   "title": "batman",
  "genres": ["horror"]
}
]
```

**Checks:**
- Search for `horror`, it should have one resulting document.
- Get Settings, `searchableAttributes` value should be : `["*"]`

#### 2. No settings

- Create index
- Add documents
```json
[
{
  "id": 1,
   "title": "batman",
  "genres": ["horror"]
}
]
```
**Checks:**
- Search for `horror`, it should have one resulting document.
- Get Settings, `searchableAttributes` value should be : `["*"]`

#### 3. Settings after documents addition

- Create index
- Add documents
```json
[
{
  "id": 1,
   "title": "batman",
  "genres": ["horror"]
}
]
```
- Add settings 
```json
{
  "attributesForFaceting": ["genres"] 
{
```

**Checks:**
- Search for `horror`, it should have one resulting document.
- Get Settings, `searchableAttributes` value should be : `["*"]`

**Comment by MarinPostma** [comment] 2020-12-08 14:39
duplicate of #761

**Closed by MarinPostma** 2020-12-08 14:39 UTC
Labels: type:bug, type:ux
