### ISSUE TITLE
MeiliSearch::TimeoutError

### ISSUE THREAD

**Issue by drougojrom** [meilisearch/meilisearch#3747] opened 2023-04-17 08:33 UTC
**Description**
After I send a search request with the following params (below), I get `MeiliSearch::TimeoutError` from both meilisearch rails and ruby libraries.

```
{
  "offset": 0,
  "limit": 5,
  "attributesToHighlight": [
    "title",
    "description",
    "authors_simple"
  ],
  "filter": "territories=US AND (language=en)",
  "q": "I will always write be"
}
```

This problem repeats for any `q` value which has its length bigger than 21 characters, including spaces.

**Expected behavior**
Search should return a proper result.

**Current behavior**

```
/home/deployer/proxy_search/shared/bundle/ruby/3.1.0/gems/meilisearch-0.22.0/lib/meilisearch/http_request.rb:113:in `rescue in send_request': The request was not processed in the expected time. Net::ReadTimeout with #<TCPSocket:(closed)> (MeiliSearch::TimeoutError)                        
/home/deployer/proxy_search/shared/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Meilisearch version: 1.1.0     
- meilisearch-ruby version: v0.22.0

**Comment by drougojrom** [comment] 2023-05-15 09:44
Sorry for the late reply, here're the settings and some common objects we have.
1. Settings

```
 => 
{"displayedAttributes"=>["*"],                                                     
 "searchableAttributes"=>["title", "authors_simple", "categories", "keywords", "publisher", "narrators_names"],
 "filterableAttributes"=>                                                          
  ["anyplay_book_id", "authors_simple", "cache_status", "language", "licenses_count", "narrators_names", "publisher", "territories", "title"],
 "sortableAttributes"=>["rating_int:desc", "release_date_int:desc"],               
 "rankingRules"=>["words", "typo", "licenses_count:desc", "proximity", "attribute", "sort", "exactness"],
 "stopWords"=>[],                                                                  
 "synonyms"=>{"nyc"=>["new york"]},                                                
 "distinctAttribute"=>nil,                                                         
 "typoTolerance"=>{"enabled"=>true, "minWordSizeForTypos"=>{"oneTypo"=>2, "twoTypos"=>4}, "disableOnWords"=>[], "disableOnAttributes"=>[]},
 "faceting"=>{"maxValuesPerFacet"=>2000},                                          
 "pagination"=>{"maxTotalHits"=>1000}} 
```

2. A common response object

```
{"hits"=>                                                                          
  [{"title"=>"Dead Silence",                                                       
    "authors_simple"=>"S.A. Barnes",                                               
    "categories"=>["Action & Adventure", "Science Fiction", "Horror", "Fiction"],  
    "keywords"=>"[\"Action & Adventure\", \"Science Fiction\", \"Horror\", \"Fiction\"]",
    "narrators"=>["Lauren Ezzo"],                                                  
    "anyplay_book_id"=>546351,                                                     
    "id"=>"546351",                                                                
    "book_id"=>"449216",                                                           
    "cover_url"=>"http://images.findawayworld.com/v1/image/cover/CD433430",        
    "description"=>                                                                
     "<p><b>\"The audiobook read by Lauren Ezzo makes for compulsive, edge-of-seat listening.\" - <i>Buzzfeed</i></b><br><b><br>\"Ezzo's dark tone and emotional connection terrify and comfort listeners in equal measure. Not for the faint of heart.\"<i>-AudioFile Magazine</i></b><br><b><i><br>Titanic </i>meets <i>The Shining</i> in S.A. Barnes’ <i>Dead Silence</i>, a SF horror novel in which a woman and her crew board a decades-lost luxury cruiser and find the wreckage of a nightmare that hasn't yet ended.<br><br></b><b>A GHOST SHIP.</b><br><b>A SALVAGE CREW.</b><br><b>UNSPEAKABLE HORRORS.</b><br><br>Claire Kovalik is days away from being unemployed—made obsolete—when her beacon repair crew picks up a strange distress signal. With nothing to lose and no desire to return to Earth, Claire and her team decide to investigate.<br><br>What they find at the other end of the signal is a shock: the <i>Aurora</i>, a famous luxury space-liner that vanished on its maiden tour of the solar system more than twenty years ago. A salvage claim like this could set Claire and her crew up for life. But a quick trip through the <i>Aurora </i>reveals something isn’t right.<br><br>Whispers in the dark. Flickers of movement. Words scrawled in blood. Claire must fight to hold onto her sanity and find out what really happened on the <i>Aurora</i>, before she and her crew meet the same ghastly fate.<br><br><b>A Macmillan Audio production from Tor Nightfire</b></p>",
    "rating"=>4.33,
    "release_date"=>"2022-02-08",
    "slug"=>"dead-silence-0aa1e265-81d9-4240-ae1a-bae4f1380376",
    "cache_status"=>"cached",
    "territories"=>
     ["AD",
      "AE",
      "AF",
      "AG",
      <...>,
      "ZW"],
    "language"=>["en"],
    "created_at"=>"2023-04-06T16:52:51.502Z",
    "updated_at"=>"2023-04-06T16:52:51.502Z",
    "rating_int"=>43,
    "release_date_int"=>2022,
    "licenses_count"=>141},
   {"title"=>"They Stole Our Hearts",
    "authors_simple"=>"Daniel Kraus",
    "categories"=>["Toys, Dolls, Puppets", "Horror & Ghost Stories", "Bears", "Animals", "Juvenile fiction"],
    "keywords"=>"[\"Toys, Dolls, Puppets\", \"Horror & Ghost Stories\", \"Bears\", \"Animals\", \"Juvenile fiction\"]",
    "narrators"=>["Kirby Heyborne"],
    "anyplay_book_id"=>477578,
    "id"=>"477578",
    "book_id"=>"417119",
    "cover_url"=>"http://images.findawayworld.com/v1/image/cover/CD401918",
    "description"=>
     "<p><b>The heart-pounding sequel to <i>They Threw Us Away</i>, about a group of teddy bears looking for a place to call home…and answers to life’s biggest questions. </b><br><br>The teddies—clever Buddy, brave Sunny, sweet Sugar, and wise Reginald—have managed to find a child. Life with Darling is far better than any they’ve known. But something's not right—the promised bliss of Forever Sleep hasn’t come. And they are kept a secret from Darling’s mother, hidden underneath the child’s bed in the dusty darkness.<br><br>Then the inevitable happens: Mama discovers the teddies. And like all adults they’ve met thus far, she responds with fear and anger. The teddies must watch as one of their friends is destroyed. The remaining trio barely escape, thrust back into a world that does not want them.<br><br>Disillusioned and lost, the teddies embark on a journey back to the factory where they were created. En route, they find a civilization of discarded teddy bears. The comfort of a town of teddies has its allure…but the need for answers weighs heavy. And there’s something definitely <i>off</i> about these new teddies. Will our heroes accept their strange rules? Or must they dig deep for one more grand adventure to finally learn why they were thrown away?</p>",
    "rating"=>3.5,
    "release_date"=>"2022-01-11",
    "slug"=>"they-stole-our-hearts",
    "cache_status"=>"cached",
    "territories"=>
     ["AD",
      <...>,
      "ZW"],
    "language"=>["en"],
    "created_at"=>"2023-04-06T20:11:42.873Z",
    "updated_at"=>"2023-04-06T20:11:42.873Z",
    "rating_int"=>35,
    "release_date_int"=>2022,
    "licenses_count"=>123}
]
```

Just in case, territories is an array that may have up to 255 territories. The full list is:
```
"AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ, BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV, BW, BZ, CA, CC, CD, CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DJ, DK, DM, DO, DZ, EC, EE, EG, EH, ER, ES, ET, FI, FJ, FK, FM, FO, FR, GA, GB, GD, GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, HK, HM, HN, HR, HT, HU, ID, IE, IL, IM, IN, IO, IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI, KM, KN, KP, KR, KW, KY, KZ, LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, MA, MC, MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ, NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, PF, PG, PH, PK, PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RW, SA, SB, SC, SD, SE, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC, TD, TF, TG, TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM, US, UY, UZ, VA, VC, VE, VG, VI, VN, VU, WF, WS, YE, YT, ZA, ZM, ZW" 
```

**Comment by oluademola** [comment] 2023-06-06 11:10
Hello @drougojrom. I tried reproducing the issue using the search query, settings, and the two sample documents you provided. However, I was unsuccessful in reproducing the problem through a direct call to the engine using cURL and Postman. Can you confirm if you were able to reproduce the issue with the same set of data you provided? If not, could you please share the exact documents you used and the steps you took to reproduce the issue using a direct call to the engine? Thanks

**Comment by gillian-meilisearch** [comment] 2023-07-04 07:22
I'll close this issue out as it has been a while since it's been updated. Please feel free to re-open if there's additional information available to continue 🙏🏻

**Closed by gillian-meilisearch** 2023-07-04 07:23 UTC
Labels: needs more info, support
