### ISSUE TITLE
MeiliSearch fails to start using Homebrew services on macOS with M2 chip 

### ISSUE THREAD

**Issue by PierreMouchan** [meilisearch/meilisearch#3629] opened 2023-03-30 15:24 UTC
**Describe the bug**
MeiliSearch fails to start using Homebrew services on macOS with M2 chip (Apple Silicon). 
However, it starts successfully when running manually.

**To Reproduce**
1. Install MeiliSearch using Homebrew
2. Try starting MeiliSearch via Homebrew services: `brew services start meilisearch -d`
3. See error message:
```text
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/pierremouchan/Library/LaunchAgents/homebrew.mxcl.meilisearch.plist` exited with 5.
/opt/homebrew/Library/Homebrew/extend/kernel.rb:243:in `safe_system'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:249:in `launchctl_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:266:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:115:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:90:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:90:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:112:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Expected behavior**
MeiliSearch should start without errors when using Homebrew services.

**Screenshots**
N/A

**Meilisearch version:** 
v1.0.2

**Additional context**
- Device: Apple Mac
- OS: macOS (Apple Silicon)
- Architecture: arm64

Please let me know if you need any additional information about my system.

**Comment by oluademola** [comment] 2023-04-05 09:00
Hello @PierreMouchan. Is this a fresh installation, or you once had meilisearch running with brew before, and it failed after installing a new version? If it's not a fresh installation, you might be encountering this error because you failed to remove the existing meilisearch database (data.ms) in `/opt/homebrew/var/meilisearch/data.ms`. Either way, I would encourage you to check the meilisearch log file in `/opt/homebrew/var/log` to give us more context about your issue.

**Comment by PierreMouchan** [comment] 2023-04-05 09:21
Hey @oluademola , it failed after installing a new version. 

The ```/opt/homebrew/var/log/meilisearch.log``` file is warning me that: (but has not been updated for 3 days)
```Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.```

I followed all the instructions, uninstalling and installing with brew again and it not worked either. 


Here is the results with ```brew services start meilisearch -d -v```


```
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading meilisearch from API
==> Generated service file for meilisearch:
   <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
   <plist version="1.0">
   <dict>
   	<key>Label</key>
   	<string>homebrew.mxcl.meilisearch</string>
   	<key>LimitLoadToSessionType</key>
   	<array>
   		<string>Aqua</string>
   		<string>Background</string>
   		<string>LoginWindow</string>
   		<string>StandardIO</string>
   		<string>System</string>
   	</array>
   	<key>ProgramArguments</key>
   	<array>
   		<string>/opt/homebrew/opt/meilisearch/bin/meilisearch</string>
   		<string>--db-path</string>
   		<string>/opt/homebrew/var/meilisearch/data.ms</string>
   	</array>
   	<key>RunAtLoad</key>
   	<true/>
   	<key>StandardErrorPath</key>
   	<string>/opt/homebrew/var/log/meilisearch.log</string>
   	<key>StandardOutPath</key>
   	<string>/opt/homebrew/var/log/meilisearch.log</string>
   	<key>WorkingDirectory</key>
   	<string>/opt/homebrew/var</string>
   </dict>
   </plist>


/bin/launchctl enable gui/501/homebrew.mxcl.meilisearch
/bin/launchctl bootstrap gui/501 /Users/pierremouchan/Library/LaunchAgents/homebrew.mxcl.meilisearch.plist
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/pierremouchan/Library/LaunchAgents/homebrew.mxcl.meilisearch.plist` exited with 5.
/opt/homebrew/Library/Homebrew/extend/kernel.rb:243:in `safe_system'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:249:in `launchctl_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:266:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:115:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:90:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:90:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:112:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by oluademola** [comment] 2023-04-05 09:33
Hello @PierreMouchan,

Thank you for the additional information. Actually, you don't have to reinstall brew, so here is the problem: 
```
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
```
It's a database incompatibility issue. If you don't care about the data in your meilisearch instance, you can just delete the data.ms (`/opt/homebrew/var/meilisearch/data.ms`) as I have previously mentioned to resolve the issue, or you could create a dump as a backup delete the `data.ms`, and launch your instance with the dump to resolve the issue.

Hope this helps. Thanks.

**Comment by PierreMouchan** [comment] 2023-04-05 09:55
I following the instructions, it did not worked and I encounter the exact same bug as above.

**Comment by oluademola** [comment] 2023-04-05 10:41
I can understand your concerns. However, if you're still encountering this error: `Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2)`, it can only mean one thing, and that is the `data.ms `folder is yet to be deleted. Can you try to check your root and delete any `data.ms` you find as well this directory: `/opt/homebrew/var/meilisearch` to delete any `data.ms` you find?

**Comment by PierreMouchan** [comment] 2023-04-05 10:54
How the meilisearch.log is being updated?
I've ran it manually and with the debug and verbose command, the file hasn't been updated since April 2. 

I cannot confirm I still encounter the same error. And yes, I can confirm the data.ms has been deleted.

**Comment by oluademola** [comment] 2023-04-05 11:11
You are most likely seeing the date when the service last ran correctly. I am not sure if the dates are attached to each of the error messages. Can you please show me the logs?

**Comment by PierreMouchan** [comment] 2023-04-05 11:14
![CleanShot 2023-04-05 at 13 12 46](https://user-images.githubusercontent.com/38973205/230064404-bd8ff5cc-6f41-4d3f-a419-5a0131598ca9.png)

```
[2023-03-05T11:50:06Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 1685, number_of_documents: 947 }
[2023-03-05T11:50:06Z INFO  index_scheduler] A batch of tasks was successfully completed.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
Error: Your database version (0.30.5) is incompatible with your current engine version (1.0.2).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/advanced/updating.html.
```

**Comment by oluademola** [comment] 2023-04-05 11:51
Thanks for the info. I might be wrong, but I think the errors displayed here represent the number of times you have tried to run the service but failed. I'd like to know where is your current db path and did you, by any chance, change the db path for meilisearch? Here is what you can do as a workaround. Run:  
`opt/homebrew/opt/meilisearch/bin/meilisearch --db-path <specify a new file path for your meilisearch db>`

**Comment by PierreMouchan** [comment] 2023-04-05 12:04
doing that command launch successfully meilisearch with the new db, every files and configuration are newly created into that folder. Works perfectly when launched manually.

With homebrew, i'm still encountering the same problem.
I tried to manually change the db path inside the plist of meilisearch ```LaunchAgents/homebrew.mxcl.meilisearch.plist``` but that one is overwritten every time I start ```brew services start meilisearch -v -d```

**Comment by oluademola** [comment] 2023-04-05 12:41
It is very strange you're encountering this after removing the data.ms folder. However, editing db path in the service file should be doable. I understand .plist gets overwritten but have you tried editing the db path in the service file from this directory `/opt/homebrew/Cellar/meilisearch` ? Let me know if that works for you.

**Comment by oluademola** [comment] 2023-04-06 07:27
Hello @PierreMouchan. Thanks again for the details. This is very strange. I am not sure what could be wrong here, but I'd investigate this with the team and get back to you with more information.

**Comment by PierreMouchan** [comment] 2023-04-06 07:35
> Hello @PierreMouchan. Thanks again for the details. This is very strange. I am not sure what could be wrong here, but I'd investigate this with the team and get back to you with more information.

Hey, thanks for your time and your support.

**Comment by oluademola** [comment] 2023-04-26 23:51
Hi @PierreMouchan. Sorry for the delay. Unfortunately, I couldn't reproduce this issue. Could you please let me know if you encounter this issue using v1.1? In the meantime, you could consider using our [cloud solution](https://cloud.meilisearch.com) it might be a good option for you.

**Comment by PierreMouchan** [comment] 2023-04-27 08:22
Since the new update, everything is fine! thanks again for your support ;) @oluademola

**Comment by curquiza** [comment] 2023-05-10 13:23
I close this issue then. Feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-05-10 13:23 UTC
Labels: support
