### ISSUE TITLE
Can't create index (OS error 22)

### ISSUE THREAD

**Issue by amab8901** [meilisearch/meilisearch#3017] opened 2022-11-01 09:17 UTC
**Describe the bug**
Can't create index

**To Reproduce**
1. `cargo run` in meilisearch root folder
2. 
```
curl   
    -X POST 'http://localhost:7700/indexes'   
    -H 'Content-Type: application/json'   
    --data-binary '{
        "uid": "movies",
        "primaryKey": "id"
    }'
```
Response:
```
{
	"taskUid": 0,
	"indexUid": "movies",
	"status": "enqueued",
	"type": "indexCreation",
	"enqueuedAt": "2022-11-01T08:44:00.269189619Z"
}
```
3. 
```
curl \
  -X GET 'http://localhost:7700/tasks/0'
```
Response:
```
{
	"uid": 0,
	"indexUid": "movies",
	"status": "failed",
	"type": "indexCreation",
	"details": {
		"primaryKey": "id"
	},
	"error": {
		"message": "Invalid argument (os error 22)",
		"code": "internal",
		"type": "internal",
		"link": "https://docs.meilisearch.com/errors#internal"
	},
	"duration": "PT0.000368400S",
	"enqueuedAt": "2022-11-01T08:44:00.269189619Z",
	"startedAt": "2022-11-01T08:44:00.274817501Z",
	"finishedAt": "2022-11-01T08:44:00.275185901Z"
}
```
4. 
5. 

**Expected behavior**
I expected the `"status"` field to be `"succeeded"` rather than `"failed"` in the response from `curl -X GET 'http://localhost:7700/tasks/0' `

**Screenshots**
Attempting to post index:
![image](https://user-images.githubusercontent.com/83634595/199200278-9d0e9a3e-3092-44d8-aab8-5f42303dbe78.png)

Attempting to get indexes:
![image](https://user-images.githubusercontent.com/83634595/199200385-2f940f2f-d573-449a-b8f6-da8d261e90a6.png)

Checking task status:
![image](https://user-images.githubusercontent.com/83634595/199200470-3431dbc2-1633-457f-836b-bfe34c05870a.png)

**Meilisearch version:** [e.g. v0.20.0]
0.28.1

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]
OS: Archlinux
Architecture: x86_64

---

EDITED by @curquiza & @dureuill 

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/) https://github.com/meilisearch/milli/pull/699)
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by amab8901** [comment] 2022-11-01 12:23
It feels like this error message `"Invalid argument (os error 22)"` is key to solving this issue. So I searched for that error message in this repository and it didn't show any results. I wonder where in the code this error message originates from :thinking:

**Comment by amab8901** [comment] 2022-11-01 12:50
When I write `ulimit -S`, I get the output `unlimited`, so setting it to 10000 seems like a reduction and thus doesn't seem to serve the purpose of increasing the ulimit. 

When I write `ulimit S` (or `ulimit -Sn`, which gives same output), I get the output `1048576`, which is still far greater than 10000. So if 1048576 is too low, I'm not sure why I should reduce it to 10 000?

the 38 operations were just multiple attempts to do the same operation as described in the post. I read in the docs that it displays ma 20 items at a time, so I was curious on what would happen if you exceed 20, thus the large number of identical tasks. 

I initially tried to follow the instructions in [here](https://docs.meilisearch.com/learn/getting_started/quick_start.html#add-documents) to add documents. I did exactly like it said and then in attempt to narrow down the scope of the problem, I looked in the APi documentation and used the info therein to send POST request directly to index, and thus it seems like the problem starts with the index rather than starting with the document.

**Comment by Avey777** [comment] 2022-11-01 14:26
![image](https://user-images.githubusercontent.com/35259040/199256980-9a23428e-a2ba-40bc-be74-e1f0c58fd7b8.png)

**Comment by amab8901** [comment] 2022-11-01 15:06
> ![image](https://user-images.githubusercontent.com/35259040/199256980-9a23428e-a2ba-40bc-be74-e1f0c58fd7b8.png)
> 
> Meilisearch version: [e.g. v0.20.0] 0.30.o rc1
> 
> Additional context Additional information that may be relevant to the issue. [e.g. architecture, device, OS, browser] OS: Windows10 Architecture: x86_64

Are you trying to say that you came across a similar problem, or is this a hint on how to solve it? or is it something else?

**Comment by curquiza** [comment] 2022-11-02 13:32
Hello everyone, thanks for the report, the core team will work on it asap

For core team: we noticed it's not related to the new index scheduler!

**Comment by irevoire** [comment] 2022-11-07 13:22
The problem is flaky on macOS and ubuntu but does appear from time to time.
And I can reproduce it 100% of the time on archlinux.
It seems to be linked to a bump of milli from the `v0.12.1` to the `v0.12.2`, but it needs more investigation.

**Comment by amab8901** [comment] 2022-11-07 14:03
> 

Are there any junior-level contributions I can make to help solve the issue? Or is this something advanced that only people with lots of experience can solve? I've been in Rust for a few months

**Comment by amab8901** [comment] 2022-11-07 14:25
> The problem is flaky on macOS and ubuntu but does appear from time to time. And I can reproduce it 100% of the time on archlinux. It seems to be linked to a bump of milli from the `v0.12.1` to the `v0.12.2`, but it needs more investigation.

What exactly do we need to do to solve the problem? Can you break it down into sub-tasks or specific questions that need to be addressed?

**Comment by amab8901** [comment] 2022-11-08 17:38
> > What exactly is a "bump" of milli though? I'm not familiar with the "bump" concept.
> 
> It means upgrading milli version in this repo to include the bug fix

Is there an article or something where I can read more about it? I'm trying to understand like the definition of "bump" and how to use the term more generally

**Comment by curquiza** [comment] 2022-11-08 22:39
A "dependency bump" means "upgrade a dependency", is a common term used, see for example [this random tutorial](https://tuleap.net/doc/en/developer-guide/front-end/bump-dependencies.html) I found when typing "bump dependency" on Google

But no worry with this @amab8901, @irevoire was writing this for traceability and for helping his own team internally to investigate the bug.

**Comment by dureuill** [comment] 2022-11-14 12:34
I reproduced the issue on an up-to-date KDE Archlinux and think I have a fix:

- it looks like it is caused by the Rust `lmdb-sys` package using the system's version of lmdb if it is installed
- On KDE archlinux lmdb (v. 0.9.29-1 for an up-to-date system) is very likely to be installed due to baloo which depends on it and is a KDE program
- The system version of lmdb is likely to be incompatible with the version used by meilisearch
- Modifying `lmdb-sys` to always use the vendored version appears to fix the issue. Adding a `vendored` feature like is done in https://lib.rs/crates/libgit2-sys is a way of adding this behavior back-compatibly
- The line of the issue: https://github.com/meilisearch/lmdb-rs/blob/main/lmdb-sys/build.rs#L62
- I will open a PR shortly to add such a `vendored` feature to `lmdb-rs` and make sure we make use of it in `meilisearch`

**Comment by dureuill** [comment] 2022-11-14 13:18
[PR is here](https://github.com/meilisearch/lmdb-rs/pull/11)

**Comment by curquiza** [comment] 2022-11-17 16:50
Closed by https://github.com/meilisearch/meilisearch/pull/3084

**Closed by curquiza** 2022-11-17 16:50 UTC
Labels: bug, milli

**Comment by amab8901** [comment] 2022-11-18 05:39
hey why is this closed when there are 2 tasks left?

**Comment by curquiza** [comment] 2022-11-18 09:24
Tasks have been done. The issue has now been updated, thanks
