### ISSUE TITLE
Wrong number of totalHits and totalPages on Search route

### ISSUE THREAD

**Issue by pespantelis** [meilisearch/meilisearch#4130] opened 2023-10-17 00:24 UTC
**Describe the bug**
The `POST: /indexes/{index_uid}/search` route returns wrong number of `totalHits` and `totalPages`.

**To Reproduce**
- Search in an index with a specific page:
```json
{
  "page": 5
}
```
- `v1.4.0`: the values are correct:
```json
{
  "hits": [...],
  "query": "",
  "processingTimeMs": 9,
  "hitsPerPage": 20,
  "page": 5,
  "totalPages": 25,
  "totalHits": 500
}
```
- `v1.4.1`: the values are wrong:
```json
{
  "hits": [...],
  "query": "",
  "processingTimeMs": 2,
  "hitsPerPage": 20,
  "page": 5,
  "totalPages": 21,
  "totalHits": 420
}
```

**Expected behavior**
The route should return the correct number of `totalHits` and `totalPages`.

**Meilisearch version:**
v1.4.1

**Additional context**
I think that is related with #4108.

**Comment by CaroFG** [comment] 2023-10-18 07:55
Hi! 

 Could you give more info about your settings? I can't reproduce your issue with default settings. Why do you think it's related to #4108, are you using the distinct attribute?

**Comment by pespantelis** [comment] 2023-10-18 10:26
Hello @CaroFG!

You are right, I forgot to mention that I'm using `"distinctAttribute": "id"`. All other settings are configured with their default values.

In my case, I have an index with 500 documents. The `totalHits` and `totalPages` change based on the page value:
```
page: 1 -> totalHits: 500, totalPages: 25
page: 2 -> totalHits: 480, totalPages: 24
page: 3 -> totalHits: 460, totalPages: 23
...
```

**Comment by CaroFG** [comment] 2023-10-18 12:27
Indeed, there's an issue with pagination when the distinct attribute is set. @meilisearch/engine-team 

When `product_id` is set as distinct attribute and I use pagination, everything seems to be working fine when we only request page 1, but the problem becomes apparent when requesting other pages:

- `totalHits` returns the number of hits of the current page + remaining pages 
- `totalPages` returns the number of the current page + remaining pages . So if it's the last page, it would return `1`.

I have tested it with this small dataset of 14 products:

```
[
    {
      "id": 1,
      "description": "Leather Jacket",
      "brand": "Lee Jeans",
      "product_id": "123456",
      "color": "Brown"
    },
    {
      "id": 2,
      "description": "Leather Jacket",
      "brand": "Lee Jeans",
      "product_id": "123456",
      "color": "Black"
    },
    {
      "id": 3,
      "description": "Leather Jacket",
      "brand": "Lee Jeans",
      "product_id": "123456",
      "color": "Blue"
    },
    {
      "id": 4,
      "description": "T-Shirt",
      "brand": "Nike",
      "product_id": "789012",
      "color": "Red"
    },
    {
      "id": 5,
      "description": "T-Shirt",
      "brand": "Nike",
      "product_id": "789012",
      "color": "Blue"
    },
    {
      "id": 6,
      "description": "Running Shoes",
      "brand": "Adidas",
      "product_id": "456789",
      "color": "Black"
    },
    {
      "id": 7,
      "description": "Running Shoes",
      "brand": "Adidas",
      "product_id": "456789",
      "color": "White"
    },
    {
      "id": 8,
      "description": "Hoodie",
      "brand": "Puma",
      "product_id": "987654",
      "color": "Gray"
    },
    {
      "id": 9,
      "description": "Sweater",
      "brand": "Gap",
      "product_id": "234567",
      "color": "Green"
    },
    {
      "id": 10,
      "description": "Sweater",
      "brand": "Gap",
      "product_id": "234567",
      "color": "Red"
    },
    {
      "id": 11,
      "description": "Sweater",
      "brand": "Gap",
      "product_id": "234567",
      "color": "Blue"
    },
    {
      "id": 12,
      "description": "Jeans",
      "brand": "Levi's",
      "product_id": "345678",
      "color": "Indigo"
    },
    {
      "id": 13,
      "description": "Jeans",
      "brand": "Levi's",
      "product_id": "345678",
      "color": "Black"
    },
    {
      "id": 14,
      "description": "Jeans",
      "brand": "Levi's",
      "product_id": "345678",
      "color": "Stone Wash"
    }
  ]
  ```

**Comment by curquiza** [comment] 2023-10-18 12:57
I checked in v1.4.0, and this bug has indeed been introduced into v1.4.1, probably by the PR you linked (https://github.com/meilisearch/meilisearch/pull/4108) 😞 

Engine team cannot afford to work on this during this week, but if someone is available in the meantime to fix it, PR are welcome, it will save us some time
⚠️ tests should be added to avoid this kind of issues in the future

Pinging @vivek-26: since you created the PR, maybe you have more inputs about where the bug comes from?

**Comment by curquiza** [comment] 2023-10-19 08:38
Thank you very much @vivek-26 ❤️

I created a branch `release-v1.4.2` -> can you do your changes on this branch on make your PR point to it? The purpose is to merge the bug fix into `release-v1.4.2`

**Comment by curquiza** [comment] 2023-10-19 08:38
We will release v1.4.2 once the bug fix is merged

**Comment by curquiza** [comment] 2023-10-19 11:52
No worries, thank you very much for fixing this! This is really appreciated

**Closed** 2023-10-19 15:18 UTC
Labels: bug
