### ISSUE TITLE
run failed with win 11

### ISSUE THREAD

**Issue by vae1970** [meilisearch/meilisearch#4428] opened 2024-02-20 15:06 UTC
**Describe the bug**
run failed with win 11

**To Reproduce**
1. rum meilisearch-windows-amd64.exe in cmd

**Expected behavior**
expect success run

**Screenshots**
![image](https://github.com/meilisearch/meilisearch/assets/8981146/64faeff1-7038-441a-a708-177276ac226c)

**Meilisearch version:**
[e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]
win 11
![image](https://github.com/meilisearch/meilisearch/assets/8981146/df684d16-4c16-43e8-8ea1-21a45869eea5)

**Comment by ManyTheFish** [comment] 2024-02-21 10:02
Hello @vae1970,
Which Meilisearch version are you using?

**Comment by vae1970** [comment] 2024-02-22 03:10
the latest: meilisearch 1.6.2
![image](https://github.com/meilisearch/meilisearch/assets/8981146/e8c8e5c0-09ca-4212-918b-bc00caf357dd)

**Comment by ManyTheFish** [comment] 2024-02-22 10:02
Hello @vae1970, 
I see the error message is an `error os 1`; this error appears when Meilisearch doesn't have the right to write into the database path (default: ./data.ms). Can you ensure that meilisearch runs with the proper access to the database directory?

**Comment by vae1970** [comment] 2024-02-27 05:23
yes, when i run meilisearch, the directory data.ms is created automatically

**Comment by ManyTheFish** [comment] 2024-02-28 09:46
Hello @vae1970,
do you see the data.ms folder created in your directory?

**Comment by vae1970** [comment] 2024-02-28 09:47
yes, it created automatically

**Comment by curquiza** [comment] 2024-03-06 16:07
Hello people watching this issue. We don't have any easy way to reproduce the issue... if someone working with Windows can help us on this one.

**Comment by curquiza** [comment] 2024-09-17 10:13
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-09-17 10:13 UTC
Labels: needs more info, windows, help wanted
