### ISSUE TITLE
Search not working for comma separated primary key

### ISSUE THREAD

**Issue by surenderaphro** [meilisearch/meilisearch#4227] opened 2023-11-23 16:31 UTC
Hi,
I need to search comma-separated primary keys and other values. I have used separatorTokens but am still unable to achieve it. Please help us to meet this requirement.

**Comment by surenderaphro** [comment] 2023-11-24 13:48
just to elaborate the above issue, the separatorTokens "," is being ignored. We have checked "domain/indexes/foundations/settings/separator-tokens" end point and comma is shown correctly in the response. 

We are trying to search for example: "3904, 23469" and "3904, 23469, 1936" and also "Sweden, Canada" and "Sweden, Canada, India"

separatorTokens "," is being ignored in regular search as well as for multi-search endpoint.

any help?

**Comment by ManyTheFish** [comment] 2023-11-27 09:27
Hello @surenderaphro,
The issue behind what you are trying is that you will deactivate the comma everywhere in the index, so if you have several searchable attributes, they will all ignore the comma; in your example, you don't have only a comma but a space too, if you want to achieve what you are trying to do, I suggest to add `, ` (comma + space) in the [dictionary setting](https://www.meilisearch.com/docs/reference/api/settings#dictionary), forcing Meilisearch to join the two characters together, then, I suggest to add `, ` (comma + space) in the non-separator-tokens setting as well to ensure that they are not considered separators.

Let me know if it worked for you,
See you!

**Comment by surenderaphro** [comment] 2023-12-06 10:07
Hi @ManyTheFish 
I am sharing samples below please check.

Settings Config;-

{
    "displayedAttributes": [
        "foundation_id",
        "lno",
        "sort",
        "name",
        "language",
        "status",
        "phrase",
        "remarks",
        "type",
        "frontend_count",
        "show_to_free_users"
    ],
    "searchableAttributes": [
        "*"
    ],
    "filterableAttributes": [
        "city_ids",
        "city_list",
        "country_ids",
        "country_list",
        "gender_ids",
        "gender_list",
        "language",
        "nation_list",
        "purpose",
        "purpose_ids",
        "purpose_list",
        "status",
        "subject",
        "subject_list"
    ],
    "sortableAttributes": [
        "frontend_count",
        "show_to_free_users"
    ],
    "rankingRules": [
        "sort",
        "words",
        "exactness",
        "proximity",
        "attribute",
        "show_to_free_users:desc",
        "frontend_count:desc"
    ],
    "stopWords": [
        "NoGG",
        "the"
    ],
    "nonSeparatorTokens": [
        " ",
        ","
    ],
    "separatorTokens": [],
    "dictionary": [
        " ",
        ","
    ],
    "synonyms": {},
    "distinctAttribute": null,
    "typoTolerance": {
        "enabled": true,
        "minWordSizeForTypos": {
            "oneTypo": 5,
            "twoTypos": 9
        },
        "disableOnWords": [],
        "disableOnAttributes": []
    },
    "faceting": {
        "maxValuesPerFacet": 100,
        "sortFacetValuesBy": {
            "*": "alpha"
        }
    },
    "pagination": {
        "maxTotalHits": 26000
    }
}


Document Sample:-



{
            "foundation_id": 3752,
            "lno": "4121",
            "sort": "SOS",
            "name": "SOS Bidrag",
            "language": "2",
            "status": "NoAppl",
            "phrase": "Ändamål Stöd Stipendier AB delar ut bidrag till alla tänkbara ändamål Stipendiet kan sökas endast genom att registrera dig på http www globalgrant com swe Har du inte tillgång till Internet hemma eller på skolan så finns det på närmaste bibliotek Du kan inte ansöka om stipendium retroaktivt Ämne Inga restriktioner Öppet för Alla enskilda personer i hela världen Således kan inga föreningar eller juridiska personer söka Det finns inga krav på viss ålder bostadsort eller nationalitet Utdelning Högst 10 000 kr per stipendium tre gånger årligen Endast dom som får stipendium meddelas övriga kan se vilka som fick stipendium på http www globalgrant com cgi swe new gg cgi sid language swe page winners html Ansökan Senast 30 september 31 januari respektive 31 maj årligen Ansökan endast på vår hemsida Skicka inte ansökan kompletteringar betyg intyg förklaringar etc per post care cult ecolog edu entrep fost grad high journal music peace perfart phd philan photo prim proj tec ugrad welfare visualart undef Sweden Undef unisex SOS Stipendier Stöd Stipendier AB SOS Ektorpsvägen 4A 13147 NACKA ",
            "remarks": "2020-08-21 edited /LH\n2016-06-19 edited /LH\n2015-11-27 edited/LH\n2015-07-20 edited/LH\n2011-12-28 edited/LH\n2009-08-25 edited /LH\n2008-05-26 formated/KA\n2007-01-23 Formatted by LH",
            "type": "Aktiebolag",
            "frontend_count": 5106,
            "show_to_free_users": 1
        },
        {
            "foundation_id": 13471,
            "lno": "q15625",
            "sort": "Dreijer, P H",
            "name": "Per och Helen Dreijers stiftelse för allmännyttiga ändamål",
            "language": "2",
            "status": "Active",
            "phrase": "Stiftelsen skall ha till ändamål att genom utdelande av understöd eller bidrag främja vård och uppfostran av barn lämna understöd för beredande av undervisning eller utbildning utöva hjälpverksamhet bland behövande främja vetenskaplig forskning främja religiösa välgörande sociala konstnärliga idrottsliga eller andra därmed jämförliga kulturella eller eljest allmännyttiga ändamål Tillgångar 7 582 237 cult edu fost phd philan proj welfare teo undef Sweden Undef Per och Helen Dreijers stiftelse för allmännyttiga ändamål Dreijer P H Box 6050 181 06 LIDINGÖ Annan stiftelse",
            "remarks": "2023-01-08 Updaterad AS\n2018-04-12 Updated adr/AS\n2017-03-08 Updated AS\n2015-08-07 Updated LS+web/AS\n2011-12-02 Updated from email/AS\n2011-08-10 Talked to Bengt Krohn/auditor for them.He cannot give any public info because they are exempted from it, but says there is activity in the foundation, and that he suggest that we keep it in active status/AS\n2011-08-08 Expired by LH until we learn anything new\n38193\n2008-01-04 Classified/YC\n2007-12-04 updated with a woman, she will not give the name and phone/KA\n2007-04-16 updated/KA",
            "type": "Annan stiftelse",
            "frontend_count": 1697,
            "show_to_free_users": 1
        },
        {
            "foundation_id": 3059,
            "lno": "030",
            "sort": "FVO",
            "name": "Föreningen FVO",
            "language": "2",
            "status": "Active",
            "phrase": "FVO förvaltar ca 150 st olika fonder Föreningen ger tillfällig ekonomisk hjälp och råd till behövande huvudsakligen till äldre handikappade och sjuka vid akuta behov Genom personligt besök efter tidsbeställning Bidragsbehovet skall kunna dokumenteras av socialt verksam person Ytterligare information kan erhållas på ovanstående telefonnummer eller hemsida Ingen utdelning till personer som uppbär socialbidrag care fost welfare undef Storstockholm Sweden Föreningen FVO FVO Köpmangatan 15 4 tr 111 31 STOCKHOLM ",
            "remarks": "37267    (q7103,q7104)\n2021-09-20 Updated AS\n2019-01-24 Updated AS\n2017-09-05 Updated email from Lars/AS\n2017-08-29 Updated from email Lars/AS\n2017-07-03 Updated from email/AS\n2017-03-13 Updated AS\n2015-08-07 Updated LS+web/AS\n2013-07-21 Updated web/AS\n2010-06-17 Updated web/AS\n2008-06-03 Updated with Annelie Håkansson/YC\n2007-09-19 Text om inkomst/YC\n2007-08-20 Har skickat brev om blankett och fått svar, fonden måste kontaktas per telefon/YC",
            "type": "Annan stiftelse",
            "frontend_count": 1038,
            "show_to_free_users": 1
        },
        {
            "foundation_id": 12061,
            "lno": "q2439",
            "sort": "Söderberg, G",
            "name": "Gustaf Söderbergs Stiftelse",
            "language": "2",
            "status": "Double",
            "phrase": "Avkastningen skall utbetalas såsom understöd till främjande av barns eller ungdoms forstran som ungdom räknas man till och med 26 år eller utbildning eller till vård av behövande ålderstigna sjuka eller lytta svenskar som oförskyllt råkat i nödläge Ansökan Personligt brev Mars juni och november Tillgångar 152 769 095 care edu fost undef Sweden Gustaf Söderbergs Stiftelse Handelsbanken Söderberg G Stiftelsetjänst 106 70 STOCKHOLM Stockholms län Annan stiftelse",
            "remarks": "2023-01-17 Updated AS\n2020-07-21 Updated AS\n2018-04-25 Updated AS\n2017-03-08 Updated AS\n2014-06-25 Updated LS/AS\n2012-09-12 Updated via tel/AS\n2012-06-19 Updated LS/AS\n2010-03-30 Updated behörighet från kund/AS\n2009-10-07 Updated w/tel. Karin P./AS\n2009-09-06 Updated LS/AS\n2007-06-26 updated with Karin/KA\n2007-01-29 Formatted by LH\n37612\n2006-08-17 Printed Stiftelsebrev/LR",
            "type": "Annan stiftelse",
            "frontend_count": 1035,
            "show_to_free_users": 0
        },
        {
            "foundation_id": 12010,
            "lno": "q2367",
            "sort": "Frykberg, R",
            "name": "Ragnhild Frykbergs Stiftelse",
            "language": "2",
            "status": "NoAppl",
            "phrase": "Du kan ansöka om bidrag till studier eller sjukvård Maximalt bidragsbelopp 5 000 kronor i undantagsfall 10 000 kronor vid mycket svåra sjukdoms eller handikappfall Ansökan Ingen särskild ansökningsblankett behövs i stället skriver du kort om dig själv Gäller det sjukvård berättar du om vilken sjukdom eller vilket handikapp det gäller och vad pengarna ska användas till exempelvis läkarkostnader medicin hjälpmedel rekreationsresa etc Bifoga personbevis slutskattsedel och läkarintyg som styrker vårdbehovet Gäller det studier vill vi veta vad du ska läsa var någonstans och vad du vill använda pengarna till För utlandsstudier krävs också en enkel kostnadskalkyl där det framgår hur finansieringen ska lösas Bifoga personbevis slutskattsedel och intagningsintyg från skolan eller universitetet där du läser eller ska läsa Ansökan kan bara tas emot under oktober månad Utdelning sker vid årsskiftet eller under januari påföljande år Ansökningar som kommer in under andra tider på året makuleras olästa RFS har inget kansli med anställd personal Tillgängligheten på telefon är begränsad och e posten läses inte varje dag under hela året För mer information se fondens hemsida care grad high ugrad undef Sweden unisex Ragnhild Frykbergs Stiftelse c o Frykberg Frykberg R Pl 2496 Norrby 763 94 Hallstavik Stockholms län Annan stiftelse",
            "remarks": "37609\n2019-03-26 Updated AS\n2018-01-25 Updated AS\n2017-03-08 Updated AS\n2015-06-27 Updated LS+web/AS\n2013-08-06 Updated LS+web/AS\n2012-05-14 Updated web+LS/AS\n2010-06-17 Updated web/AS\n2009-09-23 Updated web/AS\n2007-02-20 Classification ok/YC\n2007-01-23 Formatted by Lars",
            "type": "Annan stiftelse",
            "frontend_count": 980,
            "show_to_free_users": 0
        }
		
		
		Search Request payload JSON:-
		
		{
            "q":  "Care Cancer",
            "sort": ["frontend_count:desc"],
            "page": 1,
            "limit": 50,
            "hitsPerPage": 50
        }

**Comment by ManyTheFish** [comment] 2023-12-12 17:07
Hello @surenderaphro,
After investigating your dataset, I don't see how your example showcases the issue. I may have misunderstood your issue. Could you explain what you expect with your example?

Moreover, I see that no searchable attributes are set in your settings; Meilisearch will only search in these fields, and in none are set, any query containing a `q` parameter will return an empty result.
I suggest using the following settings in your case:
```json
{
  "displayedAttributes": [
    "foundation_id",
    "lno",
    "sort",
    "name",
    "language",
    "status",
    "phrase",
    "remarks",
    "type",
    "frontend_count",
    "show_to_free_users"
  ],
  "searchableAttributes": [
    "sort",
    "name",
    "language",
    "status",
    "phrase",
    "remarks",
    "type"
  ],
  "filterableAttributes": [
    "city_ids",
    "city_list",
    "country_ids",
    "country_list",
    "gender_ids",
    "gender_list",
    "language",
    "nation_list",
    "purpose",
    "purpose_ids",
    "purpose_list",
    "status",
    "subject",
    "subject_list"
  ],
  "sortableAttributes": [
    "frontend_count",
    "show_to_free_users"
  ],
  "rankingRules": [
    "sort",
    "words",
    "exactness",
    "proximity",
    "attribute",
    "show_to_free_users:desc",
    "frontend_count:desc"
  ],
  "stopWords": [
    "NoGG",
    "the"
  ],
  "nonSeparatorTokens": [
    ", "
  ],
  "separatorTokens": [],
  "dictionary": [
    ", "
  ],
  "synonyms": {
    
  },
  "distinctAttribute": null,
  "typoTolerance": {
    "enabled": true,
    "minWordSizeForTypos": {
      "oneTypo": 5,
      "twoTypos": 9
    },
    "disableOnWords": [
      
    ],
    "disableOnAttributes": [
      
    ]
  },
  "faceting": {
    "maxValuesPerFacet": 100,
    "sortFacetValuesBy": {
      "": "alpha"
    }
  },
  "pagination": {
    "maxTotalHits": 26000
  }
}
```

What do you think?

**Comment by surenderaphro** [comment] 2023-12-14 07:18
We are trying to search for example: "3904, 23469" and "3904, 23469, 1936" and also "Sweden, Canada" and "Sweden, Canada, India"
But we are unable to get the 2nd parameter like in  "Sweden, Canada" getting  "Sweden, Canada" match and "Sweden" match not getting "Canada" matches.
Could you give me a solution for it?

**Comment by curquiza** [comment] 2023-12-27 08:55
Hello @surenderaphro, if you are still around, is it possible to have detailed steps to reproduce the bug? 😊

**Comment by curquiza** [comment] 2024-02-12 13:20
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-02-12 13:20 UTC
Labels: needs more info
