### ISSUE TITLE
Bug with distinct attributes and nbHits

### ISSUE THREAD

**Issue by bsurai** [meilisearch/meilisearch#2532] opened 2022-06-17 11:43 UTC
This is my GitHub [repository](https://github.com/bsurai/meilisearch-distinct-documents) with:
 - dataset
 - meilisearch settings
 - test case
 - screenshots

I hope it's pretty well documented.

**Comment by curquiza** [comment] 2022-06-20 08:08
Hello @bsurai thanks a lot for your repo explaining the issue!
 We'll try to take care of this as soon as possible!

**Comment by Kerollmops** [comment] 2022-06-22 09:52
Hey @bsurai,

Thank you for the time you took to set up a reproducible environment, I was able to reproduce the behavior on my side. I have done [an explanation of what is happening](https://github.com/meilisearch/milli/pull/563) and the reason why it is tricky to fix without impacting the performance. The PR I linked improved a little bit the situation by prioritizing a part of the code that was responsible for the final `nbHits`/`estimatedNbHits` count, you will see 131 instead of 171 when you fetch the first 20 results.

I hope it helps,
Have a good day!

**Comment by bsurai** [comment] 2022-06-23 09:05
@Kerollmops Thank you for efforts.
I think, we will try some type of workarounds:

Creation 2 types of indexes. One for detailed items and one for unique items. 
Pros:
  - it returns nbHits more accurate.
  - it should be fast
  
Cons: 
 - we need 2 indexes instead of one.

**Comment by curquiza** [comment] 2022-06-23 14:50
Closed by #2546, will be present in rc1! 🚀

**Closed** 2022-06-23 14:54 UTC
Labels: bug, milli

**Comment by curquiza** [comment] 2022-12-07 09:27
Hello @freescout-helpdesk, I see the issue you are talking about is [this one](https://github.com/meilisearch/meilisearch/issues/3200). We will let you know in the open issue, this one is an old and irrelevant one anymore.

See you there
