### ISSUE TITLE
Memory usage keeps increasing without being released

### ISSUE THREAD

**Issue by thanhtoan1196** [meilisearch/meilisearch#2014] opened 2021-12-16 03:51 UTC
**Describe the bug**
Memory usage keeps increasing without being released, can only reboot to free up memory.
Memory increased to 33.9G in 2 days.
![image](https://user-images.githubusercontent.com/16433547/146304972-a11fb2b7-8f4d-4290-8b62-85c0f5349aba.png)

**To Reproduce**
1. Deploy MeiliSearch
2. Use MeiliSearch
3. Check the memory after a while

**Expected behavior**
Memory is automatically freed

**MeiliSearch version:** getmeili/meilisearch:v0.23.0

**Comment by curquiza** [comment] 2021-12-16 17:00
Hello @thanhtoan1196 
This is a weird issue you have!

Do you have the same issue using v0.24.0?

Also, can you tell us about
- What do you mean "use MeilISearch"? Did you do indexation or search as well?
- What is the OS?

Thanks for your report

**Comment by thanhtoan1196** [comment] 2021-12-16 17:09
@curquiza
- 0.24.0 has a storage problem so I don't use it
https://github.com/meilisearch/meilisearch-kubernetes/issues/89
- "use MeilISearch" means search
- I use alpine (docker image)
https://github.com/meilisearch/MeiliSearch/blob/main/Dockerfile

**Comment by curquiza** [comment] 2021-12-16 17:37
On which OS do you run your docker? Windows? Linux? MacOs?

**Comment by thanhtoan1196** [comment] 2021-12-17 01:17
I run docker on Linux

**Comment by irevoire** [comment] 2022-01-10 19:13
Hello @thanhtoan1196, I looked at the heap usage of MeiliSearch through [massif](https://valgrind.org/docs/manual/ms-manual.html).
Here you can see what happens when I index 10 times the [movies.json](https://docs.meilisearch.com/movies.json) from the [meilisearch quick start](https://docs.meilisearch.com/learn/getting_started/quick_start.html#add-documents):
![image](https://user-images.githubusercontent.com/7032172/148816691-e99d4f4a-92d3-487e-877e-fbd0b15d9f82.png)
As you can see on the right, between each peak, the heap usage falls back to 3MiB.

So, to me, what you observe is just memory-mapped pages not being freed by the OS because no one is using this memory (like caches but handled by the OS). But if another program starts to require a lot of RAM, the OS should free some pages from MeiliSearch.

I can be wrong on some details, but I think that's the big picture.
@Kerollmops do you confirm or want to explain further?

**Comment by K2ouMais** [comment] 2022-01-11 11:07
I am watching the memory usage aswell in v0.23 and it seems the memory is increasing with each added document.

Seems something is off for some reason.

I am watching the docker containers with the command "docker system df".

After the first import I see this:
![{644A344E-0C50-436E-B548-699642FD60B8}](https://user-images.githubusercontent.com/52510455/148931339-ebad4670-5f77-49df-9808-1f750db2ce5a.png)

After the second import of the same data and after indexing I see this:
![{CD0FE723-A9E4-4679-A786-36FCCD7AC3F2}](https://user-images.githubusercontent.com/52510455/148931468-b4f08439-2f4d-441f-9618-a7f275dd8812.png)

In the index is the same amount of documents but I dont know why the space usage by the container got bigger.

I am using CSV for updating my index like this:
```php
$meiliFile = storage_path('app/gleif_files/') . substr($this->baseName, 0, -8) . '.meilisearch.csv';
$meiliClient = new Client(config('goldencopy.meilisearch_host'));
$meiliClient->index('lei2_data')->addDocumentsCsv(file_get_contents($meiliFile), 'id');
```

**Comment by curquiza** [comment] 2022-06-16 13:38
Closing this since we are not able to reproduce and we are missing information!
Feel free to open a new issue with more details so that we can reproduce the bug if needed 😄

**Closed by curquiza** 2022-06-16 13:38 UTC
Labels: performance
