### ISSUE TITLE
Installation Error - tls connection init failed

### ISSUE THREAD

**Issue by cherring07** [meilisearch/meilisearch#4258] opened 2023-12-15 16:24 UTC
When installing I'm getting the following error. 
Error: Transport(Transport { kind: ConnectionFailed, message: Some("tls connection init failed"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("download.johtani.info")), port: None, path: "/unidic-mecab-2.1.2_src.zip", query: None, fragment: None }), source: Some(Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) }) })
warning: build failed, waiting for other jobs to finish... 

**Meilisearch version:**
[e.g. v1.5.0]

**Comment by ng5** [comment] 2023-12-19 21:49
I just tried to build from source today. I'm having same error.

**Comment by curquiza** [comment] 2023-12-20 13:06
Hello everyone,

can you give us a little bit more information: how did you install Meilisearch? How did you trigger the issue?

**Comment by ng5** [comment] 2023-12-20 21:56
I followed build from source as mentioned in the documentation

**Comment by curquiza** [comment] 2023-12-20 23:12
@ng5 I don't manage to reproduce the issue

```bash
git clone https://github.com/meilisearch/meilisearch
cd meilisearch
git checkout latest
cargo run --release
```

works for me

**Comment by ng5** [comment] 2023-12-21 05:09
i tried to build on a new ubuntu 22.04 lts docker container anf it compiled successfully. earlier i was building it on my archlinux system and it fails on it. let me send exact instructions to reproduce it. thanks

**Comment by curquiza** [comment] 2024-02-12 13:20
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-02-12 13:20 UTC
Labels: needs more info
