### ISSUE TITLE
Deleted documents are still in search results

### ISSUE THREAD

**Issue by chamby** [meilisearch/MeiliSearch#1809] opened 2021-10-13 23:58 UTC
**Describe the bug**
Deleted documents are still in search results even after a deletion request and the update queue is fully processed.

**To Reproduce**
I will try to get something reproducible. The state of my index is such that requesting the document by id returns `404` but a search that would include the document does in fact have a document with the deleted id.

Additional deletion requests for that id also do nothing to affect the search results.

I can also create a document with the same id and the search results are still the old document! The search results are pulling from stale data that I can't seem to affect anymore. I am going to dump the data and see if the imported data can reproduce this on another machine.

**Expected behavior**
Deleted documents should not show up in search results once the deletion has been processed.

**MeiliSearch version:** [e.g. v0.20.0]
v.0.22.0

**Additional context**
Ubuntu 20.04

**Comment by chamby** [comment] 2021-10-14 01:59
I created a dump and imported the dump to v.0.23.1 on my local machine. The document exists when I request it via id. I will try to import the dump on my production machine in order to fix my issue.

**Comment by curquiza** [comment] 2021-10-14 12:39
Hello @chamby! Thanks for your report, this is indeed really weird...
I close this issue because we cannot reproduce it, but feel totally free to re open if you have this issue again, or if someone can provide detailed steps to reproduce it.

**Closed by curquiza** 2021-10-14 12:39 UTC
