### ISSUE TITLE
Test failure on windows

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/meilisearch#1966] opened 2021-12-02 19:17 UTC
**Describe the bug**
There is a bug on window with the `index::delete_index::loop_delete_add_documents ` test introduced by the task store (#1796). I have disabled this test on windows for now, since it doesn't seem to impact unix builds.

```
---- index::delete_index::loop_delete_add_documents stdout ----
thread 'index::delete_index::loop_delete_add_documents' panicked at 'assertion failed: `(left == right)`
  left: `String("failed")`,
 right: `"succeeded"`: {"uid":1,"indexUid":"test","status":"failed","type":"indexDeletion","details":{"deletedDocuments":null},"error":{"message":"An internal error has occurred. `The process cannot access the file because it is being used by another process. (os error 32)`.","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"},"duration":"PT0.377988900S","enqueuedAt":"2021-12-02T18:52:32.635101Z","startedAt":"2021-12-02T18:52:32.921473Z","finishedAt":"2021-12-02T18:52:33.013089900Z"}', meilisearch-http\tests\index\delete_index.rs:63:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Ln11211** [comment] 2022-10-02 05:00
Hey there,
What exactly should one do to tackle/close this issue successfully? Do I need to test for the same error and post the logs somewhere?

**Comment by Ln11211** [comment] 2022-10-02 05:01
I'm interested, but I want to know more about it before I commit. Any help @curquiza :)?

**Comment by irevoire** [comment] 2022-10-03 17:52
Hey @Ln11211, basically, we don't know; the first thing you should do is enable these tests and try to run a `cargo test` on windows.
If it doesn't work, it's nice; you'll be able to debug it from your machine.
If it works, you should fork our repo and let the CI crashes for you.

Sorry, we don't know why it's failing or how to fix the issue. We don't even have a windows machine to reproduce the issue; thus, you're alone on this issue :grimacing:

**Comment by Ln11211** [comment] 2022-10-05 16:33
> Hey @Ln11211, basically, we don't know; the first thing you should do is enable these tests and try to run a `cargo test` on windows. If it doesn't work, it's nice; you'll be able to debug it from your machine. If it works, you should fork our repo and let the CI crashes for you.
> 
> Sorry, we don't know why it's failing or how to fix the issue.

Hey how do I enable tests? could please tell how to begin, I have read about cargo test( in Rust docs and also installed the cargo package today)

**Comment by curquiza** [comment] 2022-10-06 12:57
Hello @Ln11211 
I cannot say more about this issue, as you can see, it's not an issue where we can give you information about how to begin: it's definitely not a "good first issue", but a "help wanted" one. We really don't know why it happens and how to fix it.
We have this test failing on a Windows machine, and if someone could help us with it, for example by running the test on their side and seeing how to fix it, it would be awesome. Maybe the issue is not even here anymore. In this case, we would like to re-activate this test again

**Closed** 2022-10-27 14:07 UTC
Labels: bug, windows, contribution accepted, help wanted, hacktoberfest
