### ISSUE TITLE
Exact letter / character search?

### ISSUE THREAD

**Issue by wassim** [meilisearch/meilisearch#2559] opened 2022-06-28 13:44 UTC
Hi, I'm trying to achieve the following results

**example 1 :**

- cat
- account
- mac

search term : `"c"` should only return `cat` but returns all words

**example 2 :**

- github
- magic
- raging

search term : `"gi"` should only return `github` but returns all words

I have disabled typo tolerance on my index, moved "exactness" to top ranking rules and removed "words" and "proximity" ranking rules but Meilisearch still returns unexpected results.

Is it possible to do a search that match the letters / characters position in a given word?

**Comment by oluademola** [comment] 2022-06-29 19:04
Hello @wassim 

This is the expected behaviour. Meilisearch would not understand that you only want to retrieve results for `cat` if you used the search term = `"c"`. Meilisearch uses the prefix search methodology, thus it begins by comparing the search term (in this case, `"c"`) against the beginning of each word in your dataset. It then returns all documents that contain the search term (`"c"`), and it returns all documents in the above-mentioned sequence. If you wanted to get results that only contained `"cat"` you could run a phrase search with `q = "cat"`

I'm afraid it's not possible to do a search that match the letters / characters position in a given word at the moment perhaps @gmourier might have more info.

Hope this answers your question. Thank you.

**Comment by curquiza** [comment] 2022-07-06 16:11
Hello @wassim, since you cannot reach what you expect currently with Meilisearch, I've open a product discussion [here](https://github.com/meilisearch/product/discussions/492) so that we ensure your feedback is taken into account by the product team.

Thanks again for your report
I close this issue then!

**Closed by curquiza** 2022-07-06 16:11 UTC
Labels: support
