### ISSUE TITLE
 Access is denied. (os error 5) when loading indexes from dump (Windows 11)

### ISSUE THREAD

**Issue by greevesh** [meilisearch/meilisearch#2597] opened 2022-07-09 09:18 UTC
Access is denied. (os error 5) when loading indexes from dump (Windows 11)

While migrating from Meilisearch 0.25.0 to the latest version following the [guide](https://docs.meilisearch.com/learn/advanced/updating.html#updating-from-v0-15-0-or-above) until step 4, the following command -

`./meilisearch --import-dump /dumps/your_dump_file.dump --master-key="MASTER_KEY"`

will yield this response - 

`[2022-07-09T08:50:31Z INFO  meilisearch_lib::index_controller::dump_actor] Loading dump from 2022-07-08 07:42:22.281689200 UTC, dump database version: 0.25.2, dump version: V4
[2022-07-09T08:50:31Z INFO  meilisearch_lib::index_controller::dump_actor::loaders::v4] Loading dump from 2022-07-08 07:42:22.281689200 UTC, dump database version: 0.25.2, dump version: V4
[2022-07-09T08:51:00Z INFO  meilisearch_lib::index_controller::dump_actor::loaders::v4] Loading indexes.
Error: Access is denied. (os error 5)`

What I've tried -

- Running Git Bash as admin
- Turning off Antivirus
- Adjusting the UAC settings
- Running the following command - `net user administrator /active:yes`
- Running Windows' Install and Uninstall Troubleshooter

**Comment by oluademola** [comment] 2022-07-18 06:55
Hi @greevesh 

Sorry for the inconvenience. I've been unable to reproduce the problem, and I'll try again later and get back to you. In the meantime, I suggest using [docker](https://docs.meilisearch.com/learn/getting_started/quick_start.html#setup-and-installation). Thank you.

**Comment by oluademola** [comment] 2022-07-31 20:36
Hi @greevesh 

I am not able to reproduce this error. This error is most likely not related to meilisearch but rather a configuration issue on your machine, as indicated by the error message. The reason for this error could be a wrong Windows configuration or a corrupted user account that is blocking you from having the rights. There are some easy fixes that you can try out, to fix this issue in this [article](https://windowsreport.com/error-5-access-is-denied-fix/). I hope this helps. 

Thank you very much.

**Comment by curquiza** [comment] 2022-08-23 12:01
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2022-08-23 12:01 UTC
Labels: windows, support
