### ISSUE TITLE
Web interface not working if a master key is set

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/MeiliSearch#1339] opened 2021-04-15 19:05 UTC
**Describe the bug**

The web interface of meilisearch (`meilisearch-http/public/interface.html`) is not working as expected if a `MEILI_MASTER_KEY` has been set for the meilisearch instance.
The user fill the apiKey but it doesn't do anything and he can't see the indexes or the results of the search.
In the interface, when entering the `apiKey` in the `API Key input`, the value of the `X-Meili-API-Key` for the queries will never be updated and the user will never be able to see anything in the interface. (All the requests get a 401 response)
At each change of the `API Key input`, the variable `apiKey` in the localstorage should be updated.

**To Reproduce**

Run `cargo run --release -- --master-key "masterkey"`
Add some data to your meilisearch
Go to `localhost:7700` in your favourite browser
Make sure that you don't have a variable `apiKey` set in your localstorage, if so delete it.
Try to do a search or check indexes -> should not work
Enter your apiKey `masterkey`
Try to do a search or check indexes -> **should work** but is not working at the moment

**Expected behavior**

The value of the variable `apiKey` in the localstorage should be updated each time the user change the `API Key input`.

**Desktop (please complete the following information):**

 - OS: macos
 - Browser: chrome/safari

**Additional context**

Since Meilisearch v0.20.0

**Comment by eskombro** [comment] 2021-04-15 19:09
I tested with MACOS and FIREFOX, same behavior. This behavior is not present in v0.19.0.

**Comment by sanders41** [comment] 2021-04-15 21:00
I'm going to make a guess that this one is my fault because I made an update to the API key field. I didn't see this testing, but reading through the issue here I'm thinking I must have had an apiKey in my localstorage without know it.

**Comment by curquiza** [comment] 2021-04-19 10:45
So sorry we introduced this bug in v0.20.0!
It's not your fault @sanders41, we (the Meili team) should have done a better check before merging!
We are currently working on a new dashboard that will be present in the v0.21.0, so this issue should be removed with the release of the v0.21.0 😉

**Comment by NatBLida68** [comment] 2021-06-11 08:10
@curquiza  can you tell me when is v0.21.0 is going to be released ?   because 0.20   is making so much trouble in my production server  with cpu and mem usage spiking to 100% resulting a 502   our team even updated ram and disk in droplet but still it is  not functioning as expected

**Comment by curquiza** [comment] 2021-06-11 10:01
Hello @NatBLida68!
Is your pb related to this dashboard issue?

Be sure we are doing our best to release the v0.21 as soon as possible. We hope releasing the first RC of the v0.21 by the end of June.
But we don't recommend using RC versions in production.

If you have issue with the current MeiliSearch it would be helpful you share with us your dataset, your configuration, your step and your machine specificities so that we can reproduce your issue. But not in this issue since it does not seem to be related. You can join us on slack or email. 
It would be really helpful for the core team to have concrete case failure we can reproduce 🙂

**Comment by curquiza** [comment] 2021-06-30 17:16
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421

**Closed by curquiza** 2021-06-30 17:16 UTC
Labels: project:dashboard, v0.21:fixed
