### ISSUE TITLE
facetsDistribution returning thousands of Facets, instead of just the few calculated ones

### ISSUE THREAD

**Issue by bbarclay** [meilisearch/meilisearch#2168] opened 2022-02-14 08:59 UTC
facetsDistribution seems to be getting all my facets, which causes the page to load really slow. Here's an example. Why isn't facetsDistribution filtering to only. the top 10, for instance. 

[``]([url](url)
<img width="1058" alt="Screen Shot 2022-02-14 at 1 00 42 AM" src="https://user-images.githubusercontent.com/374088/153831797-c6a57bbc-76e0-47b8-a31b-20b751b875d3.png">
<img width="205" alt="Screen Shot 2022-02-14 at 1 00 19 AM" src="https://user-images.githubusercontent.com/374088/153831804-a5df045b-9f49-479e-81df-b5fbcb14019f.png">
)

What seems to be happening is that its' not just grabbing the top 10 keywords, it's grabbing the whole database of keywords. Any idea what might be causing this?

**Comment by curquiza** [comment] 2022-03-02 18:36
Hello @bbarclay

Sorry for the late answer!

> What seems to be happening is that its' not just grabbing the top 10 keywords

It's expected, Meilisearch will return the whole facet value in your dataset.

If you need another behavior, you can open a discussion in the product repository so that the product team will be aware of it and can consider your request: https://github.com/meilisearch/product/discussions
Feel free to give your detailed usage, it will be really helpful!

Thanks in advance, and sorry again for the delay!
I close this issue since it's a feature request and not a bug.

**Closed by curquiza** 2022-03-02 18:36 UTC
