### ISSUE TITLE
Huge index when importing dump to v1.4.x

### ISSUE THREAD

**Issue by dtomlinson91** [meilisearch/meilisearch#4144] opened 2023-10-21 23:41 UTC
**Describe the bug**
Importing a dump from v1.3.0 to v1.4.2 results in the index ballooning in size from 52.92GB to 888.36GB!

**To Reproduce**
We're using an umbrella chart that just uses [meilisearch-kubernetes Helm chart](https://github.com/meilisearch/meilisearch-kubernetes) as a dependency.

1. Create a dump on v1.3.0 (0.2.6 Helm chart)
2. `rm -rf /meili_data/data.ms` inside the container
3. Change `dependencies.version` in `Chart.yaml` to 0.2.7 [I tried setting `image.tag` to both v1.4.0 and v1.4.2]
4. Set `environment.MEILI_IMPORT_DUMP` to import the dump
5. Set `startupProbe.InitialDelaySeconds` to really high to allow the import time to run
6. Run `helm upgrade`

**Expected behavior**
I expect the database to be roughly the same size as before.

**Screenshots**
Given below

**Meilisearch version:**
Dump taken on v1.3.0 (0.2.6 Helm chart), import done on v1.4.0 and v1.4.2 (0.2.7 Helm chart).

**Additional context**
Running on GKE with 4vCPU and 45Gi Memory. The name of a 2TB (SSD) PVC is passed to the chart using `persistence.existingClaim`. We're using the [meilisearch-kubernetes Helm chart](https://github.com/meilisearch/meilisearch-kubernetes).

Could be related to #4114 except this doesn't go away for me.

Looking at the logs the index starts to balloon when at this log entry:
```
[2023-10-21T21:51:14Z DEBUG milli::update::index_documents::extract] merge word-position-docids database
```

I'm using a single index with ~17million documents totalling ~53GB:

- The settings for this index: https://gist.github.com/dtomlinson91/f34d9bde501f0d4fb37a6d6bb86351b9#file-settings-json
- `/stats` on v1.3.0 before importing: https://gist.github.com/dtomlinson91/f34d9bde501f0d4fb37a6d6bb86351b9#file-stats-pre-json
- `/stats` on v1.4.2 after importing: https://gist.github.com/dtomlinson91/f34d9bde501f0d4fb37a6d6bb86351b9#file-stats-json
- The dump file to reproduce (1.3GB): https://storage.googleapis.com/precision_shared/meilisearch/20231020-193828874.dump (this will be available for 7d)
- The debug logs during the import: https://storage.googleapis.com/precision_shared/meilisearch/import-logs.csv (7 days)
  - There's ~18k log entries.
  - I removed `update: RemapDocumentAddition` and `update: ComputeIdsAndMergeDocuments` entries from the logs as there's around 22 million log entries for these
  - If you need them, I can export them to say BigQuery and make it available for you to use?
- The env vars:
<img width="626" alt="SCR-20231021-rsgp" src="https://github.com/meilisearch/meilisearch/assets/53234158/5693963b-9e6a-4557-9b82-93adc8491840">

- The result of `du -ah data.ms` while the import job is running:
<img width="537" alt="image" src="https://github.com/meilisearch/meilisearch/assets/53234158/4ce05184-876e-4e52-82e7-479ba98a20e7">

Usually we run 2vCPU, 12GB RAM with 150GB SSD times 2 instances for failover. I over provisioned for the import but this did happen when running at its normal size.

**Comment by ManyTheFish** [comment] 2023-10-30 15:41
Hello @dtomlinson91,
I haven't managed to reproduce your bug so far. I've tried your data on both versions, but I didn't see any disk usage difference.
I'm sorry to ask, but could you try to retry on a fresh instance?

Thank you for your report, don't hesitate to comeback to me when you have more information.

**Comment by dtomlinson91** [comment] 2023-11-03 14:43
@ManyTheFish hmm weird one for sure! I'll have time next week, I'll start g from scratch and reindex, dump and upgrade and report back. Thanks for looking into it.

**Comment by curquiza** [comment] 2023-12-15 11:49
hello @dtomlinson91 do you have more information about this? 😊

**Comment by curquiza** [comment] 2024-01-03 17:16
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-01-03 17:16 UTC
Labels: needs more info, support
