### ISSUE TITLE
Regression bug with accentuation

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch#3628] opened 2023-03-30 15:08 UTC
**Describe the bug**
Hi team, I was implementing ruby, and I found a bug that I could reproduce in the CURL as well:

**To Reproduce**

Given this data and index configuration:

```
curl --location 'http://localhost:7700/indexes/books/documents' \
--header 'Authorization: Bearer masterKey' \
--header 'Content-Type: application/json' \
--data '[
    {
        "objectId": 123,
        "title": "Pride and Prejudice",
        "year": 1813,
        "author": "Jane Austen",
        "genre": "romance"
    },
    {
        "objectId": 456,
        "title": "Le Petit Prince",
        "year": 1943,
        "author": "Antoine de Saint-Exupéry",
        "genre": "adventure"
    },
    {
        "objectId": 1,
        "title": "Alice In Wonderland",
        "year": 1865,
        "author": "Lewis Carroll",
        "genre": "adventure"
    },
    {
        "objectId": 2,
        "title": "Le Rouge et le Noir",
        "year": 1830,
        "author": "Stendhal",
        "genre": "romance"
    },
    {
        "objectId": 1344,
        "title": "The Hobbit",
        "year": 1937,
        "author": "J. R. R. Tolkien",
        "genre": "adventure"
    },
    {
        "objectId": 4,
        "title": "Harry Potter and the Half-Blood Prince",
        "year": 2005,
        "author": "J. K. Rowling",
        "genre": "fantasy"
    },
    {
        "objectId": 2056,
        "title": "Harry Potter and the Deathly Hallows",
        "year": 2007,
        "author": "J. K. Rowling",
        "genre": "fantasy"
    },
    {
        "objectId": 42,
        "title": "The Hitchhiker'\''s Guide to the Galaxy",
        "year": 1978,
        "author": "Douglas Adams"
    },
    {
        "objectId": 190,
        "title": "A Game of Thrones",
        "year": 1996,
        "author": "George R. R. Martin",
        "genre": "fantasy"
    }
]'

curl --location --request PUT 'http://localhost:7700/indexes/books/settings/filterable-attributes' \
    --header 'Content-Type: application/json' \
    --header 'Authorization: Bearer masterKey' \
    --data '["author", "year"]'
```

When I do this search on `v1.0.2`

```
curl --location 'http://localhost:7700/indexes/books/search' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer masterKey' \
--data '{
    "q": "prince",
    "filter": "year > 1930 AND author = \"Antoine de Saint-Exupéry\""
}'
```

I got these results:

```
{
    "hits": [
        {
            "objectId": 456,
            "title": "Le Petit Prince",
            "year": 1943,
            "author": "Antoine de Saint-Exupéry",
            "genre": "adventure"
        }
    ],
    "query": "prince",
    "processingTimeMs": 0,
    "limit": 20,
    "offset": 0,
    "estimatedTotalHits": 1
}
```

But in the new version v1.1.0-rc.3

```
{
    "hits": [],
    "query": "prince",
    "processingTimeMs": 0,
    "limit": 20,
    "offset": 0,
    "estimatedTotalHits": 0
}
```

**Expected behavior**
I expect still to find the same results in the new version.

**Additional context**
After experimenting, I discovered that changing the "é" by "e" in the data works. But I do it on search-time. It does not.

**Comment by bidoubiwa** [comment] 2023-03-30 15:19
it does not work as well on rc2, 1 and 0.

**Comment by curquiza** [comment] 2023-03-30 15:54
Cannot reproduce it in rc3, seems to have been fixed

Tests have been added: https://github.com/meilisearch/meilisearch/pull/3621/files#diff-7dfdaaa482a27a03e4cea11a31637c7b419b8c66cd342fcd6ef0feaaa8098bde

Closing this, let me know if I'm wrong!

**Closed by curquiza** 2023-03-30 15:54 UTC
Labels: bug
