### ISSUE TITLE
Deploy to Heroku?

### ISSUE THREAD

**Issue by baskin** [meilisearch/MeiliSearch#689] opened 2020-05-17 16:42 UTC
Hi Team,
I was trying to deploy MeiliSearch to heroku using the docker image. 
I was not able to. The app continued to crash w/o emitting any useful logs.

I also stumbled across the [diff](https://github.com/meilisearch/MeiliSearch/commit/7eb63339333c708ceb87ae5b576cd6da9b47ecd9#diff-6a1b6963e828b69fcc667e3c45df78bb) where the heroku artifacts were removed from README and elsewhere. 

Is there any prior history of MeiliSearch working/not working on heroku?

**Comment by MarinPostma** [comment] 2020-05-17 20:46
@eskombro maybe?

**Comment by tpayet** [comment] 2020-05-18 11:05
Hey @baskin,
Can you show us the log? When we were using Heroku we didnt use the Docker image, but we used the Rust buildpack. 
We removed the one-click button deploy to Heroku, because Heroku does not have a persistent file system so when the heroku dyno is shutted down for any reason, you are losing all of your MeiliSearch data written on disk.

**Comment by baskin** [comment] 2020-05-18 12:49
This was from the last run


> 2020-05-18T11:00:44.158263+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] Environment: "development"
2020-05-18T11:00:44.158283+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] Commit SHA: "UNKNOWN"
2020-05-18T11:00:44.158286+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] Build date: "2020-04-11T09:28:20.281549100+00:00"
2020-05-18T11:00:44.158308+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] Package version: "0.10.0"
2020-05-18T11:00:44.158357+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] No master key found; The server will have no securities.If you need some protection in development mode, please export a key. export MEILI_MASTER_KEY=xxx
2020-05-18T11:00:44.158358+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] If you need extra information; Please refer to the documentation: http://docs.meilisearch.com
2020-05-18T11:00:44.158362+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] If you want to support us or help us; Please consult our Github repo: http://github.com/meilisearch/meilisearch
2020-05-18T11:00:44.158362+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  meilisearch] If you want to contact us; Please chat with us on http://meilisearch.com or by email to bonjour@meilisearch.com
2020-05-18T11:00:44.159048+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO  tide::server] Server is listening on: http://0.0.0.0:7700
2020-05-18T11:01:42.515883+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by eskombro** [comment] 2020-05-18 12:55
Hello @baskin,

Can you please tell me how are you running the docker image to be able to reproduce this behaviour exactly?

Also, as @tpayet suggests, you can deploy MeiliSearch with Heroku without the Docker container. And mind the fact that persistence can't be guaranteed

Thanks

**Comment by baskin** [comment] 2020-05-18 13:52
I followed the steps listed [here](https://devcenter.heroku.com/articles/container-registry-and-runtime#releasing-an-image)

First pulled the meilisearch image from docker hub. The exec'ed the following:
* docker tag getmeili/meilisearch:v0.10 registry.heroku.com/<app>/web 
* docker push registry.heroku.com/<app>/web
* heroku container:release web -a <app>

**Comment by tpayet** [comment] 2020-05-19 18:58
The problem here might be that the Docker image is built for a specific architecture when Heroku might be running another one. 
Maybe should we try to build a multi-arch image for Docker image following [the docker documentation](https://docs.docker.com/docker-for-mac/multi-arch/)

**Comment by Kerollmops** [comment] 2020-05-20 09:40
> 2020-05-18T11:00:44.159048+00:00 app[web.1]: [2020-05-18T11:00:44Z INFO tide::server] Server is listening on: http://0.0.0.0:7700

It is strange that the binary even started to listen, I thought that a binary compiled for another architecture wouldn't even start at all, but maybe I'm wrong.

**Comment by qdequele** [comment] 2020-12-05 17:57
Hello @baskin,

Sorry I will close this issue, we already answer this question [here](https://github.com/meilisearch/MeiliSearch/discussions/1092). 

Thanks,

**Closed by qdequele** 2020-12-05 17:57 UTC
