### ISSUE TITLE
windows crashes after running for a while

### ISSUE THREAD

**Issue by yongheng0911** [meilisearch/meilisearch#3586] opened 2023-03-13 12:34 UTC
Performance: No response
Restarting meilisearch does not work
Rebooting your computer system will fix it

**Comment by oluademola** [comment] 2023-03-14 08:52
Hello @yongheng0911,

Could you please provide more context about the issue for us to help you?
Is it the Meilisearch server that is crashing or your windows machine? If it's the Meilisearch server crashing, at what point do you experience it? During the indexing process? What version of Meilisearch are you running?

Looking forward to your response. Many thanks.

**Comment by yongheng0911** [comment] 2023-03-14 13:58
The Meilisearch server crashed
v1.0.2   meilisearch-windows-amd64.exe
Local debug project I first connect meilisearch crash after the project can not start up
To be sure, I didn't do anything to meilisearch when it crashed, including read and write

**Comment by yongheng0911** [comment] 2023-03-14 14:06
> Hello @yongheng0911,
> 
> Could you please provide more context about the issue for us to help you? Is it the Meilisearch server that is crashing or your windows machine? If it's the Meilisearch server crashing, at what point do you experience it? During the indexing process? What version of Meilisearch are you running?
> 
> Looking forward to your response. Many thanks.

Meilisearch server crashed
v1.0.2 meilisearch-windows-amd64.exe
The local debug project couldn't start after I connected to meilisearch crash
To be sure, I didn't do anything with meilisearch when it crashed, including read and write

**Comment by yongheng0911** [comment] 2023-03-14 14:06
> Hello @yongheng0911,
> 
> Could you please provide more context about the issue for us to help you? Is it the Meilisearch server that is crashing or your windows machine? If it's the Meilisearch server crashing, at what point do you experience it? During the indexing process? What version of Meilisearch are you running?
> 
> Looking forward to your response. Many thanks.

I found him unresponsive for a long time. And then it will recover. It can last up to an hour

**Comment by oluademola** [comment] 2023-03-14 14:32
Hello @yongheng0911,

Sorry for the inconvenience. Unfortunately, I cannot reproduce the problem using a Windows 11 machine. I have tried the same binary (meilisearch-windows-amd64.exe v1.0.2 ), and it works correctly as seen in the screenshot below

<img width="940" alt="Screenshot 2023-03-14 153021" src="https://user-images.githubusercontent.com/101267639/225033831-41b4f6aa-8f1c-4430-ae44-e5cb2ebb3322.png">


What exactly happens when you launch Meilisearch? What is the specification of your machine? You mentioned it is unresponsive for a long time, and then it becomes responsive; what do you mean by that? Do you know how I can reproduce this problem?

**Comment by yongheng0911** [comment] 2023-03-14 14:38
> Hello @yongheng0911,
> 
> Sorry for the inconvenience. Unfortunately, I cannot reproduce the problem using a Windows 11 machine. I have tried the same binary (meilisearch-windows-amd64.exe v1.0.2 ), and it works correctly as seen in the screenshot below
> 
> <img alt="Screenshot 2023-03-14 153021" width="940" src="https://user-images.githubusercontent.com/101267639/225033831-41b4f6aa-8f1c-4430-ae44-e5cb2ebb3322.png">
> 
> What exactly happens when you launch Meilisearch? What is the specification of your machine? You mentioned it is unresponsive for a long time, and then it becomes responsive; what do you mean by that? Do you know how I can reproduce this problem?

![image](https://user-images.githubusercontent.com/127751358/225035318-e6f73adf-1952-44a8-a1be-cd3db36967ef.png)
![image](https://user-images.githubusercontent.com/127751358/225035484-3476623e-4083-4123-93d5-8728d84fa8f4.png)
He is in a perpetual wait

**Comment by yongheng0911** [comment] 2023-03-14 14:39
> > Hello @yongheng0911,
> > Sorry for the inconvenience. Unfortunately, I cannot reproduce the problem using a Windows 11 machine. I have tried the same binary (meilisearch-windows-amd64.exe v1.0.2 ), and it works correctly as seen in the screenshot below
> > <img alt="Screenshot 2023-03-14 153021" width="940" src="https://user-images.githubusercontent.com/101267639/225033831-41b4f6aa-8f1c-4430-ae44-e5cb2ebb3322.png">
> > What exactly happens when you launch Meilisearch? What is the specification of your machine? You mentioned it is unresponsive for a long time, and then it becomes responsive; what do you mean by that? Do you know how I can reproduce this problem?
> 
> ![image](https://user-images.githubusercontent.com/127751358/225035318-e6f73adf-1952-44a8-a1be-cd3db36967ef.png) ![image](https://user-images.githubusercontent.com/127751358/225035484-3476623e-4083-4123-93d5-8728d84fa8f4.png) He is in a perpetual wait

![image](https://user-images.githubusercontent.com/127751358/225035892-5d984007-5e37-4a6f-9ea8-acf6f457b70d.png)
![image](https://user-images.githubusercontent.com/127751358/225036175-9710650a-7c03-406c-adfc-29a7c0f58fc3.png)

**Comment by yongheng0911** [comment] 2023-03-14 14:58
> 你好@yongheng0911,
> 
> 带来不便敬请谅解。不幸的是，我无法使用 Windows 11 机器重现该问题。我尝试了相同的二进制文件 (meilisearch-windows-amd64.exe v1.0.2)，它可以正常工作，如下面的屏幕截图所示
> 
> <img alt="截图 2023-03-14 153021" width="940" src="https://user-images.githubusercontent.com/101267639/225033831-41b4f6aa-8f1c-4430-ae44-e5cb2ebb3322.png">
> 
> 当您启动美丽搜索时究竟会发生什么？你的机器规格是多少？你提到它很长一段时间没有反应，然后它变得有反应了；你是什​​么意思？你知道我如何重现这个问题吗？



> > Hello @yongheng0911,
> > Sorry for the inconvenience. Unfortunately, I cannot reproduce the problem using a Windows 11 machine. I have tried the same binary (meilisearch-windows-amd64.exe v1.0.2 ), and it works correctly as seen in the screenshot below
> > <img alt="Screenshot 2023-03-14 153021" width="940" src="https://user-images.githubusercontent.com/101267639/225033831-41b4f6aa-8f1c-4430-ae44-e5cb2ebb3322.png">
> > What exactly happens when you launch Meilisearch? What is the specification of your machine? You mentioned it is unresponsive for a long time, and then it becomes responsive; what do you mean by that? Do you know how I can reproduce this problem?
> 
> ![image](https://user-images.githubusercontent.com/127751358/225036572-f05234e0-4b47-477f-8465-37c714f0345c.png) ![image](https://user-images.githubusercontent.com/127751358/225036708-de2a8b82-a178-4d56-97d0-ec5655ca6a29.png)

Restarting meilisearch takes 188MB of memory
If there is no response, the memory usage is 3.5MB
He seems to be giving up on the memory usage resulting in unresponsiveness

**Comment by oluademola** [comment] 2023-04-06 07:25
Hello @yongheng0911. Sorry for the delayed response. Can you try the latest [version](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.0) and let us know if this issue persists?

**Comment by curquiza** [comment] 2023-05-10 13:23
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-05-10 13:23 UTC
Labels: support
