### ISSUE TITLE
docker compose not working

### ISSUE THREAD

**Issue by deroccha** [meilisearch/meilisearch#2292] opened 2022-04-05 11:00 UTC
I have the following setting in my docker-compose 

```
  meilisearch:
    container_name: ${PROJECT_SUFFIX}_meilisearch
    image: getmeili/meilisearch:latest
    restart: always
    depends_on:
      - db
    volumes:
      - ./sql:/data.ms
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_NO_SENTRY: 'true'
      MEILI_MASTER_KEY: null
      MEILI_ENV: 'development'
    ports:
      - target: 7700
        published: 7700
        protocol: tcp
```

on start will throw the following error :  **Error: Meilisearch (v0.26.1) failed to infer the version of the database. Please consider using a dump to load your data.**

I already cleaned up couple of times the shared Folder but the error persist.

**Comment by curquiza** [comment] 2022-04-05 11:38
Hello @deroccha 

Have you updated the version of Meilisearch? The error message says you are trying to run Meilisearch with v0.26.1, but your documents have been added using an older version (like v0.25.0?).
Is it the case?

**Comment by deroccha** [comment] 2022-04-05 11:41
@curquiza after upgrade I deleted the mounted folder and even  docker fully rested``docker system prune -u``

**Comment by oluademola** [comment] 2022-04-05 14:49
Hi @deroccha If I understand you correctly, you've upgraded to version 0.26.1 of Meilisearch and now you're getting the following error: Error: Meilisearch (v0.26.1) failed to infer the version of the database. Please consider using a dump to load your data.
Have you tried removing specifically your database folder (data.ms) and using this version to reindex your documents all over again?

**Comment by deroccha** [comment] 2022-04-05 15:37
Hi @curquiza I made a custom builded container and tagged that on build with the right platfom for M1 and now works. Previously I deleted all specific meilisearch data's but did not worked

**Comment by curquiza** [comment] 2022-04-07 13:14
@deroccha glad to read you found out an issue. I'm a little bit annoyed since we did not succeed to reproduce your issue on our side (on M1).

If you have the time, can you share with us how you build it?

**Comment by fritzfr** [comment] 2022-04-12 07:52
Hey,

I'm also encountering the error:

> Error: Function not implemented (os error 38)

while trying to build an arm64 docker image from `getmeili/meilisearch:v0.26.1`.

```
#9 [linux/arm64 1/3] FROM [docker.io/getmeili/meilisearch:v0.26.1@sha256:10f72ecdd219a54be8d3d17e231888047ec5bf1b38548f773880cbf8eaeb0f4a](http://docker.io/getmeili/meilisearch:v0.26.1@sha256:10f72ecdd219a54be8d3d17e231888047ec5bf1b38548f773880cbf8eaeb0f4a)
#9 extracting sha256:0857af6692e3c2c1b2d380b06b1a02b15a494c0b3300865af0300e4a6f0e2f90 0.2s done
#9 DONE 1.5s
#11 [linux/arm64 2/3] COPY [data.ms](http://data.ms/).snapshot /
#11 DONE 0.1s
#12 [linux/arm64 3/3] RUN ./meilisearch --no-analytics --ignore-snapshot-if-db-exists --import-snapshot data.ms.snapshot
#12 0.144 [2022-04-11T09:41:13Z INFO  meilisearch_lib::index_controller] Loading from snapshot "data.ms.snapshot"
#12 1.229 Error: Function not implemented (os error 38)
```

**Comment by curquiza** [comment] 2022-04-14 14:23
Hello @fritzfr 

We have M1 internally and we did not succeed to reproduce your issue. Can you detail the commend you launched to have this problem?

**Comment by fritzfr** [comment] 2022-04-14 14:29
Hey @curquiza 
I believe everything works fine on M1, I have an M1 Macbook too. The issue I am describing is happening **on a x86 machine**, that is our Gitlab runner. It has a pipeline that is building a multi-arch docker image using `docker buildx`.
The Dockerfile looks like this:

```docker
FROM getmeili/meilisearch:v0.26.1
COPY data.ms.snapshot /
RUN ./meilisearch --no-analytics --ignore-snapshot-if-db-exists --import-snapshot data.ms.snapshot 
```

and the Pipeline contains:
```yaml
variables:
  CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}
  CONTAINER_TAG_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  CONTAINER_PLATFORMS: linux/arm64,linux/amd64
```

```
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx build --platform $CONTAINER_PLATFORMS --push --tag $CONTAINER_RELEASE_IMAGE .
```

**Comment by curquiza** [comment] 2022-04-14 16:37
Thanks for the details 🙂

We are not CI experts, and docker experts either, but we succeeded to deploy CI creating cross-platform image for Meilisearch without any issue. We had this issue before providing a docker image for M1, but now we don't have any problem. Meaning you probably have an issue regarding your docker settings, but I cannot help you more...
Maye be you should take a look at [our CI manifest](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-docker-tag.yml) to reproduce it into your own CI?

**Comment by curquiza** [comment] 2022-05-02 08:31
I close this issue due to a lack of answer, feel free to ask to reopen if needed

**Closed by curquiza** 2022-05-02 08:31 UTC
Labels: needs more info

**Comment by adicco** [comment] 2022-05-11 14:23
Hello @curquiza,

I am also encountering a similar issue:

```
➜  docker-env docker run -it --rm -p 7900:7700 -v meili_dump:/dumps -v meili_db_upd:/data.ms getmeili/meilisearch:latest meilisearch --import-dump /dumps/20220511-141824941.dump 
[2022-05-11T14:19:59Z INFO  meilisearch_lib::index_controller::dump_actor] Loading dump from 2022-05-11 14:18:24.943074016 +00:00:00, dump database version: 0.26.1, dump version: V4
[2022-05-11T14:19:59Z INFO  meilisearch_lib::index_controller::dump_actor::loaders::v4] Loading dump from 2022-05-11 14:18:24.943074016 +00:00:00, dump database version: 0.26.1, dump version: V4
[2022-05-11T14:20:07Z INFO  meilisearch_lib::index_controller::dump_actor::loaders::v4] Loading indexes.
Error: Meilisearch (v0.27.0) failed to infer the version of the database. Please consider using a dump to load your data.
```

What I did prior:

- Attach a `meili_dump` volume to my previous meili instance that was running `getmeili/meilisearch:v0.26.1` (I am trying to upgrade to 0.27)
- Create a dump (POST /dumps; which yielded `20220511-141824941.dump`)
- Start another container to import the dump (see above)

**Comment by curquiza** [comment] 2022-05-16 08:06
Hello @deroccha 
If I'm correct this is related to https://github.com/meilisearch/meilisearch/issues/2389
Let's discussion in the open issue instead of here
