### ISSUE TITLE
MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size.

### ISSUE THREAD

**Issue by Northn** [meilisearch/meilisearch#2743] opened 2022-09-04 18:50 UTC
**Describe the bug**
When we decided to test a new version of MeiliSearch on our forum (XenForo CMS with custom addon) we have began importing all documents to it. So, when the indexation has began, we have ran into some MeiliSearch internal error: MDB_BAD_VALSIZE.

**To Reproduce**
I really have no idea why it happens. We don't have such issue on MeiliSearch 0.28.1, but have in any 0.29 versions. I thought that problem could occur due to auto-batching feature, tried to turn it off but still. Tried to set indexation threads count to 0 but whatever, the problem is still is. Another interesting fact is that this problem doesn't happen when sending problem request manually via curl. I can attach (problem?) request body if you want.

**Expected behavior**
Indexation process completes successfully.

**Screenshots**
No screenshots. I can reproduce this problem and record a video if you want.

**Meilisearch version:**
[v0.29.0rc2](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.0rc2)
Problem occurs on any 0.29 version.

**Additional context**
WSL2, Windows 11

**Comment by curquiza** [comment] 2022-09-05 08:47
Hello @Northn 

Thanks for this report!
Can you try launching Meilisearch with the `--disable-auto-batching` flag? This way we will know if it's auto-batching

Also, with only this information, we can't reproduce the issue and thus fix this bug.

Could you share your dataset or a piece of your dataset where the issue is visible?
You can share it privately by email, of course. 
We know sharing datasets is not something people like, but it will be definitely helpful for Meilisearch 🙏 We already proceeded like this before, be sure we will delete your dataset once the bug is fixed, it's only for test purposes, of course.

**Comment by Northn** [comment] 2022-09-06 16:19
> Hello @Northn
> 
> Thanks for this report!
> 
> Can you try launching Meilisearch with the `--disable-auto-batching` flag? This way we will know if it's auto-batching I miss read, you already tested it!
> 
> Also, with only this information, we can't reproduce the issue and thus fix this bug.
> 
> Could you share your dataset or a piece of your dataset where the issue is visible? You can share it privately by email, of course. We know sharing datasets is not something people like, but it will be definitely helpful for Meilisearch 🙏 We already proceeded like this before, be sure we will delete your dataset once the bug is fixed, it's only for test purposes, of course.
> 
> Thanks in advance for your help

Hello,
Sorry for delay, I've sent the required data to your mail. Thanks for attention.

**Comment by curquiza** [comment] 2022-09-08 07:49
Closed by #2759 and meilisearch/milli#628, will be available in v0.29.0rc3 today

**Comment by Arsapol** [comment] 2022-11-11 06:50
I face this problem again in v0.30.0rc1 with linux-aarch64.

**To Reproduce**
I have upgraded from v0.29.1 to v0.30.0rc1 in order to prevent duplicated documents in search route.
If I use batch size of 4-10, everything works fine.
But if I use batch size more than 5,000,  error message appear.

**Expected behavior**
Indexation process completes successfully.

**Screenshots**
<img width="402" alt="Screen Shot 2565-11-11 at 13 48 17" src="https://user-images.githubusercontent.com/1591044/201280259-391d46ba-2a91-43e3-8d8a-46a9923921e1.png">
<img width="410" alt="Screen Shot 2565-11-11 at 13 47 51" src="https://user-images.githubusercontent.com/1591044/201280203-c2036e57-8e65-434a-8d65-273dcdf18219.png">
<img width="397" alt="Screen Shot 2565-11-11 at 13 48 04" src="https://user-images.githubusercontent.com/1591044/201280228-9615148a-da02-42df-b6ad-a398b3a08f96.png">

**Meilisearch version:**
[v0.30.0rc1](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc1)

**Comment by Kerollmops** [comment] 2022-11-11 09:16
Hey @Arsapol,

Would it be possible to have access to you dataset? This kind of issue is likely due to long words, it shouldn't happen!

You can send us a subset of your dataset that reproduces the issue if you are not thrilled to send the full one. You can send it to kero@meilisearch.com.

Thank you again for the bug report.

**Comment by Arsapol** [comment] 2022-11-12 07:48
> Hey @Arsapol,
> 
> Would it be possible to have access to you dataset? This kind of issue is likely due to long words, it shouldn't happen!
> 
> You can send us a subset of your dataset that reproduces the issue if you are not thrilled to send the full one. You can send it to [kero@meilisearch.com](mailto:kero@meilisearch.com).
> 
> Thank you again for the bug report.

Hi @Kerollmops 
I've just sent you some of my dataset to your email.

**Comment by Kerollmops** [comment] 2022-11-12 11:15
I can't reproduce the issue by just sending this subset of your dataset. Have you changed the settings? Can you provide a minimal reproducible example?

**Comment by Arsapol** [comment] 2022-11-12 16:39
**Step to reproduce**
1. Create index named "orders" with partition key named "orderId"
2. Setting index with this setting below
```json 
{
    "filterableAttributes": [
        "company",
        "status",
        "transferStatus",
        "paymentStatus",
        "branchId",
        "type",
        "phoneNumber",
        "products",
        "source",
        "updatedTimestamp",
        "timestamp",
        "netAmount",
        "saleChannel",
        "source",
        "orderNumber",
        "isStore",
        "recipient",
        "discounts",
        "customerId",
        "sellerId"
    ],
    "sortableAttributes": [
        "timestamp",
        "saleChannel",
        "paymentMethod",
        "netAmount",
        "transferStatus",
        "paymentStatus"
    ],
    "pagination": {
        "maxTotalHits": 200000
    },
    "faceting": {
        "maxValuesPerFacet": 500000
    },
    "rankingRules": [
        "sort",
        "typo",
        "exactness",
        "attribute",
        "words",
        "proximity"
    ]
}
```
3. Upload my datasets

**Comment by Kerollmops** [comment] 2022-11-12 16:55
I followed your guide to reproduce the issue and could not see any issues. I am on a MacBook Pro M1. The dataset you sent to my mailbox only contains 13 documents. Not sure if this is what you wanted to send.

**Comment by Arsapol** [comment] 2022-11-13 07:09
> I followed your guide to reproduce the issue and could not see any issues. I am on a MacBook Pro M1. The dataset you sent to my mailbox only contains 13 documents. Not sure if this is what you wanted to send.

@Kerollmops I've just sent you another of my datasets.

**Closed** 2022-11-17 16:51 UTC
Labels: bug, milli, v0.29.0
