### ISSUE TITLE
Can't filter on documents with double or/and simple quote

### ISSUE THREAD

**Issue by storm23** [meilisearch/meilisearch#2380] opened 2022-05-06 15:31 UTC
**Describe the bug**
Unable to find document containing an attribute value containing simple or/and double quotes from a filtered search.

**To Reproduce**
1. insert documents
POST /indexes/test/documents
```
[
    {
        "id": "test_1",
        "monitor_diagonal": "27' to 30'"
    },
    {
        "id": "test_2",
        "monitor_diagonal": "27\" to 30\""
    },
    {
        "id": "test_3",
        "monitor_diagonal": "27\" to 30'"
    }
]
```
2. Set filterable
POST /indexes/test/settings
```
{
    "filterableAttributes": [
        "monitor_diagonal"
    ]
}
```
3. Try to find document "test_3" 
POST /indexes/test/search
```
{
    "filter": [
        "monitor_diagonal = '27\" to 30\\''"
    ]
}
```
=> 0 hits

**Expected behavior**
Double escape : \\' and \\" needs to be interpreted has \' and \"

**Meilisearch version:** [e.g. v0.20.0]
v0.26.1

**Comment by oluademola** [comment] 2022-05-10 09:52
Hello @storm23 👋

Thank you for the thorough explanation,  I'm also able to reproduce the issue, which is most certainly a bug. I'll pass this along to our core team for review.

Thank you for bringing this to our attention 🙂

**Comment by curquiza** [comment] 2022-05-16 08:52
Thanks @oluademola and @storm23 for the report

@irevoire is this bug easy to fix, or is it complexe with our current "filter language"?

**Comment by curquiza** [comment] 2022-05-30 12:11
Checked directly with @irevoire, should be ok to fix this for v0.28.0, we'll keep you informed if we have any problem solving this

**Comment by curquiza** [comment] 2022-06-09 16:13
Reopening since it's not fixed on meilisearch side

**Closed** 2022-06-09 17:11 UTC
Labels: bug, milli

**Comment by mariopepe** [comment] 2023-03-09 17:35
It is still a bug!!!

**Comment by curquiza** [comment] 2023-03-09 18:39
Hello @mariopepe 
Can you open a new issue describing how to reproduce the bug you got?
