### ISSUE TITLE
Duplicate documents in the search route

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3021] opened 2022-11-02 13:58 UTC
The engine can return multiple versions of the same document (with the same document id). It should not be possible as a document with a specific document id must erase the previous version of itself. This bug appears in version v0.29.0 but not v0.28.1.

A strange coincidence is that [we released the soft-deleted feature in this exact version](https://github.com/meilisearch/milli/pull/557). Here is [a thread explaining the issue users have](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1665160818982859). We have private access to the settings one user was using when triggering this bug.

This bug could also show documents that had nothing in common with a user query. It was due to the fact that documents were wrongly deleted and, as ids are reused, associated to a completely different document.

---

EDIT by @curquiza 

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/): https://github.com/meilisearch/milli/pull/723
- [x] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by Kerollmops** [comment] 2022-11-08 13:29
This PR will be fixed by https://github.com/meilisearch/milli/pull/690.

**Comment by qbx2** [comment] 2022-11-10 01:19
Is it going to soft-delete duplicated documents when the fix applied?

**Comment by Kerollmops** [comment] 2022-11-10 09:08
Hey @qbx2,

There was a bug in our internal implementation of the soft-deletion system, this system must be invisible to the user, it is a system that speed-up the deletion and replacement of documents. A document must be replaced or updated when its document id matches one of the documents already in the database.

**Comment by curquiza** [comment] 2022-11-10 15:43
Closed by #3036

**Comment by thijndehaas** [comment] 2022-11-24 09:08
Should this also be fixed in Meilisearch [v0.30.0rc3](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc3) ?
We have a lot of duplicate documents now. I have made a back-up of the data.ms folder with all duplicate documents if that is needed.

**Comment by Kerollmops** [comment] 2022-11-24 09:14
Hey @thijndehaas,

Once you trigger the bug in a version of Meilisearch that is either v0.29.0 or v0.29.1 the _data.ms_ is corrupted and you will not be able to export your documents even by using a dump. The only way to "recover" from that is to reimport your records by hand from your primary database i.e. Postgres, MongoDB.

If you imported your documents in the correct way I describe and you see duplicated documents could you please describe the way you use Meilisearch and if possible provide a minimum reproducible example?

**Comment by thijndehaas** [comment] 2022-11-24 09:39
Yes I hoped maybe I could send the corrupted data.ms folder if it contains some useful data. I have not found yet how I can reproduce it. 

When we clear the data.ms folder we have script to index all items at once. Then we have some scripts that update items that have changed, that scripts run all day.

Yesterday when I did a full clean index everything was fine and today I have 38 duplicates on a page with 78 products (red has the same `id` earlier in the page):
![afbeelding](https://user-images.githubusercontent.com/18503351/203749117-881998a4-ab8c-4e4b-8eaf-e176305bfa53.png)

**Comment by curquiza** [comment] 2022-11-29 11:17
Hello @thijndehaas 
Can you try with [v0.30.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0) release we just published?

also, if you still have the issue, feel free to open a new issue with details information to reproduce the bug. The most important is we have the information (dataset, repository...) to reproduce the bug.
Thanks in advance for your help on this 🙏 this is really appreciated.

**Comment by Kerollmops** [comment] 2022-11-29 15:25
Reopening as this issue is always present, even in the latest release, v0.30.0. The only way it seems to reproduce is by replacing many documents i.e. 9000 tasks. Note that the _update or replace_ operation is internally removing and reindexing the documents. Therefore this issue can also be triggered with document deletion.

@thijndehaas sees duplicated documents with the same EAN, a typical issue we thought we fixed by closing this issue just before. You can see [the discussion on this Slack thread](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1669728210702369?thread_ts=1669285766.672869&cid=CP9DVS1RQ).

---

It can seem like an isolated case but [another user is experiencing the same issue](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1669732739110449?thread_ts=1669649241.451239&cid=CP9DVS1RQ). @0x15f doesn't report duplicated documents (maybe because he uses only the filtering features on this index), but he reports the _Missing key in the documents database_ error when sending documents deletion operations, a typical issue we thought we fixed by closing this issue just before. He is also experiencing _An unexpected crash that occurred when processing the task_ but doesn't have the logs, he will run again the v0.30.0 and try to provide the logs. We also know that he is running Meilisearch on an xfs file system.

This is the same user that is related to #3163, you can find a link to the corrupted data.ms file there.

**Comment by thijndehaas** [comment] 2022-11-29 16:08
> Therefore this issue can also be triggered with document deletion.

I think this should be 'Therefore this issue can also be triggered with document **additions**.'

I have successfully replaced the index with the swap function now and will check if it happens again.

Perhaps this can be reproduced by having multiple scripts push in large amounts of documents in batches at the same time, and then shuffle data inside a subarray of the documents to force updates.

**Comment by mmachatschek** [comment] 2022-11-30 08:26
Hi there,

I'm running into kind of the same issue.

We noticed, that meili was returning wrong search documents while doing a geo searches. (Vienna results popped up in london results). So we didn't have duplicate entires in the search, but completely different results to what was requested via filters on meilisearch.

I was using v0.29.1 updated to v0.29.2 and recreated the index (only updating didn't resolve the issue). The search documents are correct now, if we encounter any problems when doing document updates/additions/deletes and the search results seem odd, I'll keep you posted.

Some details on the index and meili (if relevant):

Version: v0.29.1 (where the issue popped up initially)
Special search functionality features in usage: distinct attribute, geosearch

**Comment by curquiza** [comment] 2022-12-05 15:05
Hello everyone

For people using v0.29.2, we have just released [v0.29.3](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.3) that might help you, if not, let us know.
v0.29.2 did NOT contain the bug fix for this bug, and we are sorry for the confusion.

For people using v0.30.0, we are still working on the bug fix. v0.30.1 will come in the week.

**Comment by thijndehaas** [comment] 2022-12-17 13:44
It took way longer as before and it is just in one of our websites but the problem seems to be back in 0.30.3 with a fresh installation/data.ms folder. I will update with more information. Was there a way to get more debug information about this problem?

**Comment by loiclec** [comment] 2022-12-19 09:40
@thijndehaas

**Comment by loiclec** [comment] 2022-12-19 09:54
@thijndehaas It is surprising, but evidently something went wrong once again 😞 Thank you again for reporting the bug. I will investigate it today with priority. There isn't a lot you can do to help debug the problem. However, I do have a few questions that could help me:

1. Can you confirm that you reimported the documents "from scratch"? (i.e. from an empty index and not using a dump, using the `POST /indexes/{index_uid}/documents` and `PUT /indexes/{index_uid}/documents` routes)
2. Did any `documentAdditionOrUpdate`, `settingsUpdate`, or `documentDeletion` task fail? If so, what were their error messages? Did any one of them cause a crash? Note that you can use the [`GET /tasks` route](https://docs.meilisearch.com/reference/api/tasks.html#get-tasks) to get this information.
3. What happens if you update or delete this document again? Some information that would interest me is: (1) the details of the task after completion, and (2) the new results of the search query.
4. Do you know whether the other fields of this document (`4-50252`) are correct?

**Comment by thijndehaas** [comment] 2022-12-19 10:29
1. I never dump the indexes, I have never looked into it because I can re-index all documents pretty fast after an update.
2. This time all 1.157 tasks have completed successfully.
3. When I found the duplicates I created a new index and swapped it. When I search in the old **(corrupt)** index the duplicates are gone now. I'm not sure how they are fixed. When indexes are swapped, are they re-created in the background or is some memory cleared?
4. The data in the documents seems correct compared to the current data.

A minute ago my colleague found another websites where the problem is back. I will try to debug the corrupt documents there before I swap all data.

**Comment by loiclec** [comment] 2022-12-19 15:48
@thijndehaas  Thank you for all the information 😄  We have reproduced and fixed the bug! (PR: https://github.com/meilisearch/milli/pull/750 ). My hope is that we can release meilisearch v0.30.5 with this fix within the next couple of days. We will keep you updated about the status of the release.

**Comment by irevoire** [comment] 2022-12-19 16:25
My hope is that it's the last time we reopen this issue :see_no_evil:

**Comment by curquiza** [comment] 2022-12-21 12:12
Fixed (definitely 🤞) by https://github.com/meilisearch/meilisearch/pull/3267. Will be integrated into v0.30.5 that will be released during the day

sorry again for the inconvenience

**Closed by curquiza** 2022-12-21 12:12 UTC
Labels: bug, milli
