### ISSUE TITLE
ARM Docker Image

### ISSUE THREAD

**Issue by HelloEdit** [meilisearch/MeiliSearch#536] opened 2020-03-20 16:25 UTC
it would be cool if Meili would work on my raspberry pi 3 and 4 (arm64).

**Comment by Kerollmops** [comment] 2020-03-23 08:56
Hey @HelloEdit,

I saw your messages on Crisp, thank you for your interest in the project. I also read that you wanted to take a little bit of your time to try cross-compile MeiliSearch to ARM, do you think you could make us a pull request when your are done?

I would prefer you cross-compile a raw binary instead of a Docker image containing the binary, this way it would be useful to everyone, bot only Docker users. We can make the Docker image pull the binary at startup, but if you don’t have time we will work on that later on.

**Comment by HelloEdit** [comment] 2020-03-24 19:05
I tried with xcargo to build a binary for the `aarch64-unknown-linux-gnu` platform. but I had a few mistakes and I'm not sure how to deal with them. Well, if you've got any leads, I'll take it!

**Comment by Kerollmops** [comment] 2020-03-25 11:47
I will probably look into the [run-on-architecture](https://github.com/marketplace/actions/run-on-architecture) Github Action tool today.

To make sure I don't make a mistake: Raspberry 4 runs on armv7 and Raspberry 3 runs on armv6, so it would be good to have both but armv6 only would be fine for both versions of the Raspberry?

**Comment by HelloEdit** [comment] 2020-03-25 14:33
If I don't make mistake, the Raspberry Pi 3 can runs on armv8 only if you have a 64bits OS. So it think armv8 is a good compromise.

**Comment by Kerollmops** [comment] 2020-03-25 15:48
> So it think armv8 is a good compromise.

I suppose you mean ARMv7. The problem is that I am not sure that MeiliSearch will work correctly on a 32bit arch, but I will try to provide a binary. I am already working on that in #540.

**Comment by HelloEdit** [comment] 2020-03-26 11:12
I just saw the sweater request! Thank you very much. Will a docker image be made available soon?

**Comment by Kerollmops** [comment] 2020-03-26 11:28
That is not planned but something you can do is to download the binary inside of your own Dockerfile by using [the installation script](https://docs.meilisearch.com/guides/introduction/quick_start_guide.html#download-and-launch) we made, in a preparation step. The current Dockerfile is compiling the engine itself.

**Comment by HelloEdit** [comment] 2020-03-26 12:00
Also, for the moment the installation script that you linked only work with amd64 and not with arm64. Are you planning to change that ?

**Comment by Kerollmops** [comment] 2020-03-27 10:11
I assigned someone that will work on this later on!
Thank you for pointing this. In the meantime you will be able to direct download the binary [from the release page](https://github.com/meilisearch/MeiliSearch/releases) on the next release.

**Comment by gnomeria** [comment] 2020-04-02 01:09
I think another usecase for the arm docker image is we could use it on AWS A1 instance (Graviton). This would provide a great cost-performance ratio for a company, especially after the distributed feature has been implemented.

A bit out of topic, can we have a more highlighted documentation and clarification on how MeiliSearch stores its indexes? In-Memory, or possibility for a persistance storage later on? Thanks

**Comment by Kerollmops** [comment] 2020-04-02 09:11
Hey @gnomeria, if I understand correctly AWS A1 instances uses a processor named Graviton which uses Neoverse cores which uses 64 bits addressing? As I read through [the Daniel Lemire blog post](https://lemire.me/blog/2019/12/11/amazons-new-arm-servers-graviton-2/) it seems like programs must be computed for ARMv8.1.

Does this makes sense or am I miss-understanding anything?

If I am right it means that I will need to compile MeiliSearch for ARMv8.1 and ARMv7, just want to be sure. We will also [make the installation script support ARM binaries](https://github.com/meilisearch/MeiliSearch/issues/536#issuecomment-604390302).

----

To answer your question, MeiliSearch stores its indexes on disk, [internally we use LMDB which is a memory mapped key-value store](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database), the one used in LDAP. We will add more information about that in the documentation, noted 😁

**Comment by gnomeria** [comment] 2020-04-03 04:03
Thanks for the clarifications @Kerollmops. Yes I think the general architecture would still be `aarch64` but for the ARMv8.1 or other next revisions, I think there's an added instruction set that can be leveraged. I mean compile it with v8.0 would be fine but in v8.1 there's an added `atomic add` IS:
`LDADDA    (Rarg0), Rtmp, Rout`
Still unsure what improvements would be made in the case of MeiliSearch. My guess it could improve the LMDB implementation.

**Comment by HelloEdit** [comment] 2020-04-10 16:10
Hi @Kerollmops, is it normal that the arm64 build is not available for the latest version?

**Comment by Kerollmops** [comment] 2020-04-10 16:14
@HelloEdit,

There currently is a problem in the build that just ended, [the ARMv8 build can't be uploaded due to an invalid credential](https://github.com/meilisearch/MeiliSearch/runs/576949782).

I don't understand why as it worked for the two other builds (linux and osx).

**Comment by HelloEdit** [comment] 2020-04-10 16:22
It's really weird indeed. Maybe Github support?In any case there is no hurry, thank you for your work ^^

**Comment by HelloEdit** [comment] 2020-04-10 19:57
Really odd indeed. if you find out where the problem is coming from, i would love to listen.
![Screenshot_20200410-215630__01](https://user-images.githubusercontent.com/25421857/79019250-3e4fdc80-7b76-11ea-8dba-0e8ce91aff36.jpg)

**Comment by Kerollmops** [comment] 2020-04-10 20:50
Yeah, the simple explanation that I found is the fact that [the `GITHUB_TOKEN` expires after 1h](https://github.community/t5/GitHub-Actions/error-Bad-credentials/m-p/37721#M3057).
The CI for the ARMv8 and ARMv7 takes more than 1h, therefore it is recommended to use a personnal access token.

I have a token from my personal account and re-run the latest release on another tag to trigger the binaries compile and publish script, copy the ARMv8 binary and moved it to [the assets of the official v0.10](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.10), therefore you will be able to get it.

During the next week we will update the installation script to support ARM architectures.

Note that the ARMv7 doesn't compile due to some 32bit known limitations, I don't think I will look more into that.

**Comment by HelloEdit** [comment] 2020-04-28 15:22
@Kerollmops Hello, I would like to inform you that the armv8 build has not been put on the v0.10.1 release page.

**Comment by Kerollmops** [comment] 2020-04-28 15:24
The build is [always running on the CI](https://github.com/meilisearch/MeiliSearch/runs/626314820) and will eventually be available on the v0.10.1 release.

This is a Docker image and you know, Docker is not the fastest interface :)

**Comment by ikaruswill** [comment] 2020-06-14 08:52
Hmm when running on ARMv8, I'm getting some weirdness.
```bash
/ # ./meilisearch
sh: ./meilisearch: not found
```
The file definitely exists, I've confirmed with interactive mode. Anyone else getting this?

**Comment by HelloEdit** [comment] 2020-06-14 09:20
Hi @ikaruswill, I suppose that you have tried to create your container with Alpine Linux as a base image. I had the same problem as you and I solved it using a debian base image. I think the problem is that Meilisearch is compiled with libc and not with musl as Alpine wants.

Anyway, you can find Debian for arm64v8 here https://hub.docker.com/r/arm64v8/debian/ (take a look at the `slim` version if size matters for you).

**Comment by ikaruswill** [comment] 2020-06-14 11:19
Yes I did use Alpine Linux, I was attempting to stick as close as possible to the official Dockerfile so I merely swapped out the part which copies the binary from build step. 

Thanks for the tip @HelloEdit!

**Comment by Kerollmops** [comment] 2020-06-25 13:31
Closing this issue because it is kind of fixed, feel free to comment or open another issue.

**Closed by Kerollmops** 2020-06-25 13:31 UTC

**Comment by HelloEdit** [comment] 2020-07-06 20:45
My current Dockerfile for Meilisearch with arm64v8 (raspberry pi 3 with Arch) using debian

```dockerfile
FROM debian:stable-slim

WORKDIR /usr/local

RUN apt-get update && apt-get install --no-install-recommends -y \
    wget \
    ca-certificates

RUN wget --quiet -O meilisearch https://github.com/meilisearch/MeiliSearch/releases/download/v0.12.0/meilisearch-linux-armv8 \
    && chmod +x meilisearch

ENV MEILI_HTTP_ADDR 0.0.0.0:7700
EXPOSE 7700/tcp

CMD ./meilisearch
```
