### ISSUE TITLE
Snapshot file permission issues

### ISSUE THREAD

**Issue by Magorx15** [meilisearch/meilisearch#3507] opened 2023-02-17 09:10 UTC
**Describe the bug**
After creating a snapshot, data.ms.snapshot file has incorrect permissions, unable to interact with it without sudo or as root

**To Reproduce**
`docker run -e MEILI_SNAPSHOT_DIR="/snapshots" -e MEILI_SCHEDULE_SNAPSHOT=true -e MEILI_SNAPSHOT_INTERVAL_SEC=10 getmeili/meilisearch:v0.29.0`
The snapshot in /snapshots folder has correct permissions (see screenshots)

`docker run -e MEILI_SNAPSHOT_DIR="/snapshots" -e MEILI_SCHEDULE_SNAPSHOT=true -e MEILI_SNAPSHOT_INTERVAL_SEC=10 getmeili/meilisearch:v0.30.0`
The snapshot in /snapshots folder has incorrect permissions (see screenshots)

**Screenshots**
Using v0.29.0
![image](https://user-images.githubusercontent.com/118532529/219595612-64262ae8-df76-4e10-ab46-175e66ca5ba0.png)
Using v0.30.0-v1.0.0
![image](https://user-images.githubusercontent.com/118532529/219598028-3f7225bf-df43-4a86-8cd7-d3d4168ffd95.png)

**Meilisearch version:** v0.29.0, v0.30.0-v1.0.0

**Comment by oluademola** [comment] 2023-02-28 10:44
Hello @Magorx15. Thank you for informing us about this problem. Indeed the snapshot permission file changed from v0.30 upward. I'm not sure if this change was intended or not; however, I'd discuss it with the team and get back to you. I understand this might trigger permission issues, but I would like to know specifically how this change impacts you. Thanks again.

**Comment by Magorx15** [comment] 2023-02-28 11:24
We are trying to upload the snapshot to somewhere else (and therefore we need read permission) which obviously fails as it needs root user for that

**Comment by Magorx15** [comment] 2023-03-03 09:33
Any updates @oluademola?

**Comment by irevoire** [comment] 2023-03-06 13:52
Hey @Magorx15, yeah, this was definitely an issue on our side; it should be fixed for the next release!
Thanks for the report 💯

**Comment by curquiza** [comment] 2023-03-07 09:36
Fixed by #3561, will be released in v1.1.0-rc.1 by the end of the week or at the beginning of next week

**Closed by curquiza** 2023-03-07 09:36 UTC
Labels: bug
