### ISSUE TITLE
No space left on device except there is space left on device

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2765] opened 2022-09-09 12:11 UTC
Doubling down on @gmourier with #2764, when I try to index his dataset, I get a « no space left on device ».
Except that... There is space on the device.
I have ~120Go available, and when I monitor the disk usage of meilisearch, on multiple datasets I noticed it was always crashing around 10Go of index size used. (here, the dataset takes 2Go).
![image](https://user-images.githubusercontent.com/7032172/189346868-1ec6dd7e-12d1-49d8-af6c-76fbe45332cd.png)

I tried to run it with `--max-task-db-size 10000g --max-index-size 10000g` but it doesn't change anything.

**Comment by curquiza** [comment] 2022-09-12 09:24
Discussed with the team, not a bug on Meilisearch file, @irevoire needs to complete with the solution to fix this

**Comment by irevoire** [comment] 2022-09-12 13:54
Ah, but I don't know the solution; it's @Kerollmops that knows

**Comment by Kerollmops** [comment] 2022-09-27 08:59
Hey everyone!

This error is triggered in the indexation process when there is no more available disk space, it can be strange that this issue is triggered as there looks like there is available space, but the engine uses a lot of temporary file in the process. @irevoire is on a linux platform that uses another disk partition for the temporary files, and this partition was filled during the indexing process.

The first part of the solution would be to document this possible issue @meilisearch/docs-team in the FAQ, and the way to fix it is by either [redefining the temporary folder](https://en.wikipedia.org/wiki/TMPDIR) or increasing its size.

**Comment by curquiza** [comment] 2022-09-27 10:12
I close this issue then! Thanks @Kerollmops for the answer

**Closed by curquiza** 2022-09-27 10:12 UTC
Labels: support, impacts docs
