### ISSUE TITLE
non searchable field appears in _matchesInfo

### ISSUE THREAD

**Issue by Thearas** [meilisearch/MeiliSearch#1864] opened 2021-11-02 08:03 UTC
**Describe the bug**

I don't know if it's a bug or a feature. The field `tags` (see the index setting below) is in `filterableAttributes` but not in `searchableAttributes`, but it may appear in `_matchesInfo` in search result.

**To Reproduce**

Here is my index setting:
```json
{
    "searchableAttributes": ["summary"],
    "filterableAttributes": ["tags"]
}
```
and document:
```json
{
    "id": 1,
    "summary": "(*´▽｀)ノノ tag 化妆包",
    "tags": ["tag1", "tag2", "foo"]
}
```
Search with `curl  -X POST 'http://localhost:7700/indexes/mydoc/search'  -H 'Content-Type: application/json'  --data-binary '{ "q": "tag", "matches": true }' | jq`:
```json
{
  "_matchesInfo": {
    "summary": [
      {
        "length": 3,
        "start": 18
      }
    ],
    "tags": [
      {
        "length": 3,
        "start": 0
      },
      {
        "length": 3,
        "start": 0
      }
    ]
  },
  "summary": "(*´▽｀)ノノ tag 化妆包",
  "tags": [
    "tag1",
    "tag2",
    "foo"
  ]
}
```

But if I query with `foo`, it returns empty hits.

**Expected behavior**

I think a field should not appear in `_matchesInfo` if it's not in `searchableAttributes`.

**MeiliSearch version:** [e.g. v0.20.0]
`v0.23.1`

**Comment by curquiza** [comment] 2021-11-03 14:22
Hello @Thearas 

Thanks for your interest in the project :)
This is indeed an expected behavior. However I opened a feature request in the dedicated repository so that your point of view is also taken into account. See: https://github.com/meilisearch/product/discussions/296

Thanks again for your report, I close this issue since it's now on the product side :)

**Closed by curquiza** 2021-11-03 14:22 UTC
