### ISSUE TITLE
Words registered in Meilisearch Synonyms are automatically converted to Chinese (Simplified), so you can process them as Japanese.

### ISSUE THREAD

**Issue by hieunguyen5501** [meilisearch/meilisearch#3646] opened 2023-04-06 06:28 UTC
Words registered in Meilisearch Synonyms are automatically converted to Chinese (Simplified), so you can process them as Japanese.
Eg: 会計 => 会计

I use api update synonyms with body as:
{
    "アカウンティング": ["会計"]
}
When i call get synonyms api to see the result the words are converted to:
{
    "アカウンティング": [
        "会计"
    ]
}

I hope you can save the correct words registered in synonyms.

Screenshots:
![image](https://user-images.githubusercontent.com/58267996/230289512-49983824-e927-4fdd-9c14-935e403eb1f1.png)
![image](https://user-images.githubusercontent.com/58267996/230289716-cd11c091-dcda-43ec-959e-125b99d1ca38.png)

Meilisearch version: v0.29.3

**Comment by oluademola** [comment] 2023-04-06 15:36
Hello @hieunguyen5501. I believe this problem is related to this [issue](https://github.com/meilisearch/meilisearch/issues/2760). The reason for this is that meilisearch normalizes synonyms before storing them. This means that when you retrieve the synonym list, the normalized synonyms are displayed rather than the ones you originally sent. It should be fixed in the attached issue; however, there is currently no ETA for this. Hope this answers your question. Thanks.

**Comment by hieunguyen5501** [comment] 2023-04-10 02:28
> Hello @hieunguyen5501. I believe this problem is related to this [issue](https://github.com/meilisearch/meilisearch/issues/2760). The reason for this is that meilisearch normalizes synonyms before storing them. This means that when you retrieve the synonym list, the normalized synonyms are displayed rather than the ones you originally sent. It should be fixed in the attached issue; however, there is currently no ETA for this. Hope this answers your question. Thanks.

@oluademola Thanks for your reply, Would you give a timeframe to fix this?

**Comment by oluademola** [comment] 2023-04-11 14:15
Hello @hieunguyen5501, as I mentioned above, there is currently no ETA for this, but the team is well aware of this issue

**Comment by miiton** [comment] 2023-04-11 23:19
Hello @hieunguyen5501 @oluademola 

If the problem is that when you register a synonym, you "see" the normalized value when you look at the settings, then #2760 you presented is correct, but I think it is correct that the synonym is internally normalized.

If the problem is that Japanese Kanji characters are converted to simplified characters, which prevents searching, this is a known problem, so I suggest you try the image in #3588 to see if it solves the problem.

**Closed** 2023-04-13 14:38 UTC
Labels: support
