### ISSUE TITLE
Tenant token doesn't inherit all permissions from API key used to generate it

### ISSUE THREAD

**Issue by francisfontoura** [meilisearch/meilisearch#2554] opened 2022-06-27 16:28 UTC
**Describe the bug**
When I try to use a tenant token signed by an admin API key to "get indexes", for example, the operation fails as forbidden.

**To Reproduce**
1. Retrieve default admin API key from GET /keys
2. Generate tenant token from admin API key
3. Use tenant token as bearer token in GET /indexes

**Expected behavior**
Endpoint should list indexes.

**Screenshots**
```
(node:160531) UnhandledPromiseRejectionWarning: MeiliSearchApiError: The provided API key is invalid.
```

**Meilisearch version:** [e.g. v0.20.0]
v0.27.2

**Comment by oluademola** [comment] 2022-06-29 10:34
Hello @francisfontoura 

This is an invalid API key problem, so a few factors may be the cause. Did you use the correct master key when you launched your Meilisearch instance? or perhaps didn't set a master key at launch?  Please remember that your tenant tokens will become invalid if the master key changes. Also, can you confirm the tenant token is not expired?

Thank you

**Comment by curquiza** [comment] 2022-07-06 16:06
I close this issue then. Feel free to ask to re-open if needed 😊

**Closed by curquiza** 2022-07-06 16:06 UTC
Labels: support

**Comment by abubakir1997** [comment] 2023-09-27 00:54
Not sure what this means:
>  the tenant token can only give access to the search endpoints for now
I tried the generated token with every endpoint in the docs and gives access to nothing. 
Please work on this, we need something equivalent to what Algolia does with its `generateSecuredApiKey` method.

Do you recommend I use the search key in my client applications? I feel like it wouldn't be ideal to use the main search key provided on the client side.

What other secure alternatives are there to using search on the client side?

**Comment by curquiza** [comment] 2023-09-27 07:59
Hello @abubakir1997 

I think there is confusion here between access keys and tenant tokens. Tenant token are used if you want to let your final user access only a part of your Meilisearch data (for example only let the user search in their own emails, but your Meilisearch contains the mails of ALL the users inside)

I recommend you use the "Default search API key" instead of creating tenant token: this API key only accesses to the search endpoint, so it's secure. https://www.meilisearch.com/docs/learn/security/master_api_keys#using-default-api-keys-for-authorization
You are right, you should not let your client application use the main key. The "Default search API key" is the one you can use on client side.

You have more information about how to secure your Meilisearch instance [here](https://www.meilisearch.com/docs/learn/security/master_api_keys)

Also, if you need more support, I recommend going to [our Discord](https://discord.meilisearch.com/) and detailing the error message you get so that we can help you. Here, the risk is we miss your message lost at the middle of our bug reports.

Have a nice day and see you on Discord if needed 👋
