### ISSUE TITLE
CPU Usage Very High

### ISSUE THREAD

**Issue by pnegahdar** [meilisearch/meilisearch#2027] opened 2021-12-20 15:08 UTC
**Describe the bug**

The CPU of meilisearch holds near 100% when the dataset is a bit large.

I haven't really been able to correlate anything yet but this doesn't happen on my smaller instance of meilisearch that has less data. 

My current data.ms directory for the slow instance is `4.2gb`.  The one not having CPU spike issues (similar dataset) is only `150mb`

While I don't think it is relevant here, I'm running the amd64 version on ARM (using rosetta, intentionally)

**Expected behavior**
No CPU Spiking

**Screenshots**

![telegram-cloud-photo-size-1-5046315646719208161-y](https://user-images.githubusercontent.com/833067/146788108-96f4a640-4bef-4f65-a567-37eecb9907b6.jpg)

**MeiliSearch version:** 

0.24.0

**Additional context**
Macos, M1, Meili 0.24 amd64.

**Comment by pnegahdar** [comment] 2021-12-20 15:08
FYI I'm happy to help directly diagnose this issue with my setup/data. Ping me if I can help :)

**Comment by ChillFish8** [comment] 2021-12-26 12:39
Out of curiosity are you sure Meili has actually finished indexing all the documents?

Looking at the CPU time it seems it's not been running for too long and a lot of people get caught out with Meili's asynchronous updates/addition resulting in the request returning immediately but the indexing potentially taking hours or even longer.

If you only recently added the documents that are currently amounting to 4.2GB then there is probably a good chance that Meili is still indexing documents. So this might be something to check.

**Comment by pnegahdar** [comment] 2021-12-27 20:23
No I had just restarted it to make sure it was happening consistently. Meili is daemonized so most of of my usage of it is deeper in the lifecycle. Also if this line:

```
 document addition done: DocumentAdditionResult { nb_documents: 1 }
```

implies it is not indexing (I'm not sure why the 1 never hits 0, even in other setups), then I am sure this CPU spike is not indexing related. 

For what its worth, I mostly solved this again by reducing the the document sizes significantly and their json depth/complexities (not sure which matters). Now Im back in the few hundred mbs of data and the CPU isn't an issue again.

**Comment by jonhassall** [comment] 2022-01-01 19:55
I have a Meilisearch directory of 2.3GB with around 550,000 items. The source data for the items is about 200MB, just two tables.

I get fairly consistent CPU usage for days at a time using nearly 2 full cores from Meilisearch.

Is this normal? I would very much like to reduce this.

**Comment by Kerollmops** [comment] 2022-01-03 15:53
Hey @pnegahdar and @jonhassall,

MeiliSearch is known to be slow when indexing a lot of documents that were received in a lot of small updates, a lot of updates with not that many documents (sent one by one for example). I advise you [to look at the `/stats` route](https://docs.meilisearch.com/reference/api/stats.html#stats) of your index to make sure that the CPU spikes are not due to an indexation step.

Please make sure to send your documents in the biggest batches you can to avoid big CPU spikes like that but be sure that [we are currently working on auto-batching technics](https://github.com/meilisearch/MeiliSearch/pull/2005) (will probably be released in v0.26). This feature will help speed up the indexing phase and reduce the number of CPU spikes you will see when sending a lot of documents.

**Comment by pnegahdar** [comment] 2022-01-03 16:37
> MeiliSearch is known to be slow when indexing a lot of documents

This is almost certainly not the case. The CPU spikes continue to exist after indexing completes. Unless the process is continually indexing? 

While my problem is solved for now, I would urge you to explore this beyond the "it's indexing" answer. I'd look into any stray routines/loops/etc that are causing issues, it definitely feels like a hot loop that isn't stopping _after_ indexing -- happy to drop some debuggers at some point to verify.

**Comment by Kerollmops** [comment] 2022-01-03 16:42
> This is almost certainly not the case. The CPU spikes continue to exist after indexing completes. Unless the process is continually indexing?
> 
> While my problem is solved for now, I would urge you to explore this beyond the "it's indexing" answer. I'd look into any stray routines/loops/etc that are causing issues, it definitely feels like a hot loop that isn't stopping _after_ indexing -- happy to drop some debuggers at some point to verify.

Ok, so have you tried to reboot MeiliSearch and look at the CPU usage, it could maybe be related to a (very) long-running search request. But that kind of issue will likely exist on a big index, with a lot of documents. How many documents do you have already indexed in the engine? You can find this information on the `/{index}/stats` route.

**Comment by raharrison** [comment] 2022-01-25 13:01
I'm also observing surprisingly high CPU usage even when the Meilisearch instance is brand new, isn't being used and has no indexed documents yet. Sometimes upwards of 5% usage when all I've done is start instance (tried docker and directly running the binary).

Is this expected? Anyone else notice this? Seems there must be a runaway process running in the background constantly?

**Comment by Kerollmops** [comment] 2022-01-25 14:40
Hey @raharrison,

That's not something normal and we never heard about this issue before. Are you sure this is meilisearch that is consuming CPU? The only thing that meilisearch does when starting is to create a database on disk using LMDB and wait for HTTP requests to come. Nothing more.

**Comment by raharrison** [comment] 2022-01-25 19:22
Yes definitely meilisearch, some screenshots below both from Docker stats + htop. Instance has just been started, no documents indexed, yet it's still constant 3-5% cpu usage. This is a very slim VM (1 vCPU), but I still wouldn't expect this much considering nothing should really be happening at all. Even tried with a completely new image (Ubuntu 20.04.3 LTS), this is the behaviour even when nothing else is running on the system at all. Using latest docker image (5e572cd963e9), haven't observed the same when using Windows though interestingly.

![image](https://user-images.githubusercontent.com/2327200/151044577-c9122dc4-353d-49dc-a40c-255936205e64.png)

![image](https://user-images.githubusercontent.com/2327200/151044595-c815e141-a4aa-4437-8bd1-f011c140a960.png)

**Comment by Kerollmops** [comment] 2022-01-26 16:10
@MarinPostma, do you have any idea about what could cause this? Can the update queue or anything in the engine do polling or else?

@irevoire do you think that could be the analytics? But we send them only once per hour, so... can't be that.

**Comment by irevoire** [comment] 2022-01-26 16:22
I highly doubt it has anything to do with the analytics, but you could try with the `--no-analytics` flag to see if it changes something :thinking:

**Comment by raharrison** [comment] 2022-01-26 16:27
Same results even with analytics disabled. Just tried on a completely different and beefier machine and seeing similar things:

![image](https://user-images.githubusercontent.com/2327200/151204041-5a37e218-262a-4846-a253-772efe485af3.png)

**Comment by raharrison** [comment] 2022-01-26 16:33
Does look like a regression though, just tried v0.24.0 and things are looking a lot better:

![image](https://user-images.githubusercontent.com/2327200/151205270-1ebf0fbe-fe36-4096-9151-17968e011133.png)

**Comment by MarinPostma** [comment] 2022-01-26 17:43
> Does look like a regression though, just tried v0.24.0 and things are looking a lot better. Change appeared in v0.25.0:
> 
> ![image](https://user-images.githubusercontent.com/2327200/151205270-1ebf0fbe-fe36-4096-9151-17968e011133.png)
> 

Could be the scheduler then, let me take a look at that

**Comment by curquiza** [comment] 2022-02-10 15:10
Hello @pnegahdar!

We did not succeed to reproduce your issue.
We need more steps and context to try to reproduce it, like the number of documents @Kerollmops asked [here](https://github.com/meilisearch/meilisearch/issues/2027#issuecomment-1004215998) 🙂

**Closed** 2022-05-04 15:19 UTC
Labels: bug, needs more info, performance

**Comment by liesislukas** [comment] 2023-04-16 10:58
I have similar issue even running on very powerful machine. 32 CPUs, only 1 100% constantly and 31 almost idle, full details here: https://github.com/meilisearch/meilisearch/discussions/3680 :/
