### ISSUE TITLE
Meilisearch tasks stuck after upgrade on GCP

### ISSUE THREAD

**Issue by samcfinan** [meilisearch/meilisearch#4197] opened 2023-11-07 22:34 UTC
I used the upgrade script (https://github.com/meilisearch/meilisearch-migration) to update a Meilisearch instance running on GCP from 1.0.1 to 1.4.2. This issue is currently being [treated on Discord](https://discord.com/channels/1006923006964154428/1171553466880106547).

For context, since it's running as a systemctl service, I ran the upgrade as root.

The upgrade succeeded, however tasks appear to be enqueued forever. The database size is at ~30% of disk space and the instance has plenty of memory.

```
{
            "uid": 2365924,
            "indexUid": "wines",
            "status": "enqueued",
            "type": "documentAdditionOrUpdate",
            "canceledBy": null,
            "details": {
                "receivedDocuments": 1,
                "indexedDocuments": null
            },
            "error": null,
            "duration": null,
            "enqueuedAt": "2023-11-07T19:36:16.119546869Z",
            "startedAt": null,
            "finishedAt": null
        }
```

**Comment by dureuill** [comment] 2023-11-08 08:31
Hello @samcfinan :wave:

I'm sorry this is happening to you!
We don't have any known issue with tasks being enqueued indefinitely, however, it is possible that a task remains enqueued for a long time if other tasks are being processed first. When this happens, it might be a bit hard to find out which tasks are being processed. Here's a relevant issue:  https://github.com/meilisearch/meilisearch/issues/3886

To make sure it is not what happens, could you check the output of the following requests:

1. `curl 'http://localhost:7700/tasks?limit=1&statuses=processing` are there any tasks processing?
2. `curl 'http://localhost:7700/tasks?limit=1&statuses=succeeded` what is the succeeded task with the highest id? Does that change regularly?
3. If (2) always answers the same task, it is possible that this task was handled in priority, and tasks with higher ids are being processed (quickly, so they don't appear in `processing`). In that case, fetch the date displayed in the `EnqueuedAt` field of the task returned in (2), let's say it is `2023-11-08T18:23:16.0Z` or something, and perform the following query: `curl 'http://localhost:7700/tasks?limit=1&statuses=succeeded&beforeEnqueuedAt=2023-11-08T18:23:16.0Z`. Does this query return a different task? If so, does the returned task change regularly? If so, it means these tasks with a lower task id are being processed.

I hope this will help troubleshoot your issue 😊

**Comment by samcfinan** [comment] 2023-11-08 13:28
Hi @dureuill , thanks for the reply:

The task with the highest ID that has succeeded is:

```
        {
            "uid": 2368625,
            "indexUid": "profiles",
            "status": "succeeded",
            "type": "documentAdditionOrUpdate",
            "canceledBy": null,
            "details": {
                "receivedDocuments": 1,
                "indexedDocuments": 1
            },
            "error": null,
            "duration": "PT0.202497143S",
            "enqueuedAt": "2023-11-08T12:55:32.233712623Z",
            "startedAt": "2023-11-08T12:55:32.236644614Z",
            "finishedAt": "2023-11-08T12:55:32.439141757Z"
        },
        ```
        There are no tasks that are processing.
        
        It appears that tasks on the `profiles` index consistently succeed in a short period of time. `profiles` has infrequent writes compared to other indexes. Tasks on all other indexes are indefinitely enqueued.

**Comment by dureuill** [comment] 2023-11-08 15:55
Does `curl 'http://localhost:7700/tasks?limit=1&statuses=succeeded&beforeEnqueuedAt=2023-11-08T12:55:32.233712623Z` consistently return the same task?

> There are no tasks that are processing.

It can happen that no task are indicated as processing, but that some got processed anyway.

**Comment by samcfinan** [comment] 2023-11-08 16:28
> Does `curl 'http://localhost:7700/tasks?limit=1&statuses=succeeded&beforeEnqueuedAt=2023-11-08T12:55:32.233712623Z` consistently return the same task?

The `profiles` index will process tasks. Only 1 task is submitted every few minutes (on new user creation). Those tasks are processed nearly immediately. The `wines` index has thousands of tasks in its queue that are not being processed.

**Comment by dureuill** [comment] 2023-11-09 08:36
Hello again, 

If possible, I would be interested in trying to reproduce the issue. Do you think you could provide me with a temporary access to the involved machine, or with a dump that reproduces the issue?

A minimal reproducer would be even better, but I understand it might be difficult to come up with.

Feel free to DM me on Discord.

**Comment by curquiza** [comment] 2024-01-03 17:17
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-01-03 17:17 UTC
Labels: needs more info, support, indexing
