### ISSUE TITLE
Meili gets stuck when indexing requests overwhelm it

### ISSUE THREAD

**Issue by nikita2206** [meilisearch/MeiliSearch#522] opened 2020-03-12 17:19 UTC
When sending indexing requests (`POST /indexes/{index}/documents` or PUT) too often it can result in Meili freezing and not responding to any requests at all. 
I am running it inside docker container, from my experience it starts from 28 RPS in single-thread, at that point it stops responding to any requests (clients are able to TCP-connect but after sending the request, the response never comes back).

**Comment by nikita2206** [comment] 2020-03-12 17:21
I've also tried to implement backpressure:
 - there were 10 threads running each adding new documents (single document per request)
 - after adding a document it would poll the `/indexes/{index}/updates/{updateId}` endpoint to make sure it was processed
This had the same problem

**Comment by nikita2206** [comment] 2020-03-13 07:35
Seems to be fixed on 0.8.5-rc.3

**Comment by qdequele** [comment] 2020-03-13 09:26
Hi @nikita2206. Indeed, the problem has been fixed in version 0.8.5-rc.3 and will also be fixed in release 0.9.0 which will be released very soon. The code is finished, we finish the documentation and sdk before making an official release.

**Comment by Kerollmops** [comment] 2020-03-13 10:21
For your information the fixes have been made in #439 and #340. This bug was related to the fact that LMDB, the key-value store MeiliSearch is using internlly, is ACID and fully serialized (which means that it accepts only one write transaction at the same time) and that is the problem: When the engine receive a new update, it could be already working on an update and cannot open another write transaction, therefore to fix that we split the database in two, one for the list of updates to process and another which contains the engine structures to make the engine work. This way, the engine is able to accept user updates **and** process update at the same time without blocking the user request.

**Comment by nikita2206** [comment] 2020-03-14 09:13
Very informative, thanks! Just saying to add some feedback:
I was evaluating Meili as a search engine for the platform that’s already-running in prod and the way search works is great and how fast and small-footprint it is. Unfortunately I had to choose not in favor of meili because there’s no support for languages other than English, oh also it was a bit of a struggle trying to find out what’s wrong when for some update batches I’d get `wrong data` (I think, I don’t remember exactly) response, had to split my batch in half multiple times until I found the offending but that contained letter `å`

**Comment by Kerollmops** [comment] 2020-03-14 10:36
Hum... very interresting, would it be possible to have a subset of your dataset, to help us analyse the bug?

We are aiming to support the maximum languages and please the most wide set of people, It would be very helpful to have data that you would like to see supported by the engine. Did you tried with the v0.8.5-rc.3 too? Is this error still present in this version?

Thank you for your help and great feedback! That's very helpful :)

**Comment by nikita2206** [comment] 2020-03-14 14:10
@Kerollmops oh I see now that it supports all latin languages which could work for us! So I've just got in front of a computer and the letter that caused the issue was actually `ñ` as in `Castaño`. Seems like that should be reproducible easily, if it's not then I can send you a subset of data in private. Thank you for prompt responses!

**Comment by Kerollmops** [comment] 2020-03-24 13:40
Hey @nikita2206,

We tried to reproduce the but in intern and it doesn't seem we are able to find the bug, indexing a document which contains the `ñ` character.

Would it be possible that you share a subset of your dataset, please? You can use [Firefox send](https://send.firefox.com/) and send the link to our email address bonjour@meilisearch.com.

**Comment by nikita2206** [comment] 2020-05-22 14:28
Oh, I didn't notice your comment! Hopefully will have some time to test it again in the near few days, chances are I won't experience that issue this time

**Comment by MarinPostma** [comment] 2020-06-24 14:48
We can't reproduce, and the topic seems dead, so i'm closing. Feel free to reopen if you encounter this problem again

**Closed by MarinPostma** 2020-06-24 14:48 UTC
Labels: bug, need-repro

**Comment by JoshGlazebrook** [comment] 2020-07-06 01:47
I've been implementing Meilisearch in one of my projects. About 250k total documents in the index. Originally I was going to do a full sync index, and then anytime an underlying data item is updated in my database, I would then trigger a single document update, but this ended up with 50k+ pending updates and it wasn't ever going to keep up + locking up.

I've switched to doing a full sync initially, and then batch updating anything updated in the last 30 minutes in one update to try and get around this.

Is this expected? I was hoping to have "streaming" updates, but it doesn't seem to be possible.

**Comment by codenoid** [comment] 2025-05-26 05:01
my indexes size is now growing after waiting for hours (growing to about 107GB)

but it seems starting to stuck because my RAM usage is 26.5/29.2GB

if it was elasticsearch, it would be still fine importing all of the documents

do I need to tune something?
