### ISSUE TITLE
Internal error: task 669380 panicked

### ISSUE THREAD

**Issue by yyao19** [meilisearch/meilisearch#4210] opened 2023-11-14 15:58 UTC
When I use meili search, got an return back of   
`{
    "message": "task 669380 panicked",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
}`.

What is the type of error, anyone has ideas?

**Comment by dureuill** [comment] 2023-11-20 08:25
Thank you for your report, @yyao19, and apologies for the belated answer.

The type of error you're getting is indicative of a code defect in the software, so I'm truly sorry you're encountering this issue!

To understand better the scope of the issue and hopefully address it, we need more information:
1. After which action was the error response returned?
2. What is the configuration of Meilisearch?
3. If you have access to the standard error output of Meilisearch, can you provide us with the panic message associated with the error? Panic messages typically contain the string: `panicked at`.

Thank you for opening this report and for any answer!

**Comment by curquiza** [comment] 2023-12-15 11:39
We close this because this is unfortunatelly impossible to reproduce, but we definitely consider this as a bug.
If someone has more information about this, please open a new issue with more details about this 🙏

**Closed by curquiza** 2023-12-15 11:39 UTC
Labels: bug, needs more info
