### ISSUE TITLE
Production Installation Instructions Result in Error 

### ISSUE THREAD

**Issue by hiven** [meilisearch/meilisearch#3556] opened 2023-03-02 16:50 UTC
**Describe the bug**
The production installation instructions result in an error. When followed exactly they product an error which stops the service starting. 
https://docs.meilisearch.com/learn/cookbooks/running_production.html#step-4-run-meilisearch-as-a-service

**To Reproduce**
Follow the steps exactly as required on Debian 10 or Debian 11

**Expected behavior**
In step 4.2 you should see:
```
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-10 14:27:49 UTC; 1min 8s ago
 Main PID: 14960 (meilisearch)
```

**What you actually see:**
systemd[1]: Started Meilisearch.
systemd[2834]: meilisearch.service: Failed to execute command: Permission denied
systemd[2834]: meilisearch.service: Failed at step EXEC spawning /usr/local/bin/meilise
systemd[1]: meilisearch.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: meilisearch.service: Failed with result 'exit-code'.

**Meilisearch version:** Latest Version

**Comment by hiven** [comment] 2023-03-03 11:32
After tinkering around, running this additional command (not included in your tutorial) seems to fix things. Is this right to include this?

sudo chmod +x /usr/local/bin/meilisearch

**Comment by Magorx15** [comment] 2023-03-03 12:38
https://docs.meilisearch.com/learn/update_and_migration/updating.html#install-the-desired-version-of-meilisearch

But indeed this could be somewhere in the tutorial as well

**Comment by oluademola** [comment] 2023-03-09 08:59
Hello @hiven 

Ideally, the installation method you mentioned above (curl -L https://install.meilisearch.com | sh) should download the meilisearch binary as an executable. I have tried this on ubuntu, and I do not need to run chmod +x meilisearch to make it executable. However, I agree that if for some reason, meilisearch is not downloaded as an executable, we could mention running the chmod +x command. I'd try to reproduce it with a Debian machine as well. 

Thanks for the report.

**Comment by curquiza** [comment] 2023-04-11 09:59
> I'd try to reproduce it with a Debian machine as well.

@oluademola can you please let us know if it works on Debian or not?

**Comment by oluademola** [comment] 2023-04-11 11:40
Hello @curquiza. No, I could not reproduce the problem, and following the guide works for me. However, I reckon users might experience this error when directly downloading meilisearch, let's say, for example, from the Github repo, which will require running `chmod +x meilisearch` command to allow executable permission, and the linked issue should solve the problem.

**Comment by curquiza** [comment] 2023-04-11 11:58
Thank you @oluademola for the precision

I close this issue then since nothing can be done more on the engine side. Let me know if I'm wrong

**Closed by curquiza** 2023-04-11 11:58 UTC
Labels: support

**Comment by warmwhisky** [comment] 2024-07-20 10:58
Just to add, I had this issue installing on Rocky Linux. I firstly followed the quick start guide https://www.meilisearch.com/docs/learn/getting_started/quick_start
And then https://www.meilisearch.com/docs/guides/deployment/running_production to run as a service in production.

After running `sudo chmod +x /usr/local/bin/meilisearch` all was well and running
