### ISSUE TITLE
No commitSha on /version when running MeiliSearch from Docker

### ISSUE THREAD

**Issue by eskombro** [meilisearch/MeiliSearch#712] opened 2020-05-26 13:03 UTC
When running MeiliSearch from Docker, the route `/version` returns a `comitSha` value as `UNKNOWN`

**how to reproduce**

`docker run -it -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true`

`curl http://localhost:7700/version `

RESPONSE:

```
{"commitSha":"UNKNOWN","buildDate":"2020-04-28T14:24:40.454854787+00:00","pkgVersion":"0.10.1"}
```

**Comment by MarinPostma** [comment] 2020-05-28 08:41
We spent some time investigating this with @eskombro  yesterday, and could not come up with a reasonable solution. The trick would be to copy the `.git` folder over in the wordir used by docker to build the binary, as vergen, the dependency we use to retrieve this info, looks at .git/HEAD. A nicer solution IMO would be for the production container to use github release binary instead of the one built in the current recipe

**Comment by Kerollmops** [comment] 2020-05-28 08:52
Yes, the problem is due to the `.git` folder not being accessible by the vergen dependency.
As you said we can either copy the `.git/HEAD` file to the docker build container.

Using the github release binary inside of the docker container will probably be harder to do because both, the docker and the binaries are currently built at the same time, and therefore the docker image will not be able to access the binaries. I think with Github Action we could specify that a certain build must run after another one, we should look into that.

If we do so we will have to create two GA pipelines, one for the common PRs and one for the releases.

**Comment by MarinPostma** [comment] 2020-05-28 09:07
> If we do so we will have to create two GA pipelines, one for the common PRs and one for the releases.

that seems like a reasonable solution

Also build time for the container is up to 15min (we checked yesterday with @eskombro), it may not be desirable when you only want to run the container right away

**Comment by vladdy** [comment] 2021-01-06 04:25
Can I try to work on this one? Probably I could try to address #837 at the same time.

**Comment by curquiza** [comment] 2021-03-31 21:34
I would rather not close issues in MeiliSearch since the v0.21.0 is not out 🙂

**Comment by curquiza** [comment] 2021-06-30 17:18
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421

**Closed** 2021-06-30 17:18 UTC
Labels: v0.21:fixed
