### ISSUE TITLE
Heed error: Function not implemented (os error 38)

### ISSUE THREAD

**Issue by chaskett** [meilisearch/MeiliSearch#1195] opened 2021-01-19 09:42 UTC
**Describe the bug**
Running the container fails due to 'heed error'. Changing version doesn't seem to make a difference. Perhaps related to underlying Rust function?

**To Reproduce**
Steps to reproduce the behaviour:
1. docker-compose.yml contains...
```
  search:
    image: getmeili/meilisearch:v0.18.1
    restart: always
    volumes:
      - ./data.ms:/data.ms
    ports:
      - 7700:7700
```
2. docker-compose up
In container log you will see... 
`Error: heed error; Function not implemented (os error 38)`
Have tested with image 0.13.0, 0.16.0, 0.17.0, and 0.18.1.  Using version 0.12.0 you will see a different error.

**Expected behavior**

**Desktop (please complete the following information):**
Docker Desktop, also reproducible on Google Cloud, Cloud Compute, VM Instance.

**Comment by MarinPostma** [comment] 2021-01-19 12:26
Hello @chaskett,
This is an os realtors error, can you provide me with more info about your environment?

**Comment by chaskett** [comment] 2021-01-20 04:46
Ah! I was not aware, then that could be the reason. 

I'm running the container on MacOS 11 with the new Apple silicon, and using Docker Preview 7.  I had mistakenly thought that this was an issue in the container.

**Comment by benbender** [comment] 2021-01-25 14:45
@MarinPostma same problem here. Latest docker-image on m1 apple silicon with latest docker desktop preview for m1.

**Comment by chaskett** [comment] 2021-01-27 09:19
@benbender @MarinPostma this my experience also. I'll let you know if I manage to make any progress. 

The only thing I could figure out is using v0.12 the error complaining about its ability to connect to the database - heed error related to Rust and a function to 'unwind'.

**Comment by MarinPostma** [comment] 2021-01-27 09:31
The error seems to come from docker on apple M1: we're getting a os error for an unimplemented says all. I don't have an apple silicon at hand, so it is almost impossible for me tu debug this... What's the state of virtualization on the M1? Any way to run Debian or ubuntu in a virtualized environment?

**Comment by benbender** [comment] 2021-01-29 12:39
@MarinPostma Docker runs fine in technical preview. The images however must be build as multiarch. For reference: https://bee42.com/de/blog/tutorials/dockerized-the-apple-silicon/

Meilisearch itself runs fine via homebrew on apple silicon: https://formulae.brew.sh/formula/meilisearch

**Comment by nubpro** [comment] 2021-02-15 07:33
Using the M1, facing the same error when spinning the docker container

**Comment by fharper** [comment] 2021-03-03 17:08
Got the same error myself.

**Comment by deanomus** [comment] 2021-03-22 08:51
I have the same error, any solution?

**Comment by MarinPostma** [comment] 2021-03-22 08:59
I have investigated a bit, and it seems that docker uses qemu to emulate x86 architecture on the m1. This may be the cause of the issue, and there isn't much we can do to directly address this issue.

Here are 3 workarounds:
- Run MeiliSearch without docker: rosetta seems to run meilisearch alright.
- Run a native image of MeiliSearch (compile it from source on the m1)
- Build you own docker image, with a native image of meiisearch (I think that running docker build in the meilisearch repo on your m1 should do the trick)

**Comment by Sarfarazsajjad** [comment] 2021-04-04 13:41
have someone tried creating their own version of docker image, it would be great if someone can share a working version.

**Comment by alallema** [comment] 2021-04-12 10:31
As Marin pointed out, the macos-amd64 binary works on M1, thanks to Rosetta.
But to make it work on a docker image, you have to use the linux-armv8 binary.
This is my Dockerfile for Meilisearch with arm64v8 for Apple M1 using ubuntu.
```
FROM ubuntu

WORKDIR /meilisearch

RUN apt-get update
RUN apt-get install -y\
	libc6-dev\
	wget

RUN wget --quiet -O meilisearch https://github.com/meilisearch/MeiliSearch/releases/download/v0.20.0/meilisearch-linux-armv8 \
	&& chmod +x meilisearch

ENV MEILI_HTTP_ADDR=0.0.0.0:7700
EXPOSE 7700/tcp

CMD ["/bin/sh", "-c", "./meilisearch"]
```
`docker build -t meilisearch_m1 .`
`docker run -it --rm -p 7700:7700 meilisearch_m1`

There is another solution [here](https://github.com/meilisearch/MeiliSearch/issues/536#issuecomment-654456224), it's for RapsberryPi, but It should work on M1 too.

**Comment by MarinPostma** [comment] 2021-04-12 13:05
thanks @alallema for providing a working solution! :)

I am closing this issue.

**Closed by MarinPostma** 2021-04-12 13:05 UTC
Labels: type:bug

**Comment by robsontenorio** [comment] 2021-05-24 14:57
@MarinPostma  would be nice to release on docker hub a build for m1 arm64.

**Comment by MarinPostma** [comment] 2021-05-24 16:35
@robjtede I agree, we first need to find a reliable way to build the artifacts on the CI for the M1, which I am not exactly sure how to do. We don't have much time to focus on that, so some guidance on how to do will definitely help us do that faster.

My main question is if it is possible to cross-compile meilisearch from the M1 from a x86 mac, it this is possible, we may be able tot do it directly from GHA.

**Comment by MarinPostma** [comment] 2021-05-24 18:36
@robjtede sorry wrong rob 😅

**Comment by fr3fou** [comment] 2021-06-17 16:00
Any news on the ARM docker image?

**Comment by curquiza** [comment] 2021-06-20 17:06
Hello @fr3fou, not a priority for the moment, sorry, we are working on other more emergency tasks 🙂

**Comment by sepisoltani** [comment] 2021-09-27 21:46
Is there any new docker image available for apple M1 chip ?

**Comment by curquiza** [comment] 2021-09-27 22:03
This related issue is here: https://github.com/meilisearch/MeiliSearch/issues/1290 🙂
A user provides an ARM image, see this comment: https://github.com/meilisearch/MeiliSearch/issues/1347#issuecomment-913358145

**Comment by curquiza** [comment] 2021-11-11 14:25
Hello @jaydrogers 

sorry for the delay
I don't understand why it works with MySQL since they do not seem to provide an arm image for docker: https://hub.docker.com/_/mysql
Pretty sure I miss something!
Thanks for your help

**Comment by jaydrogers** [comment] 2021-11-11 14:34
> I don't understand why it works with MySQL since they do not seem to provide an arm image for docker

This is because setting `platform: linux/x86_64` for MySQL allows it to be emulated. 

### Moving forward
Maybe a contributor from Melisearch could guide us in a better direction here (possibly @MarinPostma)?

Should we create a new issue for this so we're not tracking something on a closed issue?

Someone with repository & docker image access will need to make the image "multi-arch": https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

Let me know if you need any testing, etc. Would gladly offer any assistance to help the project. Thanks for your help! 🙌

**Comment by curquiza** [comment] 2021-11-11 15:43
There is this already existing issue https://github.com/meilisearch/MeiliSearch/issues/1290
Also, I've just started the work related to this issue: https://github.com/meilisearch/MeiliSearch/pull/1897

Will your problem be solved once #1290 is solved? Or is there another need?

**Comment by jaydrogers** [comment] 2021-11-11 15:49
Sweet! Sorry for the confusion 😅 I didn't know you had something rolling already. This looks very promising!

Once it available to test, I will definitely check that out.

For the sake of people arriving here via Google:

# 👉 If you're looking for a Meilisearch ARM Image
* See this issue: https://github.com/meilisearch/MeiliSearch/issues/1290
* Active PR is located here:  https://github.com/meilisearch/MeiliSearch/pull/1897

**Comment by herlon214** [comment] 2022-10-03 22:20
Looks like this issue started to happen again with release v0.20.0 MacOS M1 here

**Comment by curquiza** [comment] 2022-10-04 07:45
@herlon214 what do you mean? Meilisearch v0.20.0? or one of the SDK v0.20.0?

**Comment by herlon214** [comment] 2022-10-04 08:41
@curquiza nevermind, I got confused with the rust sdk version and the meilisearch version. Looks like I was trying to use meili v0.20.0 instead of the v0.29.0.
Sorry, my bad.

**Comment by curquiza** [comment] 2022-10-04 09:23
No problem! Feel free to ask your questions [here](https://github.com/meilisearch/meilisearch/discussions) or in our [Slack](https://slack.meilisearch.com/) if you don't know where you can ask 😄
