### ISSUE TITLE
Routine indexing tasks complete without adding documents, then task hangs indefinitely

### ISSUE THREAD

**Issue by UncaughtCursor** [meilisearch/meilisearch#3349] opened 2023-01-17 13:24 UTC
**Describe the bug**
As of yesterday morning, my Meilisearch instance seems to have gotten stuck. My machine now has perpetually high CPU and memory usage, even after rebooting, and the currently processing task runs seemingly indefinitely. When I checked initially, all tasks were listed as enqueued with none of them processing. After restarting the machine, the earliest task was listed as processing, but the operation, which usually takes about 35 minutes for the same index and number of documents, has not been completed in over 9 hours now. Additionally, the last few indexing tasks that were listed as completed did not appear to add any documents to the index.

**To Reproduce**
Not sure yet; my goal is to find a way to figure out what might be happening first to find some way to address this.

**Expected behavior**
I expected all of the indexing tasks to complete in 30-40 minutes as usual without losing any documents and for the CPU, memory, and disk usage to remain mostly stable.

**Screenshots**
![CPU Usage](https://user-images.githubusercontent.com/84347793/212903939-9b09bfc8-9bb2-4457-b0c3-4e2b156f5b02.png)
![RAM Usage](https://user-images.githubusercontent.com/84347793/212904018-604fe921-6a66-4456-bc84-79355676342e.png)
![Disk Usage](https://user-images.githubusercontent.com/84347793/212903942-acae28e3-9689-4240-afd6-8b612120968e.png)

**Timeline**

1/16, earlier than 7:00 - Routine behavior; indexing periodically

7:00 - Beginning of pathological behavior; indexing tasks start completing without adding documents and RAM enters an indefinite period of high usage

11:36 - The final indexing task completes; task queue stops processing completely

19:40 - I first notice the issue and restart the system; next task in the queue is listed as processing. Disk usage suddenly almost doubles and remains high indefinitely

22:30 - I restart the server again after noticing the task still hasn't completed

**Meilisearch version:** v0.30.5

**Additional context**
Platform: DigitalOcean (Droplet)
OS: Debian 10
CPU: 2 vCPUs
Memory: 16 GB
Disk: 25 GB + 350 GB modular block storage (data.ms is on the block storage)
Index size: 32,321,587 documents, 145 GB
Index update volume: 150K-200K documents every hour, uploaded in bulk

Is there any way to dig deeper into what could be happening here? I would really appreciate the help.

**Comment by dureuill** [comment] 2023-01-18 10:57
Hello @UncaughtCursor :wave:, thank you for the report!

- To ascertain the issue, next time it reproduces, and before exiting the Meilisearch process, can you give us the result of the `GET /tasks?status=processing` query? As the task query does not display the tasks with the processing tasks on top, sometimes tasks in the `processing` status can be far down the list, and using the filter on status makes it easier to ensure that there is no processing task.
- Then, if no task is returned from this query, could you check the name of the thread that uses CPU and RAM (the relevant column is RES), in `htop --filter meilisearch`, with the following options: 

  | ![htop](https://user-images.githubusercontent.com/41078892/213152409-856c4a1e-161f-436f-a0f3-f9ef13fba19e.png) |
  |---|
  | [Screenshot source](https://www.xmodulo.com/view-threads-process-linux.html) |
- Could you maybe share the full task list with us for further investigation? Or maybe even an API key with only read permission on the task list so we can investigate from our side? You can open a support thread on [our Discord](https://discord.com/invite/meilisearch) for us to provide you with further guidance on how to share this data privately.

**Comment by UncaughtCursor** [comment] 2023-01-19 07:59
Hey @dureuill, thanks for the reply!

I found out some more information about my situation.

I ended up leaving the tasks alone instead of canceling them, and surprisingly, they actually stopped processing after about 18 hours and system usage returned to normal.

Now all of the tasks that started after 7:00 are listed as "failed", and they are all listed as starting and finishing at the same time. Each task has this error:

`internal: MDB_TXN_FULL: Transaction has too many dirty pages - transaction too big.`

There are 11 of these tasks, with about 1.8 million documents in total.

Perhaps this happened because of the new auto-batching feature? I recently updated from 0.26.0, which might be why I've never had this problem before.

**Comment by UncaughtCursor** [comment] 2023-01-20 14:13
Update: I built a better system that waits for the last set of documents to finish indexing before uploading a new set. Notably, I was able to add and update documents to the index experiencing the weird behavior, but while uploading the documents that failed to index last time, the strange hanging behavior happened again, still lasting for hours. The task is properly listed as processing now, at least. I'll try to wait this one out too and see if I get a different error.

**Comment by dureuill** [comment] 2023-01-23 16:28
Thank you for the continued updates, @UncaughtCursor!

---

About `MDB_TXN_FULL`: we just discussed this with @Kerollmops, and you're probably correct that it occurs when our autobatching feature makes for bigger write transactions. However, in our understanding, this should not happen with the version of LMDB we're using.

On [LMDB master](https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L2271), there is a `mdb_page_spill` function that is intended to avoid this error except when using `MDB_MULTIPLE` (we're not), or when using child transactions of transactions that dirtied many pages (we only use nested transactions for opening DBs). 

[There's a note](https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L2289) about never spilling pages of actives cursors, and we have more than 20 active cursors in an environment during indexing, so maybe that is an issue?

@hyc, do you know of any pending issue about the unexpected occurrence of `MDB_TXN_FULL`? I couldn't find relevant ones on the LMDB issue tracker. Thank you for any help on the matter!

---

About the hanging behavior: Unfortunately, we are not currently successful at reproducing it, nor could we reproduce https://github.com/meilisearch/meilisearch/issues/3314, which appears similar. Is your task still listed as processing?

**Comment by UncaughtCursor** [comment] 2023-01-24 11:40
@dureuill The task finished processing, this time after 31 hours. After that, it proceeded to process the other documents I gave it in the normal amount of time, weirdly enough. The task after that contained more documents, yet somehow only took 22 minutes. The dozens of tasks after that, which have roughly the same number of documents, have gone off without a hitch and completed in the timeframe I expected them to.

I guess the "hanging" behavior might have actually been the system doing something, but I'm not sure what. There were a few different patterns in the CPU and memory graphs a few hours before processing completed that I normally don't see.

**Comment by irevoire** [comment] 2023-01-24 13:54
Oh, that's interesting!
We got another bug report of the exact same bug on discord, and the common factor between all of you is that you're all using digital ocean.
So it's not impossible that it's related to the system :thinking:

**Comment by loiclec** [comment] 2023-01-24 14:02
Hi @UncaughtCursor , thanks for the bug report :) I am currently investigating the issue.

**Comment by UncaughtCursor** [comment] 2023-01-26 09:21
Another update: I have another hanging task now, so it doesn't seem to be a fluke. Same high CPU and RAM usage.

**Comment by JaySunSyn** [comment] 2023-01-28 21:39
Just a thought, wondering if it could be Digitalocean / Block Storage related. https://github.com/meilisearch/meilisearch/issues/3314

**Comment by loiclec** [comment] 2023-02-01 11:44
I had the opportunity to monitor a Meilisearch instance experiencing similar (but not identical) problems. While there is no definitive explanation for this behaviour, I did find a few potential contributing factors:

1. The combination of a very large index (i.e. many times the amount of available RAM) and the use of Block Storage will _likely_ degrade the speed of indexing tasks. This is something that we need to investigate further. I'd like to quantify the expected slowdown and search for remedial strategies in the indexing logic. Issue: https://github.com/meilisearch/meilisearch/issues/3446
2. When document addition and deletion tasks are interspersed, the task scheduler is currently prevented from creating large batches. Thus, Meilisearch will be forced to execute many small incremental indexing tasks instead of one large one. If updates are coming faster than these incremental indexing tasks can finish, then Meilisearch will fall behind and the task queue will keep growing. Issue: https://github.com/meilisearch/meilisearch/issues/3440
3. We also found a performance bottleneck affecting these incremental indexing tasks. A fix for this inefficiency will be available in Meilisearch v1.0.0. Related PR: https://github.com/meilisearch/milli/pull/776. It was especially severe for:
	- servers with limited IO performance
	- indexes containing many documents with a medium/large amount of text in them
4. When a document is replaced or delete, Meilisearch merely "forgets" it instead of actually deleting it. This is a performance optimisation called "soft-deletion". When the amount of soft-deleted documents becomes too large, Meilisearch will perform a __real__ deletion of all soft-deleted documents. This operation can be very expensive and __may__ explain why certain tasks suddenly take much longer to be executed than the previous ones. We have tweaked the behaviour of soft-deletion in v1.0.0 so that the real deletion takes place more frequently, which should reduce its cost and prevent the index from growing too big. Related PR: https://github.com/meilisearch/milli/pull/747

**Comment by dureuill** [comment] 2023-07-11 14:46
@UncaughtCursor Ping from  triage, since some of the issues/PRs linked in the message above are closed/landed, does the issue still reproduce on a recent Meilisearch version (1.2 or a RC for 1.3)?

Thank you for any additional information :-)

**Comment by UncaughtCursor** [comment] 2023-07-11 23:46
@dureuill I'll check. It usually takes a few days before it gets stuck, so it might take a little while after I update.

**Comment by dureuill** [comment] 2023-07-12 07:20
thank you, let me know if it gets stuck 🙂

**Comment by curquiza** [comment] 2024-02-12 13:12
I close this issue due to a lack of answers, so the issue seems solved. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-02-12 13:12 UTC
Labels: bug, needs more info, CPU/RAM usage
