### ISSUE TITLE
Hard Separators for Phrase Search

### ISSUE THREAD

**Issue by anh1** [meilisearch/meilisearch#4322] opened 2024-01-14 18:34 UTC
Hi,
I am trying to do a phrase search where the return results give all documents for each term in a phrase. All my searches are done on the movies json provided by Meilisearch.

Issue 1:
 If I use a hard separator like "." for a search ("am.test") i get no results but if i use "am""test", I will get results. According to Meilisearch, "am.test" should be equivalent to "am""test". Is this correct? 

Issue 2:
1. client.index('movies').search('"bot""').then((res) => console.log(res)) 2 results
2. client.index('movies').search('"test"').then((res) => console.log(res)) 219 results
3. client.index('movies').search('"bot""test"').then((res) => console.log(res)) zero, **expecting at least 219 results**
4. client.index('movies').search('"movie""test"').then((res) => console.log(res)) 13 results., **expecting at least 219 results**

I want to know if these results that I'm getting are correct or are they errors. If they are correct, how can I search where I can get all documents for each term in a phrase. 

Thanks You.

**Comment by curquiza** [comment] 2024-01-15 12:58
Hello @anh1 

This is an expected behavior. Indeed, there is a special case with the « . » and the « , » due to the « number » support like « 1.2 ».
When there is no space after « . » or « , » the separator is not considered a context separator (aka hard separator). However, putting a blank space after the separator will be considered as you expect

**Comment by CaroFG** [comment] 2024-01-15 15:44
The second issue described is also an expected behavior, when you use phrase search (you enclose your query terms in `"`) Meilisearch will return documents containing all those query terms. In your case, documents containing both `bot` and `test`. 

If you want to find all documents containing `bot` and/or `test`, you should not enclose them in double quotes:
`client.index('movies').search('bot test').then((res) => console.log(res)) `

**Comment by anh1** [comment] 2024-01-15 22:51
> octavia. butler

when i run client.index('movies').search('bot test').then((res) => console.log(res)), i get 2 results.
when i run client.index('movies').search('test bot').then((res) => console.log(res)), i get 219 results.
should both run return the same amount documents?

**Comment by CaroFG** [comment] 2024-01-16 09:31
Meilisearch uses by default the "last matching strategy": it returns documents containing all the query terms first, then Meilisearch will remove one query term at a time, starting from the end of the query. 

For `client.index('movies').search('bot test').then((res) => console.log(res))`
It will first search for documents containing both query words, 'bot' and 'test', then it will search for results containing just 'bot'.

For `client.index('movies').search('test bot').then((res) => console.log(res))`
t will first search for documents containing both query words, 'bot' and 'test', then it will search for results containing just 'test'.

You can fin more info on matching strategy in the [documentation](https://www.meilisearch.com/docs/reference/api/search#matching-strategy)

**Comment by anh1** [comment] 2024-01-16 10:08
> Meilisearch uses by default the "last matching strategy": it returns documents containing all the query terms first, then Meilisearch will remove one query term at a time, starting from the end of the query.
> 
> For `client.index('movies').search('bot test').then((res) => console.log(res))` It will first search for documents containing both query words, 'bot' and 'test', then it will search for results containing just 'bot'.
> 
> For `client.index('movies').search('test bot').then((res) => console.log(res))` t will first search for documents containing both query words, 'bot' and 'test', then it will search for results containing just 'test'.
> 
> You can fin more info on matching strategy in the [documentation](https://www.meilisearch.com/docs/reference/api/search#matching-strategy)

Okay. But from a user perspective, when I type in "bot test" or "test bot", I expect all documents containing test or bot to be returned.  I wouldn't think the result  would contain only "bot" and not "test" or vice versus.  If I do a search "bot test", and only receive 2 results containing "bot", then I would assume there are no movies with the word "test" in it which is not the case.

**Comment by CaroFG** [comment] 2024-01-16 11:15
Hey, 

You are not the only want that would like another behavior. In fact, we have an open [product discussion](https://github.com/orgs/meilisearch/discussions/255) about the subject.

There are currently two matching strategies: all and last. In the discussion linked above, there are others listed, it would be great if you could give your opinion/vote, it greatly helps us shape the product and prioritise features 🙏

**Comment by CaroFG** [comment] 2024-01-16 13:52
Since both of the issues described align with the expected Meilisearch behavior, I am going to close this issue. Thank you for bringing this to our attention 🙏

**Closed by CaroFG** 2024-01-16 13:52 UTC
Labels: support
