### ISSUE TITLE
Azure instance has no dumps folder

### ISSUE THREAD

**Issue by pedrosilva57** [meilisearch/meilisearch#3822] opened 2023-06-07 14:55 UTC
**Describe the bug**
While following the steps described in the documentation to update a Meilisearch instance running on an Azure Web App, and deployed using the official Docker image, I could not find the dumps created anywhere. Supposedly, there should be a dumps folder in the root folder, next to the data.ms, however, not only there was no such folder, as the root folder was the data.ms folder. This in turn made it impossible to update the instance, as I had no dump to initialize it afterwords.

**To Reproduce**
1. Go to https://www.meilisearch.com/docs/learn/cookbooks/azure#deploy-a-meilisearch-instance-on-azure and click on 'Deploy to Azure' button in the One-click deploy section. 
2. On the Azure portal, I've selected the West Europe region, but I think this is indifferent. Same with the other fields.
3. Run the Web App, create a new index and add documents to it.
4. Create a dump for the index, either with a cURL command or through Postman.
5. Go to the Azure portal, select the instance storage account, and then go to the Storage browser and then File share. There should be only one item there: <img width="145" alt="image" src="https://github.com/meilisearch/meilisearch/assets/11228114/c0af02df-75c1-4271-8348-55a1c1f250ab">
6. Click on that item to see the contents of the file share. It should only have the content of the data.ms folder.

**Expected behavior**
The folder structure should have a root folder with the dumps folder, instead of just the content of data.ms.

**Screenshots**
Expected folder structure (example taken from a locally run Docker container):
<img width="139" alt="image" src="https://github.com/meilisearch/meilisearch/assets/11228114/5c36e52d-b677-4f88-9a03-a99cee02d41e"> 
Azure file share folder structure:
<img width="147" alt="image" src="https://github.com/meilisearch/meilisearch/assets/11228114/ac556409-ddd5-4ec9-9eed-0be6b3af238a">

**Meilisearch version:**
v1.1.0

**Comment by oluademola** [comment] 2023-06-25 21:48
Hello @pedrosilva57, 

I'm sorry for not getting back to you sooner. The issue is that the deployment template is outdated. To resolve it, please edit the deployment template as follows:

1. Edit line 276 of the template: Replace "/data/meili" with "/meili_data" as the mount path.
2. Also, on line 284, you can remove the MEILI_DB_PATH to simplify the template. By doing this, your Meili DB will be in the default path "data.ms".  You can however specify your own path if you want. 

Thank you.

**Comment by pedrosilva57** [comment] 2023-07-11 16:36
Hello @oluademola,

Thanks for the answer. I tried it and worked. 
But you should update the template or at least put a warning in the documentation.

**Comment by curquiza** [comment] 2023-07-17 11:40
hello @pedrosilva57 
Thanks for this feedback
To let you know, the meilisearch-azure repo is not maintained by us.
I opened an issue in the related repo.
https://github.com/cmaneu/meilisearch-on-azure/issues/1

Closing this issue since it's not related to us anymore

**Closed by curquiza** 2023-07-17 11:40 UTC
Labels: support

**Comment by thenotoriouscodefather** [comment] 2024-08-31 16:40
bicep template is still not updated
