### ISSUE TITLE
Error: Cannot allocate memory (os error 12)

### ISSUE THREAD

**Issue by surenderaphro** [meilisearch/meilisearch#4217] opened 2023-11-21 07:16 UTC
Hello,
I am getting the below error please give me solution.

**Comment by dureuill** [comment] 2023-11-21 08:14
Hello @surenderaphro,

Thanks for opening the issue. We need more information to hopefully reproduce and fix it.

Could you please provide:

1. The version of Meilisearch you're using
2. The operating system and environment you're running Meilisearch on (Linux/Windows/MacOS, local instance or cloud hosted, and the cloud provider if relevant)
3. Some information about your machine (available RAM and cores)
4. The sequence of actions leading to the error
5. The configuration of your Meilisearch instance (notably, the number of indexes)

**Comment by curquiza** [comment] 2024-02-12 13:20
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-02-12 13:20 UTC
Labels: needs more info
