### ISSUE TITLE
Add phonetic search for names, places, addresses

### ISSUE THREAD

**Issue by doreilly257** [meilisearch/MeiliSearch#722] opened 2020-05-27 09:58 UTC
Would it be possible to integrate a phonetic library so that results from similar sounding search words can be considered.

Something like metaphone or BMPM/BMDM (https://stevemorse.org/phonetics/bmpm.htm, http://haran.github.io/BMDMSoundex/index.html) could be encoded and stored in a document or index, for later searching.

I don't know if there is a rust equivalent of abydos (https://pypi.org/project/abydos/) which could be (re)used

**Comment by tpayet** [comment] 2020-05-27 11:34
Hello @doreilly257,

What would be your use-case? MeiliSearch does already handle typo tolerance and if you are designing search-as-you-type experience (or [incremental search](https://en.wikipedia.org/wiki/Incremental_search)), the user should be able to quickly understand that the terms he is looking for should'nt be written that way even before typing the whole words. 

Maybe am I missing something?

**Comment by doreilly257** [comment] 2020-05-27 11:42
Thomas,

Firstly Thanks for the speedy response.

Use case is twofold:
We need to find records to deduplicate and want to check for duplicates before insertion in some cases.
We want to search names based on phonetics not just text as we have lots of translated names from Arabic Hebrew etc. which are translated slightly differently.

Typo won’t capture enough of these. 

Thanks,

Daniel O'Reilly

**Comment by tpayet** [comment] 2020-05-27 12:18
Thank you, I better understand. 
I think it is not MeiliSearch job to check for duplicate on anything else than id. It is out of scope, at least for now.
Regarding text that are translated from one language two the other, I completely understand and I think MeiliSearch should be able to search through these translated datasets and that typo tolerance wont' fit this usage.
I'll let the @meilisearch/core-team prioritize this or not but thank you anyway for bringing this feedback to us :)

**Comment by doreilly257** [comment] 2020-05-27 18:31
Just to be clear we need to check for duplicates between new names and existing. So we want to search for phonetic names that exist already similar to any new name. 

Meilisearch doesn’t do the dedupe compare. Just helps us find similar sounding words to the search term. 

Thanks,

Daniel O'Reilly

**Comment by qdequele** [comment] 2020-12-05 17:52
Hello @doreilly257, 

I must close this exit for the following reasons. I think the problem is too specific and would take time to code and complicated to explain to the rest of the developers. Also, I really think that this work could be done on the data provider side. It's quite possible that you apply the phonetic translation before sending us your data. 

Thanks,

**Closed by qdequele** 2020-12-05 17:52 UTC
Labels: type:feature-proposal

**Comment by lpkobamn** [comment] 2024-08-31 05:21
especially for an online store, this is an important feature, people can often write the name of the product /brand not in English.
