### ISSUE TITLE
Phrase match error in chinese

### ISSUE THREAD

**Issue by gemini133** [meilisearch/MeiliSearch#1714] opened 2021-09-22 07:38 UTC
documents. default settings.
```
curl -s http://localhost:7700/indexes/products/documents | rq
[
  {
    "id": "123",
    "title": "小化妆包"
  },
  {
    "id": "456",
    "title": "Ipad 包"
  }
]

```

search with phrase match "化妆". no result returned.

```
curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"化妆\"" }' | rq

{
  "exhaustiveNbHits": false,
  "hits": [],
  "limit": 20,
  "nbHits": 0,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "\"化妆\""
}
```

search with phrase match "小化妆". no result returned.

```
curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"小化妆\"" }' | rq
{
  "exhaustiveNbHits": false,
  "hits": [],
  "limit": 20,
  "nbHits": 0,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "\"小化妆\""
}
```

search with phrase match "化妆包". result returned.

```
curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"化妆包\"" }' | rq
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "\"化妆包\""
}
```
search with phrase match "小化妆包". result returned.

```
curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"小化妆包\"" }' | rq
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "\"小化妆包\""
}
```

**Expected behavior**
queries: "化妆", "小化妆", "化妆包", "小化妆包" all of them should return same result.
```
 {
      "id": "123",
      "title": "小化妆包"
    }
```

**MeiliSearch version:** 

meilisearch-http 0.22.0

**Comment by gemini133** [comment] 2021-09-22 07:42
I did a quick test with an english document: `{"title": "adult face mask"}` and utilize phrase match: "adult", "adult face", "face mask", document is returned as expected

**Comment by YikSanChan** [comment] 2021-09-22 07:56
@gemini133 I guess this is because meilisearch uses jieba to tokenize the search word "小化妆包" and it is understood as "化妆包".

See https://docs.meilisearch.com/reference/under_the_hood/tokenization.html

**Comment by gemini133** [comment] 2021-09-22 07:59
yep, I think it's related to the tokenizer too. 
why does "化妆" returns nothings?
not sure how to work around this. confusing...

**Comment by gemini133** [comment] 2021-09-22 09:17
another test with just "包"
```
{
    "q": "\"包\""
}

{
    "hits": [
        {
            "id": "456",
            "title": "Ipad 包"
        }
    ],
    "nbHits": 1,
    "exhaustiveNbHits": false,
    "query": "\"包\"",
    "limit": 20,
    "offset": 0,
    "processingTimeMs": 0
}
```

**Comment by ManyTheFish** [comment] 2021-09-27 12:16
Hello @gemini133, it seems that you are [using phrase search in your queries](https://docs.meilisearch.com/learn/what_is_meilisearch/features.html#phrase-search) putting the `"` around your word.
If you remove `"` do you have the expected behavior?

**Comment by ManyTheFish** [comment] 2021-09-28 08:09
@gemini133, I can't speak any Chinese language, sorry if I don't understand the complete problem.

But, if I'm right, only the second request gets an irrelevant response, because  `Ipad 包` should never be returned for `化妆包`.

Am I right?

**Comment by gemini133** [comment] 2021-09-28 08:23
sorry, and you are right. `Ipad 包` should never be returned for `化妆包`. is it related to ranking rules?  I've tweaked it a couple times but still not what I want. So, I then go to phrase search

**Comment by ManyTheFish** [comment] 2021-09-28 08:42
I will investigate,
thank you @gemini133 for your report. 👍

**Comment by curquiza** [comment] 2021-09-29 15:31
Closed by https://github.com/meilisearch/MeiliSearch/pull/1711 containing [milli v0.17.0](https://github.com/meilisearch/milli/releases/tag/v0.17.0)

**Closed by curquiza** 2021-09-29 15:31 UTC
Labels: bug

**Comment by gemini133** [comment] 2021-10-02 03:06
here is the feedback of 0.23. Build it from the master brach

```
curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"小化妆\"" }' | rq
// wrong, must return 小化妆包
{
  "exhaustiveNbHits": false,
  "hits": [],
  "limit": 20,
  "nbHits": 0,
  "offset": 0,
  "processingTimeMs": 1,
  "query": "\"小化妆\"" 
}

---- 

curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"化妆包\"" }' | rq
// correct
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "\"化妆包\""
}

----

curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"小化妆包\"" }' | rq
// correct
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "\"小化妆包\""
}

----

curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"包\"" }' | rq
// wrong, must contain 小化妆包 too
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "456",
      "title": "Ipad 包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 1,
  "query": "\"包\""
}

---

curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "包" }' | rq
// wrong, must contain 小化妆包 too
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "456",
      "title": "Ipad 包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "包"
}

----

curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "化妆包" }' | rq
// correct
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 1,
  "query": "化妆包"
}

----


curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "化妆" }' | rq
// correct
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "化妆"
}

----

curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "小" }' | rq
// correct
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 0,
  "query": "小"
}
```

**Comment by gemini133** [comment] 2021-10-02 03:18
@curquiza @ManyTheFish

**Comment by ManyTheFish** [comment] 2021-10-04 10:08
Hello @gemini133!
In your last comment, we have different reasons to "why Meilisearch doesn't return the good response?":

### Tokenization & Phrase search

> curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"小化妆\"" }' | rq
// wrong, must return 小化妆包
{
  "exhaustiveNbHits": false,
  "hits": [],
  "limit": 20,
  "nbHits": 0,
  "offset": 0,
  "processingTimeMs": 1,
  "query": "\"小化妆\"" 
}

In Meilisearch we can only store 1 variation of a tokenized text, and this variation is given by Jieba.
here the text `小化妆包` is tokenized in two "words" as `["小", "化妆包"]`.
The search query is tokenized  in two "words" as `["小", "化妆"]`, and because it's a phrase search, we enforce an exact match on the two words:
- `"小"` == `"小"` ---------> ✅ 
- `"化妆"` =/= `"化妆包"` ---> ❌

This does not match.

### Tokenization & suffix search

> curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "\"包\"" }' | rq
`OR` curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "包" }' | rq
// wrong, must contain 小化妆包 too
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "456",
      "title": "Ipad 包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 1,
  "query": "\"包\""
}

In Meilisearch we can only store 1 variation of a tokenized text, and this variation is given by Jieba.
here the text `小化妆包` is tokenized in two "words" as `["小", "化妆包"]` (we technically can't store more variation for now).
Moreover, we don't support suffix search, we only support prefix search. This means that the word `化妆包` is never a match of the word `包`.

### Tokenization & query Words

> curl -s -X POST 'http://localhost:7700/indexes/products/search' --data '{ "q": "化妆包" }' | rq
// not sure, if jieba splits into "化妆" 和 "包", then it should contain "Ipad 包"
{
  "exhaustiveNbHits": false,
  "hits": [
    {
      "id": "123",
      "title": "小化妆包"
    }
  ],
  "limit": 20,
  "nbHits": 1,
  "offset": 0,
  "processingTimeMs": 1,
  "query": "化妆包"
}

Meilisearch tokenizes `化妆包` as `["化妆包"]` so `包` can't be a match for `化妆包`.
Moreover, if Meilisearch would tokenize `化妆包` as `["化妆", "包"]`, we couldn't match `Ipad 包` because the document doesn't contain the word `"化妆"`.



I hope my explanations were clear. Thanks a lot @gemini133 for your detailed report! 👍

**Comment by gemini133** [comment] 2021-10-05 02:49
Thanks for your detailed explanation! It's very helpful.
Honestly, I'm sort of disappointed as compared to the past experience with elasticsearch.

**Comment by ManyTheFish** [comment] 2021-10-05 07:53
I'm sorry for that.
But I have some questions.

## is it really relevant to respond `Ipad 包` to the query `化妆包`?
I used a traduction tool, and it said that `化妆包` seems to be a `Cosmetic bag`. I don't personally find that an `Ipad bag` is a good response to a `Cosmetic bag`. 🤔
Is there another traduction to `化妆包` that makes `Ipad 包` relevant?

## What is the most disappointing thing in the responses given by Meilisearch?

**Comment by gemini133** [comment] 2021-10-06 01:36
no, no, no. `Ipad 包` is not relevant to `化妆包`, but when you search for "包", they both should be returned, right?

**Comment by gemini133** [comment] 2021-10-11 02:30
@ManyTheFish  unfortunately, didn't find a way to tweak jieba except for `load_dict` loading our own dictionary. 

https://github.com/messense/jieba-rs/issues/77
