### ISSUE TITLE
self.stable_store.len() can be larger than u16 with some searches

### ISSUE THREAD

**Issue by MTRNord** [meilisearch/meilisearch#4247] opened 2023-12-09 15:07 UTC
https://github.com/meilisearch/meilisearch/blob/0fbc1511d74a83ce312984c420ed49ad447bb98e/milli/src/search/new/interner.rs#L60

I am apparently getting this assertion error in some cases:

```
Dec 09 16:20:27 worker-2 meilisearch[2303032]: thread 'tokio-runtime-worker' panicked at milli/src/search/new/interner.rs:60:13:
Dec 09 16:20:27 worker-2 meilisearch[2303032]: assertion failed: self.stable_store.len() < u16::MAX as usize
Dec 09 16:20:27 worker-2 meilisearch[2303032]: stack backtrace:
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    0: rust_begin_unwind
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    1: core::panicking::panic_fmt
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    2: core::panicking::panic
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    3: milli::search::new::interner::DedupInterner<T>::insert
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    4: <milli::search::new::ranking_rule_graph::fid::FidGraph as milli::search::new::ranking_rule_graph::RankingRuleGraphTrait>::build_edges
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    5: <milli::search::new::graph_based_ranking_rule::GraphBasedRankingRule<G> as milli::search::new::ranking_rules::RankingRule<milli::search::new::query_graph::QueryGraph>>::start_iteration
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    6: milli::search::new::bucket_sort::bucket_sort
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    7: milli::search::new::execute_search
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    8: milli::search::Search::execute
Dec 09 16:20:27 worker-2 meilisearch[2303032]:    9: meilisearch::search::perform_search
Dec 09 16:20:27 worker-2 meilisearch[2303032]:   10: tokio::runtime::task::raw::poll
Dec 09 16:20:27 worker-2 meilisearch[2303032]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I am not sure if there is a way to prevent this or if I am doing something wrong. I wasn't able to find anything in the issues or docs on this.

**Comment by dureuill** [comment] 2023-12-11 08:27
Hello @MTRNord :wave:

Unfortunately, you ran into a bug of the engine. I'm sorry this affected you 😞 
To fix that bug we'll need a way to reproduce it. I thank you for taking the time to get a  backtrace, it is displaying an expected location for this kind of issue. Sadly it won't be enough information to work with, as we need to understand what causes the explosion in the number of interned terms.

Can you provide the search queries that caused the panic? What are the settings of the affected index? What's a typical document looking like? Are there any outlier? How many documents are there in the index?

Thank you for reporting, and for any additional information.

**Comment by curquiza** [comment] 2024-01-03 17:50
@MTRNord do you have more information to provide? We cannot debug without them

**Comment by curquiza** [comment] 2024-02-12 13:20
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2024-02-12 13:20 UTC
Labels: bug, needs more info
