### ISSUE TITLE
Relevancy bug: find words separated with `-`

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2701] opened 2022-08-24 16:44 UTC
**Describe the bug**
I was trying out the new [movies](https://where2watch.meilisearch.com/) demo available on the README and I noticed when you search for « spiderman » you get no results back because it's actually written « spider-man ».
That's not ideal, maybe we could improve it somehow?

**Comment by Kerollmops** [comment] 2022-08-24 17:44
This is obviously a bug that was probably introduced with the changes made with the query tree, maybe @ManyTheFish knows the reason why?

**Comment by curquiza** [comment] 2022-08-24 17:51
I checked on v0.28.1, we don't have the bug

<img width="1351" alt="Capture d’écran 2022-08-24 à 19 50 44" src="https://user-images.githubusercontent.com/20380692/186488642-3b7e7a8a-58bb-484a-b4c6-bca4ef21952c.png">

**Comment by curquiza** [comment] 2022-08-24 17:54
Same on v0.28.0 but the mini-dashboard is supposed to be in v0.28.0, I don't understand why it fails 😱 

<img width="1303" alt="Capture d’écran 2022-08-24 à 19 53 15" src="https://user-images.githubusercontent.com/20380692/186489150-765439c5-bdf3-4088-9c8d-5012b0028f7e.png">

**Comment by curquiza** [comment] 2022-08-24 17:54
@mdubus maybe do you have an idea, is the mini-dasboard on v0.28.0? Did you add any settings?

**Comment by mdubus** [comment] 2022-08-25 08:57
Hello 👋 

The demo-movies is indeed in v0.28.0: 
<img width="407" alt="Capture d’écran 2022-08-25 à 10 50 53" src="https://user-images.githubusercontent.com/30866152/186621362-bde4ef65-d4c4-45d3-ac00-833ff7e33060.png">

Here are the settings, do you see anything that may cause this to happen? 
<img width="389" alt="Capture d’écran 2022-08-25 à 10 51 26" src="https://user-images.githubusercontent.com/30866152/186621525-69b277a4-6c08-43da-b4e5-af05f81af93a.png">

**Comment by ManyTheFish** [comment] 2022-08-25 09:47
@curquiza I'm on it

**Comment by ManyTheFish** [comment] 2022-08-25 10:08
@mdubus, can I have a text version of your settings? Copy-pasting a screenshot is a bit more laborious 😊

**Comment by mdubus** [comment] 2022-08-25 12:43
@ManyTheFish sure!
 
Here you go:

```js
{
  displayedAttributes: [ '*' ],
  searchableAttributes: [ 'title' ],
  filterableAttributes: [],
  sortableAttributes: [],
  rankingRules: [
    'typo',
    'words',
    'proximity',
    'attribute',
    'exactness',
    'release_date:desc',
    'popularity:desc'
  ],
  stopWords: [],
  synonyms: {},
  distinctAttribute: null,
  typoTolerance: {
    enabled: true,
    minWordSizeForTypos: { oneTypo: 5, twoTypos: 9 },
    disableOnWords: [],
    disableOnAttributes: []
  },
  faceting: { maxValuesPerFacet: 100 },
  pagination: { maxTotalHits: 1000 }
}
```

**Comment by ManyTheFish** [comment] 2022-08-25 14:34
Re all, I managed to reproduce the bug but only on previous versions of Meilisearch v0.28.1, the bug does not appear on the main branch

## Reproduce

Take the v0.28.1 version of Meilisearch

1) Run it on movies dataset with previous settings:
```sh
curl -X PATCH 'http://localhost:7700/indexes/movies/settings' -H 'Content-type: Application/json' --data-binary '{"displayedAttributes":["*"],"searchableAttributes":["title"],"filterableAttributes":[],"sortableAttributes":[],"rankingRules":["typo","words","proximity", "attribute","exactness","release_date:desc","popularity:desc"],"stopWords":[],"synonyms":{},"distinctAttribute":null,"typoTolerance":{"enabled":true,"minWordSizeForTypos":{"oneTypo":5,"twoTypos":9},"disableOnWords":[],"disableOnAttributes":[]},"faceting":{"maxValuesPerFacet":100},"pagination":{"maxTotalHits":1000}}'
```

2) try a simple search:
```sh
curl -XPOST  'http://localhost:7700/indexes/movies/search' -H 'Content-type: Application/json' --data-binary '{"q":"spiderman"}'
```

3) no documents

4) retry with the main branch, documents are returned properly 😮‍💨

## What fixing it in the next version

I think this bug has been fixed by https://github.com/meilisearch/milli/pull/594

I'm closing this issue, but don't hesitate to reopen it if you think that I missed something 😄

**Closed by ManyTheFish** 2022-08-25 14:34 UTC
Labels: bug, tokenizer
