### ISSUE TITLE
v1.3 - facetSearch only return 100 facetHits

### ISSUE THREAD

**Issue by emanueletoffolon** [meilisearch/meilisearch#3980] opened 2023-08-07 13:42 UTC
Hi to all!!

When I do a facetSearch, 100 hits are always returned even though I have changed the maxValuesPerFacet setting to a higher value.
Even if I set maxValuesPerFacet to a value less than 100, 100 facetHits are always returned

**To Reproduce**
1. Set maxValuesPerFacet at 100000 (my index has 75000 documents)

```
curl \
  -X PATCH 'http://localhost:7700/indexes/my-index/settings/faceting' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "maxValuesPerFacet": 100000,
    "sortFacetValuesBy": {
      "*": "count"
    }
  }'
```

3. Perform a placeholder facetSearch

```
curl \
  -X POST 'http://localhost:7700/indexes/my-index/facet-search' \
  -H 'Content-Type: application/json' \
  --data-binary '{ 
    "facetName": "producer_std.slug",
    "filter": "typologies_std.slug='vini/rossi'"
  }'
```

**Expected behavior**
Running a facets distribution search, it correctly returns more than 5000 results sorted by count and I would expect to have 5000 facetHits in a facetSearch

**Screenshots**

Current index faceting settings
![01 - index faceting](https://github.com/meilisearch/meilisearch/assets/2611534/0cad4625-ebea-4ab8-be2d-13304226ff70)

Facet distribution of a normal search
![02 - search with facet](https://github.com/meilisearch/meilisearch/assets/2611534/644c6fa2-2060-45f7-a2a4-6d9c09ecd416)

facetHits of a facetSearch
![03 - facetSearch](https://github.com/meilisearch/meilisearch/assets/2611534/e426a430-9a2d-4d35-b1c5-afa7faee1129)

**Meilisearch version:**
[e.g. v1.3]

**Other info:**
Using Laravel 10 with meilisearch-php:1.3

How can I get the same result in both searches?

Thanks

**Comment by ManyTheFish** [comment] 2023-08-08 13:32
Hello @emanueletoffolon,
There is a small misunderstanding here, the attribute `maxValuesPerFacet` is not meant to change the number of facets shown by the `search for facet value` feature but the number of facets shown in the `facetDistribution`.
The limit of facets shown by the `search for facet value` feature is not customizable for now, however, it might be a good idea to make it customizable by using the `maxValuesPerFacet` setting or by creating a dedicated one, I'm pinging @macraig on this.

I close this issue because it's not a bug, but don't hesitate to reopen it if I missed something.

Have a good day!

**Closed by ManyTheFish** 2023-08-08 13:32 UTC
Labels: bug

**Comment by curquiza** [comment] 2023-08-08 13:44
@ManyTheFish Looks like the docs is currently wrong in this case: https://www.meilisearch.com/docs/reference/api/facet_search#body

Sorry @emanueletoffolon for the issue, we are working on it to update the docs and to know if this was expected

**Comment by curquiza** [comment] 2023-08-08 15:28
Hello again @emanueletoffolon 

I had a talk with our PMs (the developer who implemented it is on Holiday) and this is indeed a limitation. The maximum of retrievable facets is `100`, and we haven't implemented a way to customize it for this first iteration.
Our PM team is aware of your feedback

Next steps
- I will fix the current wrong part of the docs
- I will open an issue to add this as a known limitation

Sorry again for the miss understanding!
