### ISSUE TITLE
Infinitely running task when modifying a large amount of documents

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4172] opened 2023-10-27 15:51 UTC
The indexing thread (_batch-operation_) seems locked into the `mdb_midl_sort` and doesn't seem to go out of this function. It is either a bug in LMDB or a wrong usage of it. I don't know if there is a way to trigger the `MDB_TXN_FULL: The transaction has too many dirty pages ` error. I will compile Meilisearch with the debug symbols (It should compile LMDB with that, too) to investigate further.

```
#0  0x000055f1626ab9c8 in mdb_midl_sort ()
No symbol table info available.
#1  0x000055f1626a0f56 in mdb_page_spill ()
No symbol table info available.
#2  0x000055f1626a8d39 in mdb_cursor_del ()
No symbol table info available.
#3  0x000055f16269c79f in heed::cursor::RwCursor::del_current ()
No symbol table info available.
#4  0x000055f16258439e in milli::update::facet::bulk::FacetsUpdateBulk::execute ()
No symbol table info available.
#5  0x000055f162541fc7 in milli::update::facet::FacetsUpdate::execute ()
No symbol table info available.
#6  0x000055f16255f545 in milli::update::index_documents::typed_chunk::write_typed_chunk_into_index ()
No symbol table info available.
#7  0x000055f1621baf2d in milli::update::index_documents::IndexDocuments<FP,FA>::execute ()
No symbol table info available.
#8  0x000055f1622333ca in index_scheduler::batch::<impl index_scheduler::IndexScheduler>::apply_index_operation ()
No symbol table info available.
#9  0x000055f162228cb7 in index_scheduler::batch::<impl index_scheduler::IndexScheduler>::process_batch ()
No symbol table info available.
#10 0x000055f16215737a in std::sys_common::backtrace::__rust_begin_short_backtrace ()
No symbol table info available.
#11 0x000055f16215c69c in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
No symbol table info available.
#12 0x000055f1629e7425 in alloc::boxed::{impl#47}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2007
No locals.
#13 alloc::boxed::{impl#47}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2007
No locals.
#14 std::sys::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/unix/thread.rs:108
No locals.
#15 0x00007fc5ae898fd4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140463266825920, -127696407101695183, -1120, 0, 140485910621264, 140463264727040, 124441581990976305, 121889489512438577}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#16 0x00007fc5ae9195ac in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.
```

**To Reproduce**

The datasets are available on [the Discogs songs dataset page](https://www.notion.so/meilisearch/Songs-from-Discogs-99cd4b510a4b41a5bfd7de215cd66b04) and on our POC machine.

```bash
./meilisearch --http-addr 0.0.0.0:7700 --http-payload-size-limit 40GiB --max-indexing-threads 12
cat ../datasets/musics/songs-discogs.settings.json | xh PATCH 'localhost:7700/indexes/songs/settings'
curl -X POST 'localhost:7700/indexes/songs/documents' -H 'Content-type:application/x-ndjson' -T ../datasets/musics/songs-discogs.ndjson
curl -X POST 'localhost:7700/indexes/songs/documents' -H 'Content-type:application/x-ndjson' -T ../datasets/musics/songs-discogs-20pct.modified.ndjson
```

**Expected behavior**

**Screenshots**
<img width="1746" alt="Capture d’écran 2023-10-27 à 17 35 49" src="https://github.com/meilisearch/meilisearch/assets/3610253/50cfd8cb-7c5b-493e-98b8-1c6758e8b1ce">

**Meilisearch version:**
it was the `main` branch (62ea81bef)

**Additional context**
Linux sd-165829 5.15.0-3-amd64 #1 SMP Debian 5.15.15-1 (2022-01-18) x86_64 GNU/Linux

**Comment by curquiza** [comment] 2023-12-18 16:37
Looks like we fixed in v1.6.0 by reducing size of transaction (with the diff indexing introduction). We are not able to reproduce it anymore.
Closing it

**Closed by curquiza** 2023-12-18 16:37 UTC
Labels: bug, indexing
