### ISSUE TITLE
Default order for searchableAttribute does not behave as expected

### ISSUE THREAD

**Issue by bebert64** [meilisearch/meilisearch#4946] opened 2024-09-19 11:05 UTC
**Describe the bug**
According to the [documentation](https://www.meilisearch.com/docs/learn/relevancy/displayed_searchable_attributes#searchable-fields), "all attributes are automatically added to the searchableAttributes list in their order of appearance". This does not seem to be the case. Instead, documents are returned in the order they were sent to Meilisearch.

**To Reproduce**
1. Create a new index
2. Upload 2 new documents, one at a time
```
{
	"id": "1",
	"a": "xxx",
	"b":  "match"
}
```
and
```
{
	"id": "2",
	"a": "match",
	"b": "xxx"
}
```
3. Search for match
4. Search Results show doc 1, and then doc 2

**Expected behavior**
I would expect searchableAttributes to be `["a", "b"]`, and so to receive doc 2 then doc 1.
To be sure, I then manually updated the searchableAttributes (using the PUT endpoint) to `["a", "b"]` and correctly received doc 2 then doc 1

**Meilisearch version:**
1.9.1

**Comment by dureuill** [comment] 2024-09-23 08:01
Hello :wave:

[This is a relevancy change introduced in v1.9.0](https://github.com/meilisearch/meilisearch/issues/4639). The [documentation was updated](https://github.com/meilisearch/documentation/issues/2852) to reflect this change, but we can also update that particular phrasing.

**Comment by bebert64** [comment] 2024-09-23 15:24
I see, thanks for the clarification.

**Comment by dureuill** [comment] 2024-11-05 08:31
The related docs issue has not been closed, but I'm closing this issue on the Meilisearch side for now, as the behavior is as intended.

Thank you again for your report, and feel free to reopen should the need arise!

**Closed by dureuill** 2024-11-05 08:31 UTC
Labels: support
