### ISSUE TITLE
query with multiple keywords returns more records than expected

### ISSUE THREAD

**Issue by bnfd** [meilisearch/MeiliSearch#1694] opened 2021-09-10 09:48 UTC
When querying `keyword1 keyword2` it returns records that only contain one of the keywords (after returning all the ones that contain both). It is like `keyword1 AND keyword2` gets returned first and then `keyword1 OR keyword2` follows. 

**MeiliSearch version:** [e.g. v0.21.0]

I'm using Ubuntu.

**Comment by curquiza** [comment] 2021-09-10 09:58
Hello @bnfd!
What is your expected behavior? Only get results containing `keyword1 AND keyword2`? :)

**Comment by bnfd** [comment] 2021-09-10 11:47
@curquiza Yes

**Comment by curquiza** [comment] 2021-09-10 12:18
Ok! What you ask is a feature request since the current behavior is totally expected.
I've just opened a discussion in the product repo https://github.com/meilisearch/product/discussions/211 so that your feature request is taken into account.

I close this issue. For anyone wanting to discuss it, go the link I send :)

**Closed by curquiza** 2021-09-10 12:18 UTC
Labels: feature request
