### ISSUE TITLE
Error when deleting index: DirectoryNotEmpty

### ISSUE THREAD

**Issue by stefkes** [meilisearch/meilisearch#1831] opened 2021-10-19 21:28 UTC
**Description**
When deleting an index using `$client->deleteIndex('Posts')` I see in the MeiliSearch output the error below. However, the index does seem to be deleted in the sense that `$client->getAllIndexes()` no longer shows the one I just tried to delete.

`ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })`

**Expected behavior**
There should not be an error

**Current behavior**
There's a `DirectoryNotEmpty` error

**Screenshots or Logs**
See above

**Environment (please complete the following information):**
- OS: Ubuntu running in a Virtualbox (Laravel Homestead) on MacOS
- MeiliSearch version: 0.23.1
- meilisearch-php version: ^0.19.2

**Comment by veerendrapolepalli** [comment] 2021-11-10 10:03
I am also getting same kind of error , we have persisted the data.ms folder in the server , when there is new update we are trying to delete the existing index and create a new index with same name , logs are attached below

[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47334 "DELETE /indexes/price HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.056508
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47338 "DELETE /indexes/attribute HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.059311
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47336 "DELETE /indexes/auto HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.089133
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47340 "DELETE /indexes/plan HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.099864
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47342 "DELETE /indexes/price HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.115724
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47344 "DELETE /indexes/profiler HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.124963
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47346 "DELETE /indexes/plan HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.141962
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47348 "DELETE /indexes/test HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.161022
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] 10.0.5.213:47350 "DELETE /indexes/performance HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.192520

Note: When i do it locally in my system while we are not able to see the error and we have followed the installation based on the docker https://docs.meilisearch.com/learn/getting_started/installation.html which is mentioned in the site

**Comment by veerendrapolepalli** [comment] 2021-11-10 10:32
We are facing the same issue , we have persisted the data.ms folder in the server , we are trying to delete the index and re create index when there is update in the document , logs i have attached below , we have done the docker installation based on the https://docs.meilisearch.com/learn/getting_started/installation.html#download-and-launch 


[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger]  "DELETE /indexes/price HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.056508
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })
[2021-11-10T09:45:12Z INFO  actix_web::middleware::logger] "DELETE /indexes/attribute HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.059311
[2021-11-10T09:45:12Z ERROR meilisearch_lib::index_controller::index_resolver] Error while deleting index: Internal(Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" })

Note  : while running it from locally we dont have any issue i mean with out docker

**Comment by curquiza** [comment] 2021-11-10 13:34
Thanks for the report. Seems related to https://github.com/meilisearch/MeiliSearch/issues/1833

Could you test @stefkes and @veerendrapolepalli if you get the same error using an old docker image, I mean v0.22.0 or v0.21.0, since v0.23.1 seems to have this bug?
Thanks a lot for your help

**Comment by veerendrapolepalli** [comment] 2021-11-10 15:50
hi @curquiza  
i have tried with version 0.22.0 i am seeing same kind of error in the delete index api 

[2021-11-10T15:34:35Z INFO  actix_web::middleware::logger]  :52470 "DELETE /indexes/performance HTTP/1.1" 204 0 "-" "python-requests/2.25.1" 0.019816
[2021-11-10T15:34:35Z ERROR ::index_controller] Error while deleting index: update store was shut down due to a fatal error, please check your logs for more info.
[2021-11-10T15:34:35Z ERROR ::index_controller] Error while deleting index: Internal Error: Directory not empty (os error 39)

Hope fully this will help u

**Comment by curquiza** [comment] 2021-11-11 13:30
Thanks @veerendrapolepalli 

In which machine do you run your docker? MacOs, Windows or Linux? If it's on MacOs or Windows, can you check using docker on Linux?

Not easy to find where the problem comes from, to be honest.

**Comment by veerendrapolepalli** [comment] 2021-11-15 21:15
i am running the docker in linux machine

**Comment by alexchuin** [comment] 2021-12-14 13:17
Hi,

I have the same issue here, Meilisearch is on Clever-cloud, index of ~4M entries.

**Comment by irevoire** [comment] 2022-01-05 14:30
I was not able to reproduce this bug either :weary: 
Here are my logs:
```
[2022-01-05T14:22:48Z INFO  actix_server::builder] Starting 24 workers
[2022-01-05T14:22:48Z INFO  actix_server::server] Actix runtime found. Starting in Actix runtime
[2022-01-05T14:23:04Z INFO  actix_web::middleware::logger] 172.17.0.1:50010 "DELETE /indexes/mieli HTTP/1.1" 202 117 "-" "mieli/0.24.2" 0.010450
[2022-01-05T14:23:04Z INFO  actix_web::middleware::logger] 172.17.0.1:50012 "GET /tasks/0 HTTP/1.1" 200 204 "-" "mieli/0.24.2" 0.000185
[2022-01-05T14:23:04Z INFO  actix_web::middleware::logger] 172.17.0.1:50014 "GET /tasks/0 HTTP/1.1" 200 428 "-" "mieli/0.24.2" 0.000208
[2022-01-05T14:23:04Z INFO  actix_web::middleware::logger] 172.17.0.1:50016 "POST /indexes HTTP/1.1" 202 117 "-" "mieli/0.24.2" 0.013358
[2022-01-05T14:23:04Z INFO  actix_web::middleware::logger] 172.17.0.1:50018 "GET /tasks/1 HTTP/1.1" 200 198 "-" "mieli/0.24.2" 0.000136
[2022-01-05T14:23:05Z INFO  actix_web::middleware::logger] 172.17.0.1:50020 "GET /tasks/1 HTTP/1.1" 200 267 "-" "mieli/0.24.2" 0.000233
[2022-01-05T14:23:05Z INFO  actix_web::middleware::logger] 172.17.0.1:50022 "GET /indexes/mieli HTTP/1.1" 200 138 "-" "mieli/0.24.2" 0.000188
[2022-01-05T14:23:05Z INFO  actix_web::middleware::logger] 172.17.0.1:50024 "POST /indexes/mieli/documents HTTP/1.1" 202 120 "-" "mieli/0.24.2" 0.018607
[2022-01-05T14:23:05Z INFO  actix_web::middleware::logger] 172.17.0.1:50026 "GET /tasks/2 HTTP/1.1" 200 230 "-" "mieli/0.24.2" 0.000164
[2022-01-05T14:23:05Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 11, number_of_documents: 11 }
[2022-01-05T14:23:05Z INFO  actix_web::middleware::logger] 172.17.0.1:50028 "GET /tasks/2 HTTP/1.1" 200 297 "-" "mieli/0.24.2" 0.000240
[2022-01-05T14:26:59Z INFO  actix_web::middleware::logger] 172.17.0.1:50030 "DELETE /indexes/mieli HTTP/1.1" 202 117 "-" "mieli/0.24.2" 0.005300
[2022-01-05T14:26:59Z INFO  actix_web::middleware::logger] 172.17.0.1:50032 "GET /tasks/3 HTTP/1.1" 200 204 "-" "mieli/0.24.2" 0.000148
[2022-01-05T14:26:59Z INFO  actix_web::middleware::logger] 172.17.0.1:50034 "GET /tasks/3 HTTP/1.1" 200 271 "-" "mieli/0.24.2" 0.000186
[2022-01-05T14:26:59Z INFO  actix_web::middleware::logger] 172.17.0.1:50036 "POST /indexes HTTP/1.1" 202 117 "-" "mieli/0.24.2" 0.015731
[2022-01-05T14:26:59Z INFO  actix_web::middleware::logger] 172.17.0.1:50038 "GET /tasks/4 HTTP/1.1" 200 198 "-" "mieli/0.24.2" 0.000116
[2022-01-05T14:27:00Z INFO  actix_web::middleware::logger] 172.17.0.1:50040 "GET /tasks/4 HTTP/1.1" 200 267 "-" "mieli/0.24.2" 0.000155
[2022-01-05T14:27:00Z INFO  actix_web::middleware::logger] 172.17.0.1:50042 "GET /indexes/mieli HTTP/1.1" 200 138 "-" "mieli/0.24.2" 0.000179
[2022-01-05T14:27:00Z INFO  actix_web::middleware::logger] 172.17.0.1:50044 "POST /indexes/mieli/documents HTTP/1.1" 202 120 "-" "mieli/0.24.2" 0.013630
[2022-01-05T14:27:00Z INFO  actix_web::middleware::logger] 172.17.0.1:50046 "GET /tasks/5 HTTP/1.1" 200 230 "-" "mieli/0.24.2" 0.000166
[2022-01-05T14:27:00Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 11, number_of_documents: 11 }
[2022-01-05T14:27:00Z INFO  actix_web::middleware::logger] 172.17.0.1:50050 "GET /tasks/5 HTTP/1.1" 200 297 "-" "mieli/0.24.2" 0.000172
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50052 "DELETE /indexes/mieli HTTP/1.1" 202 117 "-" "mieli/0.24.2" 0.013321
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50054 "GET /tasks/6 HTTP/1.1" 200 204 "-" "mieli/0.24.2" 0.000162
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50056 "GET /tasks/6 HTTP/1.1" 200 271 "-" "mieli/0.24.2" 0.000197
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50058 "POST /indexes HTTP/1.1" 202 117 "-" "mieli/0.24.2" 0.013342
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50060 "GET /tasks/7 HTTP/1.1" 200 198 "-" "mieli/0.24.2" 0.000139
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50062 "GET /tasks/7 HTTP/1.1" 200 267 "-" "mieli/0.24.2" 0.000234
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50064 "GET /indexes/mieli HTTP/1.1" 200 138 "-" "mieli/0.24.2" 0.000165
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50066 "POST /indexes/mieli/documents HTTP/1.1" 202 120 "-" "mieli/0.24.2" 0.013616
[2022-01-05T14:27:01Z INFO  actix_web::middleware::logger] 172.17.0.1:50068 "GET /tasks/8 HTTP/1.1" 200 230 "-" "mieli/0.24.2" 0.000171
[2022-01-05T14:27:01Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 11, number_of_documents: 11 }
[2022-01-05T14:27:02Z INFO  actix_web::middleware::logger] 172.17.0.1:50070 "GET /tasks/8 HTTP/1.1" 200 297 "-" "mieli/0.24.2" 0.000220
```

And here is the script I ran multiple times (which is the same thing as your PHP script I think):
```
MIELI_INDEX=bug

mieli index delete
mieli index create

mieli index get

for id in {0..10}; do jq -n -c --arg id $id --arg val $RANDOM '{ id: $id, val: $val }' ; done | mieli add -c application/x-ndjson
```

**Comment by curquiza** [comment] 2022-03-14 17:54
Since we cannot reproduce the bug and we don't have enough information, I close the issue
Feel free to test using the latest [Meilisearch version](https://github.com/meilisearch/MeiliSearch/releases) and ask to re-open it if needed :)

**Comment by bultas** [comment] 2022-11-21 18:00
We are getting same error on `v0.30.0rc2` . 
Running Meilisearch instance on Kubernetes with persistant volume.

simple request like 

```
curl -X DELETE '<meilisearch>/indexes/<index>' 
```

will return 
```
{"taskUid":33,"indexUid":"v2_staging","status":"enqueued","type":"indexDeletion","enqueuedAt":"2022-11-21T17:46:40.863515208Z"}%    
```

logs

```
[2022-11-21T17:59:19Z INFO  actix_web::middleware::logger] 10.244.0.226 "DELETE /indexes/v2_staging HTTP/1.1" 202 127 "-" "curl/7.84.0" 0.001331
```

then when I check Tasks:

```
[
 {
      "uid": 33,
      "indexUid": "<index>",
      "status": "failed",
      "type": "indexDeletion",
      "details": {
        "deletedDocuments": 0
      },
      "error": {
        "message": "An internal error has occurred. `Directory not empty (os error 39)`.",
        "code": "internal",
        "type": "internal",
        "link": "https://docs.meilisearch.com/errors#internal"
      },
      "duration": "PT0.002740018S",
      "enqueuedAt": "2022-11-21T17:46:40.863515208Z",
      "startedAt": "2022-11-21T17:46:40.865735138Z",
      "finishedAt": "2022-11-21T17:46:40.868475156Z"
    }
...
]
```

The thing is, that index was deleted as a result

**Comment by curquiza** [comment] 2022-11-22 10:52
Hello @bultas 

Do you have the same issue with v0.29.0?

**Comment by curquiza** [comment] 2022-11-22 14:36
Thanks @bultas for the update 😄 
Closing this then

**Closed by curquiza** 2022-11-22 14:36 UTC
Labels: bug, needs more info
