### ISSUE TITLE
IN filter cannot be combined with boolean OR in composite filter

### ISSUE THREAD

**Issue by moy2010** [meilisearch/meilisearch#4004] opened 2023-08-17 18:33 UTC
**Describe the bug**
When creating a composite filter, `IN` cannot be combined with boolean `OR`.

The syntax that I've been trying is:

```
field_1 IN [value1, value2] OR field_2 IN [value1, value2]
```

And with parentheses:

```
(field_1 IN [value1, value2]) OR (field_2 IN [value1, value2])
```

**Expected behavior**
The `IN` filter can be combined in a composite filter when used in conjunction with a boolean `OR`. For the examples given above, I would expect the filter to search in both `field_1` and `field_2`.

**Meilisearch version:**
 v1.3

**Additional context**
Using Rust client v0.24.1

**Comment by jaypatidar14** [comment] 2023-08-19 12:54
i can do in these issuce

**Comment by Kerollmops** [comment] 2023-09-05 13:24
Hey @moy2010 👋

Thank you for your report and sorry for the late reply. I am not sure that I understand your request. Would it be possible to express it with a reproducible example?

```bash
# Set the filterable attributes
echo '{"filterableAttributes": ["field_1", "field_2"]}' | xh PATCH 'localhost:7700/indexes/4004/settings'

# Send some documents with the specified filterable attributes
echo '[\
{ "id": 1, "field_1": "ABC", "field_2": "wow" }, \
{ "id": 2, "field_1": "what", "field_2": "abc" } \
]' | \
xh 'localhost:7700/indexes/4004/documents'

# Both of these queries shows the documents with id 1 and 2
echo '{"filter":"field_1 IN [abc, what] OR field_2 IN [wow, abc]"}' | xh 'localhost:7700/indexes/4004/search'
echo '{"filter":"field_1 IN [abc] OR field_2 IN [abc]"}' | xh 'localhost:7700/indexes/4004/search'
```

**Comment by curquiza** [comment] 2023-10-11 11:56
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Closed by curquiza** 2023-10-11 11:56 UTC
Labels: support
