### ISSUE TITLE
Key generation is not deterministic

### ISSUE THREAD

**Issue by geoffatsource** [meilisearch/meilisearch#2262] opened 2022-03-23 21:43 UTC
https://github.com/meilisearch/meilisearch/blob/7e65816d63a4b5cf7fa051b1b937476db5916009/meilisearch-auth/src/key.rs#L135

This is a problem because it limits the ability for provisioning new search nodes behind load balancers. It also complicates provisioning/replacing existing nodes without a corresponding front-end release.

**Comment by curquiza** [comment] 2022-03-24 11:23
Hello @geoffatsource 
As explained here: https://github.com/meilisearch/meilisearch/discussions/2261, this is not a bug but expected behavior. 
Any feedback will be collected in our product repository here: https://github.com/meilisearch/product/discussions/421

Closing this issue then

**Closed by curquiza** 2022-03-24 11:23 UTC
Labels: feature request
