### ISSUE TITLE
Adding documents with bad authentication throws a 500

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2331] opened 2022-04-19 15:14 UTC
**Describe the bug**
When I run meilisearch without any `data.ms` and with a masterkey.
And then I try to send documents to meilisearch WITHOUT sending my masterkey it crashes and send a 500.
I can't reproduce the bug with a non-empty `data.ms` or with a masterkey.

**To Reproduce**
1. `rm -rf data.ms`
2. `./meilisearch --master-key prout`
3. In another shell; `mieli add ~/datasets/movies.json` or `bat ~/datasets/movies.json | http post :7700/indexes/mieli/documents`

**Expected behavior**
It send the following error;
```json
{
  "code": "missing_authorization_header",
  "link": "https://docs.meilisearch.com/errors#missing_authorization_header",
  "message": "The Authorization header is missing. It must use the bearer authorization method.",
  "type": "auth"
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7032172/164036878-f9f114c9-031f-45e0-a620-878d088e06f1.png)

**Meilisearch version:**
v0.26.1
I can also reproduce the issue on main and v0.27.0 branch.

**Additional context**
I just noticed I couldn't reproduce the bug with a smaller dataset so you should try it with [the movies dataset](https://docs.meilisearch.com/movies.json)

**Comment by irevoire** [comment] 2022-04-19 15:19
And I just noticed that when I run the command with curl I get the error back;
```
irevoire@tamo ~/datasets 🕷 % curl \
  -X POST 'http://127.0.0.1:7700/indexes/movies/documents' \
  -H 'Content-Type: application/json' \
  --data-binary @movies.json
{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}%                                                                                                                
```

But meilisearch still throw a 500;
```

[2022-04-19T15:16:42Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/movies/documents HTTP/1.1" 401 221 "-" "curl/7.82.0" 0.000204
[2022-04-19T15:16:42Z ERROR actix_http::h1::dispatcher] handler did not read whole payload and dispatcher could not drain read buf; return 500 and close connection
[2022-04-19T15:16:42Z ERROR actix_http::h1::dispatcher] stream error: Handler dropped payload before reading EOF
```

**Comment by curquiza** [comment] 2022-04-20 10:08
FYI, cannot reproduce in v0.25.0 and older. The bug is present since v0.26.0.

**Comment by ManyTheFish** [comment] 2022-04-20 12:30
Hey, it seems to be related to [actix-web#2695](https://github.com/actix/actix-web/issues/2695), I will follow the advancement in case of a workaround is proposed. 🤔

**Comment by robjtede** [comment] 2022-04-20 13:24
Yes, I have seen similar reports but will prioritise a fix for this.
Can you point me to the code in Meilisearch that would handle this request.

**Comment by ManyTheFish** [comment] 2022-04-20 13:48
Sure, this error is thrown when our [authentication extractor](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-http/src/extractors/authentication/mod.rs#L87-L125) returns an error

**Comment by MarinPostma** [comment] 2022-04-20 15:07
Adding to this issue:
- This is unrelated to whether the db contains. something or not (could reproduce with full db), which makes more sense
- The size of the payload has an influence on how often this bug is triggered: sending only one document doesn't trigger it, while sending a big payload triggers it almost all the time. This makes me feel like this is a concurrency issue, where `poll_request` gets called after a response has already been returned.
- I could reproduce consistently with an extractor that fails immediately:
```rust
pub struct Fail;

impl FromRequest for Fail {
    type Error = PayloadError;

    type Future = futures_util::future::Ready<Result<Fail, Self::Error>>;

    fn from_request(req: &HttpRequest, payload: &mut actix_web::dev::Payload) -> Self::Future {
        err(PayloadError::Overflow)
    }
}

pub async fn add_documents(
    // meilisearch: GuardedData<ActionPolicy<{ actions::DOCUMENTS_ADD }>, MeiliSearch>,
    fail: Fail,
    path: web::Path<String>,
    params: web::Query<UpdateDocumentsQuery>,
    body: Payload,
    req: HttpRequest,
    analytics: web::Data<dyn Analytics>,
) -> Result<HttpResponse, ResponseError> {
```

**Comment by amab8901** [comment] 2022-11-30 05:59
why do you need to remove `data.ms`?

**Comment by curquiza** [comment] 2022-11-30 08:51
Hello @amab8901 
We remove data.ms to show we start from an empty Meilisearch instance to reproduce the issue. It gives more context to reproduce the issue 😊

**Comment by intoxicated** [comment] 2023-01-24 00:09
Not sure my issue is related to this but I was able to do without master key on development environment on v0.28. Now, I updated to v0.30.x and it appeared this issue has occurred again. Though it seemed success on logger

```
888b     d888          d8b 888 d8b                                            888
8888b   d8888          Y8P 888 Y8P                                            888
88888b.d88888              888                                                888
888Y88888P888  .d88b.  888 888 888 .d8888b   .d88b.   8888b.  888d888 .d8888b 88888b.
888 Y888P 888 d8P  Y8b 888 888 888 88K      d8P  Y8b     "88b 888P"  d88P"    888 "88b
888  Y8P  888 88888888 888 888 888 "Y8888b. 88888888 .d888888 888    888      888  888
888   "   888 Y8b.     888 888 888      X88 Y8b.     888  888 888    Y88b.    888  888
888       888  "Y8888  888 888 888  88888P'  "Y8888  "Y888888 888     "Y8888P 888  888

Config file path:	"none"
Database path:		"./data.ms"
Server listening on:	"http://0.0.0.0:7700"
Environment:		"development"
Commit SHA:		"unknown"
Commit date:		"unknown"
Package version:	"0.30.2"

Thank you for using Meilisearch!

We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html

Anonymous telemetry:	"Enabled"
Instance UID:		"6d2fe938-d748-4a83-943a-b61a8d71f6ea"

A Master Key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.

Documentation:		https://docs.meilisearch.com
Source code:		https://github.com/meilisearch/meilisearch
Contact:		https://docs.meilisearch.com/resources/contact.html

[2023-01-24T00:07:16Z INFO  actix_server::builder] Starting 2 workers
[2023-01-24T00:07:16Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2023-01-24T00:07:20Z INFO  actix_web::middleware::logger] 172.17.0.1 "POST /indexes/movies/documents?primaryKey=test HTTP/1.1" 401 221 "-" "curl/7.77.0" 0.000305
```
but got 
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/documents?primaryKey=test' \
  -H 'Content-Type: application/json' \
  --data-binary @preset.json
{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}%     
```

**Comment by curquiza** [comment] 2023-01-25 15:17
We tried to test with RCs of v1, and we don't have the issue anymore! Closing this issue then

**Closed by curquiza** 2023-01-25 15:17 UTC
Labels: bug
