### ISSUE TITLE
Unnecessary latency

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#2966] opened 2022-10-26 08:48 UTC
### Discussed in https://github.com/meilisearch/meilisearch/discussions/2965

<div type='discussions-op-text'>

<sup>Originally posted by **qdequele** October 25, 2022</sup>
I've just tested some request on my dataset of Hacker News post, and I discover that the search `zero config` take 211ms for the same result as `"zero config"`which take 6ms. Why? How are used the 205 extras milliseconds?

<div style="display: flex;">
<img width="400" alt="CleanShot 2022-10-25 at 17 11 18@2x" src="https://user-images.githubusercontent.com/6064892/197884322-a19b75e6-7697-4a27-8c42-1adc5f3f70ac.png">
<img width="400" alt="CleanShot 2022-10-25 at 17 11 08@2x" src="https://user-images.githubusercontent.com/6064892/197884331-5f1ef89f-d389-4abf-a524-48e2fda4fcfc.png">
</div>
</div>

**Comment by mohe2015** [comment] 2022-10-26 08:53
This is a duplicate of the discussion post.

**Comment by curquiza** [comment] 2022-10-26 10:03
Thanks @gmourier for the report, we will investigate this in November!

**Comment by ManyTheFish** [comment] 2022-11-23 15:42
Hello @gmourier,
I don't manage to reproduce your issue on the main branch, both search times are similar.

**Comment by gmourier** [comment] 2022-11-23 15:51
Hello @ManyTheFish, it was initially posted by @qdequele; I've transferred it here for further tech investigation. Do we miss something @qdequele ?

**Comment by qdequele** [comment] 2022-11-28 11:44
I have the same on the Crunchbase dataset by searching `crunch` (3ms) or `"crunch"` (283ms) for the exact same response. I don't know how I can help you. I just sent my documents and settings, then tried a search. 
We could do a call if you need more help. From what I understand is that the difference is the prefix search. It adds 280ms for searching for prefixes, but it's unnecessary because I already have my 20 results that match perfectly without prefixes. 

<img width="1469" alt="CleanShot 2022-11-28 at 12 39 21@2x" src="https://user-images.githubusercontent.com/6064892/204269053-c508f137-b4a9-478b-b66e-93e28a9ce2cd.png">
<img width="1474" alt="CleanShot 2022-11-28 at 12 40 56@2x" src="https://user-images.githubusercontent.com/6064892/204269119-67de79f9-b32d-41e9-836f-f85051cd0c0b.png">

**Comment by ManyTheFish** [comment] 2022-11-30 17:51
Hello @qdequele which computer are you using, how much RAM and CPU you have?

**Comment by qdequele** [comment] 2022-12-01 16:11
Hello @ManyTheFish, I have a Pro machine on the cloud. So 16Gb of RAM and 4cpu.

**Comment by loiclec** [comment] 2023-05-15 08:49
This **might** be fixed by https://github.com/meilisearch/meilisearch/pull/3542 . But it would be good to test it again once Meilisearch v1.2 is released

**Comment by Kerollmops** [comment] 2023-07-24 13:30
Hey @qdequele 👋

I know that you are the original poster of this issue. Could you try again [with v1.2.0 or even the latest version](https://github.com/meilisearch/meilisearch/releases)? We highly improved the latency and speed of the search requests. It's even available on the Cloud 😉

Have a nice day 🌻

**Comment by Kerollmops** [comment] 2023-09-06 12:50
Hey @qdequele, long time no see 👋 

I tested with [the latest v1.3.2](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.2), and the issue is no longer visible. I used [the settings and dataset available on our notion](https://www.notion.so/meilisearch/Crunchbase-Organizations-61492b8ca7a5497ba21e40af35399e52). There is always more time to process a non-exact query, but it is in the accepted delays — the v1.2.0 was probably the one release fixing the issue 🎉
<img width="1237" alt="Capture d’écran 2023-09-06 à 14 46 29" src="https://github.com/meilisearch/meilisearch/assets/3610253/ba5f0188-d2b4-4896-8e06-8d6879e3a525">
<img width="1228" alt="Capture d’écran 2023-09-06 à 14 46 15" src="https://github.com/meilisearch/meilisearch/assets/3610253/21a95a16-ee16-4808-92ee-09c11ffe571a">

**Closed by Kerollmops** 2023-09-06 12:50 UTC
Labels: bug, milli, needs more info, performance
